### ISSUE TITLE
Bug/FR: pkg-config file

### ISSUE THREAD

**Issue by PhysixProject** [lz4/lz4#1004]
**Describe the bug**
Attempting to build packages that require lz4 but there is not a pkg-config 'liblz4.pc' file 
installed, and it makes cmake have a bad time.

**Comment by Cyan4973** [comment]
A `liblz4.pc` file is installed when using this repository `make install` script : 
https://github.com/lz4/lz4/blob/dev/lib/Makefile#L172

**Comment by PhysixProject** [comment]
Aha! Thank you!
