### ISSUE TITLE
Older Xilinx FPGA LZ4 Solution URL in LZ4 Github.io

### ISSUE THREAD

**Issue by heeran-xilinx** [lz4/lz4#1010]
**Describe the bug**
I found that LZ4 GitHub.io https://lz4.github.io/lz4/ is referring Xilinx FPGA solution here:
'https://github.com/Xilinx/Applications/tree/master/data_compression/xil_lz4'
It is Xilinx outdated solution. Latest Xilinx Solution is available here:
'https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression'

**Expected behavior**
Please refer Xilinx Latest updated LZ4 FPGA solution URL link in LZ4 gitHub.io page.

**To Reproduce**
1. Go to 'https://lz4.github.io/lz4/'
2. Scroll down to  'LZ4 is used by' section and search for Hardware category. You will Find Xilinx FPGA
3. click the link 'https://github.com/Xilinx/Applications/tree/master/data_compression/xil_lz4'
4. See the README.md and you find that latest solutions are moved to 'https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression'
5. Please update older URL to new  URL:
Older: 'https://github.com/Xilinx/Applications/tree/master/data_compression/xil_lz4'
New: 'https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression'

**System (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Cyan4973** [comment]
link updated
