### ISSUE TITLE
Help identify potentially LZ4-related compression algorithm.

### ISSUE THREAD

**Issue by Massendefekt** [lz4/lz4#1015]
Hey there!

This isn't really an issue with lz4 but rather a general request for help in identifying a compression algorithm that could be LZ4 or something related.

First, some background: I've been working on / with ELF binaries produced by NVidia's compiler (`nvcc`). Of particular interest is the GPU ISA code (`ptx`) that it embeds into a section in the binary. Now, as it turns out, these code sections are compressed by default, with no official information on which compression algorithm is used. Older versions apparently used zlib / DELFATE. This is not the case any more, instead, they seem to be using an algorithm closely related to LZ4.

Attempts to decompress the generated output using both the CLI, C, and python libraries have failed so far, so maybe you can help me with this.

Here is an example of a compressed code section:
```
00000000  01 00 01 01 48 00 00 00  c0 01 00 00 00 00 00 00  |....H...........|
00000010  bf 01 00 00 40 00 00 00  03 00 07 00 34 00 00 00  |....@.......4...|
00000020  00 00 00 00 00 00 00 00  11 20 00 00 00 00 00 00  |......... ......|
00000030  00 00 00 00 00 00 00 00  f8 02 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  13 0a 01 00 f2 1c 2e 76  |...............v|
00000050  65 72 73 69 6f 6e 20 37  2e 33 0a 2e 74 61 72 67  |ersion 7.3..targ|
00000060  65 74 20 73 6d 5f 35 32  0a 2e 61 64 64 72 65 73  |et sm_52..addres|
00000070  73 5f 73 69 7a 65 20 36  34 2f 00 f9 18 69 73 69  |s_size 64/...isi|
00000080  62 6c 65 20 2e 65 6e 74  72 79 20 5f 5a 33 61 64  |ble .entry _Z3ad|
00000090  64 50 69 53 5f 78 62 28  0a 2e 70 61 72 61 6d 20  |dPiS_xb(..param |
000000a0  2e 75 36 34 1a 00 11 5f  18 00 3f 5f 30 2c 22 00  |.u64..._..?_0,".|
000000b0  0d 1f 31 22 00 0e 17 32  22 00 1f 38 21 00 01 f3  |..1"...2"..8!...|
000000c0  08 33 0a 29 0a 7b 0a 2e  72 65 67 20 2e 70 72 65  |.3.).{..reg .pre|
000000d0  64 20 25 70 3c 32 3e 3b  12 00 86 62 33 32 20 25  |d %p<2>;...b32 %|
000000e0  72 3c 36 11 00 f2 00 36  34 20 25 72 64 3c 39 3e  |r<6....64 %rd<9>|
000000f0  3b 0a 0a 0a 6c 64 5d 00  22 2e 75 17 00 4f 31 2c  |;...ld].".u..O1,|
00000100  20 5b 64 00 00 3d 30 5d  3b 2b 00 1f 32 2b 00 03  | [d..=0];+..2+..|
00000110  1f 31 2b 00 00 1f 33 2b  00 03 91 32 5d 3b 0a 6d  |.1+...3+...2];.m|
00000120  6f 76 2e 75 a4 00 f0 07  31 2c 20 25 63 74 61 69  |ov.u....1, %ctai|
00000130  64 2e 78 3b 0a 73 65 74  70 2e 67 74 2e 73 1b 00  |d.x;.setp.gt.s..|
00000140  32 70 31 2c 20 00 f4 17  39 3b 0a 40 25 70 31 20  |2p1, ...9;.@%p1 |
00000150  62 72 61 20 24 4c 5f 5f  42 42 30 5f 32 3b 0a 0a  |bra $L__BB0_2;..|
00000160  63 76 74 61 2e 74 6f 2e  67 6c 6f 62 61 6c 76 00  |cvta.to.globalv.|
00000170  21 34 2c d2 00 a2 3b 0a  6d 75 6c 2e 77 69 64 65  |!4,...;.mul.wide|
00000180  4e 00 33 72 64 35 4f 00  82 34 3b 0a 61 64 64 2e  |N.3rd5O..4;.add.|
00000190  73 2f 00 26 36 2c 35 00  11 35 c4 00 04 4f 00 01  |s/.&6,5..5...O..|
000001a0  36 00 00 ef 00 00 26 00  63 5d 3b 0a 73 68 6c 58  |6.....&.c];.shlX|
000001b0  01 22 33 2c 1a 00 20 31  3b 84 00 00 2a 00 03 7d  |."3,.. 1;...*..}|
000001c0  00 02 47 00 13 33 61 00  01 2c 00 24 35 2c 31 00  |..G..3a..,.$5,1.|
000001d0  2f 34 3b b2 00 04 21 37  2c 59 01 09 97 00 26 38  |/4;...!7,Y....&8|
000001e0  2c 1a 00 58 35 3b 0a 73  74 97 00 00 92 00 20 38  |,..X5;.st..... 8|
000001f0  5d 1c 00 45 35 3b 0a 0a  13 01 c0 3a 0a 72 65 74  |]..E5;.....:.ret|
00000200  3b 0a 0a 7d 0a 0a 00 00  00 00                    |;..}......|
0000020a

```
The actual compressed output doesn't seem to start until the `13 0a` bytes. The bytes before them encode other information (offset from start of section, 0x48 bytes; length of compressed output, 0x01c0; length of decompressed output 0x02f8).
To me, this looks very similar to LZ4 and various combinations of command line flags to `lz4` have produced very similar compressed outputs, but never exactly the same. 

Does anybody with more knowledge of LZ4 have an idea what settings they are using, what I could try next, or if this even is LZ4?

Thank you for your time and for reading this far :)

~ Yann

<details>
  <summary>Decompressed code</summary>
(There are 7 trailing new lines (0x0a) here but Github doesn't render it correctly.)
    .version 7.3
    .target sm_52
    .address_size 64
    
    
    
    .visible .entry _Z3addPiS_xb(
    .param .u64 _Z3addPiS_xb_param_0,
    .param .u64 _Z3addPiS_xb_param_1,
    .param .u64 _Z3addPiS_xb_param_2,
    .param .u8 _Z3addPiS_xb_param_3
    )
    {
    .reg .pred %p<2>;
    .reg .b32 %r<6>;
    .reg .b64 %rd<9>;
    
    
    ld.param.u64 %rd1, [_Z3addPiS_xb_param_0];
    ld.param.u64 %rd2, [_Z3addPiS_xb_param_1];
    ld.param.u64 %rd3, [_Z3addPiS_xb_param_2];
    mov.u32 %r1, %ctaid.x;
    setp.gt.s32 %p1, %r1, 9;
    @%p1 bra $L__BB0_2;
    
    cvta.to.global.u64 %rd4, %rd1;
    mul.wide.s32 %rd5, %r1, 4;
    add.s64 %rd6, %rd4, %rd5;
    ld.global.u32 %r2, [%rd6];
    shl.b32 %r3, %r2, 1;
    cvt.u32.u64 %r4, %rd3;
    add.s32 %r5, %r3, %r4;
    cvta.to.global.u64 %rd7, %rd2;
    add.s64 %rd8, %rd7, %rd5;
    st.global.u32 [%rd8], %r5;
    
    $L__BB0_2:
    ret;
    
    }

</details>

<details>
  <summary> Sample  compressed with `lz4 -12 -BD`. </summary>

      00000000  04 22 4d 18 64 40 a7 bd  01 00 00 13 0a 01 00 f2  |."M.d@..........|
      00000010  1c 2e 76 65 72 73 69 6f  6e 20 37 2e 33 0a 2e 74  |..version 7.3..t|
      00000020  61 72 67 65 74 20 73 6d  5f 35 32 0a 2e 61 64 64  |arget sm_52..add|
      00000030  72 65 73 73 5f 73 69 7a  65 20 36 34 2f 00 f9 18  |ress_size 64/...|
      00000040  69 73 69 62 6c 65 20 2e  65 6e 74 72 79 20 5f 5a  |isible .entry _Z|
      00000050  33 61 64 64 50 69 53 5f  78 62 28 0a 2e 70 61 72  |3addPiS_xb(..par|
      00000060  61 6d 20 2e 75 36 34 1a  00 11 5f 18 00 3f 5f 30  |am .u64..._..?_0|
      00000070  2c 22 00 0d 1f 31 22 00  0e 17 32 22 00 1f 38 21  |,"...1"...2"..8!|
      00000080  00 01 f3 08 33 0a 29 0a  7b 0a 2e 72 65 67 20 2e  |....3.).{..reg .|
      00000090  70 72 65 64 20 25 70 3c  32 3e 3b 12 00 86 62 33  |pred %p<2>;...b3|
      000000a0  32 20 25 72 3c 36 11 00  f2 00 36 34 20 25 72 64  |2 %r<6....64 %rd|
      000000b0  3c 39 3e 3b 0a 0a 0a 6c  64 5d 00 22 2e 75 17 00  |<9>;...ld].".u..|
      000000c0  4f 31 2c 20 5b c9 00 01  2d 5d 3b 2b 00 1f 32 2b  |O1, [...-];+..2+|
      000000d0  00 03 2e 31 5d 2b 00 1f  33 2b 00 03 91 32 5d 3b  |...1]+..3+...2];|
      000000e0  0a 6d 6f 76 2e 75 a4 00  f0 07 31 2c 20 25 63 74  |.mov.u....1, %ct|
      000000f0  61 69 64 2e 78 3b 0a 73  65 74 70 2e 67 74 2e 73  |aid.x;.setp.gt.s|
      00000100  1b 00 32 70 31 2c 20 00  f4 17 39 3b 0a 40 25 70  |..2p1, ...9;.@%p|
      00000110  31 20 62 72 61 20 24 4c  5f 5f 42 42 30 5f 32 3b  |1 bra $L__BB0_2;|
      00000120  0a 0a 63 76 74 61 2e 74  6f 2e 67 6c 6f 62 61 6c  |..cvta.to.global|
      00000130  76 00 21 34 2c d2 00 a2  3b 0a 6d 75 6c 2e 77 69  |v.!4,...;.mul.wi|
      00000140  64 65 4e 00 33 72 64 35  4f 00 82 34 3b 0a 61 64  |deN.3rd5O..4;.ad|
      00000150  64 2e 73 2f 00 26 36 2c  35 00 11 35 c4 00 04 4f  |d.s/.&6,5..5...O|
      00000160  00 01 36 00 00 ef 00 00  26 00 63 5d 3b 0a 73 68  |..6.....&.c];.sh|
      00000170  6c 58 01 22 33 2c 1a 00  20 31 3b 84 00 00 2a 00  |lX."3,.. 1;...*.|
      00000180  03 7d 00 02 47 00 13 33  61 00 01 2c 00 24 35 2c  |.}..G..3a..,.$5,|
      00000190  31 00 2f 34 3b b2 00 04  21 37 2c 59 01 09 97 00  |1./4;...!7,Y....|
      000001a0  25 38 2c 1a 00 00 97 00  28 73 74 97 00 10 5b 21  |%8,.....(st...[!|
      000001b0  00 20 5d 2c 5e 00 35 3b  0a 0a 13 01 b0 3a 0a 72  |. ],^.5;.....:.r|
      000001c0  65 74 3b 0a 0a 7d 0a 0a  00 00 00 00 63 2b f5 92  |et;..}......c+..|
      000001d0

</details>

**Comment by Cyan4973** [comment]
There is indeed a close similarity, which suggests an LZ4 encoding.

Not sure if / why it matters for you to discover the exact encoding process, as long as it decompresses correctly.
But you could try all compression levels for example. They may have used level 9. They may also use an older version of the `lz4` CLI, resulting in slightly different output.

That being said, there is no reason for nVidia to use the `lz4` CLI program exclusively.
They may have implemented their own version.
For example, they have a GPU accelerated variant at : https://github.com/NVIDIA/nvcomp

**Comment by mcroomp** [comment]
If their binary uses LZ4 they need to include the license text, so you could search it to see.

**Comment by Massendefekt** [comment]
> There is indeed a close similarity, which suggests an LZ4 encoding.

Thanks, this is encouraging!

>Not sure if / why it matters for you to discover the exact encoding process, as long as it decompresses correctly.
But you could try all compression levels for example. They may have used level 9. They may also use an older version of the lz4 CLI, resulting in slightly different output.

The exact encoding process doesn't matter (except maybe for "street cred" at the next CCC meetup). I just wasn't sure whether I was actually looking at LZ4 compression. I guess, I just have to implement a small decoder, I didn't get very far with the CLI and the python bindings - your docs cover the block format quite well, so it shouldn't be too hard:).

> If their binary uses LZ4 they need to include the license text, so you could search it to see.

@mcrumpface, I think I owe you a beer (or coffee). The CUDA EULA packaged with the binaries indeed contains a reference to LZ4 :D. I'm a bit embarrassed that I didn't come up with that myself. 

Thank you guys very much for your time and help. Keep up the great work!

**Comment by mcroomp** [comment]
You're welcome :)

There's a paper on nvcomp... they also have a different type of compression for very simple data called Cascaded

https://developer.nvidia.com/blog/optimizing-data-transfer-using-lossless-compression-with-nvcomp/
