### ISSUE TITLE
`programs/platform.h` contains Unicode character

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1018]
**Describe the bug**

1. `programs/platform.h` contains Unicode (non-7bit ASCII) character.
2. When user try to use MSVC solution file `build/VS2017/lz4.sln`, this Unicode character causes the following warning.  And build process is aborted.

```
1>fuzzer.c
1> programs\platform.h(1,1): error C2220: the following warning is treated as an error
1> programs\platform.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
```

**Expected behavior**

1. The source code doesn't contain Unicode character.
2. Complete MSVC build process without error.

**To Reproduce**
1. Open `lz4/build/VS2017/lz4.sln` with Visual C++ 2017 or greater.
2. Invoke `Menu > Build > Build Solution`.
3. During build process, compiler emits `warning C4819`.

**System (please complete the following information):**
 - OS: Windows 10 (System locale/language setting is Japan/Japanese)
 - Version: 20H2 (Build 19042.1083)
 - Compiler: MSVC 2019 (Version 19.29.30040)
 - Build System: Visual Studio (`msbuild`)

**Comment by t-mat** [comment]
### Where's the Unicode character?

We can find it with [the following command](https://stackoverflow.com/a/9395552).

```sh
grep -P -n "[^\x00-\x7F]" programs/platform.h
```

It reports

```
83:#  if (defined(__APPLE__) && defined(__MACH__)) || defined(__SVR4) || defined(_AIX) || defined(__hpux) /* POSIX.1–2001 (SUSv3) conformant */ \
                                                                                                                    ^
```

Actual character is `U+2013` which is `0xe2, 0x80, 0x93` in UTF-8.

```sh
od -j 0x1080 -t x1 -c -A x -N 16 programs/platform.h
```

```
001080  29  20  2f  2a  20  50  4f  53  49  58  2e  31  e2  80  93  32
         )       /   *       P   O   S   I   X   .   1 342 200 223   2
                                                       ^^^^^^^^^^^
```


### What's the `warning C4819`, `error C2220` and `the current code page (932)`?

`error C2220` means "treat warning as an error".

[`warning C4819`](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819),  is

> C4819 occurs when you compile an ANSI source file on a system using a codepage that can't represent all characters in the file.

In this case, it means

(1) Since there's no sign of UTF (BOM or [`/utf-8` switch](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8) of `cl.exe`), MSVC try to read this source code as plain text which is encoded by the default text encoding of the system locale.
(2) In my case, it is [code page 932 (shift_jis)](https://docs.microsoft.com/en-us/windows/win32/Intl/code-page-identifiers).
(3) In this encoding system, `0xe2, 0x80, 0x93` is invalid.  And C4819 occurs.


### Possible solution

(1) Replace `U+2013` (`–`) with `U+002D` (`-`).
(2) Add `/utf-8` to MSVC project.  But it doesn't work older MSVC versions.
(3) Force to add "UTF-8 BOM" to all source code.  It may cause other compatibility issue especially for older compilers.

Perhaps, additional validation with `grep -P -n "[^\x00-\x7F]"` may help future contributors.

**Comment by t-mat** [comment]
In PR #1019, @servusdei2018 pointed out other Unicode character (`U+0119` (ę)) in source code.

https://github.com/lz4/lz4/blob/de45d6e0fa59e1c5dc21f611dd73f91ba04aaff1/examples/frameCompress.c#L2

Since it's a name of person, we need serious discussion to change the representation or not.

I think point is where we do/don't accept Unicode character, due to technical restriction for compatibility.

For example, we do not accept any Unicode characters

(1) For all file, including documents, licenses.  Since we have some XML/(X)HTML documents, this restriction is unrealistic though.
(2) For only source code (`*.c` and `*.h`) and `Makefile`.  Other files are in UTF-8.
(3) For only lz4 core source code (`lib/` and `programs/`) and their `Makefile`.
(4) Don't care.  We accept Unicode characters everywhere.  But all files are encoded in UTF-8.

If we don't accept Unicode character in `examples/` source code,

- Ask them to change the representation of their name in the code.
- We also can propose them to represent their actual name in UTF-8, in `examples/README.md`.

**Comment by servusdei2018** [comment]
>  For example, we do not accept any Unicode characters
>
> (1) For all file, including documents, licenses. Since we have some XML/(X)HTML documents, this restriction is unrealistic though.
> (2) For only source code (*.c and *.h) and Makefile. Other files are in UTF-8.
> (3) For only lz4 core source code (lib/ and programs/) and their Makefile.
> (4) Don't care. We accept Unicode characters everywhere. But all files are encoded in UTF-8.

@t-mat I think option 3 is best, as it ensures the most compatibility for the lz4 core source code, and also doesn't impose restrictions on the examples themselves. The examples should be free to use other features like Unicode because they are, after all, examples which people can copy and edit as necessary, but the core should be as compatible as possible out of the box.

**Comment by Cyan4973** [comment]
I'm fine with option 3.

**Comment by t-mat** [comment]
I checked MSVC project files to determine which files are included in `.vcxproj`.

```sh
grep -r -h "ClCompile.*\.[ch]" build/VS2010 | sort | uniq
grep -r -h "ClCompile.*\.[ch]" build/VS2017 | sort | uniq
```

Both of results are same

```xml
    <ClCompile Include="..\..\..\lib\lz4.c" />
    <ClCompile Include="..\..\..\lib\lz4frame.c" />
    <ClCompile Include="..\..\..\lib\lz4hc.c" />
    <ClCompile Include="..\..\..\lib\xxhash.c" />
    <ClCompile Include="..\..\..\programs\bench.c" />
    <ClCompile Include="..\..\..\programs\datagen.c" />
    <ClCompile Include="..\..\..\programs\lz4cli.c" />
    <ClCompile Include="..\..\..\programs\lz4io.c" />
    <ClCompile Include="..\..\..\tests\datagencli.c" />
    <ClCompile Include="..\..\..\tests\frametest.c" />
    <ClCompile Include="..\..\..\tests\fullbench.c" />
    <ClCompile Include="..\..\..\tests\fuzzer.c" />
```

We may need to take care the following points

(1) `tests/*.[ch]`.

We should decide `tests/` also must avoid Unicode or not.

If we want to use Unicode for MSVC 2017 environment, I think it's okay to add [`/source-charset:utf-8`](https://docs.microsoft.com/en-us/cpp/build/reference/source-charset-set-source-character-set) to project file for `tests/`.  But MSVC 2010 doesn't have this option.

Removing "treat warning as error" (edit: or supress the warning) is other option to allow Unicode in source file.

In any case, we just allow Unicode in comment.  But should not allow Unicode as string literal.


(2) `lib/xxhash.[ch]`.

Since xxhash is "upstream" of lz4, it's nice to have same Unicode validation in xxHash repo.

**Comment by Cyan4973** [comment]
Would the simplest solution, to spell and enforce, be to not allow unicode characters in `tests/*.[ch]` ?

Regarding `xxhash`, I agree, it needs to apply same rules.

**Comment by t-mat** [comment]
Right.  The most simple solution is prohibiting Unicode characters in `{lib,programs,tests}/*.[ch]` for compatibility.

So the rest of the works are:

- Add `./tests/` to `tests/unicode_lint.sh`
- Add test rule to `Makefile`
- Add test rule to `.github/workflows/ci.yml`

**Comment by Cyan4973** [comment]
With #1019, the work is already done for `lib/` and `programs/`,
so all that's left is  to add `tests/`.

Also, CI automated test is setup on `travis`, which is currently disabled.
It would be better to switch to Github Actions.
