### ISSUE TITLE
add meson build system

### ISSUE THREAD

**Issue by vtorri** [lz4/lz4#1025]
is it possible to add a meson support (like zstd) ?

thank you

**Comment by t-mat** [comment]
Hi @vtorri,

As you know, we already have [contrib/meson/](https://github.com/lz4/lz4/tree/dev/contrib/meson) and [basic test for it](https://github.com/lz4/lz4/blob/3e99d07bc09e1b82ee6191527bb3e555052c55ac/.github/workflows/ci.yml#L571-L612).

Could you explain what kind of support you want?  e.g. More frequent maintenance, Fix broken tests, etc.

**Comment by vtorri** [comment]
ho sorry, i only looked  in the build/ subdirectory. Maybe it should be moved there, shouldn't it ?

**Comment by t-mat** [comment]
As for visibility, please take a look at #852, #900 and the following comment.

https://github.com/lz4/lz4/issues/852#issuecomment-657913412
> We gladly accept new patches in order to improve its capabilities.

**Comment by Cyan4973** [comment]
`build/` shall contain build script that I'm able and willing to support directly.
Unfortunately, that's not yet the case for `meson` build system,
hence it's hosted into `contrib/`, to emphasize the fact that it's reliant on community support.
