### ISSUE TITLE
LZ4_decompress_safe VS LZ4_decompress_fast(or Z4_uncompress)

### ISSUE THREAD

**Issue by Nir-Az** [lz4/lz4#1028]
Hi,

I have recently updated LZ4 version to the latest one (1.8.0 -> 1.9.3).
I have a file that was compressed with `LZ4_compress` function(using version 1.8.0) and uncompressed using `LZ4_uncompress` functions.

Since I started getting a deprecated warning regarding the use of `Z4_uncompress`  function I tried replacing it with `LZ4_decompress_safe`
I tried to compare the output of `LZ4_decompress_safe` and `Z4_uncompress` and the output is not the same.
I also tried comparing `LZ4_decompress_safe_withPrefix64k` and `Z4_uncompress` and the output is different.
Am I doing something wrong or the compress/uncompress data is really different at this versions?

Thanks.

**Comment by Cyan4973** [comment]
LZ4 is a lossless compression algorithm.
So whatever the entry point you use to decompress the same payload, it should decompress the same.
If not, there is likely a corruption error going on.

`LZ4_uncompress` has been deprecated for a long time, and needs replacing with `LZ4_decompress_safe`.
They are functionally equivalent, **but** their signatures differ.
I recommend paying attention to this point. Ensure that the right parameter is provided in the right field.
In which case, and presuming that the input is valid, both functions should return exactly the same decompressed content.

If the compressed input was corrupted, that's where both functions _may_ result in a different output.
Since the input is corrupted, both outputs are, by definition, incorrect.
But `LZ4_decompress_safe` does at least guarantee that it will respect buffer boundaries.
`LZ4_uncompress`, unfortunately, can only guarantee a few cases, but not others, due lack of information in its signature.

**Comment by t-mat** [comment]
@Nir-Az, please check the following comment and the code.

https://github.com/lz4/lz4/blob/c10863b98e1503af90616ae99725ecd120265dfb/lib/lz4.c#L1425-L1432

I recommend you to use the following 2-step replacement.

(1) Replace `LZ4_uncompress()` with `LZ4_decompress_fast()`.
(2) Replace `LZ4_decompress_fast()` with `LZ4_decompress_safe()` if you need.

**Comment by Nir-Az** [comment]
Thanks for the answers, but still I don't understand something.

(1) `LZ4_uncompress()` and `LZ4_decompress_fast()` are doing the same thing and both pop up deprecated warnings.
(2) I tried doing so and the outcome is not the same as using `LZ4_decompress_fast()`

I can see `LZ4_decompress_fast()` function is calling the generic function with 64k prefix arguments.
and `LZ4_decompress_safe()` does not.

1. Is it possible to replace 1 with the other if they use the input data differently ?
2. If I once compressed with LZ4_compress(), which decompress function match the compressed file on the new code?

Thanks

**Comment by Nir-Az** [comment]
Apparently the source input size I used as an argument was wrong, once I fixed it the *_safe() output is equal to the *_fast function.
Thanks.

**Comment by t-mat** [comment]
> (1) LZ4_uncompress() and LZ4_decompress_fast() are doing the same thing and both pop up deprecated warnings.

Sorry.  I forgot to mention about `LZ4_DISABLE_DEPRECATE_WARNINGS`.  When you `#define` it, `lz4.h` doesn't emit deprecation warnings.  You can use it for testing.

```C
#define LZ4_DISABLE_DEPRECATE_WARNINGS
#include "lz4.h"
...
```

The following code is complete example of how `LZ4_decompress_safe()` works with `LZ4_compress()` and `LZ4_compress_default()`.

```C
/* lz4-issue-1028.c  https://github.com/lz4/lz4/issues/1028

# Building
cd
mkdir lz4-issue-1028
cd lz4-issue-1028
git clone https://github.com/lz4/lz4.git

# Put this code as lz4-issue-1028.c

gcc -I lz4/lib lz4/lib/lz4.c lz4/lib/lz4hc.c lz4/lib/xxhash.c lz4-issue-1028.c
./a.out
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#define LZ4_DISABLE_DEPRECATE_WARNINGS  /* LZ4_compress() */
#include "lz4.h"

int main(int argc, char* argv[]) {
    // Generate raw (original, source) data
    int const rawDataSize = 1024 * 256;
    uint8_t* const rawData = (uint8_t*) malloc(rawDataSize);
    {
        int i;
        for(i = 0; i < rawDataSize; ++i) {
            rawData[i] = (uint8_t) ((i & 255) + (i / 256));
        }
    }
    printf("rawDataSize = %d\n\n", rawDataSize);

    int i;
    for(i = 0; i <= 1; ++i) {
        printf("i = %d\n", i);
        int const useLz4Compress   = (i & 1) != 0;

        // Compress
        int const compressBufSize = LZ4_compressBound(rawDataSize);
        uint8_t* const compressBuf = (uint8_t*) malloc(compressBufSize);

        int compressedSize = 0;
        if(useLz4Compress) {
            printf("LZ4_compress() (obsolete)");
            compressedSize = LZ4_compress(
                  rawData
                , compressBuf
                , rawDataSize
            );
        } else {
            printf("LZ4_compress_default()");
            compressedSize = LZ4_compress_default(
                  rawData
                , compressBuf
                , rawDataSize
                , compressBufSize
            );
        }
        printf(" -> compressedSize = %d\n", compressedSize);

        // Decompress
        int const decBufSize = rawDataSize;
        uint8_t* const decData = (uint8_t*) malloc(decBufSize);
        int const decDataSize = LZ4_decompress_safe(
              compressBuf
            , decData
            , compressedSize
            , decBufSize
        );
        printf("LZ4_decompress_safe() -> decDataSize = %d\n", decDataSize);

        // Verify
        int const cmp = (decDataSize == rawDataSize)
                     && (memcmp(rawData, decData, decDataSize) == 0);
        printf("%s\n", cmp ? "OK" : "NG");

        free(decData);
        free(compressBuf);

        printf("\n");
    }
    return 0;
}
```
