### ISSUE TITLE
LZ4_compress_destSize can be used between LZ4F functions ?

### ISSUE THREAD

**Issue by FutureIsM** [lz4/lz4#1038]
Hi:
    excuse me ! there is a situation of compress that i want to compress some data to a fixed size buffer for aligning memory. Of cource, i find LZ4_compress_destSize can achieve this project, but as i known, LZ4_compress_destSize can't get metadata in data, but i want i can decompress the data what i compress use  LZ4_compress_destSize anywhere. [#584 ](https://github.com/lz4/lz4/issues/584) tell me it have crosse-platforme question if compressed data don't have metadata.

there are some question:
1. if compress by LZ4_compress_destSize, can i decompress the compressed data in any OS platform ? (i can comfirm LZ4 version is same)
2. LZ4F can have head and tail, so it can avoid cross-platform question, but it don't have api like LZ4_compress_destSize for aligning memory. so what can i do to achieve it by liblz4 or liblz4Frame ?
3. do you have some suggestion about compress huge buffer to some fixed size of independent blocks of compression ?

Can anyone take a look at this issue?
Much appreciate .

**Comment by FutureIsM** [comment]
anyone can help ?

**Comment by Cyan4973** [comment]
Is there a concern in writing / transporting your own metadata ?

You merely need the decompressed size and an upper bound of the compressed size.,
or the compressed size and an upper bound of the `decompressed` size.

Generally the better choice is application dependent, that's why `liblz4` doesn't try to enforce a specific way of encoding metadata.

**Comment by FutureIsM** [comment]
yeah, i add my own metadata, and i use LZ4_compress_destSize well.

there is another question, which is how to get larger compression ratio when using LZ4_compress_destSize, puzzle me,

please help me, thanks!

**Comment by Cyan4973** [comment]
`LZ4_compress_HC_destSize()` maybe ?

**Comment by FutureIsM** [comment]
> `LZ4_compress_HC_destSize()` maybe ?

that is great，i will try it. thanks

**Comment by FutureIsM** [comment]
> `LZ4_compress_HC_destSize()` maybe ?

it work well, thanks so much.
