### ISSUE TITLE
Compression level not available in LZ4 block API

### ISSUE THREAD

**Issue by pitrou** [lz4/lz4#1041]
It seems that the LZ4 block compression API does not offer a way of setting the compression level, as opposed to the LZ4 frame compression API. Am I missing something, or is there a good reason for that?

**Comment by Cyan4973** [comment]
There are 2 APIs for the LZ4 block compression mode.
The "fast" mode (`lz4.c`) offers "acceleration" levels, which are a bit like negative compression levels for `zstd`.
The "high compression" mode (`lz4hc.c`) is where you'll see the equivalent of "compression level" for block mode.

**Comment by pitrou** [comment]
Hmm... is there a well-known rule for how to map the compression levels exposed on the command line, to parameters to `lz4.h` / `lz4hc.h` APIs?

**Comment by Cyan4973** [comment]
They mostly correspond to `lz4hc.c` levels

**Comment by pitrou** [comment]
Hmm, thank you. I guess I'll look at the source code to know exactly how the mapping goes :-)
