### ISSUE TITLE
exit code of `lz4 --test` for invalid file is non-zero

### ISSUE THREAD

**Issue by anatol** [lz4/lz4#1045]
```
lz4 --version
*** LZ4 command line interface 64-bits v1.9.3, by Yann Collet ***
```

at Arch Linux.

I have an invalid file produced by golang lz4 library (see https://github.com/anatol/booster/issues/117 for reference). I check it with `lz4` command and it complains

```
$ lz4 --test invalid.lz4
Stream followed by undecodable data at position 8 
invalid.lz4          : decoded 0 bytes    
$ echo $?
0

```
the exit code of this command is 0 (i.e. success). It sounds wrong to me.

The exit code should indicate an error and be non-zero.

**Comment by Cyan4973** [comment]
If it's very small we could use it as golden file for regression tests (or a close enough equivalent).

That it fails at position 8 looks strange to be fair. Sounds like a skippable frame.

**Comment by anatol** [comment]
Here is the first 4K of broken legacy lz4 file produced by lz4.go library.

https://drive.google.com/file/d/1ROna4lr8S06EdoVXEVzWXRbO_AdENHa5/view?usp=sharing

If you run `lz4 --test` for it the exit code would be 0 which looks wrong

```
$ lz4 --test test.lz4
Stream followed by undecodable data at position 8 
test.lz4             : decoded 0 bytes                                         
$ echo $?
0
```

**Comment by anatol** [comment]
And the lz4.go issue is tracked here https://github.com/pierrec/lz4/issues/156
