### ISSUE TITLE
no compression for compressible data

### ISSUE THREAD

**Issue by danielhrisca** [lz4/lz4#1046]
**Describe the bug**
The output file is bigger than the input file, even though the content should be easily compressible

**Expected behavior**
Some compression ratio.

**To Reproduce**
1. Save the range 0-10000 of uint32 integers to a file
2. compress the file with lz4
3. the output file has 40019 bytes (using LZ4 win64 1.9.3)

**System (please complete the following information):**
 - OS: Windows 10 x64
 - Version 1.9.3
 - Compiler using the binary from the [release 1.9.3](https://github.com/lz4/lz4/releases/tag/v1.9.3)
 - Other hardware specs Core(TM) i7-8850H CPU

**Comment by mwgamera** [comment]
The input you described is not compressible at all with LZ77-type compressors like LZ4 as it has no repeating patterns other than very short 2–3-byte sequences of zeros and LZ4 needs at least 4 bytes to match. LZ4 is not suitable for this kind of data. The only thing it can do is to add a header indicating that uncompressed data follows. The result looks as expected to me.

**Comment by danielhrisca** [comment]
I was not aware of this, thank you for the explanation
