### ISSUE TITLE
LZ4 is Too Fast!

### ISSUE THREAD

**Issue by gaia** [lz4/lz4#1055]
Just kidding. Well, almost.

While deflating a 180G archive that inflates to 560G on an NVME disk, IOwait spikes up and other processes suffer.

**I can ionice the decompression, but ideally there would be a flag to limit bandwidth used by LZ4.** 

PS: Unfortunately I don't have a downtime window, or a low usage window. The load is constant 24/7/365. I do have other machines to take over the load, but I don't want to failover (it's an involved process) everytime I need to deflated an archive and no I cannot use load balancers or any traditional HA solution.

**Comment by Cyan4973** [comment]
Assuming you are using `lz4` as part of a pipeline, you could `pv` the pipe in order to rate-limit it, on either read or write side ( or even both ).

**Comment by gaia** [comment]
thanks. forgot about `pv`. and not as familiar with it as ionice.

so from `ionice -c 3 lz4 -vdc --no-sparse archive.tar.lz4 | tar xf -`
to `lz4 -vdc --no-sparse archive.tar.lz4 | pv -q -L 8192 | tar xf -` ?

i was thinking something more convenient, in line with `rsync --bwlimit=`

maybe it is not possible due to the way lz4 works?

**Comment by Cyan4973** [comment]
It's not trivial and requires development time, and there is no bandwidth for that at the moment.
Perhaps as importantly, it's duplicating a functionality which already exists.
