### ISSUE TITLE
improve meson build system

### ISSUE THREAD

**Issue by vtorri** [lz4/lz4#1062]
* add gnu-symbol-visibility for the library (meson >= 0.48) : https://mesonbuild.com/Release-notes-for-0-48-0.html#keyword-argument-for-gnu-symbol-visibility
 * add pic for the library (meson >= 0.46 i think, not sure it appeared before 0.46)

it depends if you want to increase meson version from 0.47 to 0.48 for gnu-symbol-visibility

Vincent Torri

**Comment by Cyan4973** [comment]
Word of advise regarding version support:
it's generally preferable for build scripts to not be too much reliant on the "bleeding edge" to be effectively used by a diverse ecosystem.
A good rule of thumb is to remain compatible with at least oldest supported Ubuntu LTS version,
which currently is Ubuntu 18.04 Bionic Beaver.

**Comment by eli-schwartz** [comment]
You can use features from newer versions of meson using `if meson.version().version_compare('>=0.48')`.

That being said:

> A good rule of thumb is to remain compatible with at least oldest supported Ubuntu LTS version,
> which currently is Ubuntu 18.04 Bionic Beaver.

The original addition of the meson build script back in 2018 required Meson 0.47, which is too new for Ubuntu 18.04, so bumping that again from 0.47 to 0.48 won't reduce your support.

It is a 3.5 year old release and is broadly available, even if the Ubuntu LTS game offers 5 years of compatibility sometimes people are still willing to sacrifice the oldest one in town in the name of badly needed features.

Depends on what you need, I guess.

**Comment by tristan957** [comment]
See https://github.com/lz4/lz4/pull/1064

**Comment by tristan957** [comment]
@vtorri would be great if you could give input on the PR since you care about it.

**Comment by vtorri** [comment]
it depends if the developpers accept to bump the required minimal version of meson

**Comment by tristan957** [comment]
You should try reading through the PR :)
