### ISSUE TITLE
Ambiguous license in /ossfuzz/fuzz_helpers.h

### ISSUE THREAD

**Issue by andreaskotulla** [lz4/lz4#1073]
**Describe the bug**

The license in file /ossfuzz/fuzz_helpers.h is ambiguous.  It is not clear if the user can choose one of the licenses, or if both licenses apply. Here is the text from the file:

 * This source code is licensed under both the BSD-style license (found in the
 * LICENSE file in the root directory of this source tree) and the GPLv2 (found
 * in the COPYING file in the root directory of this source tree).

**Expected behavior**
Please clarify which licenses apply exactly. For example, add a statment like:  "You may select, at your option, one of the above-listed licenses." An example can be seen in file tests/roundTripTest.c

**To Reproduce**
Look at the header of file /ossfuzz/fuzz_helpers.h

**System (please complete the following information):**
any

**Additional context**

**Comment by Cyan4973** [comment]
Dual license are always like that : you can select, at your option, whichever license best fit your needs.
This is not specific for this repository, it is an old established rule applied evenly across a wide swath of open source contents.
