### ISSUE TITLE
Files in 1.9.3 zip are not as named in the README

### ISSUE THREAD

**Issue by adunstan** [lz4/lz4#1076]
README says to expect 

- `dll\liblz4.dll`           : The DLL of LZ4 library
- `dll\liblz4.lib`           : The import library of LZ4 library for Visual C++

But instead there are:

ls -l dll
total 548
-rw-r--r-- 1 Administrator None  59774 Nov 15  2020 liblz4.dll.a
-rwxr-xr-x 1 Administrator None 495976 Nov 15  2020 msys-lz4-1.dll

**Comment by Cyan4973** [comment]
I've updated the documentation to reflect the new naming convention.

However, this documentation is in general old (~6y old), hence it's probably out of date if not outright wrong on several details. So I wouldn't trust it blindly.
A more general update would likely be welcome. However, I can't be the one providing it : this is a build setup I never use, hence I have zero knowledge on these topics.
