### ISSUE TITLE
Visual Studio 2022 warnings - some fixed, some concerning

### ISSUE THREAD

**Issue by PrimalJohnScott** [lz4/lz4#1083]
I'm compiling the VS2017 solution after upgrading the projects to VS2022 and the latest tool chain. You're welcome to these projects, but I have a slightly different set of conventions, and it's pretty trivial anyway.

I've addressed some x64 warnings in the diff below - but they weren't really a problem.

However, the warnings: 
'lz4-dev\1.9.3\lib\lz4.c(491): warning C6385: Reading invalid data from 'v'.'
'lz4-dev\1.9.3\tests\fuzzer.c(497): warning C6385: Reading invalid data from 'compressedBuffer'.
raise a red flag for me. I think it's OK, but Visual Studio thinks they are not.

Cheers
John

`==== //GPEG/tasks/Engine/Encoder/ThirdParty/lz4-dev/1.9.3/tests/datagencli.c#1 - d:\ISILDUR-Engine\Encoder\ThirdParty\lz4-dev\1.9.3\tests\datagencli.c ====
***************
*** 107,113 ****
                      while ((*argument>='0') && (*argument<='9'))
                      {
                          size *= 10;
!                         size += *argument - '0';
                          argument++;
                      }
                      if (*argument=='K') { size <<= 10; argument++; }
--- 107,114 ----
                      while ((*argument>='0') && (*argument<='9'))
                      {
                          size *= 10;
! 						char digit = *argument - '0';
!                         size += digit;
                          argument++;
                      }
                      if (*argument=='K') { size <<= 10; argument++; }
***************
*** 131,137 ****
                      while ((*argument>='0') && (*argument<='9'))
                      {
                          proba *= 10;
!                         proba += *argument - '0';
                          argument++;
                      }
                      if (proba>100.) proba=100.;
--- 132,139 ----
                      while ((*argument>='0') && (*argument<='9'))
                      {
                          proba *= 10;
! 						char digit = *argument - '0';
! 						proba += digit;
                          argument++;
                      }
                      if (proba>100.) proba=100.;
***************
*** 143,149 ****
                      while ((*argument>='0') && (*argument<='9'))
                      {
                          litProba *= 10;
!                         litProba += *argument - '0';
                          argument++;
                      }
                      if (litProba>100.) litProba=100.;
--- 145,152 ----
                      while ((*argument>='0') && (*argument<='9'))
                      {
                          litProba *= 10;
! 						char digit = *argument - '0';
!                         litProba += digit;
                          argument++;
                      }
                      if (litProba>100.) litProba=100.;
==== //GPEG/tasks/Engine/Encoder/ThirdParty/lz4-dev/1.9.3/tests/fuzzer.c#1 - d:\ISILDUR-Engine\Encoder\ThirdParty\lz4-dev\1.9.3\tests\fuzzer.c ====
***************
*** 571,577 ****
                  for (;;) {
                      /* keep some original src */
                      {   U32 const nbBits = FUZ_rand(&randState) % maxNbBits;
!                         size_t const mask = (1<<nbBits) - 1;
                          size_t const skipLength = FUZ_rand(&randState) & mask;
                          pos += skipLength;
                      }
--- 571,577 ----
                  for (;;) {
                      /* keep some original src */
                      {   U32 const nbBits = FUZ_rand(&randState) % maxNbBits;
!                         size_t const mask = ((size_t)1<<nbBits) - (size_t)1;
                          size_t const skipLength = FUZ_rand(&randState) & mask;
                          pos += skipLength;
                      }
***************
*** 579,585 ****
                      /* add noise */
                      {   U32 const nbBitsCodes = FUZ_rand(&randState) % maxNbBits;
                          U32 const nbBits = nbBitsCodes ? nbBitsCodes-1 : 0;
!                         size_t const mask = (1<<nbBits) - 1;
                          size_t const rNoiseLength = (FUZ_rand(&randState) & mask) + 1;
                          size_t const noiseLength = MIN(rNoiseLength, (size_t)compressedSize-pos);
                          size_t const noiseStart = FUZ_rand(&randState) % (COMPRESSIBLE_NOISE_LENGTH - noiseLength);
--- 579,585 ----
                      /* add noise */
                      {   U32 const nbBitsCodes = FUZ_rand(&randState) % maxNbBits;
                          U32 const nbBits = nbBitsCodes ? nbBitsCodes-1 : 0;
!                         size_t const mask = ((size_t)1<<nbBits) - (size_t)1;
                          size_t const rNoiseLength = (FUZ_rand(&randState) & mask) + 1;
                          size_t const noiseLength = MIN(rNoiseLength, (size_t)compressedSize-pos);
                          size_t const noiseStart = FUZ_rand(&randState) % (COMPRESSIBLE_NOISE_LENGTH - noiseLength);
***************
*** 1517,1523 ****
              LZ4_setStreamDecode(&decodeStateSafe, NULL, 0);
              LZ4_setStreamDecode(&decodeStateFast, NULL, 0);
  
! #define BSIZE1 (dBufferSize - (maxMessageSize-1))
  
              /* first block */
              messageSize = BSIZE1;   /* note : we cheat a bit here, in theory no message should be > maxMessageSize. We just want to fill the decoding ring buffer once. */
--- 1517,1523 ----
              LZ4_setStreamDecode(&decodeStateSafe, NULL, 0);
              LZ4_setStreamDecode(&decodeStateFast, NULL, 0);
  
! #define BSIZE1 (dBufferSize - (maxMessageSize-(size_t)1))
  
              /* first block */
              messageSize = BSIZE1;   /* note : we cheat a bit here, in theory no message should be > maxMessageSize. We just want to fill the decoding ring buffer once. */
***************
*** 1549,1555 ****
              messageSize = maxMessageSize;
              iNext = BSIZE1+1;
              assert(BSIZE1 >= 65535);
!             memcpy(testInput + iNext, testInput + (BSIZE1-65535), messageSize);  /* will generate a match at max distance == 65535 */
              FUZ_CHECKTEST(dNext+messageSize <= dBufferSize, "Ring buffer test : second message should require restarting from beginning");
              dNext = 0;
  
--- 1549,1555 ----
              messageSize = maxMessageSize;
              iNext = BSIZE1+1;
              assert(BSIZE1 >= 65535);
!             memcpy(testInput + iNext, testInput + (BSIZE1-(size_t)65535), messageSize);  /* will generate a match at max distance == 65535 */
              FUZ_CHECKTEST(dNext+messageSize <= dBufferSize, "Ring buffer test : second message should require restarting from beginning");
              dNext = 0;
  
***************
*** 1605,1614 ****
          int const dst_min_len = 33 + (FUZ_rand(&randState) % dst_step);
          int const dst_max_len = 5000;
          int slen, dlen;
!         char* sbuf1 = (char*)malloc(src_buf_size + 1);
!         char* sbuf2 = (char*)malloc(src_buf_size + 1);
!         char* dbuf1 = (char*)malloc(dst_buf_size + 1);
!         char* dbuf2 = (char*)malloc(dst_buf_size + 1);
  
          assert(sHC != NULL);
          assert(dst_buf_size > dst_max_len);
--- 1605,1614 ----
          int const dst_min_len = 33 + (FUZ_rand(&randState) % dst_step);
          int const dst_max_len = 5000;
          int slen, dlen;
!         char* sbuf1 = (char*)malloc(src_buf_size + (size_t)1);
!         char* sbuf2 = (char*)malloc(src_buf_size + (size_t)1);
!         char* dbuf1 = (char*)malloc(dst_buf_size + (size_t)1);
!         char* dbuf2 = (char*)malloc(dst_buf_size + (size_t)1);
  
          assert(sHC != NULL);
          assert(dst_buf_size > dst_max_len);
`

**Comment by Cyan4973** [comment]
The C6385 warning at `lz4.c` line 491 is a false positive.
It believes that only 2 bytes are readable at this position, while actually 4 bytes are available. But since these 4 bytes were written in 2 consecutive commands, the analysis fails to detect that.

Unfortunately, it's very classical for code analysis tools to generate multiple false positive. Trying to reach "0 false positive" for all of them is not only not practical, but simply impossible (some code analysis tool will complain about things that other tools actually require) and sometimes dangerous, requiring to rewrite the code in weird ways which are difficult to understand and maintain (and may introduce new subtle bugs) just to please one version of one tool.

So it's always a judgment call to decide if a specific code analysis warning is worth addressing or not.

**Comment by Cyan4973** [comment]
As for : `fuzzer.c(497): warning C6385: Reading invalid data from 'compressedBuffer'.`,
well I'm using Visual Studio 2019 for my tests, and this specific code analysis warning doesn't show up.
Which shows that each version of the same analysis tool is free to change its analysis outcome.

Anyway, VS2022 complains that `compressedBuffer`'s content is invalid, but this buffer was filled just above by a call to `LZ4_compress_default()`, so its content is fine. And if there was a compression error, it's also detected before that point.

So yep, another false positive.

**Comment by Cyan4973** [comment]
@PrimalJohnScott, it seems you are suggesting a few code updates in the rest of your issue.
If you want to contribute them to `lz4`, you are welcome to submit them as a github PR,
it's much more convenient for detailed code review and merge.
