### ISSUE TITLE
LZ4F_freeCompressionContext return value should be void

### ISSUE THREAD

**Issue by xiaoyong-z** [lz4/lz4#1090]
It seems that LZ4F_freeCompressionContext always sucess, maybe the return value should be void here? This can avoid the additional check for developers.

```c++
LZ4F_errorCode_t LZ4F_freeCompressionContext(LZ4F_cctx* cctxPtr)
{
    if (cctxPtr != NULL) {  /* support free on NULL */
       FREEMEM(cctxPtr->lz4CtxPtr);  /* note: LZ4_streamHC_t and LZ4_stream_t are simple POD types */
       FREEMEM(cctxPtr->tmpBuff);
       FREEMEM(cctxPtr);
    }

    return LZ4F_OK_NoError;
}
```

**Comment by t-mat** [comment]
Good point.  Though I personally think it should return some error/success code by the following reasons:

(1) To keep API compatibility, we must keep it.
(2) It may fail in future for some reason (e.g. introduce new state to implement zlib style APIs, etc).
(3) If we can (strongly) define the behavior of the function, we may be able to add a sentence like "This function never fail" to the document.

Perhaps, you're thinking about compatibility with C++'s `nothrow` etc.  If so, please describe your situation.
( note for other readers: Sometimes, throwing exception from destructor is quite hard/annoying. )

Even if we don't change `LZ4F_freeCompressionContext()`, we can discuss about (3) or other solutions.

**Comment by xiaoyong-z** [comment]
Thanks for your explanation!  Actually this probem doesn't bring me any trouble. 
Just some comments in `lz4frame.h` bring me a little confusion, it shows that LZ4F_freeCompressionContext may return nonzero value. I'm curious under what circumstances it will return nonzero value. So i download the source code, and find that it always success, then i raised an issue here.

I think maybe (3) add some sentences in header file is a good choice?


Comments in lz4frame.h:
```
/*! LZ4F_createCompressionContext() :
 * The first thing to do is to create a compressionContext object, which will be used in all compression operations.
 * This is achieved using LZ4F_createCompressionContext(), which takes as argument a version.
 * The version provided MUST be LZ4F_VERSION. It is intended to track potential version mismatch, notably when using DLL.
 * The function will provide a pointer to a fully allocated LZ4F_cctx object.
 * If @return != zero, there was an error during context creation.
 * Object can release its memory using LZ4F_freeCompressionContext();
 */
LZ4FLIB_API LZ4F_errorCode_t LZ4F_createCompressionContext(LZ4F_cctx** cctxPtr, unsigned version);
LZ4FLIB_API LZ4F_errorCode_t LZ4F_freeCompressionContext(LZ4F_cctx* cctx);
```

**Comment by t-mat** [comment]
Thanks for the info.

> Just some comments in lz4frame.h bring me a little confusion, it shows that LZ4F_freeCompressionContext may return nonzero value. 

(edit : This first block is note for future readers who also have confusion.)

Yes, it may fail.  Maybe in the future.
If you're writing defensive code, please add extra check.  But it's okay not to check it though.

----

> I think maybe (3) add some sentences in header file is a good choice?

Please note that we've been asked multiple times to add zlib compatible "standard" APIs to LZ4F.
And as you know, almost all zlib APIs "may fail".

https://github.com/madler/zlib/blob/21767c654d31d2dccdde4330529775c6c5fd5389/zlib.h#L363-L374

So, if we decide to define the behavior of the API as a "never fail" function, it also means we'll refuse some part of these demand for LZ4F.

I'd like to wait for Yann.
Perhas we'll be able to agree that LZ4(F) version 1.x won't change current behavior and we can add it to the document.

**Comment by Cyan4973** [comment]
At the time this API was designed, it wasn't clear yet if this invocation would one day fail or not.
For example, maybe the function would detect that it's not operating on the right object, and decide fail. Or maybe a specific state value could disallow this operation. Or maybe the initial implementation was not supporting operating on `NULL` input pointer. Whatever.
So, as a defensive measure, a success return value was added.

But indeed, today this function is actually always successful, so knowing that, one could simply ignore the return value.

Now, I get the point, a success/error return value in the signature implies that the function _may_ fail, hence is a strong invitation to add a check. And adding error checks is not free, impacts both write and read complexity, hence velocity and maintenance, on top of potential spill over impact on upper layers (if the code may fail, then the caller has to consider what to do in case of failure).
So when a function never fails, it's better to signal it by making the return type `void`.
That's what I would probably select today.

Issue is, we are now locked by the requirement to keep the API compatible across versions.
So even if this function never fails, we have to preserve its signature, and therefore return a success value.

**Comment by t-mat** [comment]
:+1: for API stability.  So this request should be marked with "v2.0" milestone.

Perhaps we can add new API `void LZ4F_freeCompressionContext_neverFail(...)`.  But we also should review other LZ4F APIs for consistency.

**Comment by Cyan4973** [comment]
Yes, consistency also matters in such decisions.
There are little API details I would probably do differently today, 
but within each `LZ4` header, I keep the API consistent across versions.
