### ISSUE TITLE
Website needs to be updated: ecm 8086 assembly depacker no longer available on bitbucket

### ISSUE THREAD

**Issue by ecm-pushbx** [lz4/lz4#1097]
**Describe the bug**

[The LZ4 website](https://lz4.github.io/lz4/) lists this in the "Interoperable LZ4 ports and bindings" table:

> 8086 assembly decoder
> E. C. Masloch
> https://bitbucket.org/ecm/inicomp/src/default/

However, bitbucket has deleted all hg (Mercurial) repos since. The inicomp project has moved to https://hg.pushbx.org/ecm/inicomp/ (with [a few minor updates](https://hg.pushbx.org/ecm/inicomp/log/tip/lz4.asm) to the LZ4 depacker since).

**Comment by Cyan4973** [comment]
Thanks for the notification. The link has been updated.
