### ISSUE TITLE
One byte at time compression?

### ISSUE THREAD

**Issue by fcorbelli** [lz4/lz4#1106]
Regarding compressing a small block of memory (say ~ 4-64KB) is it possible (how?) to use LZ4 to efficiently compress it one byte at a time?

Suppose to have char buf[64000]   and output[1000000]
Instead of 
```
LZ4_compress_default(buf,output,64000,1000000);
```
something like (just pseudo-code)
```
for (int i=0;i<64000;i++)
  LZ4_compress_one_byte(buf[i],output);
LZ4_end_of_compress();
```

Why? Long to explain, let's say for implementation simplicity in a deduplicating archiver

Thanks to all answers

**Comment by Cyan4973** [comment]
Short answer is no, this is not supported.
Even if it was, this would be extremely inefficient.

**Comment by fcorbelli** [comment]
Thank you, I was 99% sure
Embedding LZ4 into zpaq is not easy, now 100% sure
