### ISSUE TITLE
GH-Actions: `ubuntu-18.04` is deprecated and will be unsupported by Apr/1/2023

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1137]
https://github.com/actions/runner-images/issues/6002

> We have started the deprecation process for Ubuntu 18.04. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 8/8/2022 and the image will be fully unsupported by 12/1/2022

Though I think that it'll be useful to support `ubuntu-18.04` in the next release of lz4.

**Comment by Cyan4973** [comment]
Interesting, 
18.04 is still within its LTS window, 
so it's surprising to deprecate it so soon.

Anyway, we can remove it from CI at any point in the future, this won't be a problem.

**Comment by t-mat** [comment]
> Interesting, 18.04 is still within its LTS window, so it's surprising to deprecate it so soon.

Yeah, but they said its their policy 😿 

https://github.com/actions/runner-images/issues/6002#issuecomment-1211854077

> > I am sad to see this removal of ubuntu-18.04 and hope you will reconsider.

> smistad as per the policy we only support the two latest LTS

**Comment by t-mat** [comment]
Great (and sane) news! ❤️ 

https://github.com/actions/runner-images/issues/6002#issuecomment-1235119350

> We have decided to prolong the deprecation until the official end of life — April 2023.
> Brownouts schedule has been adjusted as well to reflect the prolonged deprecation

**Comment by t-mat** [comment]
#1216 had been resolved this issue.
