### ISSUE TITLE
Add LeakSanitizer to our CI

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1140]
This issue partially continues #1007.

Since we don't have dedicated test for memory leak, introducing [LeakSanitizer](https://clang.llvm.org/docs/LeakSanitizer.html) may help us much.

Introducing phases may be

(1) Install LeakSanitizer.
(2) Build and run each program and example with LeakSanitizer to detect basic memory leak.
(3) Optional : Create dedicated test case for specific memory leak pattern, if we will found.
(4) Optional : Measure coverage of LZ4/HC/F/File APIs and add new example which covers unused APIs (as a example and test).

**Comment by Cyan4973** [comment]
Don't we have `valgrind` tests already, able to catch memory leaks ?

Note that I'm in favor of introducing the Leak Sanitizer to CI, I think it's a good idea.
Even if the Leak Sanitizer doesn't detect any new leak, it's still valuable to deploy it in CI.
It's just that I believe we don't start from a blind place, 
so I would expect a fairly good starting situation with regards to leaks.

**Comment by dpelle** [comment]
I see that asan is used in CI and asan includes lsan.
So unless I'm overlooking something, adding a lsan check would not add value.

**Comment by Cyan4973** [comment]
@t-mat: is there anything remaining to do on this topic ?
Keeping in mind we already have `asan` and `valgrind` tests in CI ?

**Comment by t-mat** [comment]
@Cyan4973, no, I don't need to add anything to this issue.
At that time, I think we need more check/scenario for memory/resource leakage.  But since we don't see any issue about it, I think our test is 100% okay for them.

MT/Async facility may need more checking, but it should be another issue.
