### ISSUE TITLE
lz4_decompress_safe_partial faster than lz4_decompress_safe ???

### ISSUE THREAD

**Issue by freedomhust** [lz4/lz4#1146]
**Describe the bug**
Hello, I am testing the lz4_decompress_safe_partial() and lz4_decompress_safe() function, What surprised me was that  when decompress 16KB data, lz4_decompress_safe_partial() was faster than lz4_decompress_safe(), Is my code wrong?

Here is my code :
```c
#include "stdio.h"
#include "string.h"
#include "lz4.h"
#include <x86intrin.h>
#include <time.h>

char source[40960]={0};
char sources[4][40960]={0};

#define BUFFER_SIZE 4096*4

static __inline__ unsigned long long GetCycleCount(void)
{
    unsigned long long r;
    __asm__ __volatile__("" : : : "memory");
    r =  __rdtsc();
    __asm__ __volatile__("" : : : "memory");
    return r;
}

void sjs(char a[],int x, int y)
{
	char *p;
	srand(y);
	for(p=a;p<a+x;p++)
	{
		*p=rand()%('z'-'a'+1)+'a';
	}
}

int main(void)
{
  sjs(sources[0],4096,0);
  sjs(sources[1],4096,2);
  sjs(sources[2],4096,6);
  sjs(sources[3],4096,8);
  printf("%s\n",source);
  memcpy(source,sources[0],4096);
  memcpy(source+4096,sources[1],4096);
  memcpy(source+(4096*2),sources[0],4096);
  memcpy(source+(4096*3),sources[1],4096);

  int srcLen = (int)strlen(source);
  char cmpBuffer[2*BUFFER_SIZE];
  char outBuffer[2*BUFFER_SIZE];
  int cmpSize;
  int i;

  int dstSize = LZ4_compressBound(BUFFER_SIZE);

  unsigned long long xGet;
  unsigned long long yGet;
  xGet = GetCycleCount();
  cmpSize = LZ4_compress_default(source, cmpBuffer, BUFFER_SIZE, dstSize);
  yGet = GetCycleCount();

  printf("%llu\n",yGet-xGet);
  printf("%d %d\n",cmpSize,srcLen);
  printf("compress ratio %lf\n",(double)cmpSize/(4096*4));

  srcLen = BUFFER_SIZE;
  xGet = GetCycleCount();
  for (i = cmpSize; i < cmpSize+10000; ++i) {
    int result = LZ4_decompress_safe_partial(cmpBuffer, outBuffer, cmpSize, srcLen, dstSize);
    if ((result < 0) || (result != srcLen) || memcmp(source, outBuffer, srcLen)) {
      printf("test decompress-partial error \n");
      return -1;
    }
  }
  yGet = GetCycleCount();
  printf("parital decode 16KB cost %llu\n",yGet-xGet);

  srcLen = BUFFER_SIZE - 4096;
  xGet = GetCycleCount();
  for (i = cmpSize; i < cmpSize+10000; ++i) {
    int result = LZ4_decompress_safe_partial(cmpBuffer, outBuffer, cmpSize, srcLen, dstSize);
    if ((result < 0) || (result != srcLen) || memcmp(source, outBuffer, srcLen)) {
      printf("test decompress-partial error \n");
      return -1;
    }
  }
  yGet = GetCycleCount();
  printf("parital decode 12KB cost %llu\n",yGet-xGet);

  srcLen = BUFFER_SIZE - 4096*2;
  xGet = GetCycleCount();
  for (i = cmpSize; i < cmpSize+10000; ++i) {
    int result = LZ4_decompress_safe_partial(cmpBuffer, outBuffer, cmpSize, srcLen, dstSize);
    if ((result < 0) || (result != srcLen) || memcmp(source, outBuffer, srcLen)) {
      printf("test decompress-partial error \n");
      return -1;
    }
  }
  yGet = GetCycleCount();
  printf("parital decode 8 KB cost %llu\n",yGet-xGet);

  srcLen = BUFFER_SIZE - 4096*3;
  xGet = GetCycleCount();
  for (i = cmpSize; i < cmpSize+10000; ++i) {
    int result = LZ4_decompress_safe_partial(cmpBuffer, outBuffer, cmpSize, srcLen, dstSize);
    if ((result < 0) || (result != srcLen) || memcmp(source, outBuffer, srcLen)) {
      printf("test decompress-partial error \n");
      return -1;
    }
  }
  yGet = GetCycleCount();
  printf("parital decode 4 KB cost %llu\n",yGet-xGet);
  
  srcLen = BUFFER_SIZE;
  xGet = GetCycleCount();
  for (i = cmpSize; i < cmpSize+10000; ++i) {
    int result = LZ4_decompress_safe(cmpBuffer, outBuffer, cmpSize, dstSize);
    if ((result < 0) || (result != srcLen) || memcmp(source, outBuffer, srcLen)) {
      printf("test decompress-partial error \n");
      return -1;
    }
  }
  yGet = GetCycleCount();
  printf("fully   decode 16KB cost %llu\n",yGet-xGet);

  printf("test decompress-partial OK \n");
  return 0;
}

```

And My result
```c
compress ratio 0.254517
parital decode 16KB cost 18234909
parital decode 12KB cost 14627120
parital decode 8 KB cost 9833132
parital decode 4 KB cost 5935420
fully   decode 16KB cost 23306100
test decompress-partial OK

compress ratio 0.504395
parital decode 16KB cost 39547444
parital decode 12KB cost 27681452
parital decode 8 KB cost 16605728
parital decode 4 KB cost 8839512
fully   decode 16KB cost 45082612
test decompress-partial OK

compress ratio 0.754028
parital decode 16KB cost 25695760
parital decode 12KB cost 18572052
parital decode 8 KB cost 9183416
parital decode 4 KB cost 5946812
fully   decode 16KB cost 25760800
test decompress-partial OK

compress ratio 1.002869
parital decode 16KB cost 30540472
parital decode 12KB cost 19930736
parital decode 8 KB cost 12949352
parital decode 4 KB cost 6082228
fully   decode 16KB cost 30483300
test decompress-partial OK 
```

**Comment by Cyan4973** [comment]
There shouldn't be more than a minor difference when decompressing the full block.
That's in theory.

In practice, other random impacts are possible,
such as different instruction alignments,
resulting in random performance differences, which can be actually quite large (up to ~+20%).

The randomness is not between runs, it's between produced binaries.

To mitigate this impact, one method consists in setting up many compilers, typically multiple versions of `gcc` and multiple versions of `clang`, and reproduce speed measurements across all these compilers.
Now, if the difference is consistent, then we probably have something to look into.

But if the gains vary and the winner changes depending on the compiler version, then it might be related to instruction alignment, an effect which is not controllable from C code, supposed the domain of the compiler, and translates into random performance changes for minor if not unrelated code changes.

That's the kind of side effect you get for getting too close to cpu limits ...

**Comment by freedomhust** [comment]
Thanks! perhaps my test case is too special(The next 12KB is a copy of the previous 4KB). It's enough to know that there's not much difference between the two functions. 

I have two questions:

1. Can I replace all lz4_decompress_safe() with lz4_decompress_safe_partial() without significant performance degradation? 

2. In my scenario, sometimes, the four 4KB "ABCD" I just need A or B or C or D. Is there any possible to just decompress C or D  to dst without fully decompressing A and B? is it much slower than just using lz4_decompress_safe_partial() or need extra buffer so there is no implementation?

**Comment by freedomhust** [comment]
> There shouldn't be more than a minor difference when decompressing the full block. That's in theory.
> 
> In practice, other random impacts are possible, such as different instruction alignments, resulting in random performance differences, which can be actually quite large (up to ~+20%).
> 
> The randomness is not between runs, it's between produced binaries.
> 
> To mitigate this impact, one method consists in setting up many compilers, typically multiple versions of `gcc` and multiple versions of `clang`, and reproduce speed measurements across all these compilers. Now, if the difference is consistent, then we probably have something to look into.
> 
> But if the gains vary and the winner changes depending on the compiler version, then it might be related to instruction alignment, an effect which is not controllable from C code, supposed the domain of the compiler, and translates into random performance changes for minor if not unrelated code changes.
> 
> That's the kind of side effect you get for getting too close to cpu limits ...

Thanks! perhaps my test case is too special(The next 12KB is a copy of the previous 4KB). It's enough to know that there's not much difference between the two functions.

I have two more questions:

1. Can I replace all lz4_decompress_safe() with lz4_decompress_safe_partial() without significant performance degradation?

2. In my scenario, sometimes, the four 4KB "ABCD" I just need A or B or C or D. Is there any possible to just decompress C or D to dst without fully decompressing A and B? is it much slower than just using lz4_decompress_safe_partial() or need extra buffer so there is no implementation?

Thanks a lot ^_^

**Comment by Cyan4973** [comment]
1. Yes, that's the expectation
2. No, that's impossible. You would need to compress A,B,C and D separately, as 4 KB blocks. Obviously, it would impact the compression ratio.

**Comment by freedomhust** [comment]
> 1. Yes, that's the expectation
> 2. No, that's impossible. You would need to compress A,B,C and D separately, as 4 KB blocks. Obviously, it would impact the compression ratio.

Thank you so much, my previous plan was to implement a function that could read any 4 KB of 16 KB of compressed data and not fully decompress the previous 4 KB data, which seems unnecessary according to your suggestions. lz4_decompress_safe_partial() can already solve half the problem.
