### ISSUE TITLE
Missing Windows binary packages in 1.9.4 release

### ISSUE THREAD

**Issue by tech189** [lz4/lz4#1152]
Hi, would it be possible to get pre-built Windows binary packages with the CLI for version 1.9.4, just like the previous releases? For example from the 1.9.3 release: https://github.com/lz4/lz4/releases/download/v1.9.3/lz4_win64_v1_9_3.zip Thanks!

**Comment by Cyan4973** [comment]
Sure!
`lz4` pre-built Windows binaries for `v1.9.4` have been uploaded onto the `release` page.

**Comment by tech189** [comment]
Thank you very much!
