### ISSUE TITLE
How to determine the size of `regen_buffer` in common cases? 

### ISSUE THREAD

**Issue by ChaomingZhangCN** [lz4/lz4#1153]
https://github.com/lz4/lz4/blob/4de3e98ad206f6afc85bbb4268f6c3a64fc2d487/examples/simple_buffer.c#L76

**Comment by t-mat** [comment]
[LZ4 block format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md) doesn't have any information of `src_size` (uncompressed (raw) size of original data).
So, if you'll use LZ4 or LZ4HC API (LZ4 block format APIs), you must store `src_size` as a meta data.

Please read the guidance comment of the code

https://github.com/lz4/lz4/blob/v1.9.4/examples/simple_buffer.c#L67-L73
