### ISSUE TITLE
Assistance converting .lz4, .art & .art.lz4 files into image files?

### ISSUE THREAD

**Issue by Freefromdespair** [lz4/lz4#1154]
Hello, I'm new here. To be honest, I really do not know anything about .lz4 files, but, I am asking if anyone can help me in converting some video game files into images? They're .lz4 and .art.lz4 files that I can't open in any kind of way and I've been at it for weeks trying to interact with them. I apologize if I'm not welcome here or if I'm in the wrong place to ask, but my search for answers landed me here. I'm even willing to pay for assistance if this is something that is not easy to solve.

**Comment by Cyan4973** [comment]
Have you heard of the [`lz4` data compression tool](https://packages.ubuntu.com/search?keywords=lz4) ?
Would you be able to install it ?
In which case what is your Operating System ?

**Comment by Freefromdespair** [comment]
64 bit Windows 10?

**Comment by Freefromdespair** [comment]
Even if I did install it, I'm not too tech savvy to know how to use it or how it works

...Is it?

**Comment by Cyan4973** [comment]
Do you know how to use a command line interface ?

**Comment by Freefromdespair** [comment]
No sir.

 I'm willing to learn how, if that's ever a case. Might not be simple, of course.

**Comment by Cyan4973** [comment]
OK,
let's try it this way : 
1) go to https://github.com/lz4/lz4/releases/tag/v1.9.4, download pre-generated binary [`lz4_win64_v1_9_4.zip`](https://github.com/lz4/lz4/releases/download/v1.9.4/lz4_win64_v1_9_4.zip)
2) unzip it wherever you want, you should see a `lz4.exe` program. Depending on your file manager options, the `.exe` might be hidden or not.
3) depending on settings, maybe Windows will complain this file does not come from a Microsoft store, and require you to validate you really want to run this file. So launch it once (double click), validate if Windows asks to. A command line interface will appear and disappear quickly. No other impact at this stage.
4) get your `*.lz4` files. One by one, drag'n'drop them onto the `lz4.exe`. Hopefully, it will decode them, and create a decompressed file with the same name in the same directory, but without the `.lz4` suffix.

**Comment by Freefromdespair** [comment]
ok. I'll follow these steps and come back later to give updates. thanks.

**Comment by Freefromdespair** [comment]
I did use the lz4.exe, but here's the issue:

after dropping the .art.lz4 file into the program you recommended, it becomes a .art file with 0 kilobytes, and I can't open it or convert with any software. I'm guessing the lz4.exe does work, but maybe it could be the files I'm using don't work or there's something even more specific that opens up these files. I don't know. I'm wondering if you even might know what happens if I sent you the files myself to experiment with. They're safe to use and under a .rar compression file. 

It might be out of the realm of discussing about the .lz4 program use, but if you're interested, I can send these files and gladly appreciate any help I can get. Really don't know how computers work. I'll pay for any assistance, even.

**Comment by Cyan4973** [comment]
Indeed, if these `*.lz4` files do not respect the [LZ4 Frame format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md), then they are by definition undecodable by the `lz4` utility.

It _could_ be that these files employ the inner LZ4 Block format, justifying the `.lz4` suffix (though they should not use it), and then encapsulate it into their own custom header.
In which case, retro-engineering the custom format is a whole different level of discussion, and such a task will definitely need decent decoder time to move forward. 

If you aren't able to do that yourself, be aware this can be an expensive investigation.

**Comment by Freefromdespair** [comment]
Just out of curiosity, how long would it potentially take and how expensive is the research?

**Comment by Cyan4973** [comment]
That's the problem,
it's unknown.
One has to start to even give a hint.

**Comment by Freefromdespair** [comment]
I understand now. 

Man, coding and understanding computers to this extent is tough. 

I have ONE more question about my issue then:

Do you know where I can find legitimate and professional assistance in converting .art.lz4 and .lz4 files into images? Or someone that understands computers that well?

**Comment by Cyan4973** [comment]
I don't know personally,
I would just assume it's not impossible to find.
Many programmers out there are likely capable of extracting images from these files, if they are present.
Many is not the same as **all**, but that's definitely not _rare_ either.
I've heard there are places where it's possible to request such a task specifically and get some quote, and start the relation from there, but I've no direct experience myself.
