### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by hakan-demirli** [lz4/lz4#1156]
Can we change `Block` to `Data Blocks` where the general structure of LZ4 frame format is shown as a table?
https://github.com/lz4/lz4/blob/4de3e98ad206f6afc85bbb4268f6c3a64fc2d487/doc/lz4_Frame_format.md?plain=1#L64

**Why should it change:**

My custom lz4 decoder was having problems with decoding files larger than 256KB. After debugging for about an hour, I noticed that the limit comes from the constant max block size which is specified in the compressor that I am using to test my decoder.
https://github.com/lz4/lz4/blob/4de3e98ad206f6afc85bbb4268f6c3a64fc2d487/examples/frameCompress.c#L21
Since I didn't properly read the documentation and glanced at the table before starting. I assumed that the part only consist of bunch of blocks back to back which are documented [here](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md).
So, such clarification can help people who don't read docs until it's too late.

**Comment by Cyan4973** [comment]
Sure @hakan-demirli !
It's a simple enough clarification. 
Done.
