### ISSUE TITLE
multi-threading for supporting overlap of compression and file write

### ISSUE THREAD

**Issue by xinglin** [lz4/lz4#116]
Hi,

It seems to me that in the current implementation, once a block is compressed, then it is written to the output, using the same thread. Could it be possible to add support to use two separate threads here: one does compression, and the other does disk writes? It will help overlap disk writes with compression and likely speedup the whole process. Here are some measurements I have taken. 

input file is 3.3GB. 

compression time (input and output are stored in mem): 15 seconds
$ lz4 /dev/shm/input /dev/shm/input.lz4 

copy time (disk write): 12 seconds
$ cp /dev/shm/input.lz4 /dev/sda4/

compression + disk write time: 26 seconds
$ lz4 /dev/shm/input /dev/sda4/input.lz4

As we can see, there is almost no overlap in compression and disk write time (15+12 ~= 26). If we have two separate threads, one does compression and the other does disk writes, I think we can overlap these two tasks and get the end-to-end time (the 3rd command) reduced to ~15 seconds. The problem with current implementation is when we call a fwrite() to write a compressed block, it is likely cached in the page cache. The actual disk writes will happen only when we close the output stream. Thanks,

-Xing

**Comment by Cyan4973** [comment]
Hi Xing

lz4io multi-threading is a long term objective, so sure, we can keep it in the tracker.
As suggested by @t-mat , we'll better match C11 multi-threading model to ensure best portability and future maintenance, albeit at the cost of some library to remain C99 compatible.

In the meantime, I would like to suggest you this minor modification of your benchmark exercise : 
````
$ lz4 -B4D /dev/shm/input /dev/sda4/input.lz4
````

This triggers the 64KB linked block mode (which will become default in a near future release). In my experience, it achieves better throughput in several use-cases.

**Comment by ido** [comment]
Multiple threads might not be necessary if you `mmap` the (sparse) output file and make lz4 use the `mmap`'ed memory directly as the buffer space it writes to during the compression process...  Perhaps try that first before threads?

**Comment by xinglin** [comment]
Hi Yann,

Thanks for letting me know about your plan. Looks like this feature is not going to be available anytime soon. In that case, I think I can try to work on this myself when I really need that feature. 

Setting -B4D does not seem to increase the throughput: the runtime is changed from 26.7 seconds to 28.2 seconds. Not a significant increase though.

**Comment by Cyan4973** [comment]
Thanks for the feedback.
Now that I remember, 64KB seemed to help for pipe scenario, from/to lz4 to/from another process.
This is apparently not the same outcome when writing to disk. Good to know :+1:

**Comment by xinglin** [comment]
Hi @ido,

I do need to write the output to a disk. I have tried the case to write output to memory (e.g., write to /dev/shm/). 

-Xing

**Comment by ido** [comment]
@xinglin You can `mmap` a file on disk, even one that does not exist yet, and `ftruncate` it to grow it to the right (or maximum) output size (sparsely), write to it, then `ftruncate` it again to shrink it back to the final size.  It's more efficient than `fwrite` in this case because of coherent file buffers in Linux, there is no need for a separate thread or a separate `fwrite`/copy in that case.  You can learn more about `mmap` here: http://beej.us/guide/bgipc/output/html/multipage/mmap.html

**Comment by xinglin** [comment]
Hi @ido , thanks for your suggestions. I can try that first and see what throughput I can get from it. Thanks, 

-Xing

**Comment by xinglin** [comment]
I have tried to implement to use mmap() for output but this does not seem to help: all writes are delayed until we call a msync() and the end-to-end runtime is about the same as vanilla lz4 (28 seconds). 

- Vanilla lz4 (r130)
root@node-0:/mnt/hadoop-tmp# time (lz4-master/programs/lz4 /dev/shm/linux-2.6.30-10tar /mnt/hadoop-tmp/linux.lz4; sync)
Compressed 3531868160 bytes into 1215350236 bytes ==> 34.41%

real	0m28.886s
user	0m13.257s
sys	0m1.696s

- lz4 using mmap() to for output. 
root@node-0:/mnt/hadoop-tmp# time (lz4/programs/lz4 /dev/shm/linux-2.6.30-10tar /mnt/hadoop-tmp/linux.mmap.lz4)
ftruncate to size 3531868160
Compressed 3531868160 bytes into 1215350236 bytes ==> 34.41%

real	0m28.830s
user	0m13.353s
sys	0m1.812s

I have also pushed my changes to my github repository. The diff is here in case you are interested to check it out. (I did not fix the warning of "implicit declaration of function ‘ftruncate’". It should have been defined in unistd.h.).

diff:
https://github.com/Cyan4973/lz4/compare/master...xinglin:master

my lz4 repository:
https://github.com/xinglin/lz4/commits/master

-Xing

**Comment by jmagnuson** [comment]
@xinglin I got your branch compiling on Windows 7 with the help of a [mmap wrapper](https://code.google.com/p/mman-win32/).  Here are some of my results:

- hard disk to hard disk compression  
```shell
jon@r4 /d/temp/lz4mmap_test $ time lz4_nommap.exe linux-2.6.30.10.tar linux_nommap.lz4
Compressed 353208320 bytes into 121551341 bytes ==> 34.41%

real    0m4.743s
user    0m0.000s
sys     0m0.015s

jon@r4 /d/temp/lz4mmap_test $ time lz4_mmap.exe linux-2.6.30.10.tar linux_mmap.lz4
ftruncate to size 353208320
Compressed 353208320 bytes into 121551341 bytes ==> 34.41%

real    0m1.471s
user    0m0.000s
sys     0m0.000s
```

- ramdisk to hard disk compression  
```shell
jon@r4 /d/temp/lz4mmap_test2 $ time lz4_nommap.exe /r/linux-2.6.30.10.tar ./linux_nommap.lz4
Compressed 353208320 bytes into 121551341 bytes ==> 34.41%

real    0m4.710s
user    0m0.000s
sys     0m0.000s

jon@r4 /d/temp/lz4mmap_test2 $ time lz4_mmap.exe /r/linux-2.6.30.10.tar ./linux_mmap.lz4
ftruncate to size 353208320
Compressed 353208320 bytes into 121551341 bytes ==> 34.41%

real    0m1.505s
user    0m0.000s
sys     0m0.015s
```

- ramdisk to hard disk compression with -B4D flag  
```shell
jon@r4 /d/temp/lz4mmap_test3 $ time lz4_nommap.exe -B4D /r/linux-2.6.30.10.tar ./linux_nommap.lz4
Compressed 353208320 bytes into 121507704 bytes ==> 34.40%

real    0m4.990s
user    0m0.000s
sys     0m0.015s

jon@r4 /d/temp/lz4mmap_test3 $ time lz4_mmap.exe -B4D /r/linux-2.6.30.10.tar ./linux_mmap.lz4
ftruncate to size 353208320
Compressed 353208320 bytes into 121507704 bytes ==> 34.40%

real    0m1.733s
user    0m0.000s
sys     0m0.015s
```
Should probably be taken with a grain of salt, but I measured a noticeable improvement.

**Comment by xinglin** [comment]
Hi @jmagnuson,

This is interesting. I am not sure what the exact reason. Just double check, msync() is also called before you close the output handle, correct? 

+    /* Deal with output file */
+    msync(dstFileBuffer, compressedfilesize, MS_SYNC);
+    munmap(dstFileBuffer, fileSize);
+    if ( (ftruncate(dstFiledesc, compressedfilesize)) != 0) {
+    	perror("ftruncate to compressed file size");
+       	return 1;
+    }
+    close(dstFiledesc);

**Comment by ido** [comment]
Hi @xinglin: What kernel and glibc version are you using?  I was able to achieve similar speedup to @jmagnuson using the mmap approach.  The performance improvement would be dependent on how you use mmap (what flags you pass), kernel versions (3.0 and newer should be fine), some sysctl settings, memory availability, etc.    I probably won't have time to follow up on this in the near future, but hope you were able to achieve the results you needed.

As a side note, you should not need to use `msync(...,MS_SYNC)` at all before `munmap` as the kernel can flush file cache/buffers to disk asynchronously on its own in the background (even after the process has exited).  The changes without msync() provided that you're using MAP_SHARED should be visible from other processes.  As long as your kernel version is recent (>= 2.6.32 if I recall correctly), you should see similar results, it should support coherent file buffers such that the same physical memory that you have `mmap()`ed **when using `MAP_SHARED`** (if on a file) don't require the kernel to copy the page when a new process reads that same page/block of the file.  I *think* that `MAP_PRIVATE` (which hides changes from other processes and defers writes) requires copying written-to pages by a process, which can slow things down. (The MAP_PRIVATE part is unverified, requires measurement before you believe me on this one.)  

(Some background: Asynchronously, it used to be that `pdflush`/`kupdated` kernel threads would write dirty file buffers to disk.  I think that mechanism has changed to a multiqueue/multithreaded approach -- check out BDI/`bdi_writeback` for more background.  There are some sysctl settings like `nr_pdflush_threads`, etc. that might affect performance here, especially in low memory environments.)

**Comment by Cyan4973** [comment]
This item is not on LZ4 roadmap, and is unlikely to become part of it in the foreseeable future.
