### ISSUE TITLE
Expose or document a constant that describes a best-case minimal compression length

### ISSUE THREAD

**Issue by tristan957** [lz4/lz4#1166]
**Is your feature request related to a problem? Please describe.**
In our storage engine work, we have to determine whether compression will save any space on-media.

**Describe the solution you'd like**
A constant or documentation that describes a best-case minimal compression length which actually reduces the length of the given data.

**Comment by Cyan4973** [comment]
The question is not clear, or could be interpreted in multiple ways.
Best-case minimal compression length is ~`srcSize / 250`, as [documented in the LZ4 Block format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md#compressed-block-format).
But this kind of performance is only reachable for extremely simple cases, hence generally not reached.
It's also completely unrelated to data compressibility or not.
It's unclear to me why this information would be useful.

**Comment by tristan957** [comment]
In our storage engine, we provide the capability of compressing values.

Essentially we have some logic that looks like this:

```
if (wants_compression && len(value) >= XXX) {
  compressed_value = compress(value);
  value = len(compressed_value) < len(value) ? compressed_value : value;
}
```

My question is given a value of some best-case scenario for lz4, like a run of `"000000000000..."` for example, what would that XXX be? Phrased another way, what is the minimal amount of overhead for lz4 given a best-case scenario value?

But if there is no good answer to this question, that I can remove that `XXX` check.

**Comment by tristan957** [comment]
I realize that I may have been naive initially because the overhead of lz4 is probably pretty dependent on the length of the original value to compress.

**Comment by Cyan4973** [comment]
The [LZ4 Block format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md#end-of-block-conditions) specifies that, to be compressible, an (independent) input must have a length >= 13.
