### ISSUE TITLE
' ./vcpkg integrate install ' cmd fails

### ISSUE THREAD

**Issue by Urbaner3** [lz4/lz4#1181]
write_contents("/root/.vcpkg/vcpkg.path.txt"): No such file or directory
the respond. Just fail. no idea what to do next

**Expected behavior**
Please describe what you expected to happen.

**To Reproduce**
4. See error '...'

**System (please complete the following information):**
 - Ubuntu 20.04.1-
 - Linux urbaner.site 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by Cyan4973** [comment]
I presume you are following instructions at : https://github.com/lz4/lz4#building-lz4---using-vcpkg ?

This seems to be a `vcpkg` issue, 
unrelated to `lz4`.

You may also want to reach https://github.com/microsoft/vcpkg .

cc @NancyLi1013
