### ISSUE TITLE
Is there a way to decompress from the middle of the compressed data?

### ISSUE THREAD

**Issue by sunhongmin225** [lz4/lz4#1183]
Hi, thanks for having this superior algorithm.

I am currently trying to compress/decompress a list of 64-bit integers. I've written below code by modifying [simple_buffer.c](https://github.com/lz4/lz4/blob/dev/examples/simple_buffer.c).

```c
/* Dependencies */
#include <stdio.h>   // For printf()
#include <string.h>  // For memcmp()
#include <stdlib.h>  // For exit()
#include "lz4.h"     // This is all that is required to expose the prototypes for basic compression and decompression.

/*
 * Simple show-error-and-bail function.
 */
void run_screaming(const char* message, const int code) {
  printf("%s \n", message);
  exit(code);
}

/*
 * main
 */
int main(void) {
  /* Compression */
  int num_elems = 5;
  int64_t* src_int = (int64_t*) malloc(num_elems * sizeof(int64_t));
  src_int[0] = 123123124;
  src_int[1] = 334234;
  src_int[2] = 454365346;
  src_int[3] = 23123123;
  src_int[4] = 3423423;
  const int src_size = num_elems * sizeof(int64_t);
  printf("src_size in bytes = %d\n", src_size);
  const int max_dst_size = LZ4_compressBound(src_size);
  printf("max_dst_size in bytes = %d\n", max_dst_size);
  int64_t* compressed_data = (int64_t*) malloc((size_t)max_dst_size);
  if (compressed_data == NULL)
    run_screaming("Failed to allocate memory for *compressed_data.", 1);
  const int compressed_data_size = LZ4_compress_default((const char*) src_int, (char*) compressed_data, src_size, max_dst_size);
  printf("compressed_data_size in bytes = %d\n", compressed_data_size);
  if (compressed_data_size <= 0)
    run_screaming("A 0 or negative result from LZ4_compress_default() indicates a failure trying to compress the data. ", 1);
  if (compressed_data_size > 0)
    printf("We successfully compressed some data! Ratio: %.2f\n",
        (float) compressed_data_size/src_size);
  compressed_data = (int64_t *) realloc(compressed_data, (size_t)compressed_data_size);
  if (compressed_data == NULL)
    run_screaming("Failed to re-alloc memory for compressed_data.  Sad :(", 1);

  /* Decompression */
  int64_t* const regen_buffer = (int64_t*) malloc(src_size);
  if (regen_buffer == NULL)
    run_screaming("Failed to allocate memory for *regen_buffer.", 1);
  int target_output_size = (num_elems - 1) * 8;
  const int decompressed_size = LZ4_decompress_safe_partial((char*) (compressed_data), (char*) regen_buffer, src_size, target_output_size, src_size);
  printf("decompressed_size in bytes = %d\n", decompressed_size);
  if (decompressed_size < 0)
    run_screaming("A negative result from LZ4_decompress_safe indicates a failure trying to decompress the data.  See exit code (echo $?) for value returned.", decompressed_size);
  if (decompressed_size >= 0)
    printf("We successfully decompressed some data!\n");

  /* Validation */
  // We should be able to compare our original *src with our *new_src and be byte-for-byte identical.
  for (int i = 0; i < num_elems - 1; i++) {
    printf("src_int[%d] = %ld\n", i, src_int[i]);
    printf("regen_buffer[%d] = %ld\n", i, regen_buffer[i]);
  }
  if (memcmp(src_int, regen_buffer, src_size - 1 * 8) != 0)
    run_screaming("Validation failed.  *src and *new_src are not identical.", 1);
  printf("Validation done.\n");
  free(src_int);
  free(compressed_data);
  free(regen_buffer);
  return 0;
}
```

As you can see, this code decompresses the first `(num_elems - 1) * 8` bytes by using `LZ4_decompress_safe_partial`. However, what I want to do is **to only decompress particular portion of the compressed data, and retrieve particular elements of the given source**.

For instance, after compressing all the `src_int[0], ..., src_int[4]` into `compressed_data`, let's say I only want to retrieve `src_int[2]` and `src_int[3]` as the output of the decompression, by only partially decompressing `compressed_data`.

[The document](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L274) says that the first argument of `LZ4_decompress_safe_partial` indicates where to start the decompression. How do I determine the starting position of the `compressed_data` which relates to `src_int[2]`? Is there any meta-data or other way to figure this out? Also, I assume that, since I want to have two 64-bit integers decompressed, the [targetOutputSize](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L276) should be equal to `2 * 8`. Could you confirm that this is correct?

Thanks in advance.

**Comment by Cyan4973** [comment]
It seems the use case you look for is not supported by `LZ4`, at least not with the granularity your scenario implies.

It's common, in databases, to store data in small independent blocks, in order to allow random access.
But the granularity is limited to the block size, which is typically 16 KB, sometimes as low as 4 KB.
It's not reaching the level of individual 8-bytes fields.

One thing to keep in mind is that compression ratio goes down as `srcSize` decreases.
Already, at 4 KB block size, the final compression ratio will be substantially worse than a full continuous compression.

This can be partially compensated for by using dictionaries.
But even with dictionaries, it helps to the point that blocks could be 1 KB in size and still deliver reasonable compression performance, but not to the point of extracting individual fields.

**Comment by sunhongmin225** [comment]
Thanks for your answer.
