### ISSUE TITLE
blockStreaming_linebyline got some issue..

### ISSUE THREAD

**Issue by lilingzhiatshenzhen** [lz4/lz4#1194]
Dear Sir: 
            I tried to complied it into an android project with JNI interface...but When I using blockstreaming_linebyline.c's compress and decompress...the result is totally different with the original file ..is this feature full tesed or not? 
           We almost using the 100% source code of this project..only pass the file path and name to C library

**Comment by t-mat** [comment]
>  ..is this feature full tesed or not?

It's been fully tested for [at least eight years](https://github.com/lz4/lz4/commit/43465ae8ff2ff07020ef6183172c4160ec6415fb) in GitHub Actions and travis-ci.  Of course I don't say there's no mistake though.  But please refer the following invocation commands in our `examples/Makefile`

https://github.com/lz4/lz4/blob/v1.9.4/examples/Makefile#L82-L102

----

I don't kwow much about your situation.  But please check the following things:

(1) With ndk-build, please cross-compile the test code for Android system and transfer and run it via `adb`. 
I have no idea you've checked the example with this method.  But before using JNI, this test must be done.

(2) Make sure some constants are suitable for your project.

The following hard-coded constants in `main()` may not fit your application

```
        MESSAGE_MAX_BYTES   = 1024,
        RING_BUFFER_BYTES   = 1024 * 256 + MESSAGE_MAX_BYTES,
```

**Comment by lilingzhiatshenzhen** [comment]
just sample to do below ...really don't know why the result is not correct

JNIEXPORT jbyteArray JNICALL
Java_com_shanreal_gb_utils_Lz4Utils_lz4_1compress(JNIEnv *env, jclass clazz, jstring path,
                                                  jstring out_path) {
    enum {
        MESSAGE_MAX_BYTES   = 1024,
        RING_BUFFER_BYTES   = 1024 * 256 + MESSAGE_MAX_BYTES,
    };



    //freopen("/storage/emulated/0/test.lzw", "wr", stdin);	//
   // freopen("/storage/emulated/0/C_jni_stdout.txt", "wb", stdout);	//
   // freopen("/storage/emulated/0/C_jni_stderr.txt", "wb", stderr);	//
    char* in_file_path = (char *) (*env).GetStringUTFChars(path, 0);
    char* out_file_path = (char *) (*env).GetStringUTFChars(out_path, 0);
   // fprintf(stderr,"输入文件%s，输出文件%s\n ", in_file_path, out_file_path);
    FILE* inpFp = fopen(in_file_path, "rb");
    FILE* outFp = fopen(out_file_path, "wb");

//    FILE* printf_file = fopen("/storage/emulated/0/C_printf.txt", "wb");
//    fprintf(stdout, "输入文件%s，输出文件%s\n ", in_file_path, out_file_path);
//    fwrite(stdout,1,strlen(in_file_path),printf_file);
//    fwrite(stdout,1,strlen(in_file_path),printf_file);

    test_compress(outFp, inpFp, MESSAGE_MAX_BYTES, RING_BUFFER_BYTES);


    fclose(inpFp);
    fclose(outFp);
    //fclose(printf_file);
    jbyteArray data =env->NewByteArray(1);

    return data;
    // TODO: implement lz4_compress()
}extern "C"
JNIEXPORT jbyteArray JNICALL
Java_com_shanreal_gb_utils_Lz4Utils_lz4_1decompression(JNIEnv *env, jclass clazz, jstring path,
                                                       jstring out_path) {
    enum {
        MESSAGE_MAX_BYTES   = 1024,
        RING_BUFFER_BYTES   = 1024 * 256 + MESSAGE_MAX_BYTES,
    };

    //freopen("/storage/emulated/0/test.lzw", "wr", stdin);	//
    //freopen("/storage/emulated/0/C_jni_stdout.txt", "w", stdout);	//
    //freopen("/storage/emulated/0/C_jni_stderr.txt", "w", stderr);	//
    char* in_file_path = (char *) (*env).GetStringUTFChars(path, 0);
    char* out_file_path = (char *) (*env).GetStringUTFChars(out_path, 0);
    //fprintf(stderr,"输入文件%s，输出文件%s\n ", in_file_path, out_file_path);
    FILE* inpFp = fopen(in_file_path, "rb");
    FILE* outFp = fopen(out_file_path, "wb");

//    FILE* printf_file = fopen("/storage/emulated/0/C_printf.txt", "wb");
//    fprintf(stdout, "输入文件%s，输出文件%s\n ", in_file_path, out_file_path);
//    fwrite(stdout,1,strlen(in_file_path),printf_file);
//    fwrite(stdout,1,strlen(in_file_path),printf_file);

    test_decompress(outFp, inpFp, MESSAGE_MAX_BYTES, RING_BUFFER_BYTES);


    fclose(inpFp);
    fclose(outFp);
    //fclose(printf_file);
    // TODO: implement lz4_decompression()
    jbyteArray data =env->NewByteArray(1);
    return data;
}

**Comment by t-mat** [comment]
@lilingzhiatshenzhen 

I'm really sorry.  But I can't write any advice before confirm you've chcked my (1) and (2) or not.

**Comment by lilingzhiatshenzhen** [comment]
Hi,T-mat:
          it is a little bit difficult for me to do (1)...as I am using windwos10...but (2) Absolutely I did.

BTW,,for check the code is correct or not...I did complie it on win10,,and use main() of  blockstream_linebyline.c ..

the result is actually verify:NG...we don't touch any code of this project this time

**Comment by t-mat** [comment]
I don't know what environment you've tried to compile the code.  But if you're using WSL or Visual Studio, please follow the following guide.

## WSL

Input the following commands to the WSL terminal:

```
cd
git clone https://github.com/lz4/lz4.git lz4-issue-1194
cd lz4-issue-1194
cd examples
make lineCompress
./lineCompress ./README.md

# inp = [./README.md]
# lz4 = [./README.md.lz4s]
# dec = [./README.md.lz4s.dec]
# Verify : OK
```


## Visual Studio

Open Visual Studio without project.  And invoke Visual Studio Menu Bar > Tools > Command Line > Developer Command Prompt.
In the developer command prompt, input the following commands:

```
cd /d "%USERPROFILE%\Documents"
git clone https://github.com/lz4/lz4.git lz4-issue-1194
cd lz4-issue-1194
cd examples
cl.exe /Fe:lineCompress.exe /I..\lib .\blockStreaming_lineByLine.c ..\lib\lz4.c
.\lineCompress.exe .\README.md

@rem inp = [.\README.md]
@rem lz4 = [.\README.md.lz4s]
@rem dec = [.\README.md.lz4s.dec]
@rem Verify : OK
```

**Comment by lilingzhiatshenzhen** [comment]
Dear T_mac
        Thanks for your reply...pls help below quesiton 

1)My final target is using lz4 blockstream_linebyline in Android and IOS...still use the same project with issue-11194?

2)as the ringbuffer is dictionary itself...so the compress and decompress must be the same size ?

thanks

**Comment by lilingzhiatshenzhen** [comment]
Dear T_mat:
              we tried as your mentioned  above .ONLY char file work....all other files are negative ..pls check it

**Comment by t-mat** [comment]
> 1)My final target is using lz4 blockstream_linebyline in Android and IOS...still use the same project with issue-11194?

No, you can't use this code directly for Android and iOS.
For example, they don't use `main()` as an entry point.  If you need to use, you should modify it for them.


> 2)as the ringbuffer is dictionary itself...so the compress and decompress must be the same size ?

Yes, you're right.  They must be same size.


> we tried as your mentioned above .ONLY char file work....all other files are negative ..pls check it

I'm sorry.  I don't understand what "char file" means.  Could you explain it?

**Comment by lilingzhiatshenzhen** [comment]
3) means all the files are combine with ONLY char...like .c like .txt....only ASCII ...any other file will  all be failed

**Comment by t-mat** [comment]
Thank you for explanation.

The original version of `blockStreaming_lineByLine.c` intentionally supports only text file (char file).
Therefore, `test_compress()` uses [`fgets()`](https://linux.die.net/man/3/fgets) to read a single line from `inpFp`.

If you need to use it for binary file, please take a look at `#if 0` block in `test_compress()`

https://github.com/lz4/lz4/blob/3e213fdf8e50694fdc6cafd51874394dc057b56d/examples/blockStreaming_lineByLine.c#L53-L58

You may be able to tweak them for your purpose.

- Replace `randomLength` with actual length of your binary message.
- Set proper `MESSAGE_MAX_BYTES` (in `main()`) which exceeds maximum length of your message.

**Comment by lilingzhiatshenzhen** [comment]
thanks a lot
