### ISSUE TITLE
`PATH=$(PATH)` in `tests/Makefile` causes problem in typical WSL environment

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1195]
**Describe the bug**
`make test` doesn't work in typical WSL environment.

**Expected behavior**
`make test` works.

**To Reproduce**
As of today (Nov 28, 2022), we can reproduce this issue with the following commands in WSL environment.

```sh
$ cd
$ git clone https://github.com/lz4/lz4.git lz4-issue-path
$ cd lz4-issue-path/
$ git log -1
commit 8a31e6402df11c1bf8fbb1db3b29ec2c76fe6f26 (HEAD -> dev, origin/dev, origin/HEAD)
...
Date:   Wed Nov 23 16:15:10 2022 -0800
...

$ make test
make[1]: Entering directory '/home/wsluser/lz4-issue-path/tests'
make -C ../programs lz4 CFLAGS="-O3  -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1 -g -DLZ4_DEBUG=1 "
make[2]: Entering directory '/home/wsluser/lz4-issue-path/programs'
make[2]: Leaving directory '/home/wsluser/lz4-issue-path/programs'
cc -O3  -Wall -Wextra -Wundef -Wcast-qual -Wcast-align -Wshadow -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wpointer-arith -Wstrict-aliasing=1 -g -DLZ4_DEBUG=1  -I../lib -I../programs -DXXH_NAMESPACE=LZ4_  -I../programs ../programs/datagen.c datagencli.c -o datagen
ln -sf ../programs/lz4 ../programs/unlz4
ln -sf ../programs/lz4 ../programs/lz4cat

 ---- test lz4 basic compression/decompression ----
PATH=../programs:...:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:...
/bin/sh: 1: Syntax error: "(" unexpected
make[1]: *** [Makefile:241: test-lz4-basic] Error 2
```

**System (please complete the following information):**
 - OS: Windows 11, WSL2
 - Version 21H2 (22000.1219)
 - Compiler gcc (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0)
 - Build System Makefile with `make` (GNU Make 4.3)

----
I think this error is caused by ` ` (space, 0x20) or `(` (parentheses, 0x28), in `$(PATH)`.

```
PATH=$(PATH) ./test-x.sh
```

is expanded as

```
PATH=path1:path2:/mnt/c/Program Files (x86)/path3 ./test-x.sh
```

and it seems first ` ` (space) is treated as a command separator.

**Comment by Cyan4973** [comment]
Indeed,
this `PATH=$(PATH)` statement has been added recently by some `meson`-related contribution,
pushing all tests inside `Makefile` into their dedicated `*.sh` scripts.

It's not clear to me why it's needed. 
Don't the scripts receive the same environment variables as the `Makefile` ?
The `Makefile` doesn't modify `$(PATH)`, so there is no need to re-specify it.

Another potential alternative : 
would `PATH="$(PATH)"` work better for `(` characters ?

**Comment by t-mat** [comment]
> The Makefile doesn't modify $(PATH), so there is no need to re-specify it.

Right.  All shell script invocation in the `tests/Makefile` works without `PATH=$(PATH)`.

@tristan957, do you remember the reason of [this change](https://github.com/lz4/lz4/commit/198e532300f253ada3acac3ab5428ed991adb085#diff-36b847ebf9c22d0651fe4856d7a8acb47ee2c483c79f1ccf0ed8c84889c9a394R229)?

> would PATH="$(PATH)" work better for ( characters ?

It works fine!  If we really need `$(PATH)` for each shell script invocation, this must be a solution.

**Comment by tristan957** [comment]
The reason for the change was I thought it was necessary. I am not super familiar with Makefiles, so I don't know what gets inherited. So if it can be removed, then that makes sense. But if it can't, the quoting looks good to me :)

**Comment by t-mat** [comment]
Thanks for the info, @tristan957
I think removing `PATH=$(PATH)` is the most simple and robust solution for this issue.

**Comment by tristan957** [comment]
I would agree with you. Thanks for discovering this.

**Comment by t-mat** [comment]
Ok. [Test failed](https://github.com/t-mat/lz4/actions/runs/3569819663/jobs/6000198370#step:17:845).
Since it's competely same error in [#1184](https://github.com/lz4/lz4/pull/1184#issuecomment-1329337426), it's not a random error.
I'll fix it later.
