### ISSUE TITLE
Add a Function to Build an LZ4F_CDict with a Custom Allocator

### ISSUE THREAD

**Issue by felixhandte** [lz4/lz4#1200]
**Is your feature request related to a problem? Please describe.**
Like `ZSTD_createCDict_advanced()`, it would be nice to able to pass a custom allocation function to LZ4 to use when setting up this data structure. While a full solution would also expose this for the cctx and store the vtable struct in the context etc., a minimal solution that would work just fine would be to just take in the custom functions at construction- and destruction-time.

**Describe alternatives you've considered**
`LZ4F_createCDict()` is simple enough that I could just duplicate it in my client code, but that seems brittle...

**Comment by Cyan4973** [comment]
This might be helpful:

https://github.com/lz4/lz4/blob/v1.9.4/lib/lz4frame.h#L663
