### ISSUE TITLE
LZ4 GitHub problem

### ISSUE THREAD

**Issue by Neustradamus** [lz4/lz4#1203]
Hello @lz4 team, @Cyan4973,

It is possible to clean branches?
- https://github.com/lz4/lz4/branches

Thanks in advance.

**Comment by Cyan4973** [comment]
done

**Comment by Neustradamus** [comment]
@Cyan4973: Thanks!

Why to have "release" and "dev" and not only one?

**Comment by Cyan4973** [comment]
`dev` is the main rolling branch (or `head` if you prefer)
while `release` is the "stable" branch, 
typically updated before publishing an actual release tag.

**Comment by Neustradamus** [comment]
@Cyan4973: I know but why not have only one branch, it is easy to tag a new build on the same branch...

**Comment by Cyan4973** [comment]
This is assuming everything goes smoothly. But `dev` might be progressing at its own pace, accumulating new features, while the `release` branch might be focused on reliability fixes only. So they may diverge, at least temporarily.

Besides, this technical organizational detail is largely invisible. That's unexpected to witness so much focus on erasing every branches from the project.
