### ISSUE TITLE
some questions about lz4 running on cortex-m mcu

### ISSUE THREAD

**Issue by xlbao123** [lz4/lz4#1208]
I have some questions about lz4 when porting it to mcu, please help to figure these:
1. Does `LZ4_FAST_DEC_LOOP` macro can be used on cortex-m? I defined this and it seems work. And I see the  `LZ4_decompress_safe_partial` API has a little performance improvement  when open this.
2. My scenario is mainly to decode some small files that have been compressed, so I want to have the best decoding performance. So I should use block compression instead of frame compression, right?

**Comment by Cyan4973** [comment]
`LZ4_FAST_DEC_LOOP` will work.
It may just not be optimal for your platform.
This loop is designed for modern OoO cpus with pipelines,
but for weaker cpus, especially in-order ones, it's probably overkill,
leading to inflated binary size at no or negative performance difference.

If you want to be sure, just test both variants, and report which one is best for your specific cpu.

The question of block vs frame has less to do with performance than with usability and memory.
In general, select block compression if memory management comes at a premium, and you need to fully control what is being allocated and for what.
Prefer frame compression if you plan on sharing the compressed output with others systems, possibly including logs and debugging tools.
