### ISSUE TITLE
找不到函数

### ISSUE THREAD

**Issue by Zer08Bytes** [lz4/lz4#1210]
// 计算解压后的数据大小
int decompressed_size = LZ4F_getFrameDecompressedSize(compressed_data.data(), NULL);

引入了lz4相应的.h(下载的是最新版本的lz4库)，
#include "lz4.h"
#include "lz4frame.h"

visual studio 2022 提示找不到 LZ4F_getFrameDecompressedSize这个函数，请帮忙看看看。

**Comment by Cyan4973** [comment]
1) English is the preferred language on Github
2) There is no `LZ4F_getFrameDecompressedSize()` defined anywhere in the API
3) The equivalent is `LZ4F_getFrameInfo()`, which fills a `LZ4F_frameInfo_t` structure, which contains many fields, one of which being `contentSize`, aka the information you are looking for.

**Comment by Zer08Bytes** [comment]
THANKS。
