### ISSUE TITLE
Regression when input file is a directory

### ISSUE THREAD

**Issue by imba-tjd** [lz4/lz4#1211]
**Describe the bug**

As of 1.9.3, `mkdir d; lz4 d` reports `d: is not a regular file`.

But in 1.9.4, it says `d: Permission denied` on Win and `Error 40 : Error reading d` on WSL. And it creates a 0KB *d.lz4* on WSL.

**System:**
 - OS: Windows 11 and WSL Debian 12
 - Version 1.9.4

**Comment by Cyan4973** [comment]
I can reproduce the issue on regular Linux distribution:
```
./lz4 dir 
Compressed filename will be : dir.lz4 
Error 40 : Error reading dir  
```

I presume the test checking if the input file is regular as been loosened, in an attempt to also support block device inputs.
