### ISSUE TITLE
GH-Actions (todo) : Remove Ubuntu 18.04 from CI

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1215]
**Describe the bug**

GH-Actions is starting to deprecate Ubuntu 18.04.  Some CI steps are skipped.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/898396/223277799-28f11b9a-0f63-4457-b9c6-88d56c2ef2ac.png">

**Expected behavior**

- Ubuntu 18.04 will be removed.

**To Reproduce**

- Run GH-Actions.
- See GH-Actions log message in the "Summary" section.

See also - https://github.com/actions/runner-images/issues/6002

**Comment by t-mat** [comment]
Ubuntu 20.04 supports

- gcc-{7,8,9,10,11}
  - lib32gcc, libx32gcc, gccmultilib also support same versions.
- clang-{6,7,8,9,10,11,12}

Therefore, we'll remove the following versions of compilers

- gcc-{ 4.8, 5, 6 }
- clang-{ 3.9, 4, 5 }

**Comment by DimitriPapadopoulos** [comment]
Ubuntu 18.04 has been removed from [.github/workflows/ci.yml](https://github.com/lz4/lz4/blob/dev/.github/workflows/ci.yml). Close this issue?
