### ISSUE TITLE
"Optimal" compression strategy of executable for fast decompression

### ISSUE THREAD

**Issue by richarddd** [lz4/lz4#1219]
Hello,

I'm applying an "UPX" like strategy to compress executable binaries on my system. The decompression will occur from a buffer loaded into memory.

The current approach i'm implementing is the following:

1. Splitting the binary into 1000 chunks.
2. Trim them to keep the first 4k only
3. Train a dictionary on the chunks
4. Compress using lz4 program with --favor-decSpeed (i'm actually using lz4ultra to improve compression and decompression times https://github.com/emmanuel-marty/lz4ultra)
5. Unpack using LZ4F_decompress_usingDict

However, i'm barely seeing any difference in both compression ratio and decompression speed when using the dictionary.

I found this issue where the OP seems to have the exact same methodology but seeing significant gains in compression when using a dictionary https://github.com/lz4/lz4/issues/559

I've also understand by looking at issues that the block format should yield faster uncompression. But in my case the compression ratio of using a dictionary in the block format is way worse. As far as i understand the only way of duing block format compression with dict is to use streaming API?

Are there any better approaches to by problem?

Anyway, this is my code for block compression with external dict reading from stdin and writing to stdout. I'm i doing this wrong? Is there a way to use none streaming API and an external dict to yield better results?

Thanks for the support!

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <lz4.h>

#define BUFFER_SIZE (1024*4)  // 4k buffer size

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <dictionary_file>\n", argv[0]);
        exit(1);
    }

    // Read the dictionary file
    char *dictionary = NULL;
    FILE *dictionary_file = fopen(argv[1], "rb");
    size_t dict_size;
    if (dictionary_file) {
        fseek(dictionary_file, 0, SEEK_END);
        dict_size = ftell(dictionary_file);
        fseek(dictionary_file, 0, SEEK_SET);
        dictionary = (char *)malloc(dict_size);
        fread(dictionary, dict_size, 1, dictionary_file);
        fclose(dictionary_file);
    }

    // Compress the input data using the provided dictionary
    char *input_buffer = (char *)malloc(BUFFER_SIZE);
    char *output_buffer = (char *)malloc(BUFFER_SIZE);
    size_t input_size, output_size;
    LZ4_stream_t *lz4_stream = LZ4_createStream();
    if (dictionary) {
        LZ4_loadDict(lz4_stream, dictionary, dict_size);
    }
    while ((input_size = fread(input_buffer, 1, BUFFER_SIZE, stdin)) > 0) {
        output_size = LZ4_compress_fast_continue(lz4_stream, input_buffer, output_buffer, input_size, BUFFER_SIZE, 1);
        fwrite(output_buffer, 1, output_size, stdout);
    }
    LZ4_freeStream(lz4_stream);

    // Free allocated memory
    free(input_buffer);
    free(output_buffer);
    free(dictionary);

    return 0;
}
```

**Comment by Cyan4973** [comment]
Hi @richarddd,
Unfortunately, I don't see anything obvious from this code.
As far as I can tell, it seems it would work properly.
I tested it using trivial examples, and it worked fine, meaning dictionary was effective.

There are a few possibilities here : 
1) Is the content of the dictionary used in your test effective ? How was it trained ?
2) What's the average size of a chunk ? Is it "large" (> 1 MB) ?
3) Could the chunks be so vastly different that they end up requiring very different dictionary segments, resulting in a dictionary which is average (i.e. barely effective) for all ?
4) Is the library you are using for compression (`lz4utra`) supporting dictionary compression ?
