### ISSUE TITLE
LZ4F_resetDecompressionContext() does not clear frameRemainingSize when !contentSizeFlag

### ISSUE THREAD

**Issue by QrczakMK** [lz4/lz4#1227]
**Describe the bug**
A randomized test did the following:
* Compressed and decompressed some data.
* Compressed empty data. This resulted in 11 bytes of compressed data.
* Obtained a `LZ4F_dctx` by recycling some old context with `LZ4F_resetDecompressionContext()`.
* Tried to decompress the 11 bytes.
* `LZ4F_decompress_usingDict()` failed with `ERROR_frameSize_wrong`.

**Expected behavior**
Should decompress successfully.

**To Reproduce**
I cannot reproduce this (it depends on how decompression contexts are recycled, which is hard to reproduce here), but looking at the code makes it clear what is likely the reason.

`LZ4F_resetDecompressionContext()` does not change `frameRemainingSize`, which must have remained at some non-zero value from a previous decompression session. `LZ4F_decodeHeader()` sets `frameRemainingSize` only if `contentSizeFlag`, which was not set because compressed data were empty. `LZ4F_decompress()` at `dstage_getSuffix` checked if `frameRemainingSize` is 0 which failed.

(There might be other members of the context which are not cleared but should be. Same for compression.)

**Comment by Cyan4973** [comment]
Thanks for the very clear reproduction case and solution @QrczakMK !

I would have expected the frame fuzzer to be able to generate (and therefore validate) such a scenario,
but apparently it doesn't, either a limitation or the probability for this exact scenario to happen is just too low.

Anyway, thanks to the description, I could manually create a buggy scenario.
This ended being the majority of the work.
Of course, the fix you describe works great.

_edit_: it was a limitation. The frame fuzzer is now able to randomly generate scenarios like `bug1227`.
