### ISSUE TITLE
Add Zephyr RTOS to the list of Used By projects

### ISSUE THREAD

**Issue by beriberikix** [lz4/lz4#1229]
[Zephyr RTOS](https://www.zephyrproject.org/) has [supported LZ4](https://docs.zephyrproject.org/latest/samples/compression/lz4/README.html) for some time so it would be great to add it under the list of supported Operating Systems.

**Comment by Cyan4973** [comment]
Is Zephyr based on Linux ?

**Comment by beriberikix** [comment]
Zephyr leverages many concepts and even elements of Linux, like Device Tree and Kconfig, but it is a different kernel all together. It is designed for constrained-class devices like Microcontrollers where Linux cannot run.
