### ISSUE TITLE
lz4 fails to cross-compile due to gen_manual rule

### ISSUE THREAD

**Issue by riastradh** [lz4/lz4#1240]
**Describe the bug**
lz4 uses $(CXX) to compile gen_manual, and then executes it during the build.

In a cross-build, say using a cross-compiler on an x86 system to build an lz4 that runs on aarch64, $(CXX) is a cross-compiler, so using it here yields an aarch64 executable for gen_manual, which can't be executed on x86.

**Expected behavior**
lz4 uses a native compiler for gen_manual when cross-compiling everything else.

For example, perhaps lz4 could sprout a parameter CXX_FOR_BUILD, which defaults to $(CXX), and which is used to compile gen_manual before executing it.

**To Reproduce**
Cross-compile lz4.

**Additional context**
Many other software packages that do something similar expose CC_FOR_BUILD or CXX_FOR_BUILD parameters, so there is plenty of precedent for this approach.

**Comment by Cyan4973** [comment]
A number of things to unpack here.

- `gen_manual` is not part of the standard `lz4` package. If one runs the command `make`, this will not generate (nor run) `gen_manual`.
- `gen_manual` is part of an extended list of binaries that can be created from the `lz4` repository. This extended list also includes for example test programs, such as `tests/fuzzer` . The command `make all` can be used to generate this extended list. It's primarily useful for CI tests.
- If your goal is to generate a binary package for a cross-compiled target, I'm not sure to understand why it would need the extended list of binaries, as opposed to the "core" useful package, featuring only the libraries and the CLI.
- The goal of `gen_manual` is just to generate a manual in `html` format from the source code. It's a repository-level tool. There should not be any reason to run this binary on client side, the `html` manual is supposed to be already updated.

So, I suspect the first question is, we should talk about the need to generate `gen_manual`,
and if there is no such need,
why is it generated, can or should it be excluded ?

**Comment by riastradh** [comment]
I came here from pkgsrc, which follows the convention that `all` is the standard make target for building everything important in a source tree.  The [pkgsrc packaging for lz4](https://github.com/NetBSD/pkgsrc/blob/pkgsrc-2023Q1/archivers/lz4/Makefile) doesn't do anything to override this.

I didn't investigate whether what gen_manual produces is relevant to the resulting package -- I'm just going through and fixing cross-compilation bugs in every package I stumble upon, and this is a common bug with a common fix, which is what I submitted in https://github.com/lz4/lz4/pull/1241.

Is there a better target to use instead?  Should it use the `default` target?

**Comment by riastradh** [comment]
Looks like there's no trouble with leaving the target empty in pkgsrc so it will pick whatever is the default from `make`, which avoids the cross-compilation issue.  Thanks!

**Comment by Cyan4973** [comment]
Yeah, the regular default `make` is the one intended to build `lz4` packages.

`make all` is essentially used in CI, to build _everything_ in the repository, and ensure all targets, including secondary ones, still work fine after every modification.

Maybe it's a mis-usage of the `all` target. I should have a deeper look at that, understand what's the established convention and see if it's respected.
