### ISSUE TITLE
Memory leak in lz4cli.c

### ISSUE THREAD

**Issue by BojackMa** [lz4/lz4#1246]
# TL;DR
We perfom a fuzz on lz4 and find this bug.
At line 329, LZ4IO_defaultPreferences() is called to allocate memory. However, if inFileNames is NULL, the program exits directly at line 340 without freeing the memory. It is advisable to invoke LZ4IO_freePreferences(prefs) to release the allocated memory.
https://github.com/lz4/lz4/blob/34d9127010f5c0265aad8c13baf718e27d4dd1f1/programs/lz4cli.c#L329
https://github.com/lz4/lz4/blob/34d9127010f5c0265aad8c13baf718e27d4dd1f1/programs/lz4cli.c#L340-L343
# Log File
```
==1485==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x55555560150e in __interceptor_malloc (/lz4ma/lz4/lz4+0xad50e) (BuildId: f8a4b4aa7b109d35eecf539c40dab97de0ce9dda)
    #1 0x555555716d4e in LZ4IO_defaultPreferences /lz4ma/lz4/programs/lz4io.c:150:48
    #2 0x55555570f938 in main /lz4ma/lz4/programs/lz4cli.c:329:34
    #3 0x7ffff7cb0d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)

SUMMARY: AddressSanitizer: 72 byte(s) leaked in 1 allocation(s).

Inject Error Stack:
TraceStack(frame=[Symbol(func='backtrace', off='0x5b', loc=[]), Symbol(func='do_log', off='0x1d9cfe', loc=[('/AFLFI/fault_injection/rt.c', 69, 'do_log'), ('/AFLFI/fault_injection/rt.c', 113, '__fault_injection_control')]), Symbol(func='main', off='0x1bb900', loc=[('/lz4ma/lz4/programs/lz4cli.c', 327, 'main')]), Symbol(func='??', off='0x29d90', loc=[('??', 0, '??')]), Symbol(func='__libc_start_main', off='0x80', loc=[]), Symbol(func='_start', off='0x2a6c5', loc=[('??', 0, '_start')])])
Sanitizer Stack:
TraceStack(frame=[Symbol(func='__interceptor_malloc', off='0xad50e', loc=[]), Symbol(func='LZ4IO_defaultPreferences', off='', loc=['/lz4ma/lz4/programs/lz4io.c', 150, 'LZ4IO_defaultPreferences']), Symbol(func='main', off='', loc=['/lz4ma/lz4/programs/lz4cli.c', 329, 'main'])])
```

**Comment by Cyan4973** [comment]
Note: I'm always embarrassed when a tool lazily regroups under an identical label some drastically different situations.
If the program `exit()`, then by definition it _does_ release all its memory. An explicit `free()` operation makes no difference at this point.
This scenario is vastly different from an actual memory leak, within a running program, that progressively snowballs into an unbounded memory budget. 
Conflating these 2 scenarios is more a symptom of the detection tool's weakness, that doesn't even try to distinguish a running loop from a final `exit()` branch.

Anyway, that's not the first time we have to please such tools, so we already have a solution in place to deal with these kind of issues. I'll fix it then.
