### ISSUE TITLE
Question about lz4/examples/fileCompress.c

### ISSUE THREAD

**Issue by BojackMa** [lz4/lz4#1248]
Hi, I'm a little confused about a question.
In the compress_file function, at line 41, memory allocation is performed for buf. If the memory allocation fails, should the function return directly? Because there is a possibility that the program reaches line 58, where the fread function accepts a null pointer, leading to an error.
https://github.com/lz4/lz4/blob/839edadd09bd653b7e9237a2fbf405d9e8bfc14e/examples/fileCompress.c#L41-L44
https://github.com/lz4/lz4/blob/839edadd09bd653b7e9237a2fbf405d9e8bfc14e/examples/fileCompress.c#L58

**Comment by t-mat** [comment]
Hi @BojackMa ,

You're right.  we must have `return 1;` between line 43 and 44.
