### ISSUE TITLE
How to use it without libc?

### ISSUE THREAD

**Issue by ghost** [lz4/lz4#1252]
I know that LZ4 algorithm is not necessarily depended on external libraries and your project has a great compression ratio, but I have an embedded device that doesn't support libc.

**Comment by Cyan4973** [comment]
See `LZ4_FREESTANDING` documentation

**Comment by ghost** [comment]
@Cyan4973 Does it expose any trade off in speed or compression size when using `LZ4_FREESTANDING`?

**Comment by Cyan4973** [comment]
`LZ4_FREESTANDING ` is completely orthogonal to the questions of speed vs compression sizes.
