### ISSUE TITLE
Can we have official tarball downloads that are not github archives?

### ISSUE THREAD

**Issue by bluesmoon** [lz4/lz4#1262]
**Is your feature request related to a problem? Please describe.**
In February this year Github announced that archives are no longer guaranteed to be byte for byte identical over time, so if someone uses a checksum like a SHA 256 hash of an archive, it's possible that at some point in the future this checksum would be invalid and there's no way to tell if it's because the binary has been compromised or just the underlying compression algorithm changed.  See https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/ for more details.

**Describe the solution you'd like**
I would like the lz4 project to provide official .tar.gz archives (that you create yourselves and upload to github) instead of the github automatic archive along with sha 256 checksums of each archive.

**Describe alternatives you've considered**
Considered hosting my own archive, but this would not be in sync with upstream and would not be official.

**Additional context**
NA

**Comment by Cyan4973** [comment]
A new artifact [`lz4-1.9.4.tar.gz`](https://github.com/lz4/lz4/releases/download/v1.9.4/lz4-1.9.4.tar.gz) is provided,
alongside its [`sha256` checksum](https://github.com/lz4/lz4/releases/download/v1.9.4/lz4-1.9.4.tar.gz.sha256).

**Comment by bluesmoon** [comment]
Thank you!
