### ISSUE TITLE
can't build static lib

### ISSUE THREAD

**Issue by Liam0316** [lz4/lz4#1269]
**Describe the bug**
I want to build a static lib. so I set :
set(BUILD_SHARED_LIBS OFF)
set(BUILD_STATIC_LIBS ON)
in CMakeList.txt
But I can't make it:

Scanning dependencies of target lz4_static
[  6%] Building C object CMakeFiles/lz4_static.dir/home/smit/resource_home/lz4-dev/lib/lz4.c.o
[ 13%] Building C object CMakeFiles/lz4_static.dir/home/smit/resource_home/lz4-dev/lib/lz4hc.c.o
[ 20%] Building C object CMakeFiles/lz4_static.dir/home/smit/resource_home/lz4-dev/lib/lz4frame.c.o
[ 26%] Building C object CMakeFiles/lz4_static.dir/home/smit/resource_home/lz4-dev/lib/xxhash.c.o
[ 33%] Linking C static library liblz4.a
[ 33%] Built target lz4_static
Scanning dependencies of target lz4c
[ 40%] Linking C executable lz4c
CMakeFiles/lz4c.dir/home/smit/resource_home/lz4-dev/programs/bench.c.o: In function `BMK_benchMem':
bench.c:(.text+0x193d): undefined reference to `XXH64'
bench.c:(.text+0x24e1): undefined reference to `XXH64'
collect2: error: ld returned 1 exit status
make[2]: *** [lz4c] Error 1
make[1]: *** [CMakeFiles/lz4c.dir/all] Error 2
make: *** [all] Error 2

**To Reproduce**
1. Go to  'build/cmake/CMakeList.txt'
2. add set(BUILD_SHARED_LIBS OFF)  set(BUILD_STATIC_LIBS ON) On line 66
3. cmake
4. make

make error

**System (please complete the following information):**
 - OS: Centos 7.9
 - Version 7.9
 - Compiler gcc 9.4
 - Build System cmake
 - Other hardware specs [e.g. Core 2 duo...]

**Comment by t-mat** [comment]
Hi @RyanFu999, thanks for the report.

I've confirmed your issue.  It's our mistake.  Sorry about that.

As for temporary workaround, you can use lz4's specific `CMakeLists.txt` option `LZ4_BUILD_CLI` and `LZ4_BUILD_LEGACY_LZ4C`.  For example,

```bash
cd
git clone https://github.com/lz4/lz4.git lz4-issue-1269
cd lz4-issue-1269

cd build/cmake
mkdir build
cd    build
cmake -DBUILD_STATIC_LIBS=ON -DLZ4_BUILD_CLI=OFF -DLZ4_BUILD_LEGACY_LZ4C=OFF ..
CFLAGS=-Werror make VERBOSE=1

ls      -l ./liblz4.a
file       ./liblz4.a
readelf -h ./liblz4.a
```

----

Note to contributors for further investigation:

It seems `BMK_benchMem()` invokes `XXH64()` without namespace prefix for some reason.
Last change was #1258.

**Comment by Cyan4973** [comment]
It seems we are lacking a build scenario in CI.
