### ISSUE TITLE
LZ4F_decompress is over write out_size(uncompressed orginal zie)

### ISSUE THREAD

**Issue by whyjp** [lz4/lz4#1270]
somtimes LZ4F_decompress is write over  out_size 
these value is not include originals that..

so i put at out_sze  '\0' will correct orginal uncompressed text..

Is this a bug?

**Comment by Cyan4973** [comment]
`LZ4F_decompress()` should never write beyond the provided destination buffer, which size is passed via parameter `dstSizePtr`.
It is extensively tested and fuzzed to verify this property continuously.

**Comment by whyjp** [comment]
Of course, writing beyond the out buffer is not performed.
The destination buffer is already sufficiently allocated.

The function returns with more data written to the destination buffer than the actual uncompressed size.

For example, to compress and decompress json data

There is an additional { character attached to the end of the exact source string.

\0 I wonder if the reason is that the null character does not appear.
It does not feel natural that other data is used beyond the actual released data size.

![image](https://github.com/lz4/lz4/assets/40193646/b7ec96d6-cbea-45be-b9e9-5dd446a865a8)

The expected result is either a \0 value in the last { position or
The value of the initialized buffer is maintained as \0.

Currently, \0 is arbitrarily inserted after the value of dstSizePtr returned after calling LZ4F_decompress.

**Comment by Cyan4973** [comment]
`LZ4F` compress data as binary data, and doesn't know anything about characters or end of string conventions.

There is no reason for `LZ4F` to add more bytes all by its own.
This would be a corruption event (against which, you can guess, `LZ4F` is highly tested and permanently fuzzed).
Assuming a one-pass decompression scenario, the value returned by `dstSizePtr` should be exactly the same value as `srcSize` during compression. If you have access to `srcSize` of original data, this would be the first thing to compare.

There could be other reasons to explain an extra character:
-> The compression side provided an incorrect size, 1 more byte than wanted. It happened to contain this character.
-> There was a corruption even during transport or storage (unlikely)
-> Decompression happen in an uninitialized buffer, which happen to have this character right at this position.
and possibly other variants I haven't enumerated here.
