### ISSUE TITLE
Provide offical wasm version

### ISSUE THREAD

**Issue by jimmywarting** [lz4/lz4#1271]
**Is your feature request related to a problem? Please describe.**
The problem is that there is a lack of an official WebAssembly (Wasm) version of the lz4 compression library on GitHub. This absence prevents developers from efficiently using lz4 in JavaScript runtimes that support ESM (ECMAScript Modules) with top-level await. Existing npm packages are outdated and do not expose all possible options, limiting the flexibility and performance of lz4 in modern JavaScript environments.

**Describe the solution you'd like**
I would like to request the official lz4 GitHub repository (https://github.com/lz4/lz4) to provide an official WebAssembly (Wasm) version of the lz4 compression library. This official release should be optimized for modern JavaScript runtimes and fully compatible with ESM (ECMAScript Modules), allowing developers to leverage lz4's compression capabilities efficiently. Additionally, it should expose all available options and functionalities for comprehensive usage.

**Describe alternatives you've considered**
Some alternatives to this solution include:

1. Relying on existing npm packages: Developers can currently use npm packages for lz4, but they often lack updates and do not provide full support for modern JavaScript runtimes.

2. Building a custom WebAssembly version: Developers could create a custom WebAssembly build of lz4, but this requires significant effort and may not guarantee full compatibility with ESM and top-level await.

**Additional context**
The availability of an official lz4 WebAssembly version on GitHub would greatly benefit developers working in JavaScript environments that support ESM and top-level await. It would provide a more up-to-date and optimized option for lz4 compression, enhancing both performance and usability. This feature request aligns with the evolving needs of the JavaScript community and the growing adoption of modern JavaScript features.

**Comment by Cyan4973** [comment]
This would have to be a fork.
It could still be hosted under the `github/lz4` umbrella if it's in good shape, like `lz4-java` for example,
but it requires domain expertise that deserves a dedicated project for it.
