### ISSUE TITLE
[GH Actions] All x32 tests are failed

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1275]
**Describe the bug**
All ci.yml actions fail for x32

**Expected behavior**
All tests are passed

**To Reproduce**
Run ci.yml

**System (please complete the following information):**
Github Actions

**Additional context**
For example:
- https://github.com/lz4/lz4/actions/runs/6295774403/job/17089569966?pr=1274
- https://github.com/lz4/lz4/actions/runs/6202990433/job/16857511176?pr=1273

Since we don't change any code and tests, there errors may be caused by upstream changes.

**Comment by Cyan4973** [comment]
Yep, I noticed it a few days ago, indeed.
Github, or one of its dependencies, has changed something with regards to `x32` support.
To be fixed.

**Comment by Cyan4973** [comment]
The issue has been fixed by removing `x32` tests from faulty platforms.

They are still active for Ubuntu 20.04, which still supports `x32` properly.
