### ISSUE TITLE
if not defined guard around tuning parameters in lz4.h

### ISSUE THREAD

**Issue by JedidiahPaterson** [lz4/lz4#1307]
```
#ifndef LZ4_MEMORY_USAGE_MIN 
#define LZ4_MEMORY_USAGE_MIN 10
#endif // LZ4_MEMORY_USAGE_MIN 

#ifndef LZ4_MEMORY_USAGE_DEFAULT
#define LZ4_MEMORY_USAGE_DEFAULT 14
#endif // LZ4_MEMORY_USAGE_DEFAULT

#ifndef LZ4_MEMORY_USAGE_MAX 
#define LZ4_MEMORY_USAGE_MAX 20
#endif // LZ4_MEMORY_USAGE_MAX 
```
this will allow users to add the lz4 repo as a submodule to their project and define the variables in a cmake or like system, while still providing default values for other people. This allows for tuning to be done for embedded systems as an included submodule

**Comment by t-mat** [comment]
You don't need to change `LZ4_MEMORY_USAGE_DEFAULT`, etc.
Instead of it, you can tweak it by `LZ4_MEMORY_USAGE`.

See also
- https://github.com/lz4/lz4/blob/v1.9.4/lib/lz4.h#L153-L159
- https://github.com/lz4/lz4/blob/v1.9.4/contrib/meson/meson_options.txt
