### ISSUE TITLE
LZ4 frame format

### ISSUE THREAD

**Issue by ggalatianos** [lz4/lz4#1313]
Hi,

I am having a really tough time to make a programm to compress a file using the frame format, could someone please help me?

**Comment by t-mat** [comment]
Could you explain your issue just a bit more specifically?
We can say nothing without information.

By the way, perhaps, [`examples/frameCompress.c`](https://github.com/lz4/lz4/blob/dev/examples/frameCompress.c) or [`examples/fileCompress.c`](https://github.com/lz4/lz4/blob/dev/examples/fileCompress.c) may help you.

**Comment by ggalatianos** [comment]
It is not something specific, I could not find my way in this gigantic code to use properly the functions to do the compress and decompress. And chat-gpt was not helpfull enough. I will read the examples and i'll try to use them. If not I will come back :P

**Comment by t-mat** [comment]
Good luck.  I hope [our document](https://github.com/lz4/lz4/tree/dev/doc) will help you.

@Cyan4973 it'd be nice to put doc/*.html into lz4.org?

**Comment by Cyan4973** [comment]
> Good luck. I hope [our document](https://github.com/lz4/lz4/tree/dev/doc) will help you.
> 
> @Cyan4973 it'd be nice to put doc/*.html into lz4.org?

sure !

**Comment by Cyan4973** [comment]
Link to documentation directory added to `lz4` homepage.
