### ISSUE TITLE
XXH32 symbol missing

### ISSUE THREAD

**Issue by cjm-robinhood** [lz4/lz4#1317]
**Describe the bug**
When I install liblz4-dev on Ubuntu 20 using `apt` and it installs version 1.9.2, the library is missing the XXH32 symbol, but this symbol is found on the version that is installed on Ubuntu 18

**Expected behavior**
`XXH32` symbol is included in `.so`

**To Reproduce**
1. sudo apt install liblz4-dev
2. nm -D /usr/lib/x86_64-linux-gnu/liblz4.so | grep XXH32
3. No match

**System (please complete the following information):**
 - OS: [e.g. Mac] Ubuntu
 - Version [e.g. 22] 20.04
 - Compiler [e.g. gcc] gcc 9.4.0
 - Build System [e.g. Makefile] Not building from source, installing through apt
 - Other hardware specs [e.g. Core 2 duo...] x86

**Additional context**
This is the version being installed on Ubuntu 18
```
dpkg -l | grep liblz4
ii  liblz4-1:amd64                0.0~r131-2ubuntu3.1                 amd64        Fast LZ compression algorithm library - runtime
ii  liblz4-dev:amd64              0.0~r131-2ubuntu3.1                 amd64        Fast LZ compression algorithm library - development files
```
This is the version being installed on Ubuntu 20
```
$ dpkg -l | grep liblz4
ii  liblz4-1:amd64                       1.9.2-2ubuntu0.20.04.1             amd64        Fast LZ compression algorithm library - runtime
ii  liblz4-dev:amd64                     1.9.2-2ubuntu0.20.04.1             amd64        Fast LZ compression algorithm library - development files

```

And output of looking for the symbol:

```
$ uname -a
Linux ip-10-55-46-7 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$  nm -D /usr/lib/x86_64-linux-gnu/liblz4.so | grep XXH32
0000000000018a00 T XXH32
0000000000018df0 T XXH32_createState
0000000000019090 T XXH32_digest
0000000000018e00 T XXH32_freeState
0000000000018e30 T XXH32_reset
0000000000018ec0 T XXH32_update
$
```

```
$ uname -a
Linux ip-10-55-14-112 5.15.0-1050-aws #55~20.04.1-Ubuntu SMP Mon Nov 6 12:15:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ nm -D /usr/lib/x86_64-linux-gnu/liblz4.so | grep XXH32
$
```

**Comment by Cyan4973** [comment]
While it's possible to make `liblz4` expose the `XXH32` symbol, by using some advanced build macros,
by default, it is expected not to. `xxh` symbols are considered "internal", and are not part of the public-facing `liblz4` API.

Users of `xxhash` are rather invited to install `libxxhash`, where the `XXH32` symbol is properly exposed.

**Comment by cjm-robinhood** [comment]
Thanks for taking a look here. I actually have `libxxhash` installed on my system, but I'm not making calls to it directly in my Go program, so there must be something that is transitively relying on this symbol and I guess it wants it particularly from liblz4, but this investigation is on me.
