### ISSUE TITLE
Question: In Stream API, is large ring buffer improves the compression ratio?

### ISSUE THREAD

**Issue by heroboy** [lz4/lz4#1318]
I am using lz4 compress network packet. One lz4 stream for one connection. Each block is small, but I can have a large ring buffer. Is it improve the compression ratio?

In the document:
https://github.com/lz4/lz4/blob/dev/examples/blockStreaming_lineByLine.md
It says, Line#2 depends on Line#1. My question is :
1. Is Line#3 depends on both Line#2 and Line#1 to make improvements?
2. When ring buffer reset, is that means LZ4 forget the dictionary, and re study the data from Line#X. 
    If start from the Line#X, the data's shape is very different from the previous blocks, will it make improvements?

In the example:
https://github.com/lz4/lz4/blob/dev/examples/blockStreaming_ringBuffer.c
```c
enum {
    MESSAGE_MAX_BYTES   = 1024,
    RING_BUFFER_BYTES   = 1024 * 8 + MESSAGE_MAX_BYTES,
    DECODE_RING_BUFFER  = RING_BUFFER_BYTES + MESSAGE_MAX_BYTES   /* Intentionally larger, to test unsynchronized ring buffers */
};
```
1. In document, it says "The previous 64KB of source data is __assumed__ to remain present", why the `RING_BUFFER_BYTES` is not `1024 * 64 + MESSAGE_MAX_BYTES`.
2. Is the code incorrect if the `MESSAGE_MAX_BYTES` is very large that the ring buffer can not hold 2 blocks? Or can hold some blocks, but when compressing current block, the previous blocks total bytes are less than 64KB.
4. How I can understand “The previous 64KB of source data is __assumed__ to remain present”. If it is true, the double buffer example is not correct, because `BLOCK_BYTES = 1024 * 8`.
    As I understand, does it mean the previous blocks that sum bytes at least 64KB should remain present?

**Comment by Cyan4973** [comment]
The maximum memory useful for compression is 64 KB. If your ring buffer is larger than that, it won't improve compression ratio (though it may help speed).
Below that threshold, the history window is essentially the size of your ring buffer, minus the current message (which is assumed to occupy a segment within the ring buffer).
Yes, the entire ring buffer. Even if you reached the end of the ring buffer, and the next buffer is at the beginning of the ring buffer, `lz4` will still be able to use the unmodified part of the ring buffer as history window.

> Is Line#3 depends on both Line#2 and Line#1 to make improvements?

It depends on implementation detail.
In this case, my understanding is that this example is using a ring buffer, so yes, line3 will be able to use both line2 and line1 as history buffer (assuming `ring_buffer_size >= sum(lines)`).
On the other hand, if each line was its own separate buffer, then line3 would only use line2 as history buffer. `lz4` would lose track of line1 at this point.

> When ring buffer reset, is that means LZ4 forget the dictionary,

Nope, everything still unmodified in the ring buffer, up to max 64KB, can be used as dictionary.

> why the RING_BUFFER_BYTES is not 1024 * 64 + MESSAGE_MAX_BYTES

The ring buffer is allowed to be smaller than 64KB.
This can be useful in memory constrained scenarios, where even a few KB matters.

This is not a recommendation though.
On modern systems, memory is plentiful, and 64KB doesn't represent a meaningful budget worth cropping.

> Is the code incorrect if the MESSAGE_MAX_BYTES is very large

That's fine. It will work.
Just keep in mind that the message overwrites a segment of the ring buffer, which obviously is no longer part of the dictionary. So, if the message is very large, and overwrites a majority of the ring buffer, the dictionary is reduced to what's left unmodified in the ring buffer, which might be very little. This would obviously impact compression ratio.

> How I can understand “The previous 64KB of source data is assumed to remain present”. If it is true, the double buffer example is not correct, because BLOCK_BYTES = 1024 * 8.

In double-buffer scenario, the last 64 KB of the previous buffer are presumed still present, unmodified.
If the previous buffer was smaller than 64KB, then the entire content of this buffer is presumed still present and unmodified.

There's no problem using buffers smaller than 64 KB.
They just impact the compression ratio when they are smaller than 64 KB, but that can be a price worth paying.

The real point is in guaranteeing that the expected content is still there and unmodified.
If the buffer was `free()`, it would result in a dangling pointer dereference.
If the content of the buffer was modified, it would result in the production of corrupted data.
It's the main reason to insist that this part of the memory must remain present and unmodified.

**Comment by heroboy** [comment]
My English is not good. I will try to understand what to say.

>>How I can understand “The previous 64KB of source data is assumed to remain present”. If it is true, the double buffer example is not correct, because BLOCK_BYTES = 1024 * 8.
>
>In double-buffer scenario, the last 64 KB of the previous buffer are presumed still present, unmodified.
>If the previous buffer was smaller than 64KB, then the entire content of this buffer is presumed still present and unmodified.

I am confused that your first line says "the last 64KB", and second line says it is allow to less than 64KB. 

Is it mean that it just need the one previous buffer, and if the buffer is >64KB, it just need the 64KB first(or last?) part of it?

As I said in original post how I understand "The previous 64KB of source data is assumed to remain present". If the previous block is less the 64KB, then it need the previous' previous block present. All the previous block**s** that sum up to 64KB need to be present.

**Comment by heroboy** [comment]
>>    When ring buffer reset, is that means LZ4 forget the dictionary,
>
>Nope, everything still unmodified in the ring buffer, up to max 64KB, can be used as dictionary.

>> Is the code incorrect if the MESSAGE_MAX_BYTES is very large
>
>That's fine. It will work.

For example, the ring buffer is 20KB(assume MESSAGE_MAX_BYTES is 12KB), the previous block is 10KB. And the next block is 12KB, then ring buffer will reset, and previous block will be overwritten. 
Is it find?

And why I said "forget"? 
I see the lz4 code, when reset, it set `dict pointer` from previous block to external dictionary.
Sorry I am not expert, I just make guess and have interest. I don't known what is external dict, I think it is the internal builtin dict.

**Comment by heroboy** [comment]
>It depends on implementation detail.
>In this case, my understanding is that this example is using a ring buffer, so yes, line3 will be able to use both line2 and line1 as history buffer (assuming ring_buffer_size >= sum(lines)).

You can see the chart or the example code. It is ring buffer.
My question is when decompressing line3, is it need decompressed line1 and line2 present? (when decompress should use same or larger size ring buffer. And can not use double buffered method.)

**Comment by heroboy** [comment]
Sorry I have so many question. But the api is so strange. Why I can't directly tell which blocks is present.
I want understand how to use stream api correctly to improve the compression ratio.

**Comment by Cyan4973** [comment]
This is a very complex API, and if you feel confused, I would advise against using it.

Instead, consider using the `lz4frame.h` streaming API,
which takes care of all these shenanigans, and offers a much simpler interface to users.
