### ISSUE TITLE
Fast compression manually

### ISSUE THREAD

**Issue by litalkr** [lz4/lz4#1332]
Hello, 
When I'm compressing my file manually with fast compression:
"lz4 -1",  I get some compression size.
But, when I'm using LZ4_compress_default function (1.9.4) I get a different and smaller compression size.

So how should I compress my file (fast compression) in order to get the same compression size?
With High compression, I don't have this problem - works well.

Thank you.

**Comment by Cyan4973** [comment]
The `lz4` CLI uses the `lz4frame` format.

To get the same size as the `lz4` CLI, one would have to employ `LZ4F_compressFrame()`.
And of course, select the same parameters as the ones employed by the `lz4` CLI.

The end result is unlikely to be vastly different though. It should be "roughly the same".

**Comment by litalkr** [comment]
Ok, thank you! 
There is another manual way to use fast compression, and get the same result when using 
LZ4_compress_default function?

**Comment by Cyan4973** [comment]
If by "manual" you mean "using a command line interface", the answer is: none provided in this repository.

The output of `LZ4_compress_default` is a raw block, stripped of every metadata,
which cannot be decompressed on its own.
In particular, it doesn't tell its own size (which could be derived from the file size through) nor does it tell anything about the produced decompressed size, which could be anywhere between 1x and 250x, and therefore is an issue for buffer management.

Of course, once integrated into an application, it works within a context which generally answers these questions, or at least bounds them. But that's a very different environment from a CLI interface.
