### ISSUE TITLE
Question about streaming mode vs frame mode for large data streaming

### ISSUE THREAD

**Issue by devbhanudev** [lz4/lz4#1335]
This is a basic question, what is the recommended API for a data streaming scenario? There is a large stream of data (and hence cannot fit it entirely in memory) sent on a network and compressed and decompressed at the sender and receiver end. 

1. Does the LZ4Frame API (`LZ4F_compressBound`) or streaming API (`LZ4_createStream`) make more sense? LZ4Frame looks more advanced but the fact that the other API has streaming in the name makes me wonder if that is more suitable for data streams.  I could not find much documentation about the streaming API unfortunately.
2. Do both of these APIs depend on the previous block of data for decompression, or can they be decompressed per block? 
3. When there is a dependency on previous block, what if one of the compressed block is lost over network? How many further blocks would have to be skipped to or dropped because of this? 

Thank you in advance

**Comment by Cyan4973** [comment]
>     1. Does the LZ4Frame API (`LZ4F_compressBound`) or streaming API (`LZ4_createStream`) make more sense? 

_edit_ : For streaming, the LZ4Frame API generally makes more sense.

>     2. Do both of these APIs depend on the previous block of data for decompression, or can they be decompressed per block?

It's a selectable parameter.
By default, each block depends on previous one.

>     3. When there is a dependency on previous block, what if one of the compressed block is lost over network? How many further blocks would have to be skipped to or dropped because of this?

It's essentially finished. No guaranteed recovery.

These 2 topics should not be merged. It's not up to the compression layer to solve the issues of the transport layer. It's the other way round : the compression takes advantage of some guarantees from the transport layer, if they exist.

So, either there is 1 pipe, with whatever protocol guaranteeing that all data is received and in order, and you can have a dependent data stream over it,
or you have a pile of messages, that may or may not arrive, in any order, and you should treat each message separately.

**Comment by devbhanudev** [comment]
Thank you so much for the details and the quick reply.

Regarding question 1, between LZ4 Streaming API and LZ4 Frame API, which one is recommended, as opposed to the other one for this usecase? (as I could not get much documentation about streaming API)

**Comment by Cyan4973** [comment]
Apologies, I meant : for streaming, the `LZ4Frame` API generally makes more sense.
