### ISSUE TITLE
error Decompressed : 0 MiB Error 66 : Decompression error : ERROR_decompressionFailed

### ISSUE THREAD

**Issue by Mrqqeat** [lz4/lz4#1339]
**Describe the bug**
Decompressed : 0 MiB  Error 66 : Decompression error : ERROR_decompressionFailed

**To Reproduce**
run: `lz4.exe -d 1.lz4`
->Decompressed : 0 MiB  Error 66 : Decompression error : ERROR_decompressionFailed

The file should be fine, but I don't know why this error occurred. The extracted data ended up losing some of it
[1.lz4.zip](https://github.com/lz4/lz4/files/13796912/1.lz4.zip)

**Comment by t-mat** [comment]
Hi @Mrqqeat 

I've confirmed same error message with your attached file `1.lz4`.

> The file should be fine, but I don't know why this error occurred.

The following line reports this error message:
https://github.com/lz4/lz4/blob/v1.9.4/programs/lz4io.c#L1114

It usually means corrupted file.

Could you provide more information?

- Which version of `lz4` (CLI and/or library) are you using?
- How did you create this file?

**Comment by Mrqqeat** [comment]
> Hi @Mrqqeat
> 
> I've confirmed same error message with your attached file `1.lz4`.
> 
> > The file should be fine, but I don't know why this error occurred.
> 
> The following line reports this error message: https://github.com/lz4/lz4/blob/v1.9.4/programs/lz4io.c#L1114
> 
> It usually means corrupted file.
> 
> Could you provide more information?
> 
> * Which version of `lz4` (CLI and/or library) are you using?
> * How did you create this file?

I am using version 1.9.4 of lz4
In the lz4 file, starting with character 0x70 at position 0x88EB5 is a sequence.
Corresponding to the extracted file, starting with the 0x26 character at position 0xCFFF9.
Why does the decompressed file after this sequence end? There is still a lot of data after lz4.

**Comment by Mrqqeat** [comment]
> Hi @Mrqqeat
> 
> I've confirmed same error message with your attached file `1.lz4`.
> 
> > The file should be fine, but I don't know why this error occurred.
> 
> The following line reports this error message: https://github.com/lz4/lz4/blob/v1.9.4/programs/lz4io.c#L1114
> 
> It usually means corrupted file.
> 
> Could you provide more information?
> 
> * Which version of `lz4` (CLI and/or library) are you using?
> * How did you create this file?

Thank you very much for your reply. I have another question that I didn't understand. The extracted file is indeed decompressed in sequence, but for every 64KB (0x10000) of data decompressed, the first dozen bytes of data starting from 0x10000 do not match. What are these bytes of data

**Comment by t-mat** [comment]
Thanks for the informations.

> The extracted file is indeed decompressed in sequence, but for every 64KB (0x10000) of data decompressed, the first dozen bytes of data starting from 0x10000 do not match. What are these bytes of data

I have no idea at all.  We've never seen/reported that decompressed lz4 frame is broken like it.

> In the lz4 file, starting with character 0x70 at position 0x88EB5 is a sequence.
> Corresponding to the extracted file, starting with the 0x26 character at position 0xCFFF9.
> Why does the decompressed file after this sequence end? There is still a lot of data after lz4.

Please refer [the lz4 frame format](https://github.com/lz4/lz4/blob/v1.9.4/doc/lz4_Frame_format.md) to understand the detail of your `1.lz4`

```
$ hexdump --canonical --length 16 1.lz4
00000000  04 22 4d 18 48 40 37 86  0d 00 00 00 00 00 27 50  |."M.H@7.......'P|
         |~~ ~~ ~~ ~~|~~ ~~ ~~ ~~  ~~
         |MagicNb    |F.Desc         

F.Desc.FLG = 0x48 = 0b01'0'0'1'0'0'0
                      ++ | | | | | |
                      |  | | | | | DictID   = 0
                      |  | | | | *Reserved* = 0
                      |  | | | C.Checksum   = 0
                      |  | | C.Size         = 1
                      |  | B.Checksum       = 0
                      |  B.Indep            = 0
                      Version               = 01

F.Desc.BD  = 0x40 = 0b0'100'0000
                      | -+- -+--
                      |  |   |
                      |  |  *Reserved*
                      | Block maxSize
                      *Reserved*
```

Since `F.Desc.FLG == 0x48` and `(F.Desc.FLG & 4) == 0` this file doesn't contain the content checksum (`lz4 --no-frame-crc`).
Therefore, its last 4 bytes must be the "EndMark" = { 0x00, 0x00, 0x00, 0x00 }.  But actual `1.lz4` doesn't end with it.  Also, after the header, any part of `1.lz4` doesn't match the EndMark pattern {0,0,0,0}.

```
$ tail --bytes=16 ./1.lz4 | hexdump --canonical
00000000  6c f7 09 52 6f 8c 53 6d  8f fc 60 55 63 50 93 0a  |l..Ro.Sm..`UcP..|
                                               ~~ ~~ ~~ ~~
                                               Must be 0s
```

You can confirm typical `lz4 --no-frame-crc` file with the following commands:

```
$ programs/lz4 -f --no-frame-crc ./README.md
                  ~~~~~~~~~~~~~~

Compressed filename will be : ./README.md.lz4
Compressed 5365 bytes into 3500 bytes ==> 65.24%

$ tail --bytes=16 ./README.md.lz4 | hexdump --canonical
00000000  b0 69 73 20 70 72 6f 6a  65 63 74 0a 00 00 00 00  |.is project.....|
                                               ~~ ~~ ~~ ~~
                                                 EndMark
```

So we need more information to reproduce your `1.lz4` file.

- Could you provide actual command line or library arguments which creates your `1.lz4`?
  - For example, `lz4.exe --no-frame-crc -f 1 1.lz4`
  - Or, actual snippet of code which compresses your file.
- Could you provide raw, uncompressed, actual source of `1.lz4`?

**Comment by Mrqqeat** [comment]
> Thanks for the informations.
> 
> > The extracted file is indeed decompressed in sequence, but for every 64KB (0x10000) of data decompressed, the first dozen bytes of data starting from 0x10000 do not match. What are these bytes of data
> 
> I have no idea at all. We've never seen/reported that decompressed lz4 frame is broken like it.
> 
> > In the lz4 file, starting with character 0x70 at position 0x88EB5 is a sequence.
> > Corresponding to the extracted file, starting with the 0x26 character at position 0xCFFF9.
> > Why does the decompressed file after this sequence end? There is still a lot of data after lz4.
> 
> Please refer [the lz4 frame format](https://github.com/lz4/lz4/blob/v1.9.4/doc/lz4_Frame_format.md) to understand the detail of your `1.lz4`
> 
> ```
> $ hexdump --canonical --length 16 1.lz4
> 00000000  04 22 4d 18 48 40 37 86  0d 00 00 00 00 00 27 50  |."M.H@7.......'P|
>          |~~ ~~ ~~ ~~|~~ ~~ ~~ ~~  ~~
>          |MagicNb    |F.Desc         
> 
> F.Desc.FLG = 0x48 = 0b01'0'0'1'0'0'0
>                       ++ | | | | | |
>                       |  | | | | | DictID   = 0
>                       |  | | | | *Reserved* = 0
>                       |  | | | C.Checksum   = 0
>                       |  | | C.Size         = 1
>                       |  | B.Checksum       = 0
>                       |  B.Indep            = 0
>                       Version               = 01
> 
> F.Desc.BD  = 0x40 = 0b0'100'0000
>                       | -+- -+--
>                       |  |   |
>                       |  |  *Reserved*
>                       | Block maxSize
>                       *Reserved*
> ```
> 
> Since `F.Desc.FLG == 0x48` and `(F.Desc.FLG & 4) == 0` this file doesn't contain the content checksum (`lz4 --no-frame-crc`). Therefore, its last 4 bytes must be the "EndMark" = { 0x00, 0x00, 0x00, 0x00 }. But actual `1.lz4` doesn't end with it. Also, after the header, any part of `1.lz4` doesn't match the EndMark pattern {0,0,0,0}.
> 
> ```
> $ tail --bytes=16 ./1.lz4 | hexdump --canonical
> 00000000  6c f7 09 52 6f 8c 53 6d  8f fc 60 55 63 50 93 0a  |l..Ro.Sm..`UcP..|
>                                                ~~ ~~ ~~ ~~
>                                                Must be 0s
> ```
> 
> You can confirm typical `lz4 --no-frame-crc` file with the following commands:
> 
> ```
> $ programs/lz4 -f --no-frame-crc ./README.md
>                   ~~~~~~~~~~~~~~
> 
> Compressed filename will be : ./README.md.lz4
> Compressed 5365 bytes into 3500 bytes ==> 65.24%
> 
> $ tail --bytes=16 ./README.md.lz4 | hexdump --canonical
> 00000000  b0 69 73 20 70 72 6f 6a  65 63 74 0a 00 00 00 00  |.is project.....|
>                                                ~~ ~~ ~~ ~~
>                                                  EndMark
> ```
> 
> So we need more information to reproduce your `1.lz4` file.
> 
> * Could you provide actual command line or library arguments which creates your `1.lz4`?
>   
>   * For example, `lz4.exe --no-frame-crc -f 1 1.lz4`
>   * Or, actual snippet of code which compresses your file.
> * Could you provide raw, uncompressed, actual source of `1.lz4`?

Thank you for your reply. Unfortunately, I do not have the source file for lz4 as it is a game file.
But the extracted data is available. Although some content was missing at the end.
But regarding the issue with 0x10000 just now, I am not sure if it is damaged because the previous content looks good.


But regarding the issue with 0x10000 just now, I'm not sure if it's damaged, but lz4 can extract the data, and this data is indeed usable.
I have provided a merged image, with lz4 data on the left and decompressed data on the right. You will find that the first seven times do not seem to have any problems, but the data for the eighth and ninth times clearly do not match.
Sorry for the inconvenience caused https://github.com/lz4/lz4/blob/v1.9.4/doc/lz4_Frame_format.md I don't seem to understand why this is happening
https://upload.cc/i1/2023/12/30/iexvWg.png

**Comment by t-mat** [comment]
> Unfortunately, I do not have the source file for lz4 as it is a game file.

I can't investigate further since I can't distinct this is a bug or not without actual file, command line options or code.
Please ask directly to the developer of the game to resolve your issue.

**Comment by Mrqqeat** [comment]
> > Unfortunately, I do not have the source file for lz4 as it is a game file.
> 
> I can't investigate further since I can't distinct this is a bug or not without actual file, command line options or code. Please ask directly to the developer of the game to resolve your issue.

You can use version 1.9.4 of lz4.exe to execute lz4.exe - d 1. lz4, and it will output a decompressed 1 file. This 1 file is the decompressed one, The picture I sent is a comparison of the two files before and after decompression

**Comment by Mrqqeat** [comment]
> > Unfortunately, I do not have the source file for lz4 as it is a game file.
> 
> I can't investigate further since I can't distinct this is a bug or not without actual file, command line options or code. Please ask directly to the developer of the game to resolve your issue.

I seem to know now. It's because after the decompressed output data reaches 64KB, the next four bytes in lz4 do not need to be processed. Continuing with the subsequent data processing will be correct. Thank you very much for your guidance and patient answer.
