### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [lz4/lz4#1355]
Dear @lz4 team, @Cyan4973,

I wish you a Happy New Year 2024.

It is possible to create a new release build?

The latest is 1.9.4 (2022-08-16):
- https://github.com/lz4/lz4/releases
- https://github.com/lz4/lz4/tags

Thanks in advance.

**Comment by Cyan4973** [comment]
There will be a release this year.
There is just no set date yet.

**Comment by es20490446e** [comment]
I just liked to say I'm finding your compression algorithms VERY useful. I'm using them at everything you can imagine.

Thanks 😉

**Comment by HTHou** [comment]
Also looking forward a new release of lz4-java. :-)

**Comment by t-mat** [comment]
I made a new milestone `v1.9.5` and add some issues.

https://github.com/lz4/lz4/issues?q=is%3Aissue+milestone%3Av1.9.5

If you notice/think any other issues which should be addressed as a part of `v1.9.5`, please tell us about them.

**Comment by Neustradamus** [comment]
@t-mat: Thanks, I hope that issues will be solved soon...

**Comment by JakeMerdichAMD** [comment]
@t-mat: would #791 (stabilize dictionary training api) be an appropriate addition for v1.9.5? The last relevant comment (in 2019!) said `The dictionary API was still too young to be added to "stable" for v1.9.0, but it's definitely an item on the list for next important update, be it v1.10.0 or v2.0.0 (not decided yet).`. This can have an incredible benefit for certain use cases, and equivalent features in zstd are looking to make its way into an [IETF spec](https://datatracker.ietf.org/doc/draft-ietf-httpbis-compression-dictionary/).

We've been using it in some C/C++ libs with static linking, but many lz4 bindings don't want to add the feature until it's stable-- which is fair. This makes it a bit of a pain for interoperability (or ad-hoc python scripts).

**Comment by Cyan4973** [comment]
This would push the release number to `v1.10`, instead of `v1.9.5`,
but that seems like a reasonable request.

The main reason this API is not categorized "stable" yet is that I don't know about much usage of this API outside of our own production environment, which means it's lacking some kind of "real production feedback". 

Of course, it's also a chicken/egg problem, since many potential users do not employ this API because it's not stable. But then, if it's stable, it's not supposed to change anymore, which limits the kind of adaptation that can be done.

Anyway, I could consider this item for next release nonetheless.

**Comment by es20490446e** [comment]
Don't expect software to be completely stable. It shall have a stable base, with some beta on it. A controlled amount.

As long as this beta is well tested to work for you, it's good enough.

Otherwise you will find yourself in chicken/egg.

**Comment by teo-tsirpanis** [comment]
I would appreciate a release with #1372 and #1413. There is a divergence between upstream lz4 and its vcpkg port with regards to the exported CMake packages and targets and the casing of their names, and a release with these PRs would help towards closing the gap and unifying the ecosystem.

**Comment by hassila** [comment]
> Of course, it's also a chicken/egg problem, since many potential users do not employ this API because it's not stable. But then, if it's stable, it's not supposed to change anymore, which limits the kind of adaptation that can be done.
> 

Could I perhaps suggest formalization of the dictionary "template" trick outlined here:

https://github.com/lz4/lz4/issues/399#issuecomment-329337170

As part of the formal api? It seems like a very common desired use case and it is non-obvious - basically it could be a function that takes a dictionary and returns a "template", and the another function that can create a stream from that template (basically doing the memcpy).

It is trivial functionality of course, but it would guide users in the right direction for good compression performance using dictionaries.

**Comment by t-mat** [comment]
chore: Since we're progressing to the next release, I've added #1372 and #1413 to [milestone:v1.9.5](https://github.com/lz4/lz4/issues?q=is%3Aissue+milestone%3Av1.9.5) to ease to make the next release note.

**Comment by Cyan4973** [comment]
> Could I perhaps suggest formalization of the dictionary "template" trick outlined here:
> 
> [#399 (comment)](https://github.com/lz4/lz4/issues/399#issuecomment-329337170)
> 
> As part of the formal api? It seems like a very common desired use case and it is non-obvious - basically it could be a function that takes a dictionary and returns a "template", and the another function that can create a stream from that template (basically doing the memcpy).
> 
> It is trivial functionality of course, but it would guide users in the right direction for good compression performance using dictionaries.

@hassila: this is no longer a "trick", and an official API entry point already exists, as `LZ4_attach_dictionary()` ([link](https://github.com/lz4/lz4/blob/v1.9.4/lib/lz4.h#L547)),

though to be complete it's not yet part of the *stable* API.
This last step could be done as part of current objective to bring Dictionary API for LZ4 to "stable".

**Comment by ser-0xff** [comment]
Hi!
I see `LZ4_attach_dictionary()` only for `LZ4_stream_t` which is supposed to be used on the compression side.
I would expect also to find similar `attach_dictionary` for `LZ4_streamDecode_t` for decompression side or am I missing something?
Thank you!

**Comment by Cyan4973** [comment]
Yes, there is nothing to attach on the decompression side, because there is no initialization cost.

Just use the regular `LZ4_setStreamDecode()` for streaming,
or the stateless `LZ4_decompress_safe_usingDict()` for one-shot decompression.

**Comment by ser-0xff** [comment]
Thank you!

**Comment by Cyan4973** [comment]
The next release will be numbered `v1.10.0`,
due to an extension of the stable API for dictionary compression.

**Comment by Cyan4973** [comment]
`v1.10.0` released

**Comment by Neustradamus** [comment]
@Cyan4973: Thanks! :)
