### ISSUE TITLE
r131 build error

### ISSUE THREAD

**Issue by woodstock23** [lz4/lz4#138]
Hello,
I found two minor errors:
lz4.c line 828:
//printf("offset %5i, matchLength%5i \n", (int)(ip-match), matchLength + MINMATCH);
and lz4hc.c line 106:
//#define DELTANEXTU16(p)        chainTable[(p) & MAXD_MASK]   /\* flexible, MAXD dependent */
contain c++-style comments.
This fails to compile with Intel C++ Compiler 15.0.3 on Linux.
Thanks for your excellent work!

**Comment by Cyan4973** [comment]
Good point.
These are test/debug line, left in to re-enable them easily if needed.
Maybe a `#define` will do such job better

**Comment by terrelln** [comment]
Looks like this has been fixed by 00eedb37d102afe00e1c373448c114d2d5edd4b5 and 258a5e7fa44825488fe4683f3a04c36fc944a23f.
