### ISSUE TITLE
Scatter-Gather list support

### ISSUE THREAD

**Issue by achains** [lz4/lz4#1385]
Hi,
I tried my best searching for similar issue but yet I might need your help. 

Consider a decompression scenario where compressed block doesn't reside in continuous memory. I could always copy data in continuous buffer, but memcpy comes at cost and it might be handy to be able to pass a list of <pointer, size> pairs --- parts of compressed block.

Is there any workaround I can do with LZ4 in this case? 

Thank you!

**Comment by Cyan4973** [comment]
This scenario (where compressed block doesn't reside in continuous memory) is already supported by `LZ4` and `LZ4F` streaming API,
though you would have to invoke the streaming decompression function once per block.

**Comment by achains** [comment]
I am sorry for confusing, but it might not be exactly my case. Imagine I compressed a 4K block into 1800 byte block. However, I don't have enough continuous memory, so I manually break it on two blocks (let's say both 900 bytes) and store them by different virtual addresses.
Now when it comes to decompression it seems I can't decompress these partial chunks even using streaming API. So maybe it is me who can't reproduce streaming decompression, or decompression of such incomplete sub-chunks is not allowed. 

Just for reference, there is an Intel Quickassist library that implements LZ4 on hardware accelerators. There they have a concept of "buffer list" -- non-continuous memory, that consists of "flat buffers" -- continuous chunks.

**Comment by Cyan4973** [comment]
It depends if you employ `LZ4` (the underlying block compression routine)
or `LZ4F` (the upper frame layer management).

`LZ4F` supports this scenario, 
but `LZ4` doesn't: it requires a compressed block to be presented entirely upfront.
