### ISSUE TITLE
Clion makefile error:Make execution failed with exit code = 127

### ISSUE THREAD

**Issue by Chuan1937** [lz4/lz4#1419]
**Describe the bug**
using clion to build,but it's error with Make execution failed with exit code = 127

**Expected behavior**
fix it 

**To Reproduce**
![image](https://github.com/lz4/lz4/assets/99251452/110ef246-cede-4e98-9537-c58ebfc3365e)
![image](https://github.com/lz4/lz4/assets/99251452/a32541cd-4a02-4aee-9618-11f205ab2ebb)

**System (please complete the following information):**
 - OS: [e.g. Windows 10(amd64)]
 - Version [e.g. v10.0]
 - Compiler [e.g. gcc]
 - Build System [e.g. Makefile]
 - Other hardware specs [e.g. Core 2 duo...]

**Additional context**

**Comment by t-mat** [comment]
Hi,

Unfortunately, we can say nothing without your actual error/log.
Could you put your build log (including error) to this issue?

----

I think that we can compile lz4 on fresh MSYS2/mingw-w64 with the following command.

<details>
<summary>Setup fresh MSYS2/mingw-w64 and compile lz4 on it</summary>

(1) Download and extract msys2 (command prompt)

```
cmd.exe
cd /d "%PUBLIC%\Documents"
mkdir lz4-issue-1419
cd    lz4-issue-1419
curl -LJO https://github.com/msys2/msys2-installer/releases/download/2024-05-07/msys2-base-x86_64-20240507.sfx.exe
.\msys2-base-x86_64-20240507.sfx.exe -o"." -y

: launch msys2 console
cmd.exe /c "%PUBLIC%\Documents\lz4-issue-1419\msys64\mingw64.exe"
```

(2) Initial setup (msys2 console)

```sh
pacman -Sy --noconfirm pacman
pacman -Syu --noconfirm
# msys console will be closed automatically
```

(3) Re-launch msys2 console (command prompt)

```
cmd.exe /c "%PUBLIC%\Documents\lz4-issue-1419\msys64\mingw64.exe"
```

(4) 2nd setup (msys2 console)

```
pacman -S --noconfirm git base-devel $MINGW_PACKAGE_PREFIX-{pkg-config,gcc,clang}

uname -a                   # MINGW64_NT-10.0-22631 def7 3.5.3.x86_64 2024-05-20 12:06 UTC x86_64 Msys
make -v | grep "Make"      # GNU Make 4.4.1
gcc --version | grep "gcc" # gcc.exe (Rev3, Built by MSYS2 project) 14.1.0
```

(5) Clone and build lz4 (msys2 console)

```
cd
git clone https://github.com/lz4/lz4 lz4-issue-1419
cd lz4-issue-1419
git log -1
make clean all
./lz4.exe --version  # *** lz4 v1.9.5 64-bit single-thread, by Yann Collet ***
```

(6) Uninstall, if you need (command prompt)

```
cmd.exe
cd /d "%PUBLIC%\Documents"
rmdir /S /Q lz4-issue-1419
```

</details>
