### ISSUE TITLE
latest version decreases Lz4 HC compression speed

### ISSUE THREAD

**Issue by salos1982** [lz4/lz4#143]
I use lz4 compression to improve speed of image loading. I was trying to migrate to new version of implementation and found compression performance fall down. 
I put test case here:
https://drive.google.com/file/d/0B1PbczW6QMAyUWVpMGI5WTJnQW8/view?usp=sharing

**Comment by Cyan4973** [comment]
Could you tell : 

1. from which version to which version you are experiencing this difference
2. on which platform
3. using which compiler
    - and with which compiler settings
5. finally, provide some benchmark numbers to get some perspective ?

I tried to compile your project using the provided solution, but it failed on my 2 available versions of Visual (2012 and 2013).

Regards

**Comment by salos1982** [comment]
It is strange, it is Visual Stuido 2013 project. I downloaded the zip file I sent you and it is successfuly compiled.
I tested x64 (not win32) release version on windows 7 x64 Intel core I7 3770K.

**Comment by Cyan4973** [comment]
OK, the x64 version compiles fine.

One important information here is that your program uses lz4 __hc__. This is the slower & stronger derivative. It's targeted at offline compression, hence, in contrast with the _fast_ derivative, compression timing is not considered critical, so it's much less tested.

I could test your program with both the old (v1.1.3) and new (v1.7.1) libraries. v1.7.1 is indeed slower. I'll try to understand why.

**Comment by Cyan4973** [comment]
I've been testing the oldest tag available from github (`r116`) with latest `dev` branch, here below called `v1.7.2`, comparing their speed.

It's correct to say that, for an identical compression level, `r116` runs faster.
But it also compresses less.
And when trying to find a compression level on `r116` which compresses as good as `v1.7.2`, it makes `r116` comparatively much slower.

Here are some measurements, using your provided image sample `atlas0` (in raw format) on a Mac laptop compiled with clang LLVM v8.0.0 : 

| Version | level | C.Size | C.Speed | comment |
| -------- | ---- | ------- | -------- | --------- |
| v1.7.2    | 14   | 1900978 | 3.6 MB/s | compresses more and faster than r116 -16 |
| r116       | 16   | 1901563 | 2.3 MB/s |
| v1.7.2    | 9     | 1910244 | 27.5 MB/s |
| v1.7.2    | 8     | 1916600 | 41.5 MB/s | compresses more and faster than r116 -9 |
| r116       | 9     | 1917388 | 33.5 MB/s |

So a solution to preserve speed and nonetheless get an identical or better compression ratio would be to use the newer `dev` version with a smaller compression level.

Newer version will also deliver much better decompression speed.
