### ISSUE TITLE
Parameter -c (force write to standard output) has no effect if passing also parameter -v (verbose mode)

### ISSUE THREAD

**Issue by tbadil** [lz4/lz4#1439]
**Describe the bug**
like the title description ...

**To Reproduce**
Always

**Additional context**
Let's say you use lz4 to compress large files...

In an advanced backup procedure you should know the exact length in bits of the uncompressed file within the compressed file of the previous backup. Other things are also needed but this is the first thing.

Thus, if the original file is identical to the one compressed in the previous backup, you create a hardlink and not a new compressed file.

With lz4, if during compression the length of the original file was saved with the "--content-size" parameter, the size of the uncompressed file could be obtained with the command:
lz4 -c --list <LZ4_FILE>

However the size is not expressed in bits but rounded to GB.

To have it in bits you need to add the -v parameter, but by doing this, the output is no longer directed towards the standard one (as it should be with the -c parameter). Consequently it is impossible to load the length in bits into a variable

**Comment by t-mat** [comment]
Hi @tbadil ,
Thanks for the report.  You're right.  Behavior of `lz4 --list` and `lz4 -v --list` are inconsistent.

But please note that `-c` doesn't force any human-readable data to stdout.  It forces `lz4` to output (de)compressed data to stdout.  This behavior is borrowed from `gzip`.

----

Let's compare `lz4 --list` with `gzip --list`.


## `lz4`

`lz4 --list` reports to stdout.  But `-v --list` outputs to stderr.


```
./lz4 -f .md README.md.lz4
# Compressed 5365 bytes into 3504 bytes ==> 65.31%

# lz4 --list
./lz4 --list README.md.lz4 > test--list-stdout 2> test--list-stderr

cat test--list-stdout
#     Frames           Type Block  Compressed  Uncompressed     Ratio   Filename
#          1       LZ4Frame   B4I       3.42K             -         -   README.md.lz4

cat test--list-stderr
# ** empty **


# lz4 -v --list
./lz4 -v --list README.md.lz4 > test-v--list-stdout 2> test-v--list-stderr

cat test-v--list-stdout
# ** empty **

cat test-v--list-stderr
# *** lz4 v1.9.5 64-bit multithread, by Yann Collet ***
# README.md.lz4(1/1)
#      Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
#          1       LZ4Frame   B4I    XXH32                 3504                    -         -
```


## `gzip`

`gzip` always reports to stdout.

```
gzip -kf README.md

# gzip --list
gzip --list README.md.gz > test-gz--list-stdout  2> test-gz--list-stderr

cat test-gz--list-stdout
#          compressed        uncompressed  ratio uncompressed_name
#                2385                5365  56.1% README.md

cat test-gz--list-stderr
# ** empty **


# gzip --list -v
gzip --list -v README.md.gz > test-gz-v--list-stdout  2> test-gz-v--list-stderr

cat test-gz-v--list-stdout
# method  crc     date  time           compressed        uncompressed  ratio uncompressed_name
# defla 6d40e9ef May 27 17:44                2385                5365  56.1% README.md

cat test-gz-v--list-stderr
# ** empty **
```


## Short analysis

`LZ4IO_displayCompressedFilesInfo()` uses both `DISPLAYOUT()` (stdout) and `DISPLAYLEVEL()` (DISPLAY() -> stderr).
We need to maintain their consistency.

**Comment by tbadil** [comment]
You can also solve the problem in another way, returning the size value in BITS and not in GB even when only the "--list" parameter is present, without the "-v" parameter. The important thing is that there is a way to have in stdout the length in BITS of the original decompressed file.

**Comment by Cyan4973** [comment]
I presume you meant the length in **Bytes**.

**Comment by tbadil** [comment]
Yes: bytes, not bits... sorry.

**Comment by Cyan4973** [comment]
We have a format constraint that makes it preferable to display sizes as a summarized `KB`/`MB`/`GB` metric for the condensed view,
but the verbose view does indeed return a precise size in bytes.

We just have to ensure that `stdout` is used for the output, instead of `stderr` currently,
See #1446 .
