### ISSUE TITLE
Streaming API and end of stream/marker

### ISSUE THREAD

**Issue by kostasrim** [lz4/lz4#1455]
Hi there I am having trouble understanding how to end a frame with the `stream api`.

So for example, in `zstd` a stream can end with `ZSTD_compressStream2(ctx, &out, &in, Zstd_e_end)`. This denotes the `end of the frame` so the other side can call `ZSTD_decompressStream()` until it returns `0` which means the frame is completely decoded.

Is there a way to achieve the same behavior with `lz4` ? The stream examples I found in the repository fetch the compressed data from a file and stop only when the file is fully read, that is, the end marker of the frame is actually the `EOF` of the file.

On the API side in `lz4.h` for stream compression:

```
Z4LIB_API int LZ4_compress_fast_continue (LZ4_stream_t* streamPtr, const char* src, char* dst, int srcSize, int dstCapacity, int acceleration);
```

The last parameter is `acceleration` which is irrelevant with the `end of frame`. Furthermore, the first parameter `LZ4_stream_t` seems to also be irrelevant (that is there is no member or parameter that allows to explicitly state end of frame).

```
  689 union LZ4_stream_u {
  690     char minStateSize[LZ4_STREAM_MINSIZE];
  691     LZ4_stream_t_internal internal_donotuse;
  692 }; /* previously typedef'd to LZ4_stream_t */
  693 
```

Is there something I am missing here or is it impossible to explicitly end the frame (which means that the data must be decompressed and processed by the application protocol to denote the end of the frame/stream)?

**Comment by Cyan4973** [comment]
The is a strong distinction between the [LZ4 Block format](https://github.com/lz4/lz4/blob/v1.9.4/doc/lz4_Block_format.md), which is what the `LZ4_*` API manipulates,
and the [LZ4 Frame format](https://github.com/lz4/lz4/blob/v1.9.4/doc/lz4_Frame_format.md), which is what the `LZ4F_*` API manipulates.

`zstd` is more directly comparable to the LZ4 Frame format. The LZ4 Block format is just the "raw compressed block", barebone with no metadata nor additional service.

And it matters for your question. `LZ4_compress*` only produces the compressed block, but it's up to the caller to build the necessary logic around it. For example, `LZ4_compress*` will not even include the block's compressed or decompressed sizes in the data, yet these information are necessary for decompression.
Similarly, if you want to create a multi-block logic, and generate an end of chain signal, you'll have to decide and implement one that fits your logic.

All these topics are already decided and implemented in the LZ4 Frame format, and so it's the recommended format, especially for any "advanced" need like streaming, or if you expect the produced data to be interoperable with the rest of the LZ4 ecosystem.
The [API is exposed in `lz4frame.h`](https://github.com/lz4/lz4/blob/v1.9.4/lib/lz4frame.h#L264) .
You'll want to look at symbols `LZ4F_compressBegin()`, `LZ4F_compressUpdate()` and `LZ4F_compressEnd()`.

**Comment by kostasrim** [comment]
Hi @Cyan4973 thank you so much for getting back to me.

I understand the difference between the block and a frame but for some reason I thought that you could just "say to the API that this is the last block" which would also imply the end of the frame but your explanation between `zstd` and `lz4f` makes sense.

>but it's up to the caller to build the necessary logic around it. For example, LZ4_compress* will not even include the block's compressed or decompressed sizes in the data, yet these information are necessary for decompression

Yep I understand this, it's up to the application protocol.

>The [API is exposed in lz4frame.h](https://github.com/lz4/lz4/blob/v1.9.4/lib/lz4frame.h#L264) .
You'll want to look at symbols LZ4F_compressBegin(), LZ4F_compressUpdate() and LZ4F_compressEnd().

This exactly what I needed and more than enough for my use case.

Again thank you for the quick reply 🙏
