### ISSUE TITLE
undefined reference to `clock_gettime'

### ISSUE THREAD

**Issue by eschnett** [lz4/lz4#1474]
I am building lz4 1.10.0 from source on an x86-linux-gnu system. The build aborts with

```
[13:52:29] cc -O3 -fPIC -I../lib -DXXH_NAMESPACE=LZ4_ -DNDEBUG -DLZ4IO_MULTITHREAD -pthread ../lib/lz4.o ../lib/lz4file.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o lorem.o lz4cli.o lz4io.o threadpool.o timefn.o util.o -o lz4
[13:52:29] timefn.o: In function `TIME_getTime':
[13:52:29] timefn.c:(.text+0x1e): undefined reference to `clock_gettime'
[13:52:29] collect2: error: ld returned 1 exit status
```

This might be related to https://github.com/lz4/lz4/issues/450 .

**System (please complete the following information):**
```
sandbox:${WORKSPACE}/srcdir/lz4 # uname -a
Linux indigo 6.5.0-35-generic #1 JuliaOS SMP PREEMPT Wed Feb 13 00:49:00 UTC 2013 x86_64 GNU/Linux
```
```
sandbox:${WORKSPACE}/srcdir/lz4 # gcc --version
x86_64-linux-gnu-gcc (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
sandbox:${WORKSPACE}/srcdir/lz4 # ld --version
GNU ld (GNU Binutils) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
- Build System [e.g. Makefile]
```
make -j${nproc} CFLAGS="-O3 -fPIC"
make install
```

**Comment by Cyan4973** [comment]
`gcc` `4.8.5` is pretty old by now,
yet I would expect it to support `POSIX.1-2001`.

Sometimes, some systems require additional conditions to access some API symbols.
In this case, since the code tests for the presence of `CLOCK_MONOTONIC`, and finds it, it's likely that `clock_gettime()` (which is the only user of this macro) is available.

#450 mentions a need to add `-lrt` to reach the symbol at link time.
So you could try `LDLIBS=-lrt make`, and see if it links correctly this way.

**Comment by eschnett** [comment]
Yes, `make LDLIBS=-lrt` works.

**Comment by giordano** [comment]
> gcc 4.8.5 is pretty old by now,
> yet I would expect it to support POSIX.1-2001.

The problem isn't gcc, but glibc

**Comment by cieplutki** [comment]
For glibc versions before 2.17* You have to 'manually' link with librt (.so/.a) to get access to real time clock.
You can use static link as it's cost for single, simple function like [clock_gettime](https://www.man7.org/linux/man-pages/man3/clock_gettime.3.html) is negligible.
```
294480 lz4-rt-a
294416 lz4-rt-so
```
-----
* [glibc 2.17](https://sourceware.org/glibc/wiki/Release/2.17)
> The `clock_*' suite of functions was moved from librt to libc. Some configure scripts check only whether clock_gettime() is in librt and assume that other functions like mq_gettattr() are in the same library. So, the configure check for clock_gettime() in librt needs to be extended to look for other functions as well.
