### ISSUE TITLE
Possible (minor) bug

### ISSUE THREAD

**Issue by fcorbelli** [lz4/lz4#1477]
In lz4.c there is a "strange" check
```
        if ((match > lowLimit) && unlikely(ip[-1] == match[-1])) {
            do { ip--; match--; } while (((ip > anchor) & (match > lowLimit)) && (unlikely(ip[-1] == match[-1])));
```
Maybe a missing "&" ?
### while (((ip > anchor) && (match > lowLimit)) && (

**Comment by Cyan4973** [comment]
This is on purpose.
It forces the code to use an arithmetic operation instead of branch,
thus reducing the nb of branches.

**Comment by t-mat** [comment]
I think questions for & vs && are our minor faq.  So we may be able to add comments for these tricky/cryptic conditions.
