### ISSUE TITLE
lz4c is missing

### ISSUE THREAD

**Issue by heitbaum** [lz4/lz4#1478]
**Describe the bug**

lz4c is missing. 
- Whilst this was as per the #1460
- It is used by Linux kernel builds https://github.com/torvalds/linux/blob/6342649c33d232c4e7ac690b98bcddaab10a4d8c/Makefile#L510

**Expected behavior**
Please describe what you expected to happen.

- lz4c is available

**To Reproduce**
1. Compile linux kernel (when compressed with lz4)
2. See error 'LZ4     arch/arm/boot/compressed/piggy_data
/bin/sh: 1: lz4c: not found'

**System (please complete the following information):**
 - OS: [e.g. Mac] Linux Ubuntu
 - Version [e.g. 22] 24.04
 - Compiler [e.g. gcc] gcc-14.1.0
 - Build System [e.g. Makefile] make

**Comment by Cyan4973** [comment]
To be fair, it should not matter if the linux kernel build invokes `lz4` or `lz4c`. And since `lz4c` is essentially deprecated for many years now, it would be desirable to switch the usage pattern towards invoking `lz4`.
