### ISSUE TITLE
[Question] About LZ4_decompress_safe dstCapacity parameter.

### ISSUE THREAD

**Issue by wzhengsen** [lz4/lz4#1489]
When I decompress a piece of data compressed using LZ4_compress_default, what should I choose for the dstCapacity parameter?
As far as I know:
1. In most cases, dstCapacity should be 2-3 times larger than compressedSize;
2. but in some very special cases, such as a series of identical "1111111..." strings may be compressed to a very small size, then compressed them, if you still use 2-3 times the dstCapacity may lead to failure;
3. I have considered using LZ4_decompress_safe_continue, but it still has to pass the dstCapacity parameter and still returns a failure in the case of dst exhaustion;
4. should I use the LZ4F_* function?

Thanks.

**Comment by Cyan4973** [comment]
Using the `LZ4_*` block API presumes the caller knows the size, or maximum possible size, of the block to decompress.
Without this information, it's difficult to guarantee success.
The maximum expansion factor is ~250x, which is generally too large to blindly estimate a destination buffer size.

If you don't know the decompressed size, prefer employing streaming with `LZ4F_*` (which also requires employing `LZ4F_*` for compression).
This will correctly handle all sorts of potential scenarios, including crazy ones, such as decompressing repetitively into a 1 byte buffer.

**Comment by wzhengsen** [comment]
@Cyan4973 Thanks, that solves my confusion.
