### ISSUE TITLE
Question about hash in lz4

### ISSUE THREAD

**Issue by ProProGG** [lz4/lz4#1494]
Hi, I'm a little confused about a question.
I tested the LZ4 versions r130 and 1.7.5 with a data size of 16KB, and found that version 1.7.0 has better compression performance. Comparing the code, I discovered that their hash functions are different. For input sizes smaller than LZ4_64Klimit, r130 uses hashSequence64, while 1.7.5 uses hashSequence32.I would like to ask why lz4 chooses hashSequence32 for small files, and whether the hash function affects compression performance.

`FORCE_INLINE U32 LZ4_hashPosition(const void* p, tableType_t const tableType)`
`{`
`    if ((LZ4_64bits()) && (tableType == byU32)) return LZ4_hash5(LZ4_read_ARCH(p), tableType);`
`    return LZ4_hash4(LZ4_read32(p), tableType);`
`}`

|     | compression throughput   | compression throughput | compression ratio|
|  ----  | ----  |----  |----  |
| r130  | 420MB/s | 1380MB/s | 51.94% |
| v1.7.5  | 360MB/s  |1330MB/s | 52.13%|

**Comment by Cyan4973** [comment]
Yes, that's part of the tweaking experience, some choices vary across versions.

The general idea is that searching for longer matches tends to be better on large files, while aiming for smaller matches is generally better on smaller files. 

There is a correlation with nb of candidates: on small data, there are less candidates, so less opportunities to find matches, so we are happy to even have one and take it. On large data, we have way more candidates, so we should be picky and select better (aka longer) ones. But fast mode only remembers one candidate per hash. So, when there are multiple candidates starting with the same 4 characters, it only gets to remember the last one. And it's very frequent for some sequences of characters to be way more common, therefore generating a ton of collisions.
If that's the case, we want our hash to lead to better (longer) matches, and aiming at 5 characters helps for that goal.

Now, of course, this is all heuristics, and what works "in general" for many data may not work for a specific sample. Hence it's possible to find some data where the heuristics doesn't work as well. For example, if the data _only_ contains 4-byte matches, then the 5+ strategy will completely fail. 

That being said, for the more general case, 4+ vs 5+ is not a big difference, we are talking about some relatively small advantage. 

Looking at your report, the difference is indeed not big, but it is negative, meaning that for this sample, the 4-bytes strategy of `v1.7.5` works less well than the 5-bytes strategy of `v1.7.0`. Given that you mention that this is small data (<16 KB), it's not the expectation, 4-bytes would be expected to compress better, but then again, it's just a general tendency, not a guarantee, and there are certainly some samples that will prefer the 5-bytes strategy.

What seems consistent with expectation though is speed: 5-bytes strategy is expected to be faster, both at compression and decompression speeds. Not hugely, but still measurably. And that part seems to work as expected.

**Comment by ProProGG** [comment]
Thank you for your response.I conducted further testing using silesia.tar and the results indicate that 1.7.5 performs better in compression ratio compared to r130 in some tests, while it lags behind r130 in others. Across all tests, however, r130 demonstrates superior performance in both compression and decompression compared to 1.7.5.In some test scenarios, the compression ratio of hash5 is better than that of hash4, which might be due to more hash collisions in hash4? As you mentioned, only the last candidate is remembered per hash.

I am currently more concerned about the compression performance and compression ratio of small files, maybe hash5 can be a better choice?Additionally, I would like to ask if there would be any issues arising from modifying the hash function for processing small files to hash5 in lz4 1.7.5.

`LZ4_compress_default`
`LZ4_decompress_safe`

| Data              | v1.7.0  | v1.7.5  | Compression Ratio Variation |
| ----------------- | ------- | ------- | --------------------------- |
| silesar.tar       | 51.94%  | 52.13%  | 0.19%                       |
| silesia/dickens   | 67.99%  | 67.95%  | -0.04%                      |
| silesia/mozilla   | 54.07%  | 53.90%  | -0.17%                      |
| silesia/mr        | 57.18%  | 58.60%  | 1.42%                       |
| silesia/nci       | 20.80%  | 21.61%  | 0.81%                       |
| silesia/ooffice   | 72.42%  | 70.72%  | -1.70%                      |
| silesia/osdb      | 67.25%  | 67.57%  | 0.32%                       |
| silesia/reymont   | 53.30%  | 57.45%  | 4.15%                       |
| silesia/samba     | 41.82%  | 42.21%  | 0.39%                       |
| silesia/sao       | 94.15%  | 91.14%  | -3.01%                      |
| silesia/webster   | 53.41%  | 53.81%  | 0.40%                       |
| silesia/xml       | 28.25%  | 29.26%  | 1.01%                       |
| silesia/x-ray     | 100.14% | 97.68%  | -2.46%                      |

**Comment by Cyan4973** [comment]
No, there is no "issue", it's just a slightly different bet, leading to slightly different places.

As mentioned, `hash5` is just expected to be better "in general" for large files,
while `hash4` is expected to be better "in general" for small files.
Counter examples exist for both.
