### ISSUE TITLE
Visual 2022 tests have been failing recently

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#1507]
**Describe the bug**
> Visual 2022 tests have been failing recently, though the reason why is unclear.
https://github.com/lz4/lz4/pull/1506#issuecomment-2332185262

**Expected behavior**
All VS2022 tests are done successfully.

**To Reproduce**

```bat
cmd.exe
cd /d "%PUBLIC%\Documents"
git clone https://github.com/lz4/lz4.git lz4-1506
cd lz4-1506
cd .\build\VS2022
.\build-and-test-win32-release.bat
```

**System (please complete the following information):**
my local environment
 - OS: Windows 10.0.22631, Build 22631
 - Compiler MSVC v17.11.2
 - Build System msbuild

**Additional context**
- Reproduced in GitHub Actions and my local environment.

Debug build passes, release build fails the `fullbench` test.

| Script                                | Status                                                                        |
| --                                    | --                                                                            |
| build-and-test-win32-debug.bat        | Pass                                                                          |
| build-and-test-win32-release.bat      | Fail (infinite loop at `12-LZ4F_decompLZ4F_decompress_followHintress`)        |
| build-and-test-x64-debug.bat          | Pass                                                                          |
| build-and-test-x64-release.bat        | Fail (infinite loop at `12-LZ4F_decompLZ4F_decompress_followHintress`)        |

**Comment by t-mat** [comment]
I've put the following printf to [this line](https://github.com/lz4/lz4/blob/e0781fbe4b667f529864b268c5df491a9094e3f0/tests/fullbench.c#L453) of `local_LZ4F_decompress_followHint()`.

```C
// FILE* fp = fopen("debug-log.txt", "wt");

fprintf(fp, "inPos=%12zu, inSize=%12zu, outPos=%12zu, outRemaining=%12zu, sizeHint=%12zu\n", inPos, inSize, outPos, outRemaining, sizeHint);
fflush(fp);

// fclose(fp);
```

When it doesn't complete the test, variables are:

```
inPos= 0, inSize=                    7, outPos= 0, outRemaining= 14901, sizeHint= 7
inPos= 0, inSize= 18446744073709551603, outPos= 0, outRemaining= 14901, sizeHint= 18446744073709551603
inPos= 0, inSize= 18446744073709551603, outPos= 0, outRemaining= 14901, sizeHint= 18446744073709551603
```

`18446744073709551603 == 0xFFFFFFFFFFFFFFF3 == -13 = LZ4F_ERROR_frameType_unknown`

Also, when I added more harmless debug codes to `local_LZ4F_decompress_followHint()`, eventurally it passes the test for some reason.

Since debug build doesn't raise [`assert(!LZ4F_isError(sizeHint));`](https://github.com/lz4/lz4/blob/e0781fbe4b667f529864b268c5df491a9094e3f0/tests/fullbench.c#L446), I think it's caused by MSVC's optimization issue.

**Comment by Cyan4973** [comment]
Also,
it started recently.
We can see that last merged commit, #1493, was still working perfectly fine with Visual 2022.

**Comment by Cyan4973** [comment]
Just adding a data point :
I don't have VS2022 on any system around (yet),
but I do have a Windows laptop setup with VS2019.

I tried the same test `build-and-test-win32-release.bat` in this environment,
and it completed fine, no error.

It narrows the issue towards VS2022 specifically (and likely only very recent version).

**Comment by Cyan4973** [comment]
Fixed, by moving the build operation to `debug` mode.
