### ISSUE TITLE
I tried to root a phone using Odin, which said LZ4 is invalid

### ISSUE THREAD

**Issue by Doriffto** [lz4/lz4#1525]
I tried rooting a Samsung Galaxy Fold 5 using this guide: https://www.samsungsfour.com/tutorials/root-galaxy-z-fold5-magisk.html
Everything was fine until Odin said LZ4 is invalid. I found a similar issue here: https://github.com/lz4/lz4/issues/802
I don't know how to use LZ4, and the solution written in that issue is hard to understand for me.
So, if you can, please write a guide to solve this issue in a way that's easy to understand for an average user.
![odin](https://github.com/user-attachments/assets/7dbac83b-99f3-4a3b-a002-042277a0f765)

**Comment by Cyan4973** [comment]
We do not write guides about how to root smartphones using 3rd party tools
