### ISSUE TITLE
Missing _version.py file in lz4 package causing ModuleNotFoundError

### ISSUE THREAD

**Issue by SparklingTopaz** [lz4/lz4#1529]
Hello everyone,

I am experiencing an issue with the lz4 package in Python. After reinstalling Python and the lz4 library, I encountered a ModuleNotFoundError related to a missing _version.py file. Here’s a summary of my setup and the steps I’ve taken:
Environment Details:

    Python Version: 3.13
    Operating System: Windows 10
    Installed Packages: lz4, browser_cookie3

Error Message:

When running my script, I receive the following error:

ModuleNotFoundError: No module named 'lz4._version'

This error occurs specifically in the browser_cookie3 package, which attempts to import lz4.block.

Steps Taken:

    Checked for Installation of lz4:
        I verified that lz4 is installed using pip show lz4. It confirmed the installation but did not indicate the presence of the _version.py file.

    Reinstalled lz4:
        I uninstalled and reinstalled the package using:

        pip uninstall lz4
        pip install lz4

    Checked the Installation Directory:
        I navigated to the lz4 installation directory (e.g., C:\Program Files\Python313\Lib\site-packages\lz4\) but did not find the _version.py file.

    Tried Installing Different Versions:
        I attempted to install older versions of lz4, but the issue persisted with the missing file.

    Explored Alternative Installation:
        I considered downloading the lz4 package directly from GitHub, but I wanted to check if anyone else has encountered this issue and found a solution.

Request for Help:

If anyone has experienced similar issues or knows how to resolve this problem, I would greatly appreciate your guidance. Is there a specific reason why _version.py is missing in my installation? Any help would be invaluable!

Thank you for your time!

**Comment by t-mat** [comment]
Hi @SparklingTopaz,

Since this repository is dedicated to upstream lz4 (`lz4` in the programming language C), we can't directly answer your problem about `pip` and its `lz4` package.

Please search their project page via https://pypi.org/search and ask your question in their issue board.
