### ISSUE TITLE
Allow limiting match offset max value (feature request)

### ISSUE THREAD

**Issue by jens-gpio** [lz4/lz4#154]
For microcontrollers which have very little SRAM, it would be possible to decompress large files, if the maximum match offset was limited.
This would of course increase the size of the output files, but it would result in making it possible to decompress more files on devices which has  for instance 16K RAM available.

Limiting the maximum size of the match offset does not necessarily mean that a new compressed block will be started; it just means that it's not allowed to use data, which is beyond a certain distance.
Sometimes it would pay to start a new block of compressed data, sometimes it would pay to just find another position where the compressed data could be read from.

(Note: I have a suggestion for reducing the number of 0xff in the compressed stream; I'll file a suggestion on this later)

See also my comment here: http://community.arm.com/docs/DOC-10570#comment-15939

**Comment by jens-gpio** [comment]
I'll try playing a little with MAX_DISTANCE.
I think it's great that you already have the functionality.
Normally I would pass such parameters inside a structure belonging to the process, but I do not know if that would be a preferred way in this case.
I'm aware that you can't just use a global variable, since we're speaking about a library function.
Something like 'compression objects' would probably be a good approach.

As for the decompressor, it should be fairly easy to limit the ring buffer size; even if not speaking about power of two. The IT instruction on the Cortex-M is sometimes able to "fold" and thus on Cortex-M3 use zero clock cycles; leaving only a single clock cycle for executing the CMP instruction.
If the CMP instruction is 16-bit, it can be folded into a 16-bit LDR instruction, which makes the CMP instruction zero cycle. The IT instruction allows a block of up to 4 instructions to be free (zero-cycle) if they're not executed. On other arhitectures, such as 6502 and 68000, it would probably be best to stick with power-of-two, though.

**Comment by Cyan4973** [comment]
The maximum offset is now configurable at build time,
using `LZ4_DISTANCE_MAX` macro.
This feature will be part of next release (`v1.9.0`).
