### ISSUE TITLE
Bug in LZ4_decompress_fast_continue

### ISSUE THREAD

**Issue by ryhor-spivak** [lz4/lz4#166]
Line 1401 in lz4.c:

lz4sd->externalDict = (BYTE*)dest - lz4sd->extDictSize;

looks like it should be:

lz4sd->externalDict = lz4sd->prefixEnd - lz4sd->extDictSize;

just like in LZ4_decompress_safe_continue

**Comment by Cyan4973** [comment]
Thanks for the report.
It seems you are right.

What would be even better is to produce a test case which triggers the problem. And an even better solution would be to include the test case into the fuzzer test tool.
This way, it would be checked at each future update.

**Comment by despoke** [comment]
I just found the same bug and fixed locally.

**Comment by terrelln** [comment]
I will fix it and look into finding an exposing test case.
