### ISSUE TITLE
minor typo in man page

### ISSUE THREAD

**Issue by charles-cooper** [lz4/lz4#167]
In the man page, "extensionq"
https://github.com/Cyan4973/lz4/blob/master/programs/lz4.1#L116

**Comment by Cyan4973** [comment]
Good catch ! Thanks for notification @charles-cooper .

Man, I hate this `man` file format. It's so much difficult to edit than markdown ...

**Comment by charles-cooper** [comment]
Glad to help!

**Comment by mavam** [comment]
> Man, I hate this man file format. It's so much difficult to edit than markdown

Roff is a pain to write, but fortunately there exist plenty of tools for conversion from Markdown. My favorite: [md2man](https://github.com/sunaku/md2man).

**Comment by Cyan4973** [comment]
Thanks @mavam, it's a good reference !
