### ISSUE TITLE
Performance degradation during 2 years of LZ4 development

### ISSUE THREAD

**Issue by kirillx** [lz4/lz4#174]
I previously used LZ4 version from April 2, 2013.
Just updated LZ4 in my sources with latest version (r131) and during compatibility testing found degradation in compression speed (compatibility was confirmed though). On my test text file ~400MB in size new version takes ~1.9sec to compress, while the old one took only ~1.13sec (70% slower!). This is pure compression speed, w/o any I/O as file is fully cached.

Any ideas what has happened with the fastest compression algorithm?

Machine: MacBookPro 2013, 2.3 GHz Intel Core i7
OS: Linux CentOS 7.1 x64

**Comment by Cyan4973** [comment]
Really no idea. Too many parameters can affect speed.
Sure, between 2 versions, you can expect changes, but not by that much, and in general it should better be favorable.

Maybe it could also be related to compiler version and settings.

I suspect you are using clang.
Are you able to compare with gcc ?
Are you using `-O3` flag ?

**Comment by kirillx** [comment]
No, it's standard gcc from CentOS 7.1:
gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC)
compiling with -O2, quite simple compile options:
cc -Wall -fstack-protector-all -fno-strict-aliasing -Wstrict-prototypes -Werror -O2    -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64

**Comment by Cyan4973** [comment]
`-O3` settings are used.

I'm aware `-O2` brings less performance, but haven't had enough time to investigate.
I suspect it could be because the code expects compiler to inline a few critical functions, and `-O2` is probably not aggressive enough. It could be compensated by manually selecting which functions must be inlined with `force_inline` attribute.

go-assisted build is also likely to help automate inlining decisions.

Well, bottom line : code is currently benchmarked using `-O3`, and speed regressions are checked against this setting.

**Comment by t-mat** [comment]
Hi,

I'm not sure specific versions/data performance, but I'm interested in benchmarking between versions.

So, here is a quickhack for Python3 : [test-lz4-versions-benchmark.py](https://gist.github.com/t-mat/12fc358708cded426e01)

 - NOTE : Since this has benchmarked on my busy VM, this de/compression speed result is useless.

You can use this script by the following procedure:

```
mkdir lz4-issue-174 && cd lz4-issue-174
git clone https://github.com/Cyan4973/lz4.git .
cd versionsTest
curl -JOL https://gist.githubusercontent.com/t-mat/12fc358708cded426e01/raw/test-lz4-versions-benchmark.py
python3 ./test-lz4-versions-benchmark.py --benchmark --make-j --data=../programs/COPYING
```

Basically, this script is same as `versionsTest/test-lz4-versions.py` but it execute all released (git-tagged) lz4c and lz4c32's internal benchmark.

Since it just redirects stderr, output is still broken.  But I hope this script shows basic concept.
I think it would be user's good self testing tool for typical problem: "For my own data, is rNNN slower/faster on my compiler A.B.C?".

**Comment by Cyan4973** [comment]
Thanks @t-mat 

I tried your script on a test machine.
For some reason, `\r` or `\n` are displayed "as is", without being interpreted,
as a consequence, result display is a bit difficult to read.

I was unsure if this issue was relative to some local configuration settings, so I ran it again into a Linux VM. Same result.

`````
92 ->\r1-test_dat       :     18092 ->     10582 (58.49%),  397.5 MB/s\r1-test_dat       :     18092 ->     10582 (58.49%),  397.5 MB/s , 1772.0 MB/s\r2-test_dat       :     18092 ->\r2-test_dat       :     18092 ->     10582 (58.49%),  414.4 MB/s\r2-test_dat       :     18092 ->     10582 (58.49%),  414.4 MB/s , 1772.0 MB/s\r3-test_dat       :     18092 ->\r3-test_dat       :     18092 ->     10582 (58.49%),  414.4 MB/s\r3-test_dat       :     18092 ->     10582 (58.49%),  414.4 MB/s , 1772.0 MB/s\rtest_dat         :     18092 ->     10582 (58.49%),  414.4 MB/s , 1772.0 MB/s\n'
`````

**Comment by t-mat** [comment]
Yes. In first version, I reformated it by hand.
And here revamped: [test-lz4-versions-benchmark.py](https://gist.github.com/t-mat/12fc358708cded426e01).  You can download it by same `curl` command line:
```
cd lz4-issue-174
cd versionsTest
curl -JOL https://gist.githubusercontent.com/t-mat/12fc358708cded426e01/raw/test-lz4-versions-benchmark.py
```
Revamped version will properly interpret escape sequence and show pretty line.

[test_benchmark()](https://gist.github.com/t-mat/12fc358708cded426e01#file-test-lz4-versions-benchmark-py-L122-L132) implements benchmark.  You can tweak command line options array in `proc()`.

**Comment by t-mat** [comment]
I noticed your edit2.

> I wonder what's the point of such check beyond debug builds ?

Even release/optimized build, automatic stack checking is useful feature to protect from malicious data which aim to manipulate stack.  Usually attacker's target is release/optimized build.

And perhaps it would be nice to add different compiler (gcc4/gcc5/clang) and compiler options (`-O2`, `-O3`, `-fstack-protector-all`) to this script.

**Comment by Cyan4973** [comment]
Thanks @t-mat , the new version works pretty neat !

So, to summarize,
on my test station, version r130 and r131 are fastest. By a wide margin.

`````
r128
test_dat         :     18092 ->     10582 (58.49%),  403.1 MB/s , 2112.8 MB/s
test_dat         :     18092 ->     10582 (58.49%),  405.7 MB/s , 2027.9 MB/s
r129
test_dat         :     18092 ->     10408 (57.53%),  427.6 MB/s , 2812.1 MB/s 
test_dat         :     18092 ->     10582 (58.49%),  390.8 MB/s , 2012.7 MB/s 
r130
test_dat         :     18092 ->     10408 (57.53%),  500.9 MB/s , 2809.0 MB/s 
test_dat         :     18092 ->     10582 (58.49%),  394.0 MB/s , 2016.3 MB/s 
r131
test_dat         :     18092 ->     10408 (57.53%),  503.9 MB/s , 2836.1 MB/s 
test_dat         :     18092 ->     10582 (58.49%),  384.2 MB/s , 2023.1 MB/s 
``````

That being said, these versions are compiled using upstream lz4 makefile, which uses `-O3`.
The story could be different with @kirillx settings.

**Comment by t-mat** [comment]
> I forgot what exactly is r999

In local environment, `r999` is your local working code.  `r999` doesn't touch any git related things.  It always do:

```
pushd ..   # cd /path/to/lz4/versionsTest  to  /path/to/lz4/
make all
popd
```

But for TravisCI, it means git's `head` == "last commit".
 - If Travis runs with `master` branch, `r999` means `master` branch's last commit.
 - If Travis runs with PR, `r999` means specifc PR's last commit.

**Comment by kirillx** [comment]
Yes, I was building 64bits.
Below are my measurements w/o fstack-protector and any other options. just "gcc -O2 lz4.c".
5 measurements, best one is selected. So you can see that performance of version compiled with -O2 degraded in r118. The good news is that you're absolutely right, using -O3 helps and performance of gcc version returns back to normal.

        CentOS7.1/gcc4.8.3-9    MacOS 10.11.2/clang
r131    1.63                    1.10
r124    1.6                     1.50
r120    1.61                    1.50
r118    1.58                    1.51
r117    1.19                    1.19
r116    1.19                    1.17

Adding inline/force_inline to all small functions helps gcc -O2 to achieve 1.36sec (r131), i.e. still far from ideal. So your theory about inline functions seems correct 50% only.

**Comment by Cyan4973** [comment]
r118 was the introduction of streaming modes, and indeed, it increased code complexity quite dramatically. So it took some time to properly fold it again in a way which restored initial performance.

inlining _small_ functions is only one part of the game.
It can also be necessary to inline a few selected large ones (and certainly not all of them),
as the most important objective is to hardwire, hence remove, a few branches within performance critical code sections.

It can be difficult to spot, and is likely to require a good understanding of the code.

**Comment by kirillx** [comment]
Ok. it's up to you whether to close this issue or not (depending on whether you plan to attack -O2 performance). But I would add a warning in doc somewhere, that -O3 or -Ofast is expected to be used and dramatically affects performance.

**Comment by Cyan4973** [comment]
> I would add a warning in doc somewhere, that -O3 or -Ofast is expected to be used and dramatically affects performance

Fair point.

I plan to work on performance at -O2 settings, but my availability is currently extremely limited, so this will probably have to wait a bit.

**Comment by Cyan4973** [comment]
Latest `dev` version of lz4 provides roughly the same performance at `-O2` and `-O3` on local development stations.
Not sure yet if this conclusion can be extended to multiple different platforms (ARM typically).

**Comment by Cyan4973** [comment]
I made some tests at `-O2` setting, comparing previous speed champion `r117` with newest `dev` version, below called `v1.7.2`, on a Mac laptop. The results are rather favorable : 

| Version |   compiler              | setting | C.Speed  | D.Speed |
| ------- | ------------------ | ------- | --------   | --------- |
|  r117     |  Apple LLVM 8.0.0 |  -O2    | 463 MB/s | 1.2 GB/s |
|  v1.7.2  |  Apple LLVM 8.0.0 |  -O2    | 495 MB/s | 2.4 GB/s |
|  r117     |  Apple LLVM 8.0.0 |  -O3    | 465 MB/s | 1.2 GB/s |
|  v1.7.2  |  Apple LLVM 8.0.0 |  -O3    | 495 MB/s | 2.4 GB/s |
|  r117     |  gcc 6.2.0               |  -O2    | 461 MB/s | 2.1 GB/s |
|  v1.7.2  |  gcc 6.2.0               |  -O2    | 500 MB/s | 2.5 GB/s |
|  r117     |  gcc 6.2.0               |  -O3    | 463 MB/s | 2.1 GB/s |
|  v1.7.2  |  gcc 6.2.0               |  -O3    | 505 MB/s | 2.5 GB/s |

Differences between `-O2` and `-O3` is negligible, and newer version is faster.

On a different desktop PC machine (hence not comparable to above results) : 

| Version |   compiler              | setting | C.Speed  | D.Speed |
| ------- | ------------------ | ------- | --------   | --------- |
|  r117     |  gcc 4.8.5               |  -O2    | 579 MB/s | 2.6 GB/s |
|  v1.7.2  |  gcc 4.8.5               |  -O2    | __592 MB/s__ | __2.4 GB/s__ |
|  r117     |  gcc 4.8.5               |  -O3    | 579 MB/s | 2.6 GB/s |
|  v1.7.2  |  gcc 4.8.5               |  -O3    | __619 MB/s__ | __3.2 GB/s__ |

In this case, speed difference between `-O2` and `-O3` is measurable.
It seems the reason could be attributed to the older compiler version.
So let's try a newer compiler version on same machine : 

| Version |   compiler              | setting | C.Speed  | D.Speed |
| ------- | ------------------ | ------- | --------   | --------- |
|  r117     |  gcc 5.4.1               |  -O2    | 583 MB/s | 2.5 GB/s |
| v1.7.2   |  gcc 5.4.1               |  -O2    | 616 MB/s | 3.2 GB/s |
|  r117     |  gcc 5.4.1               |  -O3    | 583 MB/s | 2.5 GB/s |
| v1.7.2   |  gcc 5.4.1               |  -O3    | 621 MB/s | 3.2 GB/s |

And indeed, with a more recent version, differences between `-O2` and `-O3` disappear.

So it seems the problem of reduced performance at `-O2` setting is specific to gcc 4.x serie.
It also seems that newer `dev` version remains nonetheless competitive compared to `r117` even at `-O2` setting and even on gcc 4.8.x.
