### ISSUE TITLE
support more input files in lz4cat 

### ISSUE THREAD

**Issue by libor-m** [lz4/lz4#184]
As the name suggests, `lz4cat` could/should behave like `cat` - when given multiple files, decompress them one after another and print to stdout. 

It scared a bit me when I noticed that it could have tried to open the second argument for writing (effectively deleting the file). I didn't even think of checking how it should be invoked, when it's called `cat`

**Comment by Cyan4973** [comment]
Good point.

> It scared a bit me when I noticed that it could have tried to open the second argument for writing (effectively deleting the file)

No risk. It will just open the first file, and then complain that it does not know what to do with more than one file.
But it won't erase second file. After all, it received instruction to write the decompressed result into stdout.

**Comment by Cyan4973** [comment]
Latest update in `dev` branch should now correctly decode multiple files provided as `lz4cat` input.
