### ISSUE TITLE
lz4 -h should print library version in addition to cli version

### ISSUE THREAD

**Issue by jzhuge** [lz4/lz4#192]
"lz4 -h" should print the library version by LZ4_versionNumber() because one cli version may work with multiple lib versions, e.g., "r128" works with 1.6.0/1.7.0/1.7.1. Other softwares (e.g. hadoop) only bundle the library code. It will make it easier to perform compatibility check if "lz4 -h" prints the lib version.

Is Linux lz4 package version actually the git tag of this repo?

**Comment by Cyan4973** [comment]
It's a good point @jzhuge .
I'll review your PR.

**Comment by Cyan4973** [comment]
Here is the current behavior in `dev` branch : 
```
./lz4 -h
*** LZ4 command line interface 64-bits v1.7.2, by Yann Collet ***
Usage :
      ./lz4 [arg] [input] [output]
```

Now library, cli and release number are one and the same, and displayed when invoking `lz4 -h` or `-lz4 -V` .
