### ISSUE TITLE
LZ4F_ERROR_srcPtr_wrong error is unecessary

### ISSUE THREAD

**Issue by nrgiii** [lz4/lz4#198]
When decompressing a large file and attempting to efficiently buffer that file, LZ4F_decompress() does not allow the source address to change addresses between calls.  This is inconvenient and, IMHO, unnecessary.  As long as the data contained in the source buffer is the same as it was during the previous call then LZ4F_decompress() should not care unless I'm missing something.

Case in point: I am writing a LZ4_File library to efficiently handle large files.  My code reads a 4 MB chunk of the file into a buffer and calls LZ4F_decompress() on that buffer to decompress chunks of the file where the size of the chunks is specified by the caller of my library.  If I get close to the end of my buffer then I would like to memmove() the remaining data to the front of the buffer and read more data from the file into the remaining space in the buffer.  Currently this does not work due to LZ4F_ERROR_srcPtr_wrong errors.

Instead of checking that the source buffer address has not changed, may I humbly suggest that the decompression context remember the contents of, say, the next 8 bytes in the buffer and raise and error if the contents (not the address) of the buffer has changed.

Norm Green

**Comment by Cyan4973** [comment]
Yes, it's a valid point.
I'll remove this check in a future version.

This was supposed to "help", or rather to force users to not forget re-presenting unconsumed input data.
But yep, it introduces also unwarranted rigidity.

So we can simply remove the check, and count on the users to remember it has to represent unconsumed input data to the decoder, whatever the position in memory.

**Comment by cheese** [comment]
This error is annoying when the frame is read from network, since the total size of the frame is not known a priori.
Adding a decompression option to disable this checking will be just fine.

**Comment by Cyan4973** [comment]
In latest `dev` branch update, the restriction of restarting streaming decompression from where it stopped has been lifted.

Of course, for decompression to work appropriately, it's still necessary to re-present remaining input data.
But now, this data can be anywhere in memory, not _only_ at the place it was present during previous invocation.
