### ISSUE TITLE
LZ4 compression speed degrades when added into VM migration

### ISSUE THREAD

**Issue by TurnUpTheSun** [lz4/lz4#212]
I am doing some work on the virtual machine (VM) migration, which means migrating a VM from one host to another through the network. The bulk of data needed to be transferred during migration is the memory pages of the VM. So i uses LZ4 to compress each page before transferring them, and on the destination host, I decompress them.
To get the compression speed and compression ratio in this situation, first I dumped the memory pages of the VM into a file. Then I used LZ4 to compress the dump file at the granularity of a single page (4K). I computed the compression speed and compression ratio using the code like below (there's no disk I/O, all in memory):
`for(i=0; i<num_of_pages; i++){

```
        gettimeofday(&t1,NULL);
        s = LZ4_compress_fast((const char*)(mem+i*TARGET_PAGE_SIZE), buf, TARGET_PAGE_SIZE, 10000, 1);
        gettimeofday(&t2,NULL);
        t_compress += (t2.tv_sec-t1.tv_sec)*1000000 + (t2.tv_usec-t1.tv_usec);
        cpr_size += s;
    }`
```

The compression speed computed through this way is 247MB/s on my machine.

Here is the confusing but interesting part:
I added the LZ4 compression into the code of VM migration, and used the same method as above to compute the compression speed. However the compression speed I got through the whole process of migration is only about 110MB/s, which is much slower than 247MB/s. I was using the same acceleration value (1) in both experiments.

This really confuses me. Can anybody help me figure out what's happening here? Thx~

For more details, the difference between the experiments of the compression of dump file and compression in migration is that, migration does some other things besides transferring pages (the compression part), while it only does compression in the dump file experiment. However, this should not affect the result of compression speed, because I use gettimeofday() function right before and after the compression function.
The VM was under the same situation (idle without any workloads running) when I generated the dump file as when I migrate it.
The physical machine I am using has Xeon 3220 CPU with 4 cores, and the virtual machine(which has only 1 VCPU) is the only workload on it, so there should be enough CPU resources for the compression.

Thanks for any reply~

**Comment by Cyan4973** [comment]
It looks unlikely to be an LZ4 issue.

VM can be quite capricious, depending on local settings and conditions.
Especially when set with a single virtual cpu, any action the VM might have to do will necessarily borrow VCPU time and impact benchmark figures. For example, it may need more memory, or release it to the host, this will be a non-negligible load on the CPU.

I suspect that if you set your VM with 2 VCPU, such discrepancies will be reduced.
Probably not eliminated, but at least reduced.

**Comment by TurnUpTheSun** [comment]
Thanks for your reply~  @Cyan4973 

1. The migration process and the VCPU of the VM are different threads of the host (I am using KVM/QEMU hypervisor, and it implement each VCPU of the VM as a single thread). They shouldn't affect each other, because the host OS will schedule them to different cores.

2. I have tried using multi VCPUs (from 1 we see this wouldn't reduce the discrepancies ,but i still have tried), and the compression speed is slow as the same.

3. I have run the experiments many times, the compression speed is always slow.

Any other suggestions?

**Comment by Cyan4973** [comment]
There are many potential reasons unfortunately, and most of them are "system related", ie outside of LZ4 scope proper.

Among the most common ones :
- Binaries used : identical ?
- Data being compressed : identical ?
- Memory usage (not just by LZ4, by the whole process) : identical ?

**Comment by TurnUpTheSun** [comment]
Could you give some more details about the third one? How would the memory usage affect the compression speed?

Both experiments of the migration and the dump file use about 1GB out of host's 8GB ram.

**Comment by Cyan4973** [comment]
When the amount of memory required is large, there is a need to "swap out" some things to make room for others. Swapping is a costly operation. Multiple tasks are bound to use more memory than a single one, although by how much is specific to your application.

What matters here is both the host and the client VM declared RAM. When VM is out of RAM, it will swap. The swapping itself might be cached by the host, hence no real "physical" swapping happens, but it's nonetheless a costly transaction between host and client.

That's just one of many possible reasons. No guarantee it's the right one for your use case. It merely sounds a plausible one.

**Comment by TurnUpTheSun** [comment]
It shouldn't be the reason for my case, because the VM is idle and ram is enough for both VM and host.

Anyway, thank you very much for the help.

**Comment by Cyan4973** [comment]
I'm sorry, I suspect we won't be able to help this issue much.
It looks as simple as stating "process A is slower when process B is also running at the same time", which doesn't seem illogical.

Even if when there are multiple CPUs, there is a global shared memory channel, which can be heavily clobbered by multiple things happening in parallel.
My only recommendation would be to limit LZ4 memory budget, so that it mostly fits into local cache, typically by reducing the block size `-B4D`. Data to compress will still come from RAM, but at least the compression process itself should remain in cache.

**Comment by TurnUpTheSun** [comment]
Thank you very mucn for your help.

Chunguang

2016-11-11 3:46 GMT+08:00 Yann Collet <notifications@github.com>:

**Comment by Hermholtz** [comment]
I know the issue is very old, just wanted to add my 2 cents. I think the main problem here was the chosen chunk size - a 4K page. So you invoked LZ4 to compress one 4K page and then decompress it on the other end. I think the overhead of various operations besides compression was dramatically high. I'd suggest choosing much bigger chunk such as 1MB, maybe even much more. It'd be best to benchmark various page sizes and then decide.
