### ISSUE TITLE
Building lz4 dll

### ISSUE THREAD

**Issue by nacho** [lz4/lz4#216]
So, I was wondering if you would accept a patch to get lz4 built as a dll. My idea to achieve this is similar to how we do it in i.e the gtk projects. You would have versioning macros:
https://git.gnome.org/browse/wing/tree/wing/wingversionmacros.h

And then when building with msvc you would define it as:
https://git.gnome.org/browse/wing/tree/nmake/config-msvc.mak#n44
or if using mingw:
https://git.gnome.org/browse/glib/tree/config.h.win32.in#n827

Clearly on lz4 this is much easier, since you would just define it for Windows on the makefile as in the config.h.win32.in or in cmake for msvc of mingw

**Comment by nacho** [comment]
See that the other possibility is to provide the .def file, but this is more painful to keep up to date.

**Comment by t-mat** [comment]
Hi, @nacho

It seems good suggestion.  But since [zstd emploies different method](https://github.com/Cyan4973/zstd/blob/47222eabd375e346719ab4080fba61c274d054a2/lib/common/zstd.h#L45), we may use same one.  Something like this:

```
// Check existence of LZ4LIB_API to allow possibility to make import library easier.
#ifndef LZ4LIB_API
#  if defined(_WIN32) && defined(LZ4_DLL_EXPORT) && (LZ4_DLL_EXPORT==1)
#    define LZ4LIB_API __declspec(dllexport)
#  else
#    define LZ4LIB_API
#  endif
#endif

...

LZ4LIB_API int LZ4_versionNumber (void);
```

@nacho, Is above good enough for your usage?

**Comment by nacho** [comment]
Yeah, I think that might do it was well

**Comment by t-mat** [comment]
Right.  Since above method also has possibility to implement _private_ library more easily, I hope we'll implement such functionality.
I mean "_private_" is similar to xxhash's [`XXH_PRIVATE_API`](https://github.com/Cyan4973/xxHash/blob/86011828f0fc77ad4d83ecfb1df88a91ebc37083/xxhash.h#L82) :

```C
// Add LZ4_PRIVATE_API which basically mimics xxhash's XXH_PRIVATE_API
#ifndef LZ4LIB_API
#  if defined(LZ4_PRIVATE_API)
#    define LZ4LIB_API static inline // >= C99 or C++
#  elif defined(_WIN32) && defined(LZ4_DLL_EXPORT) && (LZ4_DLL_EXPORT==1)
#    define LZ4LIB_API __declspec(dllexport)
#  else
#    define LZ4LIB_API /* Do nothing */
#  endif
#endif
```
Of course, we need more complicated thing for legacy compilers ;)

**Comment by Cyan4973** [comment]
Since @kou introduced #238, I guess that this issue is now answered.
