### ISSUE TITLE
Cut a new release (r131 is >1yr old and 104 commits behind)

### ISSUE THREAD

**Issue by ido** [lz4/lz4#224]
As the title of the issue says, master (currently r131) is over 1 year old and 104 commits behind dev.  Several useful patches have happened since.  @Cyan4973 can you cut a new release of lz4?

**Comment by Cyan4973** [comment]
Hi Ido

I agree this is highly overdue.
However, I'm totally tied right now, with no availability left.

I will target a new LZ4 release in September.

**Comment by ido** [comment]
No worries, September is just 2 weeks away. :smile:

**Comment by lilianmoraru** [comment]
I was planning to open such an issue and then I found this :smile:

**Comment by Cyan4973** [comment]
Next release will be called v1.7.2, thus moving to a versioning scheme

**Comment by Cyan4973** [comment]
LZ4 v1.7.3 has just been [released](https://github.com/lz4/lz4/releases/tag/v1.7.3) today,
featuring 354 commits worth of changes, so the list is quite long.
Most of them are minor improvements and fixes, but they do add up to create an overall better version.
