### ISSUE TITLE
Windows CI (Appveyor?) + Binary releases (Bintray?)

### ISSUE THREAD

**Issue by ido** [lz4/lz4#229]
Hi Yann,
  Do you have plans to add Windows builds/CI and binaries?  You can use Appveyor for Windows CI (it's similar to Travis-CI), and/or Bintray to build RPMs (RHEL/CentOS/Fedora), DEBs (Debian/Ubuntu), NuGet packages (Windows), and other packages (e.g. binary tarballs) pretty conveniently (and free).

**Comment by Cyan4973** [comment]
Currently working on a similar objective on [Zstandard](http://www.zstd.net).

When it's done there, it should prove similar to add it to lz4.

**Comment by Cyan4973** [comment]
We now have an automatic Windows Binary generator for LZ4, based on Appveyor CI.
Its first usage can be seen on [LZ4 v1.7.3](https://github.com/lz4/lz4/releases/tag/v1.7.3).
