### ISSUE TITLE
Parameter -BD can be non-deterministic

### ISSUE THREAD

**Issue by stbrumme** [lz4/lz4#230]
(tested on lz4 r131)
Running `lz4 -9 enwik8 - > /dev/null` always shows, independent of CPU/OS:
`Compressed 100000000 bytes into 42283904 bytes ==> 42.28%`

Adding the `-BD` parameter produces different filesizes:
CentOS6/lz4 (x64) from EPEL repository:

```
Compressed 100000000 bytes into 42210479 bytes ==> 42.21%
Compressed 100000000 bytes into 42210483 bytes ==> 42.21%
Compressed 100000000 bytes into 42210476 bytes ==> 42.21%
```

=> varying

Ubuntu 15.10 (Odroid C1 / ARM cpu / lz4 git HEAD g++ 5.2.1):
`Compressed 100000000 bytes into 42210493 bytes ==> 42.21%` (always same size)

Debian 6.0.10 (Xeon X3323 / lz4 git HEAD g++ 4.4.5):
`Compressed 100000000 bytes into 42210461 bytes ==> 42.21%` (always same size)

**Comment by stbrumme** [comment]
I just noted the same issue can be observed on faster compression levels, too.
`lz4 -3 enwik8 - > /dev/null`
`Compressed 100000000 bytes into 44478515 bytes ==> 44.48%` (CentOS, different size each time I run it)
`Compressed 100000000 bytes into 44478531 bytes ==> 44.48%` (Ubuntu, always same size)
`Compressed 100000000 bytes into 44478508 bytes ==> 44.48%` (Debian, always same size)

**Comment by Cyan4973** [comment]
This looks like an initialization "problem".
I understand it does not affect archive validity, archive can correctly decoded.
It's mostly a matter of having the same predictable result at each run.
I'll look into it.

**Comment by Cyan4973** [comment]
I've used a CentOS dev station to make some tests lately.
And once again, the output of `lz4` is very stable, always the same after multiple attempts.

Maybe it could be related to compiler version ?

**Comment by stbrumme** [comment]
I installed LZ4 from EPEL's RPM repository, version r131-1.el6 (=> CentOS 6).
Default compiler is GCC 4.4 but I don't know which one was used by EPEL when building the RPM.

**Comment by Cyan4973** [comment]
I've been testing this issue multiple times, on several systems and compilers, and haven't been able to reproduce it so far.

The most logical explanation would be the use of some uninitialised data,
which would end up being generally init to `0` on some (most?) systems,
but not on others.

However, I've been testing lz4 `dev` branch with both memory sanitizer and valgrind, which should both report a warning when using uninitialised memory areas. And none has produced any warning. It seems to rule out usage of uninitialised data. But then, I'm short of an explanation (and of a reproduction case).

**Comment by Cyan4973** [comment]
From @inikep : 

> I can confirm issue described here:
> It happens mainly with "-BD" and it's caused by overflow with dictBase (the part of sliding window is not available):
> dictBase=FFFFFFFFF7FC7040

The overflow of `dictBase` is correctly handled by the library, but it seems that this overflow protection results in a very small compression ratio hit (in the range of a few bytes), likely due to missed opportunity (maybe in the part which looks backward ?).

Can be investigated for completeness, though it's a fairly minor side-effect.

**Comment by Cyan4973** [comment]
I can confirm the issue.
Input data must be long enough to trigger it. Even then, some OS are more susceptible than others.
CentOS6 is the "best" one to produce non-deterministic output.

Differences are very small (a few bytes), and can be achieved with any HC level.
Not yet clear what produces them ...

**Comment by Cyan4973** [comment]
OK, got it.
It was a non-trivial bug in the inter-block update rule.
#521 should fix it.
