### ISSUE TITLE
How to create liblz4.dll on windows

### ISSUE THREAD

**Issue by vonHabsi** [lz4/lz4#237]
I want to create a liblz4.dll for a Windows platform and I have tried the methods suggested in #51, but they seem to be out of date. Is there a more up to date method for creating the dll.

**Comment by Cyan4973** [comment]
This is surprising.
I don't think there is anything new today compared to #51.
@t-mat excellent advises should still apply.

**Comment by qazbob** [comment]
Hi, you can check this project on how to create a lz4 DLL 
[https://github.com/qazbob/lz4-dll](https://github.com/qazbob/lz4-dll)

**Comment by vonHabsi** [comment]
The instructions given by @t-mat show how to create the library and the executable but they don't show  how build the DLL. The ming option doesn't seem to work.

I will try out the repo of @qazbob and update you on the result.

**Comment by vonHabsi** [comment]
The instructions given by @t-mat show how to create the library and the executable but they don't show  how build the DLL. The ming option doesn't seem to work.

I will try out the repo of @qazbob and update you on the result.

**Comment by vonHabsi** [comment]
I have tested the repo of @qazbob  https://github.com/qazbob/lz4-dll.
It was a 64bit build but  I have tested it with the application and there were no problems.
I the DLL analyzed with Dependency Walker and it gave an error message
> Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
> Error: Modules with different CPU types were found.

I am not familiar with the internals of Windows DLLs and what Dependency Walker actually does, but it may not be a problem in practice.

Thanks

**Comment by qazbob** [comment]
You can find a better VS solution files here [https://github.com/wingtk/gtk-win32/tree/master/lz4/projects](https://github.com/wingtk/gtk-win32/tree/master/lz4/projects) that were made starting from the previous repo.

**Comment by gbloice** [comment]
I'm working on using the new [vcpkg](https://github.com/Microsoft/vcpkg) tooling to create libraries for Windows, using the CMakeLists.txt in cmake_unnofficial.  Nearly got it all done, but would really like to have a new tag, r132, as r131 is a bit out of date now.

**Comment by Cyan4973** [comment]
@inikep has prepared a new project in [visual/VS2010](https://github.com/lz4/lz4/tree/dev/visual/VS2010),
called `lz4-dll`, which should answer this need
