### ISSUE TITLE
Feature Request: Release package signing

### ISSUE THREAD

**Issue by g4jc** [lz4/lz4#255]
Hello,
There is currently no way to verify the complete integrity of releases. Please consider signing your releases so that package maintainers can verify the sources prior to packaging.

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thank you

**Comment by Cyan4973** [comment]
That's an interesting suggestion.
We'll see what we can do.

My main worry here is that the process described is wholly manual. That may look fine for a single release, and as long as someone else spend the time necessary to do it, but overtime it always becomes an issue to burden the release process with additional manual steps.

So, automating it looks safer on the longer term.
But automation itself looks like a significant effort...

**Comment by Tsutsukakushi** [comment]
Even if it took half an hour per release it would be worth it because lz4 is so quite widely used and compromising could mean millions of infected devices.

Fortunately for you it's only a single command.

**Comment by g4jc** [comment]
As lz4 is a critical package in [core] on many distros, at bare minimum there should be hashes listed on the release page, and preferably signed. Failing to do so puts many users at risk of MITM and possible malware infection.

**Comment by Cyan4973** [comment]
I'll need some time to build the experience necessary to do this.

**Comment by g4jc** [comment]
You may have a look at this project, as it helps automate it. https://github.com/nicohood/gpgit
