### ISSUE TITLE
variable size output file

### ISSUE THREAD

**Issue by inikep** [lz4/lz4#256]
I can confirm issue described here:
http://encode.ru/threads/2593-smallz4?p=49893&viewfull=1#post49893

It happens mainly with "-BD" and it's caused by overflow with dictBase (the part of sliding window is not available):
dictBase=FFFFFFFFF7FC7040
dictBase=FFFFFFFFF7BC7040
dictBase=FFFFFFFFF77C7040

**Comment by Cyan4973** [comment]
Duplicate of #230 .

Could you describe a test / method which can put the issue into evidence ?
So far, I failed to reproduce it.
