### ISSUE TITLE
How to determite the header size of the lz4 file?(is this document out of date?)

### ISSUE THREAD

**Issue by imgtec** [lz4/lz4#276]
Hi, I am writing a decode for lz4 file on arm, I want to optimize the speed of
decoding and next step is to use dma to help the data coping.
my small decoder:
   https://github.com/imgtec/lz4-embedded
but i uncounted problems about the header. 
General Structure of LZ4 Frame format
---
MagicNb	F. Descriptor	Block	(...)	EndMark	C. Checksum
4 bytes	3-11 bytes			4 bytes	0-4 bytes
---
Hi, this is copy from this document
https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md
according to this document, the size of header should be 7 or 15,
but I use the hexdump to check the header, I can see the header
original file
---8<-----
00000000  7f 45 4c 46 01 01 01 00  00 00 00 00 00 00 00 00  |.ELF............|
00000010  02 00 28 00 01 00 00 00  f1 80 00 00 d4 04 10 00  |..(.............|
00000020  f4 04 10 00 02 00 00 05  34 00 20 00 01 00 28 00  |........4. ...(.|
00000030  13 00 12 00 18 f0 9f e5  18 f0 9f e5 18 f0 9f e5  |................|
00000040  18 f0 9f e5 18 f0 9f e5  18 f0 9f e5 18 f0 9f e5  |................|
00000050  18 f0 9f e5 f1 80 00 00  14 2b 07 00 c4 2b 07 00  |.........+...+..|
00000060  3c 2c 07 00 4c 2c 07 00  4c 2c 07 00 44 80 00 00  |<,..L,..L,..D...|
00000070  80 2c 07 00 b4 2c 07 00  04 e0 4e e2 08 50 2d e9  |.,...,....N..P-.|
00000080  07 00 2d e9 8c 00 9f e5  50 20 90 e5 3f 00 52 e3  |..-.....P ..?.R.|
00000090  16 00 00 9a 54 10 90 e5  02 00 51 e1 0c 00 00 1a  |....T.....Q.....|
000000a0  00 10 90 e5 70 20 9f e5  02 10 11 e0 00 20 a0 13  |....p ....... ..|
---8<----
compressed file
------
00000000  04 22 4d 18 64 70 b9 da  82 07 00 84 7f 45 4c 46  |."M.dp.......ELF|
00000010  01 01 01 00 01 00 40 02  00 28 00 0e 00 ff 11 f1  |......@..(......|
00000020  80 00 00 d4 04 10 00 f4  04 10 00 02 00 00 05 34  |...............4|
00000030  00 20 00 01 00 28 00 13  00 12 00 18 f0 9f e5 04  |. ...(..........|
00000040  00 09 00 3c 00 d3 14 2b  07 00 c4 2b 07 00 3c 2c  |...<...+...+..<,|
00000050  07 00 4c 04 00 f0 41 44  80 00 00 80 2c 07 00 b4  |..L...AD....,...|
00000060  2c 07 00 04 e0 4e e2 08  50 2d e9 07 00 2d e9 8c  |,....N..P-...-..|
00000070  00 9f e5 50 20 90 e5 3f  00 52 e3 16 00 00 9a 54  |...P ..?.R.....T|
00000080  10 90 e5 02 00 51 e1 0c  00 00 1a 00 10 90 e5 70  |.....Q.........p|
00000090  20 9f e5 02 10 11 e0 00  20 a0 13 0b 00 00 1a 20  | ....... ...... |
000000a0  10 90 e5 00 20 e0 e3 14  00 f0 05 20 20 a0 13 06  |.... ......  ...|
------
the size of header is 16byte.
for a workaround I just check the C.Szie bit and skipy 12 bytes, and my
decoder can work.
could you tell me how to decode the header? thanks!

**Comment by mwgamera** [comment]
You are correct, the frame header should have 7 or 15 bytes. In your example it has 7. It is then followed by a number of [blocks](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md#data-blocks), each starting with a 4-byte length field.
So what are you looking at in your hexdump goes like this:
```
04 22 4d 18     magic number
64 70 b9        3-byte frame descriptor
da 82 07 00     block length (492250 bytes here)
84 7f 45 4c 46  LZ4-compressed data (ie. tag byte 0x84 followed by
...               the literal "\x7fELF\1\1\1\0" and so on)
```
If there is no content size in frame header, then content of the first block will indeed start at offset 12. But one file might consist of more than one block and not all blocks have to be compressed.
Perhaps documentation could be a bit more clear about what a _block_ means—LZ4 Frame Format Description says that frame contains blocks and these blocks are described later in the same document, while LZ4 Block Format Description, despite the name, describes only the payload of these blocks, not the format of a whole block itself.

**Comment by imgtec** [comment]
finally~~~Hello:
this piece of code below works for my the version of lz4 on my host
- - -
void *lz4cpy(void *dst, const void *src, int n)
{
	const char *p;
	int error;

	p = src;

	if((p[0] != '\x04')
		|| (p[1] != '\x22')
		|| (p[2] != '\x4D')
		|| (p[3] != '\x18'))
		return memcpy(dst, src, n);
	p += 4;

	if(*p & '\x8') p += 8;
	else p += 3;

	//src = (char *)src + 7;
	//src = (char *)src + 15;
	src = (char *)src + 11;
	//src = (void *)p;

	error = __lz4cpy(dst, src, n);
	if(error>0) return dst;
	else return NULL;
}
- - -
my lz4 version is 
- - -
du@book:~/worksp/aa/lz4-embedded$ lz4 -V
*** LZ4 command line interface 64-bits r128, by Yann Collet (Apr 18 2016) ***
- - -
my deocder seems partly works, but I still don't understand the document.. 8-|
the size of header for my .lz4 file header is 11 byte?

**Comment by imgtec** [comment]
test.bin
- - - -
	"\x09\x09\x09\x20\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d"
	"\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d"
	"\x0a\x09\x09\x09\x20\x4c\x49\x4e\x55\x58\x20\x4b\x45\x52\x4e\x45"
	"\x4c\x20\x4d\x45\x4d\x4f\x52\x59\x20\x42\x41\x52\x52\x49\x45\x52"
	"\x53\x0a\x09\x09\x09\x20\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d"
	"\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d"
	"\x3d\x3d\x0a\x0a\x42\x79\x3a\x20\x44\x61\x76\x69\x64\x20\x48\x6f"
	"\x77\x65\x6c\x6c\x73\x20\x3c\x64\x68\x6f\x77\x65\x6c\x6c\x73\x40"
	"\x72\x65\x64\x68\x61\x74\x2e\x63\x6f\x6d\x3e\x0a\x20\x20\x20\x20"
	"\x50\x61\x75\x6c\x20\x45\x2e\x20\x4d\x63\x4b\x65\x6e\x6e\x65\x79"
- - - -
test.lz4
- - - -
	"\x04\x22\x4d\x18\x64\x50\x08\xe8\x91\x00\x00\x5f\x09\x09\x09\x20"
	"\x3d\x01\x00\x08\x10\x0a\x21\x00\xff\x0e\x4c\x49\x4e\x55\x58\x20"
	"\x4b\x45\x52\x4e\x45\x4c\x20\x4d\x45\x4d\x4f\x52\x59\x20\x42\x41"
	"\x52\x52\x49\x45\x52\x53\x0a\x42\x00\x0e\xf2\x07\x0a\x42\x79\x3a"
	"\x20\x44\x61\x76\x69\x64\x20\x48\x6f\x77\x65\x6c\x6c\x73\x20\x3c"
	"\x64\x68\x0a\x00\xf2\x2a\x40\x72\x65\x64\x68\x61\x74\x2e\x63\x6f"
	"\x6d\x3e\x0a\x20\x20\x20\x20\x50\x61\x75\x6c\x20\x45\x2e\x20\x4d"
	"\x63\x4b\x65\x6e\x6e\x65\x79\x20\x3c\x70\x61\x75\x6c\x6d\x63\x6b"
	"\x40\x6c\x69\x6e\x75\x78\x2e\x76\x6e\x65\x74\x2e\x69\x62\x6d\x32"
- - - -

**Comment by t-mat** [comment]
> How to determite the header size of the lz4 file?

Please read the document and source code carefully.  Since there are [many implementations](http://lz4.github.io/lz4/#interoperable-lz4) which is based on the document and source code of LZ4, you also be able to implement it.

First of all, technically there is tricky part of the specification: Skippable Frames.  But it seems you are new to LZ4 frame format, you can ignore it so far.  You can revisit this part after you'll implement other parts.  So please forget about Skippable frames.

If we can ignore skippable frame, first 6 bytes of the LZ4 frame format header always has same structure:

```
offset	data
+0	0x04
+1	0x22
+2	0x4d
+3	0x18
+4	FLG of the Frame Descriptor
+5	BD of the Frame Descriptor
```

And if bit 3 of FLG (`1<<3 = 0x08`, Content Size flag) is `0`, header and the first block structure is

```
offset	data
+6	HC of the Frame Descriptor

+7	bit [0,7] of the first block size
+8	bit [8,15] of the first block size
+9	bit [16,23] of the first block size
+10	bit [24,31] of the first block size
+11...	data of the first block (compressed or uncompressed LZ4 raw block)...
```

And if bit 3 of FLG is `1` :

```
offset	data
+6	bit [0,7] of the Content Size
+7	bit [8,15] of the Content Size
+8	bit [16,23] of the Content Size
+9	bit [24,31] of the Content Size
+10	bit [32,39] of the Content Size
+11	bit [40,47] of the Content Size
+12	bit [48,55] of the Content Size
+13	bit [56,63] of the Content Size
+14	HC of the Frame Descriptor

+15	bit [0,7] of the first block size
+16	bit [8,15] of the first block size
+17	bit [16,23] of the first block size
+18	bit [24,31] of the first block size
+19...	data of the first block (compressed or uncompressed LZ4 raw block)...
```


> (is this document out of date?)

No, it's updated and correct.

**Comment by imgtec** [comment]
thanks you very much. 
the first block is:
offset data
[7-10] block size
[11....] block data

MagicNb	F. Descriptor	Block **size**	(...)	EndMark	C. Checksum
4 bytes	3-11 bytes	4 bytes	0-4 bytes

How about add a word 'size' like above? :)

**Comment by imgtec** [comment]
```
- - - - - - -
 	[0-3]		04 22 4D 18
	[1]		FLG
	[1]		BD
	[1]		HC of the Frame Descriptor
	[3 or 11]	Content
- - - - - - -
	[4]		first block size
	[...]		data of the first block(s)
- - - - - - -
	[4]		block size
	[..]		block 
- - - - - - -
	...		more blocks
- - - - - - -
	[4]		EndMark
	[0 or 4]	C. Checksum
- - - - - - -
	EOF
- - - - - - -
```

**Comment by Cyan4973** [comment]
We can certainly improve the wording if it helps clarify

**Comment by imgtec** [comment]
:)
I think your description in this document is clear. But for some guy like me, without a dictionary I can't read English. :D
So a picture or a table is better than many words.
How do you think?
Now my program can decode the first block correctly.

**Comment by jonathanunderwood** [comment]
The thing that would really help people coding against the frame API is to expose the maximum header and footer sizes via macros.

**Comment by Cyan4973** [comment]
That's certainly not difficult to do @jonathanunderwood

**Comment by imgtec** [comment]
thank you all. I am going to close this issues.
