### ISSUE TITLE
Support mozlz4 files

### ISSUE THREAD

**Issue by svnpenn** [lz4/lz4#282]
mozlz4 are not currently supported:

~~~
$ lz4 -d search.json.mozlz4 search.json
Error 44 : Unrecognized header : file cannot be decoded
~~~

The following project does support them:

http://github.com/avih/dejsonlz4

**Comment by svnpenn** [comment]
Example file:

http://github.com/lz4/lz4/files/629232/search.json.zip

**Comment by Cyan4973** [comment]
Indeed, `mozlz4` files are non-standard files, using their own custom frame encapsulation.
Their is no plan to support the special case within `lz4`,
but I can link the `dejsonlz4` project from [lz4 homepage](http://lz4.org/), in the category non-standard formats.

**Comment by Cyan4973** [comment]
[dejsonlz4 ](https://github.com/avih/dejsonlz4) project added to[ lz4 homepage](http://www.lz4.org) .
