### ISSUE TITLE
[liblz4] LZ4_versionString() is never implemented

### ISSUE THREAD

**Issue by tannerhelland** [lz4/lz4#283]
LZ4_versionString() exists in lz4.h and also in the documentation (lz4_manual.html).

However it is never implemented in lz4.c.

I'm not sure if this is intentional (given the redundancy with LZ4_versionNumber()) but perhaps the function should be implemented, or lz4.h and the documentation revised to clarify that only LZ4_versionNumber() should be used.

**Comment by Cyan4973** [comment]
Indeed @tannerhelland, this one slipped through, impressively.
Note that all this function do is return `LZ4_VERSION_STRING `.
As all user functions are calling the macro directly, the missing implementation wasn't noticed.
We are apparently missing a unit test case to check it.
To be fixed ...
