### ISSUE TITLE
lz4cat does not work

### ISSUE THREAD

**Issue by beiDei8z** [lz4/lz4#285]
lz4cat does not work.  I removed the "multiple_inputs=1" option and then it does work, I don't understand it, I just copied the logic from a previous working version, r131.

 ```
--- ../original/programs/lz4cli.c	2016-11-22 20:34:17.000000000 +0000
+++ programs/lz4cli.c	2016-12-07 16:36:35.892711640 +0000


@@ -314,7 +320,7 @@
         forceStdout=1;
         output_filename=stdoutmark;
         displayLevel=1;
-        multiple_inputs=1;
+     // multiple_inputs=1;
     }
     if (!strcmp(exeName, UNLZ4)) { mode = om_decompress; }
```

**Comment by Cyan4973** [comment]
What do you mean by "lz4cat does not work" ?
Is that related to #284 ?

I tested `lz4cat` under various scenarios, and it seems to be working fine so far.
`multiple_inputs=1;` is required when trying to cat multiple files in a single command line.

**Comment by beiDei8z** [comment]
This is related to the path problem only in that I used a path to distinguish the various test versions.  The name has to be lz4cat so differing paths are used.

Examples. Anything other that 720 bytes at the end of the pipe is failure.  One can inspect the output to determine success but here I'm only looking for failure, eg, append gm5sum instead of wc but 720 is easier to read than ebfa35beb4dd7e825ba60988352d7a59.
```
$ od -vc /dev/zero | head | wc -c
     720
```

Test lz4 showing success of patched 1.7.4.2 and non patched r131:
```
$ od -vc /dev/zero | head | lz4 | test/patched/lz4cat | wc -c
     720
$ od -vc /dev/zero | head | lz4 | test/r131/lz4cat | wc -c
     720
```
Failure of standard lz4 1.7.4.2:
```
$ od -vc /dev/zero | head | lz4 | test/default/lz4cat | wc -c
       0
```
Test showing failed behaviour with -m flag:
```
$ od -vc /dev/zero | head | lz4 | test/patched/lz4cat -m | wc -c
       0
$ od -vc /dev/zero | head | lz4 | test/r131/lz4cat -m | wc -c
       0
```
Tests showing how everyone else I can find does it:
```
$ od -vc /dev/zero | head | cat | cat | wc -c
     720
$ od -vc /dev/zero | head | compress | zcat | wc -c
     720
$ od -vc /dev/zero | head | gzip | gzcat | wc -c
     720
$ od -vc /dev/zero | head | bzip2 | bzcat | wc -c
     720
$ od -vc /dev/zero | head | pbzip2 | pbzcat | wc -c
     720
$ od -vc /dev/zero | head | lzma | lzcat | wc -c
     720
$ od -vc /dev/zero | head | xz | xzcat | wc -c
     720
```
cat(1) takes no output file on the command line, the -m flag of lz4 is not following cat nor other cat-like decompressers including lz4cat r131. The option -m however useful is not creating a cat-like lz4 for use as lz4cat.

**Comment by Cyan4973** [comment]
indeed, `-m` seems incompatible with `stdin` input.
To be fixed

**Comment by Cyan4973** [comment]
Fixed reported issue in `dev` branch and added relevant test case in test suite.
Thanks @beiDei8z !
