### ISSUE TITLE
"lz4cat -d -" does not print the decompressed value to stdout

### ISSUE THREAD

**Issue by ignatenkobrain** [lz4/lz4#288]
Description of problem:
It seems that "lz4cat -d -" does nothing.

Version-Release number of selected component (if applicable):
lz4-1.7.3-1.fc26.x86_64

How reproducible:
Always

Steps to Reproduce:
1. echo "abcdef" | lz4 -z - foo.lz4
2. cat foo.lz4 | lz4cat -d -

Actual results:
<no output>

Expected results:
abcdef

**Comment by Cyan4973** [comment]
This issue is fixed in current `dev` branch.
See #285
