### ISSUE TITLE
different results on compress. decompress work fine.

### ISSUE THREAD

**Issue by rockygsm** [lz4/lz4#289]
Hello
Attached sample files at here. https://mega.nz/#!k4xyQDjY!5RGoPKXS9T47LNXUZ4jPeqxvY2o0EFhs3pPULCCsXhY
original pack size 0x00010AB2
original unpack size 0x00072DDC
repack with current source 0x00010A1B
i have test with LZ4_compress_fast(datain,dataout,fsize,outsize,7) and LZ4_compress
try out all acceleration -1 to 7 result never match.

Any help or idea possible on this ?

**Comment by terrelln** [comment]
The exact output of the compression is expected to potentially change between versions.  Changes to the compression algorithm can change the output (and hopefully make it smaller).  It looks like your file gets compressed slightly better now than before.

The new output can still be decompressed by the old version, and the old output can still be decompressed by the new version.

**Comment by rockygsm** [comment]
Its possible to find version used or acceleration or block size in my samples? is there any header format saved for version type ?
how ever compressed with latest version not working on arm sample which i am working. i can't  change source target i must match to same results any hint ?

**Comment by terrelln** [comment]
The output of `LZ4_compress_fast()` contains no version information, it is just a raw block, as described [here](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md).  If you want version information you need to use `LZ4F_compressFrame()` or equivalent functions.  The frame format is described [here](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md).

Why do you need the compressed data to be byte by byte the same as the previous version?

**Comment by rockygsm** [comment]
compressed len is hardcoded in target 0x00010AB2 if result is not same size its show output invalid.
if i use --no-frame-crc its compressed data size is 0x10A1B near to my sample but not exact. 
i don't think its frame base compression but i will try LZ4F and report back.

**Comment by rockygsm** [comment]
i tested with 64kb block results is very near. its possible some how to use 128kb block size ? without editing codes ?

**Comment by Cyan4973** [comment]
New version compress slightly better than older one, while preserving full format compatibility.
I struggle to understand why it would be a problem, and therefore why to keep this issue opened.
