### ISSUE TITLE
Compression speed drop-off compared to r131

### ISSUE THREAD

**Issue by vtermanis** [lz4/lz4#291]
Whilst testing lz4 dev (v1.7.4+, i.e. 70526a1) against py-lz4framed, I noticed a [performance drop off](https://gist.github.com/vtermanis/ddb42d56dcc8110623938ff4a643e09f). For levels above 11, compression takes more than 40x longer to complete in this particular test case. Notes:

- The input data is `abcdefghijklmnopqrstuvwxyz0123456789` repeated 100k times
- The call to lz4 happens [here](https://github.com/Iotic-Labs/py-lz4framed/blob/5190461b8248dadb7d9040cf60b6a4d229a15e08/lz4framed/py-lz4framed.c#L271) (i.e. to `LZ4F_compressFrame`) and from my testing this is where the drop-off occurs (i.e. not in Python wrapper)
- Note also that at compression level 11 speed is comparable to compression levels below 3 or so. (Maybe a red herring?)
- Compile options, gcc, host & Python versions are the same (I've added some details to the gist linked above.)
- Only one change to py-lz4framed (r131 VS lz4 dev) has been made (using a new constant) other than updated lz4 source ([see here](https://github.com/Iotic-Labs/py-lz4framed/commit/5190461b8248dadb7d9040cf60b6a4d229a15e08#diff-9f36d381d1a0203e3840dd665fdd2a39))

**Comment by Cyan4973** [comment]
You're right @vtermanis .
We have not yet spent time talking about it,
but there is indeed a new high compression mode,
which uses levels 11 and 12.

Its performance characteristics are indeed very different from older modes.
Summarily, it's slower and compress more than regular "HC" mode.

That being said, the synthetic sample used in your test is very special,
so it results in a fairly different experience.
Don't expect it to be representative though.

To know more about these new modes, and maybe improve on your specific sample,
I'll ping @inikep , which is the author of this module.

**Comment by inikep** [comment]
Levels 1-9 were not changed.
Level 10 is former level 16.
Levels 11-12 use optimal parsing.

**Comment by vtermanis** [comment]
Thank you @Cyan4973 & @inikep. That makes sense now. I shall update my unit tests to test up to level 11 (instead of 16) or maybe shorten my test input.

Please feel free to close this issue.

**Comment by vtermanis** [comment]
Ah, sorry, one last question: I've currently got [this](https://github.com/Iotic-Labs/py-lz4framed/blob/master/lz4framed/py-lz4framed.c#L544) as a comment for compression level:
```
level (int): Compression level. Values lower than 3 use fast compression. Recommended
             range for hc compression is between 4 and 9, with a maximum of 16.
```

Is that still a fair thing to say? (I might add a comment along the lines of "_for more details see lz4 library_".)

**Comment by inikep** [comment]
The last compression level is LZ4HC_MAX_CLEVEL currently defined in `lz4hc.h` as:
```
#define LZ4HC_MAX_CLEVEL        12
```

**Comment by vtermanis** [comment]
Thank you! I've [updated](https://github.com/Iotic-Labs/py-lz4framed/commit/85eb51033286bf3bfcce17c40f9dfb80d86be507) my documentation. (I assume it's ok to include `lz4hc.h` when linking statically.)
