### ISSUE TITLE
examples do not compile on Windows

### ISSUE THREAD

**Issue by nrgiii** [lz4/lz4#298]
With LZ4 1.7.4.2 and using  Visual Studio 2010, some of the examples do not compile using the C compiler because there are variables declared after the first statement, which is a no-no in traditional C.  C++ might work but I haven't tried it.  Someone should either fix these or require everything be built with C++.  I don't think there is a way to tell Visual Studio to accept such declarations in C.  

Here is one example. There may be others:

blockStreaming_doubleBuffer.c(94) : error C2143: syntax error : missing ';' before 'type'
blockStreaming_doubleBuffer.c(95) : error C2065: 'readCount1' : undeclared identifier
blockStreaming_doubleBuffer.c(190) : error C2143: syntax error : missing ';' before 'const'
blockStreaming_doubleBuffer.c(191) : error C2065: 'cmp' : undeclared identifier

    88         {
     89             const size_t readCount0 = read_int(inpFp, &cmpBytes);
     90             if(readCount0 != 1 || cmpBytes <= 0) {
     91                 break;
     92             }
     93
     94             const size_t readCount1 = read_bin(inpFp, cmpBuf, (size_t) cmpBytes);
     95             if(readCount1 != (size_t) cmpBytes) {
     96                 break;
     97             }
     98         }

**Comment by nrgiii** [comment]
blockStreaming_ringBuffer.c also has the same problem.  All other files compile clean on Windows.

**Comment by Cyan4973** [comment]
Examples require a C99 level compiler.

A number of Visual Studio versions do not achieve this requirement.
If I do remember correctly, they are all versions <= 2012.
Starting with version >= 2013, Visual Studio is now compatible with C99, and thus compatible with these examples.

We don't target the same level of "portability" for examples and for library.
The library source code makes the effort to be compatible with a wide number of systems, including not-yet-C99 compilers.
Examples do not even try.

We could change this policy if it matters.
Does it ?
