### ISSUE TITLE
diff -q is not portable

### ISSUE THREAD

**Issue by nrgiii** [lz4/lz4#299]
LZ4 1.7.4.2

In tests/Makefile, diff -q is called to compare files, however the -q option is not recognized by diff on some platforms (Solaris for example).

In general, it would be probably be faster and better to use the cmp command to compare files instead of diff, since the tests really want to stop at the first difference found and don't care about listing the exact differences found.

**Comment by Cyan4973** [comment]
That's a good point @nrgiii . To be improved.

**Comment by inikep** [comment]
LZ4 1.7.5 uses `gdiff` instead of `diff` for Solaris. `cmp` should also be fine.
