### ISSUE TITLE
tests/Makefile fails on Windows

### ISSUE THREAD

**Issue by nrgiii** [lz4/lz4#300]
This Makefile references .o files which are .obj files on Windows.  We need an abstraction for the object file extension similar to what we have now with $(EXE).

**Comment by Cyan4973** [comment]
cc @inikep , which has better understanding of this topic.

Note that we run Windows tests, as part of our CI suite.
The tests ensure that source code and `Makefile` correctly run on Windows
using Visual Studio, mingw and clang compilers.

Tests run fine so far, using `*.o` : see for example : https://ci.appveyor.com/project/YannCollet/lz4-1lndh/build/1.0.103/job/h27coc0rrs8cbxxr#L30
which means it's unclear in which case `*.obj` are useful or mandatory.

**Comment by inikep** [comment]
@nrgiii What kind of compiler do you use?

All lz4 Makefiles work on Windows only with MSYS2 and (gcc/MinGW or clang/MinGW).
@Cyan4973 Maybe we should include a comment in Makefiles that `This Makefile is validated for Linux, macOS, *BSD, Hurd, Solaris, MSYS2 targets`.

If you want to compile lz4 with Visual Studio there is a VS 2010+ solution in the `visual\VS2010` directory.

There is also a DJGPP Makefile in `contrib\djgpp`.

**Comment by Cyan4973** [comment]
That's a good suggestion @inikep
