### ISSUE TITLE
Need LZ4F_resetDecompressionContext() function

### ISSUE THREAD

**Issue by nrgiii** [lz4/lz4#302]
It would be useful to have a way to reset / reinitialize a decompression context.  Currently the only way to do it that I can see is to free it and create it again.   This is useful when decompressing files in a stream.

**Comment by Cyan4973** [comment]
[Doc says](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.h#L327) : 
> After a frame is fully decoded, dctx can be used again to decompress another frame

It means that, as long as the decoding process is correctly completed, you can immediately re-use the decompression context, without any need to reset it. It works well for a correctly formed stream.

However, it doesn't cover situations where current decoding is incomplete, or when there is a decoding error. In which case, it's indeed necessary to free the decoding context, and create a new one.

**Comment by Cyan4973** [comment]
In current `dev` branch, there is a new function [`LZ4F_resetDecompressionContext()`](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.h#L373) , which is indeed useful to reset a context after an error or in the middle of an ongoing decompression.

It's planned to be integrated into next release.
