### ISSUE TITLE
LZ4 library compatibility

### ISSUE THREAD

**Issue by m-maillot** [lz4/lz4#303]
Hello,

I want to compress my data with LZ4 from a Java project to/from Objective-C project. I try with library https://github.com/jpountz/ for Java and default implementation (https://developer.apple.com/reference/compression/1665429-data_compression?language=objc) for Objective-C.

I failed to compress from one and decompress from other. The header is different for each platform, do you know why ? Java will prefix with LZ4Block/ and ObjC with 0x62, 0x76, 0x34, and 0x31. It's very confused for me... I try with PHP but is the same with anoter header and I can't decompress from Java or ObjC also.

**Comment by Cyan4973** [comment]
Only versions labeled _interoperable_ can work with each other : 
http://lz4.github.io/lz4/#interoperable-lz4

Other versions use their own custom format, 
they do not guarantee to be compatible with any other version.

There is currently no known interoperable Java version.

**Comment by m-maillot** [comment]
Yes, it was pretty clear, i missed. Thank you!
