### ISSUE TITLE
lz4 very slow

### ISSUE THREAD

**Issue by ballsystemlord** [lz4/lz4#305]
Hello,
I'm running Gentoo linux 4.8.x. All programs are compiled with -O2 -msse -mETC. I'm using lz4 1.7.5.
I got the planet map osm data and needed to keep it in sync. This means decompressing 60GB bzip2 to 706GB and then recompressing it. I thought that this would be interesting to benchmark and then write it to the lwn or linux journal but your compressor is not getting anywhere near the 34MBs that is claimed.
My command looks like this:
bzip2 -kcd planet*.osm.bz2 | pv -WCcarbB 1G | lz4 -9c - | pv -Wcarb > /dev/null
I'm getting a speed of ~6MBs. Even without the -9 I still only get a rate of 8MBs.
bzip2 can decompress at a rate of 20MBs minimum 30MBs maximum.
Thoughts?

**Comment by terrelln** [comment]
Is the first or second `pv` command giving 8 MB/s?

**Comment by ballsystemlord** [comment]
Ah, my mistake. Sorry, the terminal got mixed up which pv line went first and I did not think to reverse them (mentally). Sorry to trouble you.
