### ISSUE TITLE
Unclear whether Lz4 CLI Supports Block Compression

### ISSUE THREAD

**Issue by ilganeli** [lz4/lz4#310]
Hello, I'm working on resolving an issue with LZ4 usage on Hadoop. The specific problem being that Hadoop uses the block compression specification, and not the frame specification. https://issues.apache.org/jira/browse/HADOOP-12990

 Because that data that we've ingested into Hadoop is compressed using the Lz4 CLI, it uses the frame specification, and as such is not usable in this environment. 

Is it possible to compress purely in the block compression form when using the Lz4 CLI or is its use exclusively restricted to the frame specification. Please let me know, thank you!

**Comment by Cyan4973** [comment]
Currently, the CLI is only able to generate frames.

Note that "blocks" require additional metadata for decompression, namely compressed and (upper bound of) original sizes. Not a problem when the block is part of a larger protocol which hosts those metadata, but definitely a problem if saving the block "as is", without metadata, into its own file. The compressed size could be retrieved, but the (upper bound of) original size can not.
