### ISSUE TITLE
Reusable resources?

### ISSUE THREAD

**Issue by KyleJHarper** [lz4/lz4#311]
Hey Yann, et al.,

When we were adding -m support for the LZ4 CLI program (for compressing multiple files in a single call), I noticed that it uses "cRess_t" and "dRess_t" structs, which you added to re-use resources when compressing multiple files.

I have a personal project I'm working on that uses lz4.c/.h and I rapidly compress and decompress buffers (chunks of data in memory).  Is there a similar technique that I can apply to reduce startup costs for LZ4_compress_default() and LZ4_decompress_safe()?  The functions seems streamlined/inlined but I figured I'd ask.  Any small boost in performance is a bonus.

Thanks,
Kyle

**Comment by Cyan4973** [comment]
`LZ4_decompress_safe()` is already very streamlined.
I don't expect any gain trying to do something differently. By compressing buffers to buffers, you already are in the optimal scenario.

`LZ4_compress_default()` is also pretty well streamlined.
The only thing which could be equivalent to `cRess_t` would be to use the `LZ4_compress_fast_extState()` variant, so that resources are allocated once and remain in the same place in memory (it will be necessary to properly preserve `state` accross successive compressions then).
But even then, I expect gains to be minimal, because default settings make `LZ4_compress_default()` use stack memory instead, which is almost zero cost to allocate and free.

`cRess_t` and `dRess_t` are more useful in a CLI program as they use the streaming variant `LZ4F_compress()`, which needs a lot more memory. Here, preserving resources between successive calls is more important.

**Comment by KyleJHarper** [comment]
Thanks for the feedback.  I'll run a few tests to see if using extState offers any advantage in this optimal (buffer to buffer) scenario and report back.

**Comment by KyleJHarper** [comment]
Hey Yann,

Short Version
====
You're correct, in a practical application, using the extState function didn't provide any performance gain or loss.  Synthetic tests that push the limits of lz4 more directly might show slightly wider differences, but my tests seem pretty conclusive.


Longer Version
====
My program, tyche, reads 8kb files off the disk.  These are pages from a postgresql database extracted using the linux 'dd' tool, aligned to represent the real internal structure of a PG data or index page.  To remove IO bottlenecks I put the data set into a tmpfs (ram drive).  The sample data is ~900 MB consisting of ~113,000 pages.
To stress the compression aspect of the program, I gave it a small memory pool of 50MB and restricted the compressed space to 5%.  I ran each version of the program 3 times for 5 minutes.  Essentially what happens is: the program tries to read random pages from disk and store them in the raw space, and when that runs out it compresses the buffer and stores it in the compressed space.  When no more compressed space exists, we victimize compressed buffers.  The small amount of RAM compared to the data size results in a nearly non-stop pattern of reading files in and compressing them, then evicting them.

Below are the results.

**lz4_compress_default**
```
Buffer Acquisitions : 34,292,432 (114,272 per sec).  1,904,890 hits.  32,387,542 misses.
Compressions        : 32,381,867 compressions (107,906 per sec)
Time sweeping       : 114,015 sweeps (34,443,530,041 ns)

Buffer Acquisitions : 34,538,568 (115,183 per sec).  1,918,074 hits.  32,620,494 misses.
Compressions        : 32,614,815 compressions (108,768 per sec)
Time sweeping       : 114,835 sweeps (34,501,446,428 ns)

Buffer Acquisitions : 34,384,138 (114,668 per sec).  1,909,677 hits.  32,474,461 misses.
Compressions        : 32,468,811 compressions (108,281 per sec)
Time sweeping       : 114,321 sweeps (33,952,554,724 ns)
```

**lz4_compress_fast_extState**
```
Buffer Acquisitions : 34,062,224 (113,496 per sec).  1,890,094 hits.  32,172,130 misses.
Compressions        : 32,166,443 compressions (107,180 per sec)
Time sweeping       : 113,257 sweeps (34,902,014,973 ns)

Buffer Acquisitions : 34,521,526 (115,124 per sec).  1,919,159 hits.  32,602,367 misses.
Compressions        : 32,596,671 compressions (108,705 per sec)
Time sweeping       : 114,772 sweeps (34,156,769,390 ns)

Buffer Acquisitions : 34,520,776 (115,120 per sec).  1,916,942 hits.  32,603,834 misses.
Compressions        : 32,597,917 compressions (108,708 per sec)
Time sweeping       : 114,776 sweeps (34,958,202,000 ns)
```

As you can see, both versions were achieving approximately 108,000 compressions per second of 8kb buffers using 2 CPUs (inside a virtual machine).  This equates to 108,000 compression function calls for ~885 MB of data, per second.  I still kinda new to C, so perhaps bottlenecks in my program were tampering with the results; but if so it should have  affected both tests equally so I still consider this reasonably valid data.

Also I'm a nerd and think compression is fun :)  So there's that...

Thanks!

**Comment by Cyan4973** [comment]
Thanks for feedback @KyleJHarper .
885 MB/s looks like a good performance for a 2-cores VM.
I guess you are already achieving close-to-ceiling performance in your application.

**Comment by KyleJHarper** [comment]
Glad to help.
Yes, I believe my application is as fast as it can get with my current knowledge.  You're welcome to check it out if you like; it's on my github page.

If you have no other questions or feedback, feel free to close out this issue.

Thanks!
Kyle
