### ISSUE TITLE
How to ensure correctness of the input data when decompressing

### ISSUE THREAD

**Issue by BhaveshParekh1** [lz4/lz4#322]
Hi,

When we have data in the frame, how to ensure the correctness of the data. One of the approach is to use Block-Checksum for the same. But currently on the tree I see -BX is been disable. Any reason why it is disable and can we safely enable the same again ?

**Comment by Cyan4973** [comment]
Block checksum is no longer available in lz4 cli.
Frame checksum is (and is enabled by default).

If I remember correctly, lz4 cli switched from manual framing to using `lz4frame` API, 
but this API does not support block checksum yet.
It would be a feature to add.

**Comment by BhaveshParekh1** [comment]
Any time-line when it will be added. If required i can help generating the patch for the same

**Comment by Cyan4973** [comment]
Unfortunately, no timeline yet...

**Comment by Cyan4973** [comment]
In [`blockChecsum` branch](https://github.com/lz4/lz4/tree/blockChecksum), there is an updated version of `lz4` cli and API which supports block checksum, as defined in the [specification](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md).

It's a candidate for next release

**Comment by Cyan4973** [comment]
https://github.com/lz4/lz4/pull/383

`blockChecksum` is merged into `dev`.
