### ISSUE TITLE
differentiating used dictionary by data type

### ISSUE THREAD

**Issue by DavidBrenner3** [lz4/lz4#323]
I wonder if the compression can be improved by using different dictionaries for each data type.
For example if the input buffer is a text file it could use a dictionary custom made for text compression.
Applications like Winrar achieves a higher compression ratio by using different compression techniques for specific data types.

By default it can use the current dictionary but, if the user specify a certain data type for the input buffer,
it will use the dictionary for that data type.

Is it possible to implement in lz4 too?

Regards,
David

**Comment by Cyan4973** [comment]
Yes, it's possible, and indeed, specialized dictionaries provide better gains,
but selecting which dictionary to use is the domain of application logic.

**Comment by DavidBrenner3** [comment]
> selecting which dictionary to use is the domain of application logic.
You're right.

If some day you'll think of implementing this, let me know if you need help creating those specialized dictionaries.
I'll help you as much as I can.
