### ISSUE TITLE
Nintendo Switch uses LZ4

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#327]
I know it's 100% off-topic, but worth mentioning

Nintendo Switch uses LZ4

![nintendoswitch-uses-lz4](https://cloud.githubusercontent.com/assets/898396/23538715/c1f49422-0018-11e7-877e-6735ffe38be1.jpg)

**Comment by t-mat** [comment]
You can see this information via
`Home` -> `System Settings` (Gear Button) -> `System` (Left pane) -> `Intellectual Property Notices` (Right pane)

**Comment by Cyan4973** [comment]
Thanks for the informed notification @t-mat !

Feels like a good excuse to get one ! :)

**Comment by t-mat** [comment]
No, I didn't.  I should state this fact.  I didn't say/mention anything about LZ4.  They choosed it because it's good for them.
And I'm so proud for this simple fact ;)
