### ISSUE TITLE
LZ4 detection of lz4cat and unlz4 invocation doesn't work on MS-Windows

### ISSUE THREAD

**Issue by Eli-Zaretskii** [lz4/lz4#335]
LZ4 detects that it has been invoked as 'lz4cat' or 'unlz4' by comparing its argv[0] to fixed strings.  However, on MS-Windows argv[0] can be something like "d:\foo\bar\lz4cat.exe", and the code is not prepared to deal with the .exe suffix.  This caused some tests to fail for me.

Here's a proposed patch, which also fixes a problem whereby fixed-style d:\foo/bar\baz file names would not be supported correctly:

--- programs/lz4cli.c~0	2017-01-03 07:09:52.000000000 +0200
+++ programs/lz4cli.c	2017-03-21 10:16:21.459614400 +0200
@@ -244,6 +244,7 @@ static const char* lastNameFromPath(cons
 {
     const char* name = strrchr(path, '/');
     if (name==NULL) name = strrchr(path, '\\');   /* windows */
+    else if (strchr(name, '\\')) name = strchr(name, '\\'); /* mixed */
     if (name==NULL) return path;
     return name+1;
 }
@@ -297,7 +298,7 @@ int main(int argc, const char** argv)
     LZ4IO_setOverwrite(0);
 
     /* lz4cat predefined behavior */
-    if (!strcmp(exeName, LZ4CAT)) {
+    if (!strncmp(exeName, LZ4CAT, strlen(LZ4CAT))) {
         mode = om_decompress;
         LZ4IO_setOverwrite(1);
         LZ4IO_setRemoveSrcFile(0);
@@ -306,7 +307,7 @@ int main(int argc, const char** argv)
         displayLevel=1;
         multiple_inputs=1;
     }
-    if (!strcmp(exeName, UNLZ4)) { mode = om_decompress; }
+    if (!strncmp(exeName, UNLZ4, strlen(UNLZ4))) { mode = om_decompress; }
 
     /* command switches */
     for(i=1; i<argc; i++) {

**Comment by Eli-Zaretskii** [comment]
Sorry, I see that the diff markers were interpreted as markup.  Here's the patch again as an attachment.


[diff1.txt](https://github.com/lz4/lz4/files/860498/diff1.txt)

**Comment by Cyan4973** [comment]
That's a good point @Eli-Zaretskii , I'll look into it
