### ISSUE TITLE
Expose acceleration in lz4frame

### ISSUE THREAD

**Issue by llchan** [lz4/lz4#346]
It appears that the acceleration parameter is hardcoded to 1 in lz4frame. Could we expose it as an additional field in `LZ4F_preferences_t`?

**Comment by Cyan4973** [comment]
I believe the initial idea was to allow negative compression levels,
they would map to `-acceleration`.

**Comment by llchan** [comment]
I like that, keeps it a single degree of freedom with more or less monotonic behavior. Is this something you plan to add already? Or would you prefer a PR?

**Comment by Cyan4973** [comment]
I plan to add it, I was just missing time to make it.
Shouldn't be hard.

**Comment by Cyan4973** [comment]
There's a new feature branch, called [negativeCLevels](https://github.com/lz4/lz4/tree/negativeCLevels),
which, as the name implies, allows usage of negative compression levels with lz4frame API.

Negative compression levels trigger acceleration with fast API.
For example, a level of `-3` means `acceleration = 3`.

You can try it by building this branch.
It will be merged into `dev` branch after sufficient testing.

**Comment by Cyan4973** [comment]
merged into `dev`

**Comment by vtermanis** [comment]
Hi @Cyan4973, do you know roughly when a new release might be made which will include this? (Am debating whether to make down-stream lib update or wait for next version of lz4 first.)

**Comment by Cyan4973** [comment]
There's no immediate plan for a new release.

That being said, plan can be updated, if there is a need expressed for it, I can consider making a new release for this summer.

**Comment by vtermanis** [comment]
Thanks for the update, no pressure for this feature for now. I'll post again if that changes.
