### ISSUE TITLE
Add Apache Commons Compress to "interoperable LZ4 ports and bindings"

### ISSUE THREAD

**Issue by bodewig** [lz4/lz4#354]
Hi,

I couldn't find a repo for the site or I would have created a pull request.

The just released version 1.14 of [Apache Commons Compress](http://commons.apache.org/proper/commons-compress/) adds a pure Java implementation of both the block and the frame format.

**Comment by terrelln** [comment]
Thanks for the info! The website is the `gh-pages` branch of this repo.

**Comment by bodewig** [comment]
thanks for the pointer - #355
