### ISSUE TITLE
Please reference the python-lz4 updated project on homepage

### ISSUE THREAD

**Issue by jonathanunderwood** [lz4/lz4#356]
The python-lz4 project has moved and is undergoing a lot of new work (especially frame format support) here:

https://github.com/python-lz4/python-lz4

Could you update the reference on the homepage to reflect this - the link given is to an old nmaintained version.

**Comment by Cyan4973** [comment]
Hi @jonathanunderwood ,

the relevant link provided at [project's home page](https://lz4.github.io/lz4/#customs-lz4)
seems to be : https://pypi.python.org/pypi/lz4
which points towards your repo : https://github.com/python-lz4/python-lz4

Is there a problem with that ?

**Comment by jonathanunderwood** [comment]
That's fine, thanks. But since we now have frame compatibikity, can we be
promoted to the table above? Also, at this point the authors are a lot more
than Steve Not, so perhaps the author column could reflect that?

On 18 May 2017 01:18, "Yann Collet" <notifications@github.com> wrote:

Hi @jonathanunderwood <https://github.com/jonathanunderwood> ,

the relevant link provided at project's home page
<https://lz4.github.io/lz4/#customs-lz4>
seems to be : https://pypi.python.org/pypi/lz4
which points towards your repo : https://github.com/python-lz4/python-lz4

Is there a problem with that ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lz4/lz4/issues/356#issuecomment-302265983>, or mute the
thread

**Comment by Cyan4973** [comment]
Sure, I can make these changes,
though I'm a bit surprised regarding this point : 

> we now have frame compatibikity

Both pypi and github pages state : 
> At this time the project contains bindings for the LZ4 block format, which are considered stable.
Support for the LZ4 frame format is a work-in-progress

So what's the status ? Developer preview ? Would it be preferable to wait for the frame format support to be validated before moving the reference into interoperable status ?

Also, there are already 2 existing python libraries for LZ4 : 
> Python multi-threadable	Vilnis Termanis	https://github.com/Iotic-Labs/py-lz4framed
> Python	Christopher Jackson	https://github.com/darkdragn/lz4tools

Could you provide a differentiator that makes your library desirable, even in a limited set of circumstances, compared to existing ones ?

**Comment by Cyan4973** [comment]
I've added your name to the list of contributors of the Python binding.

For the reclassification into "interoperable" section, we'll wait for the binding to mature a bit regarding its support of the LZ4 frame format.
