### ISSUE TITLE
OSX linker complaint

### ISSUE THREAD

**Issue by hexabyte23** [lz4/lz4#357]
Hi All,

I try to use  function  `int LZ4IO_decompressFilename(const char* input_filename, const char* output_filename)` located in lz4io.c

To do so, I include in Makefile depending files : lz4.c, lz4hc.c, lz4frame.c ,xxhash.c and add 
 -DXXH_NAMESPACE=LZ4_

I get complaints from linker : 

Undefined symbols for architecture x86_64:
  "_LZ4_XXH32", referenced from:
      _LZ4F_headerChecksum in lz4frame.o
  "_LZ4_XXH32_digest", referenced from:
      _LZ4F_compressEnd in lz4frame.o
      _LZ4F_decompress in lz4frame.o
  "_LZ4_XXH32_reset", referenced from:
      _LZ4F_compressBegin in lz4frame.o
      _LZ4F_decodeHeader in lz4frame.o
  "_LZ4_XXH32_update", referenced from:
      _LZ4F_compressUpdate in lz4frame.o
      _LZ4F_decompress in lz4frame.o
  "_LZ4_compressBound", referenced from:
      _LZ4_compress_HC_extStateHC in lz4hc.o
      _LZ4_compress_HC_continue in lz4hc.o
      _LZ4_compressHC in lz4hc.o
      _LZ4_compressHC2 in lz4hc.o
      _LZ4_compressHC_withStateHC in lz4hc.o
      _LZ4_compressHC2_withStateHC in lz4hc.o
      _LZ4_compressHC_continue in lz4hc.o
      ...
  "_LZ4_compress_fast", referenced from:
      _LZ4IO_LZ4_compress in lz4io.o
  "_LZ4_compress_fast_continue", referenced from:
      _LZ4F_localLZ4_compress_limitedOutput_continue in lz4frame.o
  "_LZ4_compress_fast_extState", referenced from:
      _LZ4F_localLZ4_compress_limitedOutput_withState in lz4frame.o
  "_LZ4_createStream", referenced from:
      _LZ4F_compressBegin in lz4frame.o
     (maybe you meant: _LZ4_createStreamHC)
  "_LZ4_decompress_safe", referenced from:
      _LZ4F_decompress_safe in lz4frame.o
      _LZ4IO_decodeLegacyStream in lz4io.o
  "_LZ4_decompress_safe_usingDict", referenced from:
      _LZ4F_decompress in lz4frame.o
  "_LZ4_resetStream", referenced from:
      _LZ4F_compressBegin in lz4frame.o
     (maybe you meant: _LZ4_resetStreamHC, _LZ4_resetStreamStateHC )
  "_LZ4_saveDict", referenced from:
      _LZ4F_localSaveDict in lz4frame.o
     (maybe you meant: _LZ4_saveDictHC)
ld: symbol(s) not found for architecture x86_64

any ideas ?

**Comment by Cyan4973** [comment]
There are numerous linkers issues.
This suggests the linking stage was wrongly setup,
which is a generic programming issue, unrelated to `liblz4`.

I'm afraid there's nothing we can do without knowing the exact compilation lines.
