### ISSUE TITLE
pip can't upgrade lz4 from 0.9.0 to latest in macOS

### ISSUE THREAD

**Issue by larryhou** [lz4/lz4#361]
clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Ipy3c -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lz4/_version.c -o build/temp.macosx-10.12-x86_64-2.7/lz4/_version.o
    lz4/_version.c:42:10: fatal error: 'lz4.h' file not found
    #include <lz4.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of lz4
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-232SUu/lz4/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-MlcIFN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-232SUu/lz4/

ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

Python 2.7.13
pip 9.0.1 from /usr/local/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)

**Comment by Cyan4973** [comment]
have you check you have `liblz4` installed on your system ?

**Comment by larryhou** [comment]
$ brew info lz4
	lz4: stable 1.7.5 (bottled), HEAD
	Extremely Fast Compression algorithm
	http://www.lz4.org/
	/usr/local/Cellar/lz4/1.7.5 (21 files, 452.7KB)
	  Poured from bottle on 2017-05-31 at 16:32:01
	From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/lz4.rb
	$ ls -l /usr/local/lib/*lz4*
	-rwxr-xr-x  1 larryhou  admin  100220 May 31 16:07 /usr/local/lib/liblz4.1.7.5.dylib
	lrwxr-xr-x  1 larryhou  admin      18 May 31 16:07 /usr/local/lib/liblz4.1.dylib -> liblz4.1.7.5.dylib
	-rwxr-xr-x  1 larryhou  admin  448304 May 31 16:07 /usr/local/lib/liblz4.a
	lrwxr-xr-x  1 larryhou  admin      18 May 31 16:07 /usr/local/lib/liblz4.dylib -> liblz4.1.7.5.dylib 

I have installed lz4 through `brew` as above,  my `pip` is actually `pip2.7`, but I can install the latest lz4 through `pip3`

**Comment by Cyan4973** [comment]
I tested `brew install lz4`, and it correctly installs `lz4.h` in `/usr/local/include` : 

```
ls /usr/local/include/lz4*
/usr/local/include/lz4.h      /usr/local/include/lz4frame.h /usr/local/include/lz4hc.h
```

I then tried `pip install lz4`,
and it installed correctly on my mac.
My pip version uses python 3.5.

```
pip -V
pip 1.5.1 from /opt/homebrew/lib/python3.5/site-packages (python 3.5)
```

**Comment by Cyan4973** [comment]
I suspect this is more a `pip` issue than an `lz4` one.
As such, the python community is probably a better place to look for help on this topic.
