### ISSUE TITLE
Block format doc should clarify copying direction assumption

### ISSUE THREAD

**Issue by clbr** [lz4/lz4#362]
The doc states "the decoder can now proceed to copy the data from the already decoded buffer" for a match copy. A naive implementation would just memcpy() it. But this is wrong, since memcpy can copy backwards, and if there is overlap, LZ4 assumes the copy proceeds forwards, becoming essentially RLE for that part.

**Comment by Cyan4973** [comment]
I could add a sentence on overlap copy situations, to clarify that point.

Note that this is in no way specific to LZ4, any LZ77 algorithm features the same property.

**Comment by Cyan4973** [comment]
I've modified [LZ4 block format specification](https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md) to add a dedicated paragraph for overlap copy operations.

**Comment by clbr** [comment]
That works, thanks.
