### ISSUE TITLE
Unclear comment in simple_buffer example

### ISSUE THREAD

**Issue by amundhov** [lz4/lz4#363]
When I first read through the [simple_buffer example](https://github.com/lz4/lz4/blob/dev/examples/simple_buffer.c#L79-L82) I was led to believe that LZ4_decompress_safe would return with the number of bytes consumed from the source buffer.

After looking through the source I see this is indeed not the case, and would not make sense since the caller should be very interested in knowing the exact size of the resulting decompressed buffer.

**Comment by Cyan4973** [comment]
Indeed, you are right @amundhov .

The example was apparently changed mid-term from `LZ4_decompress_fast()` to `LZ4_decompress_safe()`, which also modified the signification of return value.
The code comment should have followed.

To be fixed

**Comment by Cyan4973** [comment]
Example has been modified in `dev` branch
