### ISSUE TITLE
Actualize lz4.podspec.json

### ISSUE THREAD

**Issue by ryuzmukhametov** [lz4/lz4#370]
Hi,

What do you think about updating 
https://github.com/CocoaPods/Specs/blob/master/Specs/f/b/1/lz4/128/lz4.podspec.json?
As I see last stable version (1.7.5) has some improvements (such as unaligned pointers fix).
So it can help to avoid some issues which come from Xcode 9 unexpected behaviour checker and provide general stability as well.

Thank you

**Comment by Cyan4973** [comment]
Yes, that would be great.
But I have no idea how to do that.
This package wasn't done by us, I guess any third party could update it to v1.7.5,
I guess it's more a Cocoa-related topic.

**Comment by ryuzmukhametov** [comment]
Ok, let me try to update it there. Will ping in case of any changes. So closing ticket now.

**Comment by wudijiang** [comment]
> This package wasn't done by us, I guess any third party could update it to v1.7.5,

Hi, 
I have the same problem.
Have you updated this version to 1.7.5？
