### ISSUE TITLE
potential critical bug in x64 system

### ISSUE THREAD

**Issue by kingpin58** [lz4/lz4#375]
Hi 

I build the source code in VS2015 on Win7. And my environment setting is x64 system.
I found that the VS2015 shown a warning with code 6385. It shown as below:
lz4\programs\lz4io.c(340): warning C6385: 从“out_buff”中读取的数据无效: 可读大小为“outBuffSize”个字节，但可能读取了“4”个字节。
Maybe you cannot understand Chinese, so I have translated the sentence to English( maybe not correct):
lz4\programs\lz4io.c(340): warning C6385: The data read from out_buff is invalid: the available size equals outBuffSize, but the function may read 4 chars.

Can you fix it?

Thank you!

**Comment by terrelln** [comment]
I'm not sure why VS2015 is complaining. `out_buff` is never less than [16 bytes](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L153), so it can't be a problem.

**Comment by kingpin58** [comment]
I got that. Thank you for your reply!
