### ISSUE TITLE
Does lz4 CLI support fixed block size of compressed data (using LZ4_compress_destSize) ?

### ISSUE THREAD

**Issue by ganz1049** [lz4/lz4#377]
Currently we have a use case to have fixed block size of compressed data. 
We are aware that in the source code,LZ4_compress_destSize can be used to fill fixed-size buffer with compressed data. I checked the lz4 command line utility (1.7.5), but it seems the utility does not support fixed size of compressed data.
Please correct me if i am wrong. Thanks in advance!

**Comment by terrelln** [comment]
The CLI does not support fixed size of compressed data.

**Comment by ganz1049** [comment]
@terrelln: Thanks alot for your reply!
