### ISSUE TITLE
(feature request) support compressing directory

### ISSUE THREAD

**Issue by kenliao94** [lz4/lz4#379]
Hi, currently the terminal executable lz4 doesn't support compressing folder (right?). Would it be possible to add the logic to the tool such that if it is a directory, perform tar then execute the lz4? If yes. would you like a PR on that?

**Comment by Cyan4973** [comment]
Hi @kenliao94 

I'm not sure if this is the right place for such a capability.
In general, users expect it the other way round, that is, make `tar` call `lz4`.
