### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by adamnovak** [lz4/lz4#381]
There is no `INSTALL` file, and no installation instructions in the README. Moreover, the build system is not the "standard" `./configure <options>; make; make install` pattern, so installation instructions may be necessary.

In particular, installing to a prefix seems to require a nonstandard `make; PREFIX=<whatever> make install` pattern, which should be documented.

**Comment by Cyan4973** [comment]
The installation process is supposed to be shortened to `make ; make install`.

I was surprised by the statement that `PREFIX=<whatever> make install` was "nonstandard", but indeed, it seems that name in uppercase comes from the [BSD world](https://www.freebsd.org/doc/en/books/porters-handbook/porting-prefix.html), while GNU prefers [lowercase version](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables).
 
Anyway, in [`installVars` branch](https://github.com/lz4/lz4/tree/installVars), I've rewritten `Makefile` to support both, and use the opportunity to follow more closely the GNU specification.
The `README.md` contains an "installation" section, and mirrored into an `INSTALL` file.

For review

**Comment by Cyan4973** [comment]
Merged into `dev` branch
