### ISSUE TITLE
Streaming decompression questions

### ISSUE THREAD

**Issue by Cyan4973** [lz4/lz4#394]
from @jtbandes : 

I have some small questions about the LZ4 API I was hoping you could answer. I didn't find this information explicitly stated in the header files or the wiki/manual.

1. After compressed blocks are created using `LZ4_compress_fast_continue()`, must they be passed to `LZ4_decompress_*_continue()` with the exact same boundaries, or can the decompression function accept more than one adjacent block at a time (or partial blocks)? (I suspect the documentation of these `decompress_*_continue` functions is trying to address this question, but I don't understand what is meant by "Exactly same size as encoding buffer, with same update rule")

2. Can one `LZ4_streamDecode_t` be used to decompress multiple sets of streamed blocks (from independent sequences of `LZ4_compress_fast_continue`), or must I re-do `LZ4_createStreamDecode()` each time I encounter the first block from a new sequence?

**Comment by Cyan4973** [comment]
1. Yes. Blocks created by `LZ4_compress*()` must be passed as is to `LZ4_decompress*()`, with the exact complete size of each compressed block. `LZ4_decompress*()` will not process incomplete blocks, nor multiple blocks bundled together, and will interpret such cases as errors. Maybe code documentation should be updated to express this condition more clearly.

2. Yes, `LZ4_streamDecode_t` can be re-used for multiple sets of streamed blocks.
It's cleaner to start a new stream of blocks with `LZ4_setStreamDecode()`,
to erase from its memory any reference of blocks from previous stream.
Even if you don't, correctly formed streams of blocks will work correctly.
But if compressed data is malformed for any reason,
the decoder could mis-interpret an invalid match for a correct one,
missing an opportunity to detect data corruption early.

**Comment by Cyan4973** [comment]
Code documentation updated to reflect these questions

**Comment by jtbandes** [comment]
Thanks for the clarification. I see the "prefix mode" and "external dictionary mode" in the double-buffer readme. However it's still not clear exactly when these modes are used…

Is this correct for `LZ4_compress_fast_continue` ?

- If `src` is exactly equal to `src + srcSize` from the **previous** call to LZ4_compress_fast_continue, then it uses "prefix mode" and assumes up to 64k is available (so it might read data _before_ previous `src`)
- Otherwise, if `src != previous src + previous srcSize`, then it uses "external dictionary mode", and it will **only** read data from within the previous `src` to `src+srcSize` range?

Another way of phrasing this question:
```
  Special 1 : If input buffer is a double-buffer, it can have any size, including < 64 KB.
  Special 2 : If input buffer is a ring-buffer, it can have any size, including < 64 KB.
```
What is the exact definition of double buffer? Must it be contiguous?

**Comment by Cyan4973** [comment]
> What is the exact definition of double buffer? Must it be contiguous?

No, they can be separated.
The main idea is, they are used alternatively.


> if src is exactly equal to src + srcSize from the previous call to LZ4_compress_fast_continue, then it uses "prefix mode" and assumes up to 64k is available (so it might read data before previous src)

Almost. It will indeed trigger "prefix" mode. But there is no risk if such prefix is < 64 KB : LZ4 will correctly track this limit and ensure it's never crossed.


> Otherwise, if src != previous src + previous srcSize, then it uses "external dictionary mode", and it will only read data from within the previous src to src+srcSize range?

Almost too. Indeed, when memory segments are non-contiguous, it triggers "external dictionary mode". The content of this external dictionary is the full previous contiguous segment, so it includes `[src, src+srcSize]`, but also its associated "prefix segment" if it exists.
As usual, the maximum addressable memory in this memory segment is the last 64 KB of data.

LZ4-fast can only use one of these two modes.
But LZ4-HC can use both at the same time (i.e. it can have both a prefix, and an external dictionary).
There is a long term objective for LZ4-fast to feature same capability. Not yet implemented.

**Comment by zhwufd** [comment]
If src block is [addr1, addr2], [addr3, addr4] [addr4 + 1, addr5] i.e. some src blocks are contiguous, some src blocks are not, do i need to copy all of the blocks to contiguous memory and then call LZ4_compress_fast_continue to compress?

**Comment by Cyan4973** [comment]
> If src block is [addr1, addr2], [addr3, addr4] [addr4 + 1, addr5] i.e. some src blocks are contiguous, some src blocks are not, do i need to copy all of the blocks to contiguous memory and then call LZ4_compress_fast_continue to compress?

Yes, that's the simplest way to make sure it works.

**Comment by zhwufd** [comment]
> 

Is there any zero-copy implementation of streaming compression in this case? Performance matters for some librarys.

**Comment by Cyan4973** [comment]
read https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L269
