### ISSUE TITLE
Streaming decompression issue w/emscripten

### ISSUE THREAD

**Issue by jscheid** [lz4/lz4#397]
Hi,

I'm porting the [blockStreaming_ringBuffer.c](https://github.com/lz4/lz4/blob/dev/examples/blockStreaming_ringBuffer.c) example to emscripten and I've run into an issue. I've tried to get to the bottom of it, here is my analysis, which could be completely wrong...

Because the address space is not shared and there is no OS in memory, `decBuf` happens to be allocated at a low address (say 0x159c). At some point the dictionary grows to 9216 bytes. Now `lowLimit` gets to be negative [here](https://github.com/lz4/lz4/blob/1ad9a36cfb9fc669b0b18bfcd902d3e52a3d2cbb/lib/lz4.c#L1131). Because the pointer is unsigned, it becomes something like 0xfffff19c (emscripten is 32-bit). Now [this condition](https://github.com/lz4/lz4/blob/1ad9a36cfb9fc669b0b18bfcd902d3e52a3d2cbb/lib/lz4.c#L1187) will trigger always (practically speaking) because it is an unsigned comparison. 💥 

The following patch appears to fix it:

```diff
diff --git a/lib/lz4.c b/lib/lz4.c
index 96422f8..7f48e36 100644
--- a/lib/lz4.c
+++ b/lib/lz4.c
@@ -1128,7 +1128,6 @@ LZ4_FORCE_INLINE int LZ4_decompress_generic(
     BYTE* const oend = op + outputSize;
     BYTE* cpy;
     BYTE* oexit = op + targetOutputSize;
-    const BYTE* const lowLimit = lowPrefix - dictSize;
 
     const BYTE* const dictEnd = (const BYTE*)dictStart + dictSize;
     const unsigned dec32table[] = {0, 1, 2, 1, 4, 4, 4, 4};
@@ -1184,7 +1183,7 @@ LZ4_FORCE_INLINE int LZ4_decompress_generic(
         /* get offset */
         offset = LZ4_readLE16(ip); ip+=2;
         match = op - offset;
-        if ((checkOffset) && (unlikely(match < lowLimit))) goto _output_error;   /* Error : offset outside buffers */
+        if ((checkOffset) && (unlikely(match + dictSize < lowPrefix))) goto _output_error;   /* Error : offset outside buffers */
         LZ4_write32(op, (U32)offset);   /* costs ~1%; silence an msan warning when offset==0 */
 
         /* get matchlength */
```

I'm not sure whether similar calculations in other parts of the code (e.g. [here](https://github.com/lz4/lz4/blob/1ad9a36cfb9fc669b0b18bfcd902d3e52a3d2cbb/lib/lz4.c#L517)) are unaffected or whether they work for me only because the buffer happens to be at a high enough address.

**Comment by jscheid** [comment]
On second thought, I suppose a better fix might be to cast the pointers to `int` so that the addition is kept out of the inner loop.

**Comment by jscheid** [comment]
> I'm not sure whether similar calculations in other parts of the code (e.g. here) are unaffected 

It turns out that I had to fix this in many other places (by casting to int). Would you accept a PR? My C is a bit rusty, what is the most portable way to do those casts?

**Comment by Cyan4973** [comment]
It's a great investigation @jscheid .
I believe your diagnosis is completely right.

A fix shall also preserve algorithm's speed properties for other platforms.
Keeping the addition out of the loop might help, though a cast isn't guaranteed to be free.
I'll bench the impact to make sure it's neutral.

**Comment by Cyan4973** [comment]
While I can "blind fix" the issue,
it would be great to be able to reliably reproduce the bug conditions in a CLI environment.
That would ensure that the issue is indeed fixed, and keep checking it for future revisions.
Sadly, I'm short of idea on how to do that ...

**Comment by Cyan4973** [comment]
The fix proposed doesn't seem to introduce any performance penalty (checked with `tests/fullbench -d`). Any difference I could measure was within noise threshold.
So I'm going to upload it into `dev` branch.
Though, at this stage, it's still a "blind fix" : we don't have a test case to prove that the issue is fully solved, and control it regularly later.

**Comment by Cyan4973** [comment]
Also : 
potentially related to https://github.com/lz4/lz4/issues/230

**Comment by jscheid** [comment]
Thanks for taking a look at this, and for the fix.

I'm sorry if I was unclear in https://github.com/lz4/lz4/issues/397#issuecomment-327757377 but this will also have to be fixed in many other places, see below. Sorry this is not very cleaned up... has unneeded parens etc. And as you can see, I've used the casting approach in the other places, but I understand that you think that the adding approach is better.

(I haven't tested that _all_ of these changes are necessary, but I believe most of them are.)

> Sadly, I'm short of idea on how to achieve that ...

It's going to be a PITA to set up on CI, but one possibility is to actually use emscripten... if too much work on CI, perhaps just as a test case to be run manually? I'm happy to help set this up as far as time permits.

```diff
diff --git a/lib/lz4.c b/lib/lz4.c
index 96422f8..24febb3 100644
--- a/lib/lz4.c
+++ b/lib/lz4.c
@@ -558,13 +558,13 @@ LZ4_FORCE_INLINE int LZ4_compress_generic(
                 forwardH = LZ4_hashPosition(forwardIp, tableType);
                 LZ4_putPositionOnHash(ip, h, cctx->hashTable, tableType, base);
 
-            } while ( ((dictIssue==dictSmall) ? (match < lowRefLimit) : 0)
+            } while ( ((dictIssue==dictSmall) ? (((int)match) < ((int)lowRefLimit)) : 0)
                 || ((tableType==byU16) ? 0 : (match + MAX_DISTANCE < ip))
                 || (LZ4_read32(match+refDelta) != LZ4_read32(ip)) );
         }
 
         /* Catch up */
-        while (((ip>anchor) & (match+refDelta > lowLimit)) && (unlikely(ip[-1]==match[refDelta-1]))) { ip--; match--; }
+        while (((ip>anchor) & ((int)(match+refDelta) > (int)(lowLimit))) && (unlikely(ip[-1]==match[refDelta-1]))) { ip--; match--; }
 
         /* Encode Literals */
         {   unsigned const litLength = (unsigned)(ip - anchor);
@@ -642,7 +642,7 @@ _next_match:
                 lowLimit = (const BYTE*)source;
         }   }
         LZ4_putPosition(ip, cctx->hashTable, tableType, base);
-        if ( ((dictIssue==dictSmall) ? (match>=lowRefLimit) : 1)
+        if ( ((dictIssue==dictSmall) ? (((int)match)>=((int)lowRefLimit)) : 1)
             && (match+MAX_DISTANCE>=ip)
             && (LZ4_read32(match+refDelta)==LZ4_read32(ip)) )
         { token=op++; *token=0; goto _next_match; }
@@ -799,7 +799,7 @@ static int LZ4_compress_destSize_generic(
         }
 
         /* Catch up */
-        while ((ip>anchor) && (match > lowLimit) && (unlikely(ip[-1]==match[-1]))) { ip--; match--; }
+        while ((ip>anchor) && (((int)match) > ((int)lowLimit)) && (unlikely(ip[-1]==match[-1]))) { ip--; match--; }
 
         /* Encode Literal length */
         {   unsigned litLength = (unsigned)(ip - anchor);
@@ -1128,7 +1128,6 @@ LZ4_FORCE_INLINE int LZ4_decompress_generic(
     BYTE* const oend = op + outputSize;
     BYTE* cpy;
     BYTE* oexit = op + targetOutputSize;
-    const BYTE* const lowLimit = lowPrefix - dictSize;
 
     const BYTE* const dictEnd = (const BYTE*)dictStart + dictSize;
     const unsigned dec32table[] = {0, 1, 2, 1, 4, 4, 4, 4};
@@ -1184,7 +1183,7 @@ LZ4_FORCE_INLINE int LZ4_decompress_generic(
         /* get offset */
         offset = LZ4_readLE16(ip); ip+=2;
         match = op - offset;
-        if ((checkOffset) && (unlikely(match < lowLimit))) goto _output_error;   /* Error : offset outside buffers */
+        if ((checkOffset) && (unlikely(match + dictSize < lowPrefix))) goto _output_error;   /* Error : offset outside buffers */
         LZ4_write32(op, (U32)offset);   /* costs ~1%; silence an msan warning when offset==0 */
 
         /* get matchlength */
@@ -1201,7 +1200,7 @@ LZ4_FORCE_INLINE int LZ4_decompress_generic(
         length += MINMATCH;
 
         /* check external dictionary */
-        if ((dict==usingExtDict) && (match < lowPrefix)) {
+        if ((dict==usingExtDict) && ((int)match < (int)lowPrefix)) {
             if (unlikely(op+length > oend-LASTLITERALS)) goto _output_error;   /* doesn't respect parsing restriction */
 
             if (length <= (size_t)(lowPrefix-match)) {
```

**Comment by Cyan4973** [comment]
Thanks for the complementary patch.
Indeed, for the compression side, I believe this issue is related to #230.

During compression, the pointer underflow doesn't degenerate into an actual "error" : it just fails a test, missing a few opportunities to compress a few more bytes. So the compressed result is less optimal than it could be, albeit by a microscopic amount.

Still, it would be desirable to fix, as long as it does not generate worse side effects, such as measurable speed losses (which seems unlikely).

**Comment by jscheid** [comment]
Heads up, while the above patch fixes the issue in my case (i.e. porting the streaming example to emscripten) _with the default configuration_ of `MESSAGE_MAX_BYTES = 1024`, I'm getting errors when increasing this to `2048` or other higher values, so I'm led to believe the patch is incomplete.

How do we proceed from here, what do you think of my suggestion of adding a test case utilising emscripten and Node.js? It might be useful in finding such corner cases, even if it's impractical to run on Travis.

**Comment by Cyan4973** [comment]
Having a test case utilising emscripten and Node.js would be quite handy.

Best case, it would be able to run on CI environment (typically travisCI), so that the test can be run continuously against future updates. It's generally possible to install something in the travis' container, so it's not an impossible scenario.
