### ISSUE TITLE
Doubt on Decompression time on ARM9 ? 

### ISSUE THREAD

**Issue by Tahata** [lz4/lz4#401]
Hello ,
I compile the decompress lz4 code on ARM9 ( 32bits, 32 kByte L1 cache ) , run in 400MHz , and I observe the Decompress time is about 2,5 Sec . where in Gzip is about 5 Sec. Seem it is not very fast compare to Gzip as run on Intel x86 , I expect it can be 10 time faster than Gzip. Is it an issue or somethings expected  ?

Thank you

**Comment by Cyan4973** [comment]
Indeed, it's slower than expectation.
It's difficult to guess why, remote access to target would be necessary for further investigation.

In the meantime, you may try these actions : 
- Check version of lz4 used
- Force value of `LZ4_FORCE_MEMORY_ACCESS` to `0`, `1` or `2` during compilation. Check if it makes any difference.
- Test speed on small files (< 32 KB) if you can measure it

**Comment by Tahata** [comment]
Thank you so much ,Cyan4973 
I've seen on the release note of Lz4 1.7.3 mention : Improved: Significant speed boost on ARMv6 and ARMv7
In your Opinion , may it be faster than Lz41.8 ? May be I can try with version 1.7.3

**Comment by Cyan4973** [comment]
In theory, 1.8.0 should perform as well or better than 1.7.3,
but we never know, maybe there is a regression for this platform instead.

**Comment by Tahata** [comment]
Thank you Cyan4973
I try to use 1.7.3 but can not because seem the code size is bigger than 1.8 , it increase to 27KB , instead of just 4.6KB in 1.8 . This is a problem with my system . Do you know why the code size are too different , any Configuration to reduce it ?

**Comment by Cyan4973** [comment]
It's difficult to tell.
You apparently have specifics needs, for a specific platform, and possibly a specific build system.
None of these is trivial nor can be guessed out of context.
Useful assistance requires accessing these elements.

**Comment by Tahata** [comment]
Yes it clear, Thank you for your kindly advise
