### ISSUE TITLE
Disable library symbols visibility

### ISSUE THREAD

**Issue by mikir** [lz4/lz4#410]
I use lz4 library as a part of bigger shared library and I want to hidden all lz4 library symbols. To achieve this, I have changed slightly definition of LZ4LIB_API macro:

```
#ifndef LZ4LIB_API
#  if defined(LZ4_DLL_EXPORT) && (LZ4_DLL_EXPORT==1)
#    define LZ4LIB_API __declspec(dllexport)
#  elif defined(LZ4_DLL_IMPORT) && (LZ4_DLL_IMPORT==1)
#    define LZ4LIB_API __declspec(dllimport) /* It isn't required but allows to generate better code, saving a function pointer load from the IAT and an indirect jump.*/
#  elif defined(__GNUC__) && (__GNUC__ >= 4)
#    define LZ4LIB_API __attribute__ ((__visibility__ ("default")))
#  else
#    define LZ4LIB_API
#  endif
#endif
```

This allows user to define LZ4LIB_API macro during compilation (in my case, I define it as empty for gcc).

Could you please consider to integrate this change? Many thanks. Miki

**Comment by terrelln** [comment]
I'd love to make this possible, please submit a PR! I'd like to separate the visibility from the rest of the macro and only allow users to override that, like in [zstd](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L22).

**Comment by mikir** [comment]
OK. Please find out the corresponded Pull Request here: https://github.com/lz4/lz4/pull/412

**Comment by Cyan4973** [comment]
#412 is merged
