### ISSUE TITLE
Store forwarding in copying match

### ISSUE THREAD

**Issue by odaira** [lz4/lz4#411]
This section of code in LZ4_decompress_generic suffers from many blocked loads due to failed store forwarding.

        if (unlikely(offset<8)) {
            const int dec64 = dec64table[offset];
            op[0] = match[0];
            op[1] = match[1];
            op[2] = match[2];
            op[3] = match[3];
            match += dec32table[offset];
            memcpy(op+4, match, 4);
            match -= dec64;
        } else { LZ4_copy8(op, match); match+=8; }
        op += 8;

        if (unlikely(cpy>oend-12)) {
            BYTE* const oCopyLimit = oend-(WILDCOPYLENGTH-1);
            if (cpy > oend-LASTLITERALS) goto _output_error;    /* Error : last LASTLITERALS bytes must be literals (uncompressed) */
            if (op < oCopyLimit) {
                LZ4_wildCopy(op, match, oCopyLimit);
                match += oCopyLimit - op;
                op = oCopyLimit;
            }
            while (op<cpy) *op++ = *match++;
        } else {
            LZ4_copy8(op, match);
            if (length>16) LZ4_wildCopy(op+8, match+8, cpy);
        }

I confirmed it using OProfile with`ld_blocks 0x2` on x86 Haswell and `PM_CMPLU_STALL_ST_FWD` on POWER8.

Is the current implementation a result of balancing the code simplicity against the speed, or is it acceptable to further optimize the code?

It is hard to estimate a speed-up by removing the store forwarding, but my guesstimate by accumulating the CPU cycles hit around the load instructions is up to a 20% speed-up in LZ4_decompress_fast on POWER8. Recent x86 CPUs have relatively better store forwarding than POWER, so the benefit might be smaller on x86.

FYI, LZ4_decompress_fast on POWER8 spends 50% of the CPU cycles stalling in the CPU backend.  I guess 20% for the store forwarding and 30% for cache misses.

**Comment by terrelln** [comment]
I'd be very interested if this bit of code can be made faster (especially for x86), so long as it doesn't regress on other architectures. This piece of code is replicated in [zstd](https://github.com/facebook/zstd/blob/dev/lib/decompress/zstd_decompress.c#L1044), so any win here should translate to zstd as well.

As long as there is a measurable improvement, it is worthwhile to add more code. However, we would like to avoid architecture-specific code or assembly. We would accept it for a large enough win, but it would have to be well encapsulated, and have a fallback implementation in C.

**Comment by odaira** [comment]
Thanks, I'll try to optimize this.

**Comment by Cyan4973** [comment]
Any progress on this topic ?
Or shall we close it ?
