### ISSUE TITLE
Disable WholeProgramOptimization and allow linking with static crt for Windows msvc builds

### ISSUE THREAD

**Issue by MaxRis** [lz4/lz4#423]
Hello and thank you for the development of lz4!

We're building lz4 on Windows as well, but have faced troubles to customize Visual Studio 2010 solution for our needs ( pretty wide used build parameters btw ).

There are few things which creates difficulties:

1. Since only Visual Studio 2010 solution project files are available, we are using them to build with Visual Studio 2015. The issues is that Visual Studio 2010 was the last version of Visual Studio where WholeProgramOptimization was added by default for all builds. Starting with next versions of Visual Studio WholeProgramOptimization is not turned on anymore. Compiling with this param by VS 2015 creates binaries incompatible with others 3rd party binaries produced by VS 2015 (we expect to install some libs from packager manager, not building everything manually all the time).
As temp solution we're adjusting available VS 2010 project files and removing WholeProgramOptimization setting from [them](https://github.com/apache/arrow/pull/1333/files#diff-dd2c927b437d5c1b71ce2d1b3780d907R26).
2. We want optionally build binaries linked with static msvc crt (by default it's dynamic). To workaround this we've adjusted VS 2010 project files [one more time](https://github.com/apache/arrow/pull/1333/files#diff-dd2c927b437d5c1b71ce2d1b3780d907R50). Based on this changes it's possible to build with linking to static crt just with additional param passed to `msbuild` ( `/p:RuntimeLibrary=MultiThreaded` )

The same issues with similar currently applied workarounds we have with zstd library.

Could you please suggest if there exists better way to handle Windows build customization?

Thanks!

**Comment by Cyan4973** [comment]
If all it takes is to edit project files to remove `WholeProgramOptimization` and specify static linking, I'm happy to review and merge a patch with one or both changes.

**Comment by MaxRis** [comment]
@Cyan4973 sounds great, thanks! I will prepare changes both for lz4 and zstd.

**Comment by MaxRis** [comment]
Closing since it was resolved in merged PR.
