### ISSUE TITLE
[Question]Do we have memory allocated in LZ4 decompression?

### ISSUE THREAD

**Issue by yinsimei** [lz4/lz4#425]
Hello and thanks a lot for your development of lz4 library.

I notice that we don't have any APIs that allow externally allocated memory for lz4 decompression. After a quick glance in `LZ4_decompress_generic`, I find that there is actually no memory allocated there. So I would like to ask a question about it to make sure because memory allocation is something quite critical in our application.

Sorry for the silly question and thank you very much for your time.

**Comment by Cyan4973** [comment]
Hi @yinsimei 
There is, indeed, no memory allocation needed for LZ4 decompression.

**Comment by yinsimei** [comment]
Thanks a lot for your reply! It solves my problem.
