### ISSUE TITLE
Compress ratio compared with Block vs Streaming vs Frame API?

### ISSUE THREAD

**Issue by pahome** [lz4/lz4#428]
I have a questions about whose compress ratio is the best in the three APIs?

**Comment by Cyan4973** [comment]
If neglecting headers / metadata, they should all be identical.

Frame API has additional metadata, though its only a few bytes per block.
Block API doesn't have metadata, but that means user needs to provide and save this information on its own, which generally costs also a few bytes.

**Comment by pahome** [comment]
ok, I thought double buffer will be better than other streaming apis.
maybe the advantage of lz4 is the speed and it will sacrifice much performance in compress ratio.
