### ISSUE TITLE
'--' cannot be used to separate options from input file

### ISSUE THREAD

**Issue by planet36** [lz4/lz4#429]
$ lz4 -- foo
Incorrect parameters
Usage :
      lz4 [arg] [input] [output]

input   : a filename
          with no FILE, or when FILE is - or stdin, read standard input
Arguments :
 -1     : Fast compression (default) 
 -9     : High compression 
 -d     : decompression (default for .lz4 extension)
 -z     : force compression
 -f     : overwrite output without prompting 
 -h/-H  : display help/long help and exit

$ lz4 --version
*** LZ4 command line interface 32-bits r128, by Yann Collet (Apr 18 2016) ***

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02
"""
Guideline 10:
The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.
"""

**Comment by Cyan4973** [comment]
The `--` separator is available since [v1.8.0](https://github.com/lz4/lz4/releases/tag/v1.8.0).
I just checked that it works appropriately.

The version tested, `r128`, is [a bit too old](https://github.com/lz4/lz4/releases/tag/r128), amd doesn't support it.
