### ISSUE TITLE
would like ISA-L's compression numbers added to comparison chart

### ISSUE THREAD

**Issue by dankimmel** [lz4/lz4#433]
This could be contentious, but I feel it'd be helpful for determining newcomers whether to use LZ4:

Could you add ISA-L's compression / decompression throughput and ratios to your `README.md` benchmark numbers? It would be helpful to have that comparison point, even though their algorithms are hardware-specific and therefore not applicable to everyone.

**Comment by Cyan4973** [comment]
I'm afraid it's indeed a bit specific, and probably not applicable.

To begin with, I don't have relevant hardware to test and produce numbers.
Besides, an important issue with external hardware solutions is that transferring data from memory to the bus introduces a latency cost, which makes it difficult to compare with software implementations. It's no longer about peak performance, it's about how well it integrates with the application. Network scenarios are probably fine with it, but mem-to-mem compression is a poorer fit. Btw, many scenarios adressed by LZ4 are mem-to-mem.

Should you wish to make your own comparison, a good start would be to provide a patch for its integration within [lzbench](https://github.com/inikep/lzbench/), which is the framework we use for compression comparisons.
