### ISSUE TITLE
lz4 -d --rm does not preserve timestamp

### ISSUE THREAD

**Issue by expressoCoder** [lz4/lz4#441]
Using lz4 v1.8.0 on CentOS 6.8 x86_64

Compressing with `lz4` or `lz4 --rm` will preserve timestamp
Decompressing with `lz4 -d` will also preserve timestamp.

However `lz4 -d --rm` will not preserve timestamp

**Comment by terrelln** [comment]
I can reproduce the issue, and will look into it shortly.

**Comment by Cyan4973** [comment]
fixed by @terrelln
