### ISSUE TITLE
what is the frame footer?

### ISSUE THREAD

**Issue by psteinb** [lz4/lz4#445]
Hi,
I am just trying to follow the example on frame based compression, the example defines a preprocessor symbol by the name of `LZ4_FOOTER_SIZE`. 

https://github.com/lz4/lz4/blob/0b203b04f6b5085f9f98c8c78c6535399264d755/examples/frameCompress.c#L13

The `lz4frame.h` doesn't define anything alike. the documentation for the frame format doesn't cite a footer at all.

So I am wondering, what this is?

On a related note, the [frame format docs](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md) do not define what the header is as well. Only the header checksum is defined.

**Comment by psteinb** [comment]
Cool, thanks a bunch. I'd fancy to submit a PR so that is documented in 
the example as well as in the design docs for the frame API.

I'd love to use lz4 in a multi-threaded fashion. In that context, is the 
frame API thread-safe? For this I am considering the following 2 cases:

a) call the following sequence
LZ4F_createCompressionContext+LZ4F_compressBegin+LZ4F_compressUpdate+LZ4F_compressEnd+LZ4F_freeCompressionContext
in each thread separately and also create the relevant structs once per 
thread?

b) call LZ4F_createCompressionContext once, then start the parallel 
region and call the sequence 
LZ4F_compressBegin+LZ4F_compressUpdate+LZ4F_compressEnd per thread, 
after ending the parallel processing, I'd call LZ4F_freeCompressionContext.

thanks for your help so far.
P

**Comment by Cyan4973** [comment]
- You will need one context per thread
- contexts can be re-used by successive compression jobs

Which gives : 

For each thread : 
```
LZ4F_createCompressionContext()
(.. do some works ...)
LZ4F_freeCompressionContext
```

For each work : 
```
LZ4F_compressBegin()
LZ4F_compressUpdate()  // as many times as necessary
LZ4F_compressEnd()
```

**Comment by psteinb** [comment]
thanks for all your answers and for picking it up in #458. Question is how to deal with a global macro specifying this as [frameCompess.c](https://github.com/lz4/lz4/blob/0b203b04f6b5085f9f98c8c78c6535399264d755/examples/frameCompress.c#L13) does?

**Comment by Cyan4973** [comment]
Do you mean, you would like macros like the ones defined in example program `frameCompress.c` by Zbigniew (`LZ4_HEADER_SIZE` and `LZ4_FOOTER_SIZE`) to be available in the API ?

Note there is already [`LZ4F_HEADER_SIZE_MAX`](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.h#L238) defined in the API.
There is no "footer size" though.

**Comment by psteinb** [comment]
Yes, something like that in the API would be just wonderful.

**Comment by Cyan4973** [comment]
I've been looking at the example program, `frameCompress.c`, to understand in which circumstance a footer size would be useful. And currently, it does not feel obvious.
I believe that, as a first action, I should revisit this example, and maybe fix a few details so that its API usage reflects what we believe is "good practice" (note: I'm not the original author of this example).
We'll see after this update if a footer size is still a useful information to expose.
Maybe all it will take is to improve the API documentation (and the example).

**Comment by psteinb** [comment]
Improved documentation is always helpful. Go for it for sure! For my particular case, I mostly use the footer for calculating the upper bound of the expected size of the encoded signal. For this, it is nice to rely on the API as it relieves me of the risk (as a client of lz4frame) to use the wrong value for the footer size. Further, I have less magic numbers in my code, which typically impose a maintenance hazard.

**Comment by Cyan4973** [comment]
Indeed, you are right.
And that's the issue : `LZ4F_compressFrameBound()` is supposed to already include any kind of header / footer size, so a user shouldn't need to worry about.
That's why I need to look deeper into this example ...

**Comment by Cyan4973** [comment]
I've updated the `frameCompress.c` example (compression part)
and the new version doesn't need additional constant.
I believe it better reflects the way we expect the LZ4F API to be used.
There is PR opened for comment at #460.

**Comment by psteinb** [comment]
Super cool! I am going to change my code accordingly.
