### ISSUE TITLE
Question: Are releases only available on dev branch deemed stable?

### ISSUE THREAD

**Issue by vtermanis** [lz4/lz4#462]
Dear developers & maintainers,

> The "master" branch is considered stable, at all times.

Is the [1.8.1*](https://github.com/lz4/lz4/releases/tag/v1.8.1.2) release deemed to be stable (given it's received a tag and github release entry) despite not being on the master branch yet?

Regards,
VT

**Comment by vtermanis** [comment]
D'oh! Just realised 1.8.1 is on master. Please ignore.

**Comment by Cyan4973** [comment]
All releases are deemed stable.
`v1.8.1.2` is based on the same patch level as the `master` branch (dfed9fa1d77f0434306d377c4da1f7191d3ba08a)
