### ISSUE TITLE
Regression from 1.8.0 to 1.8.1.2

### ISSUE THREAD

**Issue by nacho** [lz4/lz4#464]
I seem to get the following compile error:
bench.o: In function `UTIL_getTime':
/builddir/DCV_JHBUILD/sources/lz4-1.8.1.2/programs/util.h:198: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status

**Comment by nacho** [comment]
Thanks for the quick response. I'll close the issue and let you know if the next release does not fix it.

**Comment by GitMensch** [comment]
I had the same issue with the 1.8.1.2 release. Exchanging programs/util.h with https://raw.githubusercontent.com/lz4/lz4/7dba09af47dd3daa1562a6332a643a1a59dba4a8/programs/util.h + `make clean` + `make` fixes the issue.
