### ISSUE TITLE
'LZ4_MAX_INPUT_VALUE' was not declared

### ISSUE THREAD

**Issue by yaohanlan** [lz4/lz4#466]
the interface 'LZ4_compress_default' has "srcSize : supported max value is LZ4_MAX_INPUT_VALUE",
but I can not find the define. is it replaced by "LZ4_MAX_INPUT_SIZE"?

**Comment by Cyan4973** [comment]
[Yes](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L156

**Comment by yaohanlan** [comment]
please update the description.
