### ISSUE TITLE
Unpacked attribute unsupported on Intel/Windows

### ISSUE THREAD

**Issue by mathstuf** [lz4/lz4#468]
We've received [a report](https://gitlab.kitware.com/vtk/vtk/issues/17239) about lz4 not compiling with Intel's compiler on Windows due to `FORCE_MEMORY_ACCESS` not being selected properly. On Windows, the Intel compiler acts closer to MSVC than GCC, so the check should probably also require `!defined(_WIN32)` in the Intel branch when trying to use option 1.

**Comment by mathstuf** [comment]
Some research shows a mention in [this SO answer](https://stackoverflow.com/questions/1537964/visual-c-equivalent-of-gccs-attribute-packed/9504047#9504047) that Intel on Windows uses `__pragma(pack)` for this stuff, so it should be excluded it seems.

**Comment by Cyan4973** [comment]
Thanks for the patch @mathstuf !
Indeed, one needs an Intel Compiler on Windows to test this out.
A pity we can't (yet) automate that test within our automated CI suite.
