### ISSUE TITLE
Question: double buffer and block smaller than 64k

### ISSUE THREAD

**Issue by MiloszKrajewski** [lz4/lz4#473]
Hi,

I'm trying to understand streaming/decompression of blocks smaller than 64k.
I'm trying to write decoder with double buffer and I'm not sure if I understand it right.

Let's say compressed stream says maximum buffer size is 64k, so I allocate 2 x 64k buffers. 
Let's say first block is 64k and decompressed it to buffer A. Then the second block comes and it is NOT full 64k (let's say it is just 1024 bytes). I decompress it to buffer B. Now Third block comes and it is 64k again. I can write it to buffer A, of course, but buffer B contains ONLY 1024 bytes of "previously decompressed" data.

The question is: do I need to combine this 1024 bytes and previous (64k - 1024) and save it in some contiguous space somehow or I can assume that this new 64k block depends on previous block ONLY (1024 bytes in this case)?

**Comment by Cyan4973** [comment]
The `LZ4_compress_fast_continue()` interface features some side effects which can be difficult to master. In particular, it can "join" contiguous blocks, and then treat them as if they were a single block, which can make a difference for small (< 64KB) blocks.

If you want to avoid side effect related to "joining contiguous blocks",
I recommend you make sure both buffers are separated.
A distance of a single byte is enough.

This way, next block _only_ depends on previous block.

**Comment by MiloszKrajewski** [comment]
But this is only when I control both compression and decompression. When assuming no knowledge about compressor, decompression may depend on many (!) previous blocks, as there is a change they have been joined during compression.
Therefore: flipping buffers like I described above is not an universal strategy. Using ring buffer is not either, as small block just after ring buffer wrapped around, would leave dictionary in invalid state, part of it is on the end of ring buffer and tail of dictionary is on beginning of ring buffer.

I will write next part as statement, but it is more like a question, I'm just looking for confirmation of my understanding:

"Universal" decoder based on ring buffer would:
1) work fine with large (>=64k) blocks, as next blocks depend on just one previous block, and "wrapping around" ring buffer is not a problem (and no special actions are needed) as long as buffer is bigger than 64k + blocksize + 8
2) with smaller blocks of unknown origin (may have been merged) the universal/safe approach would be to copy 64k from end of ring buffer to beginning of ring and buffer and decompress block after that. Bigger ring buffer is, less copying needed.

**Comment by Cyan4973** [comment]
Yes.
_If you don't control the compression side_, you have to assume that __up to 64KB__ of previously decoded data will be needed to decompress next block.

Strategies to "keep" previous 64KB can vary, there are multiple possible solutions.
The 2 ones you mention look fine.
`64k + blocksize + 8` works fine in ring buffer mode too.

**Comment by MiloszKrajewski** [comment]
Still trying to confirm what I understand:

`Prefix64k` mode may provide better result than `ExtDict` as it is possible that reused sequence spans across previous 64k and current block?

**Comment by Cyan4973** [comment]
Yes, prefix mode will then "combine" multiple contiguous blocks as a single "past prefix" for next block.
So it increases compression efficiency for next block.
