### ISSUE TITLE
Question: LZ4_MEMORY_USAGE

### ISSUE THREAD

**Issue by KyleJHarper** [lz4/lz4#489]
Hello Yann et al.,

My apologies if there's a better avenue to post this type of question.

In lz4.h there's a variable called LZ4_MEMORY_USAGE and the description is as follows:
```C
/*!
 * LZ4_MEMORY_USAGE :
 * Memory usage formula : N->2^N Bytes (examples : 10 -> 1KB; 12 -> 4KB ; 16 -> 64KB; 20 -> 1MB; etc.)
 * Increasing memory usage improves compression ratio
 * Reduced memory usage may improve speed, thanks to cache effect
 * Default value is 14, for 16KB, which nicely fits into Intel x86 L1 cache
 */
```

Ignoring L1 cache limitations and the subsequent cache-misses we'd endure, does the memory used affect the bytes/sec performance?  In other words, does lz4 have to do additional work with a larger setting and therefore slow down as a result?  Or is it simply greater (potential) compression ratio at the cost of just memory?

Thanks,
Kyle

**Comment by Cyan4973** [comment]
With larger tables, it increases the odd of `lz4` finding a match, which improved compression ratio.
There is a limit though : this is still a "single sample per position" strategy, so it can't find the 3rd match which would have been better. To get beyond that, one needs `lz4hc`.

If there was no cache effect, it would only be just that : more memory for more compression ratio.

But we can't ignore cache effect. When table size is increased, it mechanically translates into cache misses, which cost some performance, noticeably.

**Comment by KyleJHarper** [comment]
Perfectly understandable.  And I agree, we can't ignore cache in the real world; I was merely wondering if it was more instructions for lz4 logic.  I believe you answered everything :)

Thanks my friend!

**Comment by KyleJHarper** [comment]
My apologies, I forgot to close.  Thanks again for the info!
