### ISSUE TITLE
Question: get better compression ratio

### ISSUE THREAD

**Issue by EdvardD** [lz4/lz4#491]
I tried lz4 console utility and it gives me good compression ratio at levels start from 3 and higher:
`size: 2.43G`
`level: 1 rate: 41.79% compression_time: 21.76s decompression_time: 2.29s`
`level: 2 rate: 41.79% compression_time: 18.77s decompression_time: 2.51s`
`level: 3 rate: 33.35% compression_time: 31.26s decompression_time: 2.3s`
`level: 4 rate: 32.96% compression_time: 37.38s decompression_time: 2.31s`
`level: 5 rate: 32.8% compression_time: 44.76s decompression_time: 2.27s`
`level: 6 rate: 32.71% compression_time: 54.99s decompression_time: 2.31s`
`level: 7 rate: 32.63% compression_time: 72.66s decompression_time: 2.38s`

I also tried to use lz4 lib in C++ on the same data and got:
`rate: 42.0262 compression_time: 10.3973 decompression_time: 2.24998`

Is there any possibility to get the same behaviour as with utility? So I wanna change compression level while use lz4 lib in C++.

**Comment by Cyan4973** [comment]
I suspect you used the _fast_ compression variant, in `lz4.h`,
where the parameter is not a compression level, but an _acceleration_ value.

The higher _acceleration_ is, the faster the compression, and the lower the compression ratio.
See function documentation in https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L170

The high compression variant is exposed in `lz4hc.h`.
See https://github.com/lz4/lz4/blob/dev/lib/lz4hc.h#L56 .

**Comment by EdvardD** [comment]
You are right. Thanks!
