### ISSUE TITLE
LZ4F_compressUpdate fails

### ISSUE THREAD

**Issue by bjornar-s** [lz4/lz4#498]
LZ4F_compressUpdate fails with dest buffer too small yet buffer is LZ4F_compressBound + LZ4_HEADER_SIZE + LZ4_FOOTER_SIZE.
Attached failing source data.

[failing_block.txt](https://github.com/lz4/lz4/files/1906363/failing_block.txt)

**Comment by Cyan4973** [comment]
Do you flush your data in between, 
or is it passed to `LZ4F_compressUpdate()` as a single block ?

**Comment by bjornar-s** [comment]
Nope, sorry, found the problem, I was using that same LZ4F_compressBound retvalue for the input also, a couple bytes to many ... :-0
