### ISSUE TITLE
the 1.8.1 shortcut slows down decompress_fast

### ISSUE THREAD

**Issue by svpv** [lz4/lz4#506]
The shortcut introduced in cc4a109b0df7d12cfd0f26960ba3548d9b7915ba only benefits the `decompress_safe` routines, but slows down the `decompress_fast` routines (this is because the input length is not known, so the condition `ip + ... <= iend` never holds). In fact, `decompress_fast` is now **slower by about 9%** than `decompress_safe`. And if you remove the shortcut from `decompress_fast`, but keep the shortcut in `decompress_safe`, the latter is still faster. At least with the kind of data I'm using. If the same holds true for other kinds of data, this may leave no chance for the `decompress_fast` family after all.

**Comment by Cyan4973** [comment]
I confirm the issue.
Using latest `dev` branch and test program `fullbench`, I measure on my laptop : 
```
 4-LZ4_decompress_safe           : 211948032 ->  2518.2 MB/s
```
versus
```
 1-LZ4_decompress_fast           : 211948032 ->  2302.9 MB/s
```

Your analysis is also spot on : the shortcut is effectively disabled for `_fast` variant, due to input size being unknown.

In feature branch `fasterFastDec`, I simply enabled the shortcut for `_fast` variant, by setting input size arbitrarily to `LZ4_compressBound(originalSize)`. It seems to work : 
```
 1-LZ4_decompress_fast           : 211948032 ->  2573.6 MB/s
```
Now the `_fast` variant is once again faster, if only by very little.

Generally speaking, we don't recommend the `_fast` variant, due to security concerns.
The only valid scenario is when data can be "trusted", which is generally limited to data being produced and consumed on the same machine.

**Comment by svpv** [comment]
Oh, I didn't realize that the shortcut could be enabled in the `decompress_fast` mode, exactly because the input size is unknown and assumptions about the size can work to our advantage. So indeed the code works faster on the `fasterFastDec` branch.  Although still not as fast as `decompress_safe`, with the kind of data that I'm using.

However, there seems to be a better way out.  If we can make assumptions about the input size which work to our advantage, we can further eliminate the input size check altogether, by propagating the `safeDecode` constant:
```c
        if ((safeDecode ? (ip + 14 /*maxLL*/ + 2 /*offset*/ <= iend) : 1)
          &               (op + 14 /*maxLL*/ + 18 /*maxML*/ <= oend)
          & ((token < (15<<ML_BITS)) & ((token & ML_MASK) != 15)) ) {
```
**However**, this `safeDecode` constant that should be eliminated at compile time, it seems to interfere somehow with the `decompress_safe` case, which now works slightly slower. I found that it helps to spell out the expressions as directly as possible, using the constant to be propagated as the outer condition:
```c
        int shortcut;
        if (safeDecode)
            shortcut = (ip + 14 /*maxLL*/ + 2 /*offset*/ <= iend)
                     & (op + 14 /*maxLL*/ + 18 /*maxML*/ <= oend)
                     & (token < (15<<ML_BITS)) & ((token & ML_MASK) != 15);
        else
            shortcut = (op + 14 /*maxLL*/ + 18 /*maxML*/ <= oend)
                     & (token < (15<<ML_BITS)) & ((token & ML_MASK) != 15);
        if (shortcut) {
```
But you should please check for yourself.  I'm using gcc-7 on x86_64 GNU/Linux.

**Comment by Cyan4973** [comment]
Unfortunately, there is a problem with enabling the shortcut for `decompress_fast`.

`decompress_fast` doesn't guarantee anything if the input is malformed. But it's supposed to work properly  if input is valid.

Input buffer size can be anything, though obviously, it must have at least the size of the compressed block. Which means, it can be _exactly_ the compressed size.
Hence, _if input is a valid LZ4 compressed block_, then `decompress_fast` shall ___not___ read input beyond compressed size.

Incidentally, that's the reason why end-of-block parsing restrictions exist.
Now, let's look at the worst case : 
- last five bytes must be literals
- last sequence starts with a one-byte token (total 6-bytes)
- penultimate sequence must specify at least a 2-bytes offset (total 8-bytes)
Hence, penultimate sequence has enough room to blindly copy 8-bytes literals from input (even if none is needed after all).

But not enough room to blindly copy 16 bytes from input.
And unfortunately, that's exactly what the shortcut is doing.

Without any information on input buffer size, unfortunately, there's no way to trigger the shortcut while preserving existing guarantees.

So I guess the only remaining option is to remove the shortcut entirely in "fast" mode.
And I suspect it also means that, for many cases, the "fast" mode will no longer be the fastest.

**Comment by Cyan4973** [comment]
In branch [`decFast`](https://github.com/lz4/lz4/tree/decFast),
there is a new patch 
which sole purpose is to remove the shortcut when `decompress_fast()` is selected.

As far as I can tell, it seems enough to make `decompress_fast()` faster than `decompress_safe()` on `gcc`, and about the same speed on `clang`.

**Comment by svpv** [comment]
Hmm, `decompress_fast` can read its input liberally as long as it feels there's enough output to produce.  So the logic of the `safe` shortcut is: there must be enough input bytes and enough output capacity.  The logic of the `fast` shortcut: as long as there's enough output to fill, valid input can't be exhausted too soon.  So I believe your example doesn't qualify, because the constraint on the output `op + 14 + 18 <= end` won't allow the penultimate token to enter the shortcut. But we better work out the tight bound when this is possible and when not.

**Comment by svpv** [comment]
So, what's the worst case, when we think that there's still a lot of output to produce, but in fact it takes only a few input bytes to produce all the output, so we must already be very careful not to read past the input?

Let's consider the situation where we need to copy 16 bytes without reading past the input. In the worst case, there will be the minimum number of literals, namely: the token we're copying from will have 0 literals, and the last token will have 5 literals. This leaves `16 - 5 - /* last token */ 1 - /* this offset */ 2 = 8` free bytes.
```
m|off|. . . . . . . .|m|1 2 3 4 5
 ^
 |1 2 3 4 5 6 7 8 9 a b c d e f g
 start copying 16 bytes from here
```
Now how many output can 8 bytes produce?  The most efficient method to flood the output is to use one more token with a big match length.  The maximum match length of such a token is $4+15+4\cdot255+254=1293$, and there's also 5 last literals.

Now, how do we step from here to the tight bound, and what the shortcut check `op + N <= oend` should be? :smile:

**Comment by Cyan4973** [comment]
I don't think it's worthwhile to pursue.
The shortcut doesn't bring much benefit to `LZ4_decompress_fast()`, even when it's forcefully enabled.
So that feels too much complexity for too small a benefit.

**Comment by Cyan4973** [comment]
Merged patch improving performance of `decompress_fast()`.
