### ISSUE TITLE
The Download Insight sensitivity level does not allow this file.

### ISSUE THREAD

**Issue by iga1976** [lz4/lz4#539]
Symantec Endpoint Protection complains about the exe and dll of the release 1.8.2 and sends them in quarantine. Can you do something to fix the issue?
![sep_download_insight](https://user-images.githubusercontent.com/15953166/40176048-ac258cb2-59e2-11e8-960a-4840a1ee5217.png)

**Comment by Cyan4973** [comment]
Surprising, that's really the first time I see such an issue.

Did you download the exe files from the "release" page ?
They are generated automatically from appveyor CI, using mingw64.
Maybe Symantec is extra cautious, and just doesn't trust non-signed binaries ?

**Comment by iga1976** [comment]
You asked some questions. I don't know the answers. And I cannot spend time on this. I am just using the product as it is. It's your interest to address it or not. Or, skip this.
