### ISSUE TITLE
add isLittleEndian test to optional define

### ISSUE THREAD

**Issue by irov** [lz4/lz4#544]
like that LZ4_FORCE_MEMORY_LITTLE_ENDIAN

and code
#ifdef LZ4_FORCE_MEMORY_LITTLE_ENDIAN
#define LZ4_readLE16 LZ4_read16
#else
static U16 LZ4_readLE16(const void* memPtr)
{
    if (LZ4_isLittleEndian()) {
        return LZ4_read16(memPtr);
    } else {
        const BYTE* p = (const BYTE*)memPtr;
        return (U16)((U16)p[0] + (p[1]<<8));
    }
}
#endif

Thanks!

**Comment by terrelln** [comment]
@irov why do you need this? Even the oldest compilers should be able to figure out that `LZ4_isLittleEndian()` is a constant expression and remove the dead code in the opposite branch https://godbolt.org/g/562P4g.

**Comment by irov** [comment]
You are right, I spend a lot of time in Debug mode, and decided to optimize this a little.

**Comment by Cyan4973** [comment]
We have no plan to add another build macro and associated preprocessor instructions
for the purpose of improving runtime speed of debug builds.

If this is an important use case for you, you may simply modify the source file, typically by making `LZ4_isLittleEndian()` a constant.
