### ISSUE TITLE
Support for --no-stdout type argument

### ISSUE THREAD

**Issue by norbusan** [lz4/lz4#545]
Dear all,

we want to use lz4 together with other compression programs in TeX Live, and to keep code clean we would prefer a way to compress a file *always* to file.lz4 using only command line options plus file name:
```
  $selected_compressor $compressor_options $file
```
should create `$file.lz4`, as it does with xz, gzip, ...

Unfortunately lz4 tries to guess the mode and sometimes sends the compressed file to stdout (this happens when frontend programs use our installer), instead of generating a file. This is clearly documents in the man page (I just happened to read it too late).

Would it be possible to implement an option negating --stdout, so that the following:
```
  lz4 --rm -z --no-stdout FILE
```
always generates `FILE.lz4` independently from whether stdout is the console or not?

Thanks

Norbert

**Comment by Cyan4973** [comment]
would such an option work for you ?
`lz4 --rm -z FILE FILE.lz4`

This is the original behavior of lz4 : `lz4 src dst`

Later on, it was altered to more closely mimic `gzip` behavior.
For example, this one should also work : 
`lz4 --rm -z FILE -c > FILE.lz4`
or this one : 
`lz4 -m --rm -z FILE`

**Comment by norbusan** [comment]
Hi
thanks for your comment. I am well aware that using lz4 with two arguments will work. The problem is that we support various different compressors, depending on availability and user preference. All but lz4 work in a way that if passed only one argument which is a file, it is compressed, independent of stdout:
```
gzip FILE  # produces FILE.gz
xz FILE     # produces FILE.xz
...
```
unfortunately
```
lz4 FILE
```
depends on stdout. 

To keep the code uniform for all compressors, I would like to see an option that disables the stdout detection method and always work in the style as gzip works.

**Comment by norbusan** [comment]
Ah, wait, ...
```
lz4 -m --rm -z FILE
```
should work? Would that mean that the `-m` is the solution?

**Comment by norbusan** [comment]
Indeed, reading again the man page, `-m` is what I want. Sorry for the noise, closing this bug.
