### ISSUE TITLE
LZ4_compress_xxx_continue documentation confusion

### ISSUE THREAD

**Issue by mxmauro** [lz4/lz4#549]
Hi,

`LZ4_compress_fast_continue` says _Important : The previous 64KB of compressed data is assumed to remain present and unmodified in memory!_. The compressed data is the output but in samples the double/ring buffer is applied on the input.

Which is correct?

Regards,
Mauro.

**Comment by terrelln** [comment]
It should say the input data, not the compressed data.

**Comment by mxmauro** [comment]
Thanks @terrelln for answering. I'll leave the issue opened as a reminder for the developers.
