### ISSUE TITLE
lz4 decompression

### ISSUE THREAD

**Issue by Nitika123** [lz4/lz4#551]
I have compressed the data using https://github.com/lz4/lz4-java and want to decompress it in https://github.com/lz4/lz4. It is not giving me the required results. Is it possible to do so?

**Comment by terrelln** [comment]
The function [LZ4_decompress_safe()](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L149) should work.

**Comment by Cyan4973** [comment]
not sure how metadata (compressed and decompressed sizes) are saved (or not) when using `lz4-java`. It may differ depending on entry point. Probably a question for @odaira .

For compatibility with `LZ4_decompress_safe()`, you want metadata to _not_ be part of compressed data.
