### ISSUE TITLE
Could you please add this new binding to the website?

### ISSUE THREAD

**Issue by marianopeck** [lz4/lz4#554]
Sorry that I am duplicating the request but i got no response on the [forum.](https://groups.google.com/forum/#!topic/lz4c/xtQxwCuF8mY). Maybe I have better luck here....

Maybe the person to contact is @t-mat ?

Thanks in advance and thanks for this wonderful library.

**Comment by Cyan4973** [comment]
Hi @marianopeck 

Sorry, I thought it was already done, but I apparently was confused with the recent smalltalk zstd binding also from Instantiations.

Also : I went to the proposed link, but I could not find any link nor any mention of some LZ4 source code to download. Could you provide a more specific link ?

Last, there is already an LZ4 smalltalk binding registered at : 

Language | Author | URL
| --- | --- | --- |
| Smalltalk (Pharo) | Mariano Martinez Peck | http://smalltalkhub.com/#!/~marianopeck/LZ4/ |

Does the new binging supercede this older one ?

**Comment by marianopeck** [comment]
Hi @Cyan4973 

No worries, thanks for your answer. And yes, we also asked about ZStandard :)

The new binding does not supercede (although it is way better and more complete) the old one for Pharo Smalltalk. For the link, I would still like to have https://www.instantiations.com/products/vasmalltalk/. The binding comes already shipped with our product (VA Smalltalk) and we don't have a separate link/page for the LZ4 binding. For example, in [this link](https://www.instantiations.com/products/vasmalltalk/whatsnew.html) you can see we mention the LZ4 binding.  But again, we believe it's better the more generic link to VA Smalltalk. 

I would let the Smalltalk (Pharo) row as it is and I would just add this one new with:

Smalltalk (VA Smalltalk ) | Instantiations | https://www.instantiations.com/products/vasmalltalk/

Could that be possible?

**Comment by Cyan4973** [comment]
The bindings section is so far reserved to self-contained LZ4 bindings, that people can download and use freely in their own projects.

If the LZ4 binding is part of a larger product suite, from which it cannot be separated,
it can still be added, to the [references](https://lz4.github.io/lz4/#references) section.

**Comment by marianopeck** [comment]
Hi @Cyan4973 

I understand what you mean but I am not sure the conclusion. Technically speaking, it's a binding/wrapper so that from VA Smalltalk we call the LZ4 C library via a FFI. On top of that we also added support for Smalltalk stream  classes etc... 

Now...as how it is shipped, we simply choose to make it as part of the core language (VA Smalltalk). Imagine as if  the Java SDK, or Python, or .NET or whatever would come directly with a LZ4 binding in its core libraries (loaded by default). 

Any people that download VA Smalltalk would have the LZ4 binding already loaded (obviously they can unload it too). As this binding is fairly new for VA Smalltalk the documentation is a bit spare on the web. See [this link](http://www.instantiations.com/docs/91/wwhelp/wwhimpl/js/html/wwhelp.htm#href=pr/compression1.html).

The only difference with ZStandard (from VA Smalltalk point of view) is that this one is not part of the core and lives on a repository to which people can connect and download it. 

Does this clarify something?

**Comment by Cyan4973** [comment]
Thanks for the link @marianopeck,
I think I can use it and add the binding to the list

**Comment by marianopeck** [comment]
Thanks @Cyan4973 !
