### ISSUE TITLE
verbose output, showing completed time incorrectly it seems if I am not mistaken.

### ISSUE THREAD

**Issue by xekon** [lz4/lz4#555]
I am running Ubuntu 18.04 and lz4 was installed like so:
sudo apt-get install liblz4-tool

I have been experimenting with different ways of performing backups quicker.

originally I used:
sudo dd if=/dev/sda1 bs=8M | gzip -1 - | dd of=gvsip.gz status=progress

now I am trying out this:
sudo e2image -ar /dev/sda1 - | lz4 -v > `date +%F`.raw.e2image.lz4

when the command completes it reports:

```
sudo e2image -ar /dev/sda1 - | lz4 -v > `date +%F`.raw.e2image.lz4
e2image 1.44.1 (24-Mar-2018)
*** LZ4 command line interface 64-bits r128, by Yann Collet (Apr  3 2018) ***
Blocks size : 4096 KB
Using stdin for input
Using stdout for output
Sparse File Support is automatically disabled on stdout ; try --sparse 
Compressed 6999244800 bytes into 891785059 bytes ==> 12.74%                    
Completed in 18.81 sec
```

However I watched the second counter on the clock in my system tray, and it actually took approximately 34 seconds from the time I hit enter.

34 seconds is actually the fastest way I have found of creating a compressed backup image, so I am very happy about that! However I thought I should point this error out.

**Comment by Cyan4973** [comment]
Thanks for pointing that out @xekon .

`lz4io.c`, which is responsible for I/O pipe and file operations, track elapsed time using the function [`clock()`](https://www.tutorialspoint.com/c_standard_library/c_function_clock.htm) from the [C Standard Library](https://en.wikipedia.org/wiki/C_standard_library) [`time.h`](https://en.wikipedia.org/wiki/C_date_and_time_functions).

This function has already failed me in the past, when used in conjunction with multi-threading : it would report the total amount of time spent executing the program, adding the time from each thread.
My current understanding is that `clock()` doesn't seem to really track the time, rather, it seems to track the _execution time_.

In which case, it could explain the behavior you observed : if the `lz4` process is fast enough, it may actually be waiting for input data, using less than one core. And waiting time is effectively excluded. 

If it matters, we could probably fix this issue by using time function from our own wrapper [util.h](https://github.com/lz4/lz4/blob/dev/programs/util.h).

**Comment by scheff173** [comment]
@Cyan4973 

> clock() doesn't seem to really track the time, rather, it seems to track the execution time.

You may replace "seems to" with "does". ;-) IMHO, a better doc. can be found e.g. in cppreference.com [`clock()`](https://en.cppreference.com/w/c/chrono/clock):

> **clock** time may advance faster or slower than the wall clock, depending on the execution resources given to the program by the operating system. For example, if the CPU is shared by other processes, **clock** time may advance slower than wall clock. On the other hand, if the current process is multithreaded and more than one execution core is available, **clock** time may advance faster than wall clock.

**Comment by Cyan4973** [comment]
Measuring elapsed time is fixed in `dev` branch.
I used this opportunity to also introduce a `cpu load` indicator, so that one can know if the observed speed is primarily cpu or I/O driven.

Minor detail : 
in order to output elapsed time when using `lz4`, I had to use command `-vv`, not `-v` as reported above.
