### ISSUE TITLE
Is there some way to automatically generate a dictionary?

### ISSUE THREAD

**Issue by ironwallaby** [lz4/lz4#561]
Hello!

I noticed that `zstd` has a method of [automatically generating a dictionary from a set of data files](https://github.com/facebook/zstd#dictionary-compression-how-to). Is there some similar automated way to generate a dictionary from a dataset in `lz4`? (Ideally, I'd love to be able to do this from C, rather than from the command line, but I'll take whatever I can get!)

If not, can you give me some insight into an algorithm that can generate an efficient dictionary for a given dataset?

Thank you!

**Comment by Cyan4973** [comment]
`lz4` recommends using the dictionary generator of `zstd`. 
Just limit its size to 64KB, using command `--maxdict=#`.
`zstd` dictionary generator is also available through a C API, exposed in `zdict.h`.

**Comment by ironwallaby** [comment]
Perfect, I had missed that. Thank you!
