### ISSUE TITLE
Is there any possible to introduce partially decompression to lz4 library?

### ISSUE THREAD

**Issue by hsiangkao** [lz4/lz4#566]
Hi,
We introduced a new read-only file system EROFS with compression support to the Linux kernel.

In order to enhance the random read and reduce the memory overhead for the file system, we introduce partially decompression at head in byte-unit (stop decompression at the arbitrary position,not just as sequence-unit like LZ4_decompress_safe_partial but byte-unit since there is no extra memory to use LZ4_decompress_safe_partial).

LINK: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/staging/erofs/unzip_lz4.c#n52
which is not the optimal implementation, so is there possible to support this feature in the official LZ4 library?

Therefore I could use it in the Linux kernel directly...

Thanks in advance.

Thanks,
Gao Xiang

**Comment by Cyan4973** [comment]
Hi @hsiangkao ,

this is interesting,
so far we received no strong request to develop this exact feature,
and the general feeling was that it could add some unwanted load right into the critical loop, reducing decompression performance.

That being said, this wasn't investigated thoroughly, and there might be ways to hide the performance issue.

**Comment by Cyan4973** [comment]
In branch `partialDecode`, you'll find an experimental source code providing the requested feature.

It's accessible through existing function `LZ4_decompress_safe_partial()`, which now offers the guarantee to never write beyond `targetOutputSize` bytes.
The function signature remains identical, in order to not break API (yes, there are users of this function).

**Comment by Cyan4973** [comment]
merged into `dev`

**Comment by hsiangkao** [comment]
Thanks Cyan, I will look into that. :+1 : )
and I think some performance optimization paths could be implemented later, it will reduce compression file system extra memory overhead as much as possible :)

Thanks,
Gao Xiang

**Comment by hsiangkao** [comment]
@Cyan4973,

(continued...)
I mean at least we could add a new API, and do some further customized optimization paths for exactly the nb of bytes requested.
I am looking into the latest code and port to the linux kernel to remove my hacked code (unzip_vle_lz4.c).

Thanks,
Gao Xiang
