### ISSUE TITLE
New "interoperable LZ4 port" for .NET Standard 1.6+

### ISSUE THREAD

**Issue by MiloszKrajewski** [lz4/lz4#568]
Hi Yann,

I'm not sure if this is the best place to put it ("issues") but I would like to ask you to link my new "interoperable LZ4 port" for .NET Standard 1.6+ (which includes .NET Core 1.0, .NET Framework 4.6, Mono, Xamarin and UWP) from LZ4 website. It replaces (also mine) lz4net.

Thanks,
Milosz Krajewski

**Comment by Cyan4973** [comment]
Sure @MiloszKrajewski ! Great work !
Your version is added : https://lz4.github.io/lz4/#interoperable-lz4.
