### ISSUE TITLE
Please consider meson as the build system

### ISSUE THREAD

**Issue by nacho** [lz4/lz4#582]
Quite a few projects are getting ported to meson (most of gnome is already ported, X, wayland and many others), mainly because it is easier to maintain than plain makefiles or cmake projects and supports most of the platforms out there.

**Comment by Cyan4973** [comment]
I do not plan moving away from `Makefile`.

That being said, it's perfectly possible for a community-maintained Meson build package to be hosted inside the LZ4 reference repository, the same way [one currently exists for zstd](https://github.com/facebook/zstd/tree/dev/contrib/meson).
If you are willing to write such a script, you are welcomed !

**Comment by nacho** [comment]
sounds good, I'll try to come up with it when I have time. Thanks!
