### ISSUE TITLE
Feature Request: discard cache

### ISSUE THREAD

**Issue by iyokan** [lz4/lz4#585]
lz4's INPUT-FILE and OUTPUT-FILE is usually big and accessed sequential.  So more useful cached pages are discarded.  I am using local patch as follows:

```
diff --git a/programs/lz4io.c b/programs/lz4io.c
index cdc4c27..9c6c8b2 100644
--- a/programs/lz4io.c
+++ b/programs/lz4io.c
@@ -53,6 +53,7 @@
 #include <time.h>      /* clock */
 #include <sys/types.h> /* stat64 */
 #include <sys/stat.h>  /* stat64 */
+#include <fcntl.h>     /* posix_fadvise */
 #include "lz4io.h"
 #include "lz4.h"       /* still required for legacy format */
 #include "lz4hc.h"     /* still required for legacy format */
@@ -618,6 +619,10 @@ static int LZ4IO_compressFilename_extRess(cRess_t ress, const char* srcFileName,
             /* Read next block */
             readSize  = fread(srcBuffer, (size_t)1, (size_t)blockSize, srcFile);
             filesize += readSize;
+
+            /* free cached pages */
+            posix_fadvise(fileno(srcFile), 0, ftell(srcFile), POSIX_FADV_DONTNEED);
+            posix_fadvise(fileno(dstFile), 0, 0             , POSIX_FADV_DONTNEED);
         }
         if (ferror(srcFile)) EXM_THROW(37, "Error reading %s ", srcFileName);

@@ -630,6 +635,10 @@ static int LZ4IO_compressFilename_extRess(cRess_t ress, const char* srcFileName,
         compressedfilesize += headerSize;
     }

+    /* Release cache */
+    fsync (fileno(dstFile));
+    posix_fadvise (fileno(dstFile), 0, 0, POSIX_FADV_DONTNEED);
+
     /* Release files */
     fclose (srcFile);
     fclose (dstFile);
```

Colud you please considering this feature?

**Comment by Cyan4973** [comment]
HI @iyokan ,
thanks for your suggestion.

As a preamble, I respectfully disagree with the primary statement that "OUTPUT-FILE is usually big" : this is clearly not my experience. Good news : your patch doesn't need this condition to be useful.
Even if the file is "sometimes/rarely" big, it seems like a nice idea to preserve cache memory, especially if the file is not going to be accessed again after compression.

Note that it can be hard to know if the file is going to be accessed again after compression. It's a wild guess, that could prove wrong in a number a cases.
This introduces a new requirement : such active cache eviction should be controllable, in some way, by user. 
As you can guess, it makes the patch a bit more complex.

But there is more.
The main issue with this patch is that it relies on functions which are not portable (as in : not part of standard C libraries). They belong to posix environment, which is a subset of environments that LZ4 can run on. Even then, from a quick look at documentation, this interface seems to feature subtle differences depending on exact posix version.

I'm not saying that it's not possible, as we already support posix functions.
But adding such dependency must be done with great care.
It must be enabled only when we can detect and be sure that linking stage will work.
We must define and enforce a clean behavior when it's not available.
So it's more than just adding a few lines.

Still, it's an interesting suggestion.
So I'll keep this feature request opened. We'll try to look at it and possibly implement it when time permits.

**Comment by iyokan** [comment]
Thank you for considering the feature.

To be honest OUTPUT-FILE is not matter with my workload.
I am using lz4 for virtual machine image backup as follows:
```
backup% ssh host lvcreate -s -n snap0 -L 20g /dev/vg0/lv0
backup% ssh host lz4 -c -v /dev/vg0/snap0 > snap.lz4
backup% ssh host lvremove /dev/vg0/snap0
```
Under this operation the qemu-kvm process runnning on host swaps out.
Setting `vm.swappiness = 1` does not solve the problem.
O_DIRECT can't be use with fopen.  So I use fadvise.

**Comment by felixhandte** [comment]
Yeah, I don't think there's a perfectly portable way to implement this. So it would have to be gated.

One alternative would be to pipe data into and out of lz4 with something that understands `O_DIRECT`. E.g., `dd iflag=direct bs=4M ... | lz4 ... | dd oflag=direct bs=4M ...`. Might be worth a shot?

**Comment by bwsw** [comment]
@felixhandte It works that way, but the compression is slower than with bare LZ4, though.

**Comment by Cyan4973** [comment]
I remember testing `lz4` many years ago with some kind of "no-cache-please" order, with the same objective to not pollute the cache.
It would always end up being slower than the "normal" version, sometimes quite substantially.
So I abandoned this direction.

When I say "many years ago", I mean it : it was on Windows, using win32 api, storage was a physical spin disk, I'm not even sure if `lz4` was open source yet. So many things have changed since, it could make the result different.

Nonetheless, it's a reference point. Due to this past experience, I would not expect `lz4` without FS cache to work faster than with cache. I'm rather wondering how much the loss will be.

**Comment by Cyan4973** [comment]
This is an unpromising direction.
One would need some substantial positive measurements to ensure it's bringing a tangible benefit to the table, given the risky nature of the change (with regards to portability and link stage).
