### ISSUE TITLE
LZ4 Frame format specification

### ISSUE THREAD

**Issue by MiloszKrajewski** [lz4/lz4#591]
Specification can be found in two places:
1) doc (https://github.com/lz4/lz4/blob/master/doc/lz4_Frame_format.md)
2) wiki (https://github.com/lz4/lz4/wiki/lz4_Frame_format.md)

The problem is that wiki one is the one returned by googling "LZ4 Frame format". I was a little bit surprised that "dictionary id" has been removed from header. Surprised or not, I've seen it with my own eyes: "it is not longer there". So I removed it from my implementation...

Today I found out that google takes you to wrong one and I need to do a emergency release :-)

**Comment by Cyan4973** [comment]
Sorry for the misunderstanding @MiloszKrajewski .
Indeed, I completely forgot that page, and it's no longer up to date.
It will be better remove it entirely, 
or at least link it to the official specification within `/doc` directory, 
so that a single source of truth remains.

**Comment by Cyan4973** [comment]
The wiki page now redirects to the source of truth in repository.
Thanks for reporting the discrepancy !
