### ISSUE TITLE
LZ4F_decompress() documentation improvement

### ISSUE THREAD

**Issue by andysworkshop** [lz4/lz4#597]
[This line](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.h#L403) states that `LZ4F_isError()` can be used on the return value. It cannot without first checking that the value is `<0`. The documentation should state that the user should first do that.

This is because `LZ4F_isError()` effectively only does `return code > -20`. The caller must first establish that they have a negative code to begin with.

**Comment by Cyan4973** [comment]
The return type of these functions is a `size_t`.
A `size_t` is unsigned, so it cannot be negative.

`LZ4F_isError()` only works properly if you preserve the original `size_t` type.

If the return value is casted to `int` before that stage, you end up with the problem described in the question : error values become negative.
