### ISSUE TITLE
[Feature] list an archive content with --list

### ISSUE THREAD

**Issue by stokito** [lz4/lz4#598]
Almost all compressors allows to see the archive contents without of full extracting:
```
$ gzip --help | grep list
  -l, --list        list compressed file contents
```
This allows to see a real uncompressed file size, the original file name, the original modify time and extremely useful for archive manages to show this information for a user.

For example I archived with `lzop` the file `Original File Name.txt` and then listed it's contents:
```
$ lzop -lvN archive.lzo 
Method         Length    Packed  Ratio     Date    Time   Name
------         ------    ------  -----     ----    ----   ----
LZO1X-1       3454395   1287345  37.3%  2018-10-31 05:53  Original File Name.txt
```

So I wanted to add `lz4` support to the `engrampa` (from Mate Desktop)  and to the `File Roller` (from Gnome)  archive managers and wanted to use the `-l` option but it turned out that

```
 -l     : compress using Legacy format (Linux kernel compression)
```

And it looks like no any option to just see an archive content.
So my question is:
1. Which meta information about the original file lz4 does preserve? 
 * Can we see uncompressed size (looks like with `--content-size` this information is stored) and which maximum size can be shown (e.g. gzip can't show sizes more that 4Gib).
* modification date and time and does it contains time zone info
* permissions
* file name - and it can be non ASCII and contains some special characters and even new line symbol `\n`
* MIME content type
2. Is any possibility to add the `--list` option?

**Comment by stokito** [comment]
The similar request I added to Zstandard https://github.com/facebook/zstd/issues/1402 and there was some related discussion with propose to use the `tar` program but that's not a convenient solution for several reasons.

**Comment by Cyan4973** [comment]
It's possible to add a `--list` option in the future.
But it won't list all the things you mention.

In particular, it won't save any filename.
Filename is assumed to be either given during decompression, or derived from compressed name.
Permissions and date/time might be saved directly in the compressed file metadata.
`--list` is not expected to mention these metadata, because they are not necessarily representative of original file (they might have been altered after compression).

That basically leaves " uncompressed size ", and with it compression ratio, on top of a few lz4 specific options (block size, checksum, etc.) that may not be of interest to you.

LZ4 is indeed expected to be combined with `tar` or with any other archiver that takes care of the file structures, such as directory tree, and metadata. Archiver is considered a separate layer.

**Comment by gabrielstedman** [comment]
I had a first go at implementing --retrieve-content-size option still quite rough around the edges.
https://github.com/gabrielstedman/lz4/commit/5a96c7faca8e374d6a38d5dbf94351da134dbdc5

**Comment by Cyan4973** [comment]
The new command `--list` has been added to `lz4 v1.9.1`.

While it works, I don't think it's complete, because it only supports single-frame files.
A more complete implementation should scrub the whole file to support multi-frames files, as well as legacy and skippable frames, and optionally consider a verbose mode (`-v --list`).

So I'm not sure if we can "close" this issue.

**Comment by gabrielstedman** [comment]
Thank you for taking the time to adapt my patch, I'm afraid I still need to improve my C skills quite a lot.
It's been a great learning experience, I'd love to try and implement these improvements, but it's probably better for someone more experienced like yourself for the task.

**Comment by Cyan4973** [comment]
Nothing comes "magically", it's only through regular effort and exposure that one gets better at programming, for any language.
I'm happy to help / guide any future patch on the matter, even if only for learning purposes. If it was not for the pressure to issue a release soon enough, I would have let you complete this one, providing more hints whenever needed.

**Comment by stokito** [comment]
I tested the new version (BTW Ubuntu has some old version 1.8).
By default uncompressed (original) size is not stored and to store it you need to add `content-size` option i.e.
```
$ lz4 -k -9 --content-size file.txt
$ lz4 --list file.txt.lz4
Block   Compressed     Uncompressed      Ratio    Check  Filename
  B7I    429447                                     -             -   XXH32  file.txt.lz4 
```
And this  `content-size` option add additional 8 bytes (i.e. long) so archivers may always add it.

> Permissions and date/time might be saved directly in the compressed file metadata.
Could you elaborate on this? For me it's unclear if we can store the permissions. I tried and it looks like during decompression permissions are just copied from archive.

**Comment by gabrielstedman** [comment]
I've made some progress implementing multi-frame support here: https://github.com/gabrielstedman/lz4/commit/6017cc7643dfea6a163a147506b89a11d3a9e35b

It still needs testing and cleaning up, what's the best way to produce skippable frames?

Here is what the output looks like when run with -v:

```
 » /tmp  ~/lz4/lz4 --list -v -m /tmp/*.lz4
*** LZ4 command line interface 64-bits v1.9.1, by Yann Collet ***
Filename:1cs.lz4
Frame:1
Type:LZ4Frame
Block:B4I
Compressed:3369
Check:XXH32
Uncompressed:5534
Ratio:   0.6088

Filename:1leg.lz4
Frame:1
Type:LegacyFrame
Compressed:3350

Filename:1sncs.lz4
Frame:1
Type:LZ4Frame
Block:B4I
Compressed:3361
Check:XXH32

Filename:1zncs1leg1cs.lz4
Frame:1
Type:LZ4Frame
Block:B4I
Compressed:3361
Check:XXH32

Filename:1zncs1leg1cs.lz4
Frame:2
Type:LegacyFrame
Compressed:3350

Filename:1zncs1leg1cs.lz4
Frame:3
Type:LZ4Frame
Block:B4I
Compressed:3369
Check:XXH32
Uncompressed:5534
Ratio:   0.6088

Filename:2sncs.lz4
Frame:1
Type:LZ4Frame
Block:B4I
Compressed:3361
Check:XXH32

Filename:2sncs.lz4
Frame:2
Type:LZ4Frame
Block:B4I
Compressed:3361
Check:XXH32

Filename:rand.lz4
Frame:1
Type:LZ4Frame
Block:B4I
Compressed:22942
Check:-

          Compressed         Uncompressed     Ratio  Filename
                3369                 5534    0.6088  1cs.lz4 
                3350                    -         -  1leg.lz4 
                3361                    -         -  1sncs.lz4 
               10080                    -         -  1zncs1leg1cs.lz4 
                6722                    -         -  2sncs.lz4 
               22942                    -         -  rand.lz4 
```

**Comment by Cyan4973** [comment]
> For me it's unclear if we can store the permissions. I tried and it looks like during decompression permissions are just copied from archive.

That's exactly what happens. Permissions are just transferred from source to compressed file, and then from compressed file to destination file.
There's no permission information stored anywhere in the frame format.

**Comment by Cyan4973** [comment]
@gabrielstedman, that's a nice achievement !

Now, remaining effort is mostly in selecting a presentation.

On this front, I like to look at `xz --list`, or `xz -v --list` for the verbose mode.

For the verbose mode, it starts with a file summary, and then add one line per frame.
For example : 
```concat.xz (2/23)
  Streams:            22
  Blocks:             22
  Compressed size:    1,174.7 KiB (1,202,852 B)
  Uncompressed size:  4,315.7 KiB (4,419,281 B)
  Ratio:              0.272
  Check:              CRC64
  Stream padding:     0 B
  Streams:
    Stream    Blocks      CompOffset    UncompOffset        CompSize      UncompSize  Ratio  Check      Padding
         1         1               0               0         977,708       3,265,536  0.299  CRC64            0
         2         1         977,708       3,265,536           1,012           4,016  0.252  CRC64            0
         3         1         978,720       3,269,552          44,636         112,640  0.396  CRC64            0
         4         1       1,023,356       3,382,192           5,636          12,288  0.459  CRC64            0
         5         1       1,028,992       3,394,480           7,268          16,384  0.444  CRC64            0
         6         1       1,036,260       3,410,864           2,148           4,096  0.524  CRC64            0
         7         1       1,038,408       3,414,960           3,884           8,192  0.474  CRC64            0
         8         1       1,042,292       3,423,152           2,136           4,096  0.521  CRC64            0
         9         1       1,044,428       3,427,248           3,856           8,192  0.471  CRC64            0
        10         1       1,048,284       3,435,440          39,224         112,640  0.348  CRC64            0
        11         1       1,087,508       3,548,080           7,620         112,640  0.068  CRC64            0
        12         1       1,095,128       3,660,720           7,708         112,640  0.068  CRC64            0
        13         1       1,102,836       3,773,360             932           8,795  0.106  CRC64            0
        14         1       1,103,768       3,782,155           1,332          13,292  0.100  CRC64            0
        15         1       1,105,100       3,795,447           2,372          32,787  0.072  CRC64            0
        16         1       1,107,472       3,828,234           8,548         112,640  0.076  CRC64            0
        17         1       1,116,020       3,940,874           8,736         112,640  0.078  CRC64            0
        18         1       1,124,756       4,053,514          10,948          70,855  0.155  CRC64            0
        19         1       1,135,704       4,124,369           9,336         112,640  0.083  CRC64            0
        20         1       1,145,040       4,237,009           6,204          65,536  0.095  CRC64            0
        21         1       1,151,244       4,302,545          49,168         112,640  0.437  CRC64            0
        22         1       1,200,412       4,415,185           2,440           4,096  0.596  CRC64            0
```

Not everything is applicable to `lz4`, so it's only a matter of getting inspiration from.
For example, `lz4` format doesn't define a "padding".
Also, `lz4` defines multiple types of frames, frames often contain multiple blocks, and blocks can be of different type.
Still, information available and to display is relatively close.
So I suspect something "similar enough" could be produced.

**Comment by gabrielstedman** [comment]
Thanks @Cyan4973 I'll look into producing similar output.
What's the best way to generate skippable frames?

**Comment by Cyan4973** [comment]
> What's the best way to generate skippable frames?

Unfortunately, we don't have tools for that.
So it's all manual : push the correct bytes (the specification is relatively simple).

**Comment by gabrielstedman** [comment]
I've done a few changes here: https://github.com/gabrielstedman/lz4/commit/06160df4e89c3ed6f42b2fe9177b38d02672f1a0

Got output like this WDYT?
Still need to test skippable frames if you're happy with the output I'll open a PR as soon as I do.

```
» ~/lz4 (list2*) ./lz4 --list -m testfiles/*.lz4
Compressed  Uncompressed     Ratio  Filename
  3.29 KiB      5.40 KiB    0.6088  1cs.lz4 
  3.27 KiB             -         -  1leg.lz4
  9.84 KiB             -         -  1ncs1leg1cs.lz4
  3.28 KiB             -         -  1sncs.lz4
  6.56 KiB             -         -  2sncs.lz4
 28.86 KiB     68.04 KiB    0.4242  3cs.lz4 
  3.18 GiB      3.30 GiB    0.9659  biglz4.lz4 
 » ~/lz4 (list2*) ./lz4 --list -m -v testfiles/*.lz4
*** LZ4 command line interface 64-bits v1.9.1, by Yann Collet ***
1cs.lz4(1/7)
     Fames           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3369                 5534    0.6088

1leg.lz4(2/7)
     Fames           Type Block Checksum           Compressed         Uncompressed     Ratio
         1    LegacyFrame     -        -                 3350                    -         -

1ncs1leg1cs.lz4(3/7)
     Fames           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3361                    -         -
         2    LegacyFrame     -        -                 3350                    -         -
         3       LZ4Frame   B4I    XXH32                 3369                 5534    0.6088

1sncs.lz4(4/7)
     Fames           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3361                    -         -

2sncs.lz4(5/7)
     Fames           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3361                    -         -
         2       LZ4Frame   B4I    XXH32                 3361                    -         -

3cs.lz4(6/7)
     Fames           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3369                 5534    0.6088
         2       LZ4Frame   B4I    XXH32                 2604                 5199    0.5009
         3       LZ4Frame   B4I    XXH32                23583                58942    0.4001

biglz4.lz4(7/7)
     Fames           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B7I    XXH32           3418158428           3538681856    0.9659


    Compressed  Uncompressed     Ratio  Filename
      3.29 KiB      5.40 KiB    0.6088  1cs.lz4 
      3.27 KiB             -         -  1leg.lz4
      9.84 KiB             -         -  1ncs1leg1cs.lz4
      3.28 KiB             -         -  1sncs.lz4
      6.56 KiB             -         -  2sncs.lz4
     28.86 KiB     68.04 KiB    0.4242  3cs.lz4 
      3.18 GiB      3.30 GiB    0.9659  biglz4.lz4 
```

**Comment by gabrielstedman** [comment]
A few more modifications as per the advice given:

```
» ~/lz4 (list2*) ./lz4 --list -m  testfiles/*.lz4
    Frames           Type Block   Compressed   Uncompressed     Ratio  Filename
         1       LZ4Frame   B7D  1005.10 KiB     250.00 MiB    0.0039  1csbdbx.lz4 
         1       LZ4Frame   B4I     3.29 KiB       5.40 KiB    0.6088  1cs.lz4 
         1    LegacyFrame     -     3.27 KiB              -         -  1leg.lz4
         3              -     -     9.84 KiB              -         -  1ncs1leg1cs.lz4
         1 SkippableFrame     -     108.00 B              -         -  1skippable.lz4
         1       LZ4Frame   B4I     3.28 KiB              -         -  1sncs.lz4
         7              -     -    38.80 KiB              -         -  2sncs1skip1leg3cs.lz4
         2       LZ4Frame   B4I     6.56 KiB              -         -  2sncs.lz4
         3       LZ4Frame   B4I    28.86 KiB      68.04 KiB    0.4242  3cs.lz4 
         1       LZ4Frame   B7I     3.18 GiB       3.30 GiB    0.9659  biglz4.lz4 
 » ~/lz4 (list2*) ./lz4 --list -m -v testfiles/*.lz4
*** LZ4 command line interface 64-bits v1.9.1, by Yann Collet ***
1csbdbx.lz4(1/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B7D    XXH32              1029220            262144000    0.0039

1cs.lz4(2/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3369                 5534    0.6088

1leg.lz4(3/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1    LegacyFrame     -        -                 3350                    -         -

1ncs1leg1cs.lz4(4/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3361                    -         -
         2    LegacyFrame     -        -                 3350                    -         -
         3       LZ4Frame   B4I    XXH32                 3369                 5534    0.6088

1skippable.lz4(5/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1 SkippableFrame     -        -                  108                    -         -

1sncs.lz4(6/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3361                    -         -

2sncs1skip1leg3cs.lz4(7/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3361                    -         -
         2       LZ4Frame   B4I    XXH32                 3361                    -         -
         3 SkippableFrame     -        -                  108                    -         -
         4    LegacyFrame     -        -                 3350                    -         -
         5       LZ4Frame   B4I    XXH32                 3369                 5534    0.6088
         6       LZ4Frame   B4I    XXH32                 2604                 5199    0.5009
         7       LZ4Frame   B4I    XXH32                23583                58942    0.4001

2sncs.lz4(8/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3361                    -         -
         2       LZ4Frame   B4I    XXH32                 3361                    -         -

3cs.lz4(9/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B4I    XXH32                 3369                 5534    0.6088
         2       LZ4Frame   B4I    XXH32                 2604                 5199    0.5009
         3       LZ4Frame   B4I    XXH32                23583                58942    0.4001

biglz4.lz4(10/10)
     Frame           Type Block Checksum           Compressed         Uncompressed     Ratio
         1       LZ4Frame   B7I    XXH32           3418158428           3538681856    0.9659

```

I'm not displaying the blocks per frame yet but that could be easily added later.

**Comment by Cyan4973** [comment]
Looks great @gabrielstedman !

Regarding the value of `Ratio`, in order to be consistent with the `-b` benchmark utility, I would rather inverse the product.
aka, if "uncompressed size" is 1 KB, and "compressed size" is 0.5 KB, the ratio is "2.0".

Finally, try to add a few tests in `tests/Makefile`.
The objective of automated tests is not to display something, as no one will consult the results, but to make it generate an error code (`$? != 0`) when something goes wrong. So it matters to automatically detect if something is wrong.

**Comment by gabrielstedman** [comment]
I'll add some tests no problem.
Regarding the value of `Ratio` I'm a bit confused by why would you prefer to represent it like that when the output of the main lz4 compression is:
`Compressed 1048576 bytes into 4145 bytes ==> 0.40% ` (Represented as 0.004 in my current implementation)

**Comment by Cyan4973** [comment]
>  I'm a bit confused by why would you prefer to represent it like that when the output of the main lz4 compression is:
`Compressed 1048576 bytes into 4145 bytes ==> 0.40%`

That's a good point.
In which case, it makes sense to preserve the presentation inspired by the status line,
using the same format, aka `X.YZ%`, with up to 2 decimals after point.

**Comment by Cyan4973** [comment]
feature completed by @gabrielstedman (#708)
