### ISSUE TITLE
feature: add installation for mingw -w64 target on MSYS2

### ISSUE THREAD

**Issue by vtorri** [lz4/lz4#599]
is it possible to add installation for mingw with MSYS2 ?

just add at line 127 of lib/Makefile

MINGW32_NT-6.1 MINGW64_NT-6.1

(that is what uname returns on MSYS2) and install the DLL in the binary path instead of the library path (uninstall  should be patched too)

**Comment by vtorri** [comment]
I have a patch to allow the installation with MSYS2. I'll provide a PR this evening

**Comment by Cyan4973** [comment]
Feature merged in #605
