### ISSUE TITLE
lz4 -f with bad magic number invokes pass-through in addition to overwriting output file

### ISSUE THREAD

**Issue by dcassetti** [lz4/lz4#601]
According to the command line usage:

*** LZ4 command line interface 64-bits v1.8.3, by Yann Collet ***
...
-f     : overwrite output without prompting
...

There is no mention of pass-through mode. Without -f, a bad header is reported:
$ lz4 README_first_256_bad.lz4
Error 44 : Unrecognized header : file cannot be decoded

With -f, no error occurs, and the output file is identical to the input file:
$ lz4 -f README_first_256_bad.lz4
README_first_256_bad : decoded 233 bytes

In the attachment, one bit of the magic number is flipped, first 8 bytes are:
00000000: 04 22 4c 18 64 40 a7 d6
[README_first_256_bad.zip](https://github.com/lz4/lz4/files/2590752/README_first_256_bad.zip)

**Comment by Cyan4973** [comment]
Thanks for reporting @dcassetti .

Indeed, pass-through mode is supposed to be paired with `lz4cat`, which is equivalent to `lz4 -dcf`.

In the above example, `-d` is assumed automatically from the `.lz4` extension, while only `-f` is passed as argument. Hence `-c` is missing, and pass-through mode should not be invoked.

To be fixed.

**Comment by Cyan4973** [comment]
The pass-through mode has been restricted to `-dcf` only by @tzakian ,
fixing the issue mentioned.
