### ISSUE TITLE
feature: allow cross-compilation for Windows on unix with mingw-w64

### ISSUE THREAD

**Issue by vtorri** [lz4/lz4#602]
i have tried to cross-compile lz4 for Windows on Fedora using the mingw-w64 toolchain and I run into 2 issues : 

1. on Fedora, dlltool is prefixed with the host (i686-w64-mingw32 or x86_64-w64-ingw32), but lib/Makefile uses directly the dlltool binary. Would it be possible to use a variable (like $(DLLTOOL), set to dlltool) so that I can override it when launching 'make' ?

2. the path used o access the dll subdirectory uses backslash (\), which throw an error (the .def file is not found). Would it be possible to use slash (/) instead ? Slash is available on Windows without any problem. I can provide a PR for this issue

**Comment by Cyan4973** [comment]
Sure, a PR will be welcomed on this topic !
If you could add a build test for it, that we could automate on travis CI to make sure the feature remains available during future evolutions, this would be great !

**Comment by vtorri** [comment]
PR available for /

**Comment by vtorri** [comment]
another PR for dlltool
