### ISSUE TITLE
Question about decompression loop condition

### ISSUE THREAD

**Issue by nh2** [lz4/lz4#609]
Hey,

while trying to make my decompression loop as fast as `lz4`'s, I found something I couldn't quite figure out.

In https://github.com/lz4/lz4/blob/0983fd61eebd5123675c5afbbe5c073080c4ca96/programs/lz4io.c#L956-L970

what is the ` || (decodedBytes == ress.dstBufferSize)` part of the condition good for?

It's commented with `or still to flush`, but I cannot see how this part of the condition could ever have an effect on the loop's termination condition.

This is because

* `dstBufferSize` is a constant in this loop
* the `/* Write Block */` part doesn't have an effect on `decodedBytes` (in particular, it doesn't decrease it when data is flushed out)

This leads me to think that `decodedBytes == ress.dstBufferSize` doesn't actually track whether there's data still to flush.

The condition was introduced [here](https://github.com/lz4/lz4/commit/197982ec6cf449734f78d849ed4a845e075b2cf4#diff-abb30b1425dc9e3e5441d294b2f7e909R834) but there the same seems to hold.

Am I missing something?

**Comment by terrelln** [comment]
`LZ4F_decompress_usingDict()` sets `decodedBytes` to the number of bytes written, and `remaining` to the number of bytes read. See the documentation in https://github.com/lz4/lz4/blob/dev/lib/lz4frame.h#L380.

**Comment by nh2** [comment]
That part I was aware of, but I think what didn't occur to me was that we may be in a situation where `LZ4F_decompress_usingDict()` has consumed all input (e.g. into some internal buffer), and now only has to write out all the decompressed output, which may be a lot larger than the output buffer.

For example, it could read in 1 KB of compressed zero-bytes. Assuming those decompress to 6 KB, and `dstBufferSize` is 4 KB, then after the first call `LZ4F_decompress_usingDict()` would have set `remaining` (at that point, tracking bytes read) to 1 KB, and `decodedBytes` to 4 KB (but there's still 2 KB output that `LZ4F_decompress_usingDict()` must give us in the future).

After that, the loop would not execute again if we only checked for `pos < readSize`. `decodedBytes == ress.dstBufferSize` makes the condition complete by tracking "last time, did `LZ4F_decompress_usingDict()` completely fill its output buffer?". If yes, there's likely more data that the function wants to give us.

Thanks in any case!
