### ISSUE TITLE
lz4.org or lz4.github.io/lz4 leads to outdated Block format and Frame format documents

### ISSUE THREAD

**Issue by ecm-pushbx** [lz4/lz4#622]
The links on https://lz4.github.io/lz4 under the header Documentation lead to 
https://lz4.github.io/lz4/lz4_Block_format.html and 
https://lz4.github.io/lz4/lz4_Frame_format.html which are both outdated. The former doesn't explain the Parsing restrictions, the latter is 1.5.1 which lacks the Dictionary ID description.

**Comment by Cyan4973** [comment]
Documentation links towards format specifications now lead directly into github directory, to ensure up to date synchronization.
