### ISSUE TITLE
Announce: 8086 assembly (NASM) decoder

### ISSUE THREAD

**Issue by ecm-pushbx** [lz4/lz4#624]
I wrote my own LZ4 decoder for use in a kernel, based on the Block format and Frame format specifications. It's at https://bitbucket.org/ecm/inicomp/src/default/ Two of my projects, RxDOS and lDebug, can be booted with the inicomp depacker stage between the program and an iniload stage.

My decoder can handle arbitrary kernel sizes (but it necessarily must fit in R86M-addressable memory), allows overlapping source and destination buffers, and sequentially processes concatenated frames. It doesn't check any of the checksums. It tests that reserved bits and the dictionary bit in the Frame header are clear.

**Comment by Cyan4973** [comment]
Thanks @ecm-pushbx !
Your version has been added to the list of compatible decoders :
https://lz4.github.io/lz4/#interoperable-lz4

**Comment by ecm-pushbx** [comment]
You list it as "x86 assembly decoder", but "8086" is more specific and more accurate.
