### ISSUE TITLE
Inconsistent behavior with lz4 using tar (STDOUT)

### ISSUE THREAD

**Issue by andretf** [lz4/lz4#626]
`tar -I lz4mt -cf tcc.tar.lz4 *` is inconsistent with `-l lz4`. It's currently writing the content in the disk by its own as a default instead of passing to STDOUT when no output filename is provided. As a result I'm getting a file named "stdin" and an empty "tcc.tar.lz4". Forcing STDOUT with `-c` correct the behavior:

![image](https://user-images.githubusercontent.com/5576877/50391669-c312af00-0715-11e9-9b3d-6e78968f828a.png)

**Comment by Cyan4973** [comment]
By `lz4mt`, do you mean [this variant](https://github.com/t-mat/lz4mt) ?

**Comment by andretf** [comment]
omg, wrong rep. time to go to bed @andretf..
