### ISSUE TITLE
convert system.img to system.img.lz4

### ISSUE THREAD

**Issue by afshinnajafi** [lz4/lz4#630]
hi
 can i convert system.img to system.img.lz4  with this tool?

**Comment by Cyan4973** [comment]
Yes.
If the objective is to compress some Linux kernel image, consider using the option `-l` for "legacy format" (see [doc](https://github.com/lz4/lz4/blob/dev/programs/lz4.1.md#operation-modifiers)), which is the format used by the Linux kernel.

**Comment by afshinnajafi** [comment]
pls give an exapmle if it's possible.
and i don't know how to run this tools in ubuntu . pls advise me

**Comment by afshinnajafi** [comment]
i used below command and compressed done but is not the same of orginal file and it dosn't write.

lz4 -1 system.img system.img.lz4
or
lz4 -z -1 system.img system.img.lz4
or
lz4 -z -1 system.img

what's problem  ?

**Comment by Cyan4973** [comment]
`lz4 -l -12 system.img`

**Comment by afshinnajafi** [comment]
the size of orginal system.img.lz4 File is 1.82 GB . and after decompressing and without any changing the file , i compress it with your command (lz4 -l -12 system.img)  again but the size of the file changed (1.63 GB) and the size of it is not the same as orginal file . why  ?

**Comment by Habil0011** [comment]
abi sizde proqram varmi
