### ISSUE TITLE
is it the time to move LZ4_compress_HC_destSize to stable API?

### ISSUE THREAD

**Issue by hsiangkao** [lz4/lz4#642]
Hi,
EROFS currently uses LZ4_compress_HC_destSize/LZ4_compress_destSize in order to compress to fixed-output blocks (eg, 4KB fixed block),

https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git/tree/mkfs/erofs_lz4hc.c?h=mkfs-dev&id=f7783eb4cf5e5116c11a8587b4b835d4ff6577d8

We have applied these APIs to our smartphone products for months, but we have to use static linked lz4 library up to now.
Is there some plan to stable this series API into stable APIs in the near future? :)

Thanks,
Gao Xiang

**Comment by Cyan4973** [comment]
Sure @hsiangkao ,
this entry point will be made stable for `1.9.0`.
