### ISSUE TITLE
Use meson generator instead of custom targets

### ISSUE THREAD

**Issue by nacho** [lz4/lz4#643]
https://github.com/lz4/lz4/blob/6305e43dce0c8f0049167a41f92973fc1ef8a624/contrib/meson/contrib/gen_manual/meson.build#L27

@lzutao I think you could improve this part by using a meson generator

**Comment by lzutao** [comment]
I take a loot at [generator manpage][gen_man]. It's said that:

> NOTE: Generators should only be used for outputs that will only be used as 
> inputs for a [build target] or a [custom target][custom_target]. When you use the processed output
> of a generator in multiple targets, the generator will be run multiple times to 
> create outputs for each target. Each output will be created in a target-private 
> directory @BUILD_DIR@.
> 
> If you want to generate files for general purposes such as for generating 
> headers to be used by several sources or data that will be installed, and so 
> on, use a [custom_target] instead.

[gen_man]: https://mesonbuild.com/Reference-manual.html#generator
[build target]: https://mesonbuild.com/Reference-manual.html#build_target
[custom_target]: https://mesonbuild.com/Reference-manual.html#custom_target

In our cases, I don't think those generated manual files need to be used by
any other targets. So [custom_target] is enough.

(Though I think the current meson code is a little bit redundant.)

If you have any other opinions, please let me know.

**Comment by nacho** [comment]
ok, though I would give it a try I think it would make the code a bit simpler. One thing that I do not like much is the fact that we do not use files() for the sources but I though understand the fact that you are using join_paths everywhere...

**Comment by lzutao** [comment]
@nacho I've tried to use `files`, but we are using meson out-of-source-dir. It means that 
our `meson.build` is in separate directory other than in source dir. The project owner 
didn't want to let those `meson.build` files near `.c` files.
So I cannot use `files`.

**Comment by lzutao** [comment]
I have asked about alternative methods on Meson IRC. The Meson authors had no idea 
other than using `join_paths()`.

**Comment by nacho** [comment]
About this:
https://github.com/lz4/lz4/blob/dev/contrib/meson/lib/meson.build#L22

Do we need msvc specific flags?

**Comment by nacho** [comment]
BTW thanks a lot for working on this. As soon as I have time I'll port gvsbuild to use meson.

**Comment by lzutao** [comment]
Thanks. PR here #644.
