### ISSUE TITLE
ambiguous MFLIMIT

### ISSUE THREAD

**Issue by svpv** [lz4/lz4#647]
Been pondering over the spec again.  It reads, "The last match must start at least 12 bytes before end of block... blocks < 13 bytes cannot be compressed." I believe that this is ambigous.

It says that when I'm at the end of the block:

```
... | U8 | U8 ||
              ^
	      |
              `-- end ptr
```

I can go back 12 byte and start a match there:

```

... | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 ||
    ^						       ^
    |                                                  |
    `--------------------------------------------------|
```

So it seems that 12-byte inputs, in fact, can be compressed.  For example, if I've got 12 "a" charactres, they can be compressed with an overlapping match as follows:

```
[tok llen=1 mlen=6] [lit "a"] [off=1] [tok llen=5 mlen=0] [lit "aaaaa"]
```

So would that be a valid compressed stream, according to the spec?

**Comment by Cyan4973** [comment]
The last match must start no farther than 12 bytes before the end of the block.

Even with an overlapping match, it needs to copy "something past", at least one byte,
so the source must be at least 13 bytes for a match to be possible.

In your example, the last match starts at `6+5=11` bytes before the end of the block.
A decoder is allowed to reject a block finishing this way.

**Comment by Cyan4973** [comment]
Updated block format documentation with more details on end of block conditions, covering this question.
