### ISSUE TITLE
MSYS2, Windows 10 :filtering OS fails in lib/Makefile

### ISSUE THREAD

**Issue by vtorri** [lz4/lz4#651]
on Windows 10, with MSYS2 64 bits, uname returns the value

MINGW64_NT-10.0

and 

MINGW32_NT-10.0 for 32 bits

so lib/Makefile must be updated (line 127).

**Comment by vtorri** [comment]
i can provide a pull request if you prefer

**Comment by Cyan4973** [comment]
sure !

**Comment by vtorri** [comment]
should this issue be closed ?

**Comment by Cyan4973** [comment]
Yes @vtorri , thanks to your patch #652
