### ISSUE TITLE
Where is lz4hc?

### ISSUE THREAD

**Issue by cafarm** [lz4/lz4#660]
The LZ4 benchmarks show the transfer + decompression time of LZ4 HC -9. Googling around I see some folks discussing an lz4hc command line app. Installing this repo, I only have lz4, lz4c, and lz4cat command line apps.

I see that there is a deprecated -hc option but it is not clear to me if this is the same as lz4hc. Is "lz4 -9" now the same as what used to be "lz4 -hc -9" and "lz4hc -9"?

**Comment by Cyan4973** [comment]
Just use `lz4 -9`. 

There should not be any need to use legacy commands by now.
There is only one binary. Even `lz4c` and `lz4cat` are (supposed to be) just links towards `lz4`.

For completeness, note that `lz4` compression levels can go up to `-12`. Gains are less and less tangible, while compression speed is more and more impacted. So these additional levels are meant for very asymmetric scenarios (compress once, decompress *a lot* of times).

**Comment by cafarm** [comment]
Ok great. Thank you for the response. I was surprised not to be seeing decompression speeds faster than zstd, so I thought I might be missing something. Perhaps it's just the data I'm working with but zstd is producing a smaller compressed tar and its decompressing it faster as well (although compression takes longer).

**Comment by Cyan4973** [comment]
If you are measuring speed at I/O level, while decompressing a `tar` archive for example, then it's likely the case that `zstd` decompresses faster, just by virtue of reading less bytes from storage.

LZ4 decompression speed is in a somewhat different league. At multiple GB/s, it's closer to `memcpy()`. This is useful for in-memory processes, where speed is more critical.
But at I/O level, it's simply too fast. The CPU is simply waiting for more data to come down the pipe.

This might be measurable with `top`, or `time`, or any other cpu activity monitor.

**Comment by arashams** [comment]
Do you know how fast the lz4 is?
I tried to do lz4 with-1 option (to be the fastest) but I couldn't get a higher speed than 121MB / s, but as you may read before some people get higher speed! around 911MB/s
I was wondering why that's happening?
Or do they use multi-thread?

**Comment by Cyan4973** [comment]
You can get higher speeds, with for example `lz4 --fast=8`.
That being said, `lz4 -1` should be way faster than 100 MB/s.
What kind of cpu are you using ?

**Comment by arashams** [comment]
It's  actually 40 core xeon e5-2650 be @ 2.30 GHz processor

**Comment by Cyan4973** [comment]
This is likely incorrect then.
There is a bit of variance depending on files, but even in worst case scenarios, I don't see how it could come down to such speed.

2 remaining elements : 
- how is generated the `lz4` version you are trying
- how is measured the speed

**Comment by arashams** [comment]
I use lz4 -1 -B4 (for 64KB block size)
I tried to update the Lz4 on the terminal it returns this:
python-lz4 is already the newest version (0.7.0+dfsg-3build1).
I saw a newer version here but I don't know how to use it. :(
I download it first then I used make command, and then make install, (lz4 1.9.2) but I don't know how to run this app on the Ubuntu terminal.  what is the command to use?
Could you help me to install and use the new version of LZ4?

**Comment by Cyan4973** [comment]
> I used make command, and then make install
> how to run this app on the Ubuntu terminal.

did you tried typing `lz4` ?

> I download it first

On Ubuntu, an alternative is to use the native package manager,
`sudo apt install lz4`
though this will probably install an older version,
and local compilation + installation should work too.

**Comment by arashams** [comment]
```
root@compress5:~# sudo apt install lz4
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package lz4
```
I used this to install lz4:
```
root@compress5:~# apt-get install python-lz4
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-lz4 is already the newest version (0.7.0+dfsg-3build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@compress5:~#
```
I tried to upgrade and update repositories, but I think it's the latest version in the repository.
How should I install latest version manually and run it in the terminal? 
the apt-get version seems to be very old.

**Comment by Cyan4973** [comment]
> How should I install latest version manually and run it in the terminal? 

`make`
`sudo make install`
`lz4`

**Comment by arashams** [comment]
I did that, but how do I know this is the version that I install manually, not the version that I've installed from apt-get?
```
root@compress5:~# lz4 --version
*** LZ4 command line interface 64-bits r128, by Yann Collet (Apr 18 2016) ***
root@compress5:~#
```


> 
> 
> > How should I install latest version manually and run it in the terminal?
> 
> `make`
> `sudo make install`
> `lz4`

**Comment by Cyan4973** [comment]
`which lz4`

you can also uninstall the `apt-get` version to be sure that only the manually installed version remains.

**Comment by arashams** [comment]
Thank you!
I removed it with apt-get remove, so this is the latest version I suppose.
```
root@compress5:~/lz4-1.9.2# which lz4
/usr/local/bin/lz4
```

> 
> 
> `which lz4`
> 
> you can also uninstall the `apt-get` version to be sure that only the manually installed version remains.

**Comment by Cyan4973** [comment]
Yes it is.
Can be further checked with `lz4 -V` (or `lz4 --version`).

Now test the speed with `lz4 -b someFile`.

**Comment by arashams** [comment]
Wow yes it seems the speed went up to 439.5 MB/s
I can see that it uses only one core CPU, is there any way to use all 40 cores to 100 percent of their processing power and then see the compression speed?

**Comment by Cyan4973** [comment]
It (generally) doesn't make sense for an I/O application, where the bandwidth is limited at some much slower speed anyway.

`lz4` can be multi-threaded, but this is more at a programming level : for example, a database will have multiple queries in flight, each one featuring some compression / decompression operation. This will allow the database application to multi-thread compression across as many cores as necessary.

But the `lz4` cli is not able to do that. It's purely single-threaded, primarily for simplicity, but also because in most cases, it's faster with one thread than I/O can provide.

**Comment by arashams** [comment]
Thanks for all the info. I calculated the compression rate based on the 125.66Gb file that I compressed with LZ4 and it takes 17m41s I guess the reason I get 121MB/s is that the loading a file to memory might be slow! since by doing -b it says:

```
Not enough memory for 'testfile.xml' full size; testing 928 MB only...
testfile.xml     : 973078528 -> 385567534 (39.62%),  439.5 MB/s , 2146.2 MB/s
```
Update:

```
root@compress5:~# sudo hdparm -Tt /dev/sda

/dev/sda:
 Timing cached reads:   20218 MB in  1.99 seconds = 10138.36 MB/sec
 Timing buffered disk reads: 400 MB in  3.00 seconds = 133.12 MB/sec
```

```
root@compress5:~# sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.615925 s, 1.7 GB/s
```

**Comment by Cyan4973** [comment]
This seems in line with the `buffered disk reads` info.
Considering the huge size of the file read, at 125 GB, it's unlikely to be cached.

**Comment by arashams** [comment]
Thank you!
>
> 
> This seems in line with the `buffered disk reads` info.
> Considering the huge size of the file read, at 125 GB, it's unlikely to be cached.

**Comment by arashams** [comment]
I know LZ4 uses some kind of CRC, but can I find more details anywhere?
Like the version of the CRC? 16 32 64, right? Or could it be modified?
> 
> 
> This seems in line with the `buffered disk reads` info.
> Considering the huge size of the file read, at 125 GB, it's unlikely to be cached.

**Comment by Cyan4973** [comment]
The LZ4 frame format defines 2 checksums : 
https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md#general-structure-of-lz4-frame-format

The most common one is the final frame content checksum, generally enabled by default.
As explained in the specification, it's provided by `XXH32`.

**Comment by arashams** [comment]
So it doesn't use CRCs like RAR or ZIP that use CRCs?
Is there a way to modify it to use CRC instead?

**Comment by Cyan4973** [comment]
You can create your own format, starting from the LZ4 block format, which lets implementors select their own choice of headers and checksum.

**Comment by arashams** [comment]
May I ask which one would you recommend? CRC 32 or XXH32 for better error detection and burst detection?

**Comment by Cyan4973** [comment]
`XXH32` was selected because it was much faster

**Comment by arashams** [comment]
If we consider that we want to compress chunks of data separately (e.g. 1 GB each size) I know that 1/2^n is the probability of a collision, how can I calculate the probability of an undetected error in each chunk?
Thank you :)

**Comment by Cyan4973** [comment]
It is 1/2^n for each chunk, since only 2 values are being compared (the stored and the calculated ones).

If error detection is a concern, and a probability of 1 in 4 billion is not good enough, LZ4 frame format also defines a Block checksum, which can be combined with the Content checksum. Now, to remain undetected, an error would need to pass both the block and the content checksums, both being 32-bit. 
Block checksum is disabled by default, but can be enabled using command `-BX`.

**Comment by arashams** [comment]
2 questions

1. n is the number of bits of hash function right? LZ4 has content checksum for each data block (here it means every 1 GB file) followed by a 4-byte checksum so we have 4 * 8bits with a 1/2^(32) single-bit error probability in the whole file.
we have another header checksum we will get  1*8bit checksum with the probability single bit error of 1/2^(8), am i right?

2. I thought it was going to take longer by using-BX, but it's clearly faster. Is this right?

```
root@compress-tacc:~/ziptest# lz4 -b testfile.xml
File(s) bigger than LZ4's max input size; testing 2016 MB only...
 1#testfile.xml      :2113929216 -> 881950288 (2.397), 388.2 MB/s ,2797.5 MB/s
root@compress-tacc:~/ziptest# lz4 -b -BX testfile.xml
File(s) bigger than LZ4's max input size; testing 2016 MB only...
 1#testfile.xml      :2113929216 -> 881950288 (2.397), 377.6 MB/s ,2694.4 MB/s
root@compress-tacc:~/ziptest# lz4 -b -BX testfile.xml
File(s) bigger than LZ4's max input size; testing 2016 MB only...
 1#testfile.xml      :2113929216 -> 881950288 (2.397), 418.4 MB/s ,2606.6 MB/s
root@compress-tacc:~/ziptest# lz4 -b testfile.xml
File(s) bigger than LZ4's max input size; testing 2016 MB only...
 1#testfile.xml      :2113929216 -> 881950288 (2.397), 374.0 MB/s ,2793.1 MB/s
```

**Comment by IshaanKudchadkar** [comment]
I'm confused as to which cli command calls which internal function while executing. Does using a cli command "lz4 -1" use lz4_compress_fast() and "lz4 -9" use lz4_compress_HC()? Or how is it?

**Comment by Cyan4973** [comment]
They both end up calling `LZ4F_compressUpdate()`.
Then, `lz4frame` will decide where to route the call, depending on compression level.
`lz4frame` will invoke the regular "fast" lz4 within `lz4.c` for level 1 and `--fast=#`,
and `lz4hc.c` for level 2 and above.
