### ISSUE TITLE
Inconsistent use of allocation macros (leading to memory corruption with custom allocator)

### ISSUE THREAD

**Issue by sloutsky** [lz4/lz4#671]
lz4hc.c uses free() call directly instead of FREEMEM() macro in two places (this breaks scenario of replacing allocator)

LZ4_compress_HC() and LZ4_freeStreamHC()

**Comment by Cyan4973** [comment]
Nice catch !
Yes, this should be fixed.

**Comment by Cyan4973** [comment]
Thanks for your timely notification @sloutsky !
This is fixed, and will be part of next release (`v1.9.0`).
