### ISSUE TITLE
Using a CDict

### ISSUE THREAD

**Issue by degski** [lz4/lz4#687]
There is a `LZ4F_compressBegin`  and a `LZ4F_compressBegin_usingCDict`  function, but there don't seem to being any CDict-equivalents for `LZ4F_compressUpdate`  and `LZ4F_compressEnd`. 

Is it planned to have those or do I need to go about things differently (as I'm currently using `LZ4F_compressBegin` , `LZ4F_compressUpdate` , and  `LZ4F_compressEnd` , while I would like to move to using a CDict)?

**Comment by Cyan4973** [comment]
`LZ4F_compressBegin_usingCDict()` just replaces the initialization, aka `LZ4F_compressBegin()`.

After that, just uses the regular streaming functions `LZ4F_compressUpdate()` and `LZ4F_compressEnd()`. They are compatible.

**Comment by degski** [comment]
Thanks, I understood the replace bit, I imagined that there would be equivalents of the other functions as well.

Thanks, getting on with things ...
