### ISSUE TITLE
OS variable is not defined in lib/Makefile

### ISSUE THREAD

**Issue by moubctez** [lz4/lz4#701]
The following has been removed from **lib/Makefile**. As a consequence, building on Darwin fails with incorrect linker flags.

```
--- lib/Makefile.orig
+++ lib/Makefile
@@ -45,6 +45,7 @@ LIBVER  := $(shell echo $(LIBVER_SCRIPT)
 BUILD_SHARED:=yes
 BUILD_STATIC:=yes
 
+OS ?= $(shell uname)
 CPPFLAGS+= -DXXH_NAMESPACE=LZ4_
 CFLAGS  ?= -O3
 DEBUGFLAGS:= -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow \
```

**Comment by moubctez** [comment]
This is for 1.9.1. I see this has been fixed on master.

**Comment by Cyan4973** [comment]
Yes, I put a note on the release page about this issue,
but I'm afraid I can't change the v1.9.1 package, to preserve checksum.
