### ISSUE TITLE
Question: lz4 -t nonexistant.lz4 returns 0

### ISSUE THREAD

**Issue by imartisko** [lz4/lz4#704]
lz4 -t ./nonexistant.lz4                                                                                         
./nonexistant.lz4: No such file or directory 
echo $?                                                                                                          
0

Is this expected behaviour?

**Comment by Cyan4973** [comment]
It's clearly a bug.
Thanks for reporting @imartisko !

**Comment by Cyan4973** [comment]
fixed by @gabrielstedman (#715)
