### ISSUE TITLE
Tested v191 with 1TB of data

### ISSUE THREAD

**Issue by aleksazr** [lz4/lz4#706]
Just wanted to share that I have **successfully** tested compressing and decompressing
of every file (smaller than 1 GB) on my hard drives, using level 1.
That means text files, video, audio, exe and so on. In total, 1 TB of data in 655000 files.

Each file was loaded into buff1, compressed into buff2, decompressed into buff3,
and then memcmp of buff1 vs buff3. Also, return size was checked to be correct.

The test ran for 3 hours. Levels 2-12 would take longer, so I didn't do that.

I know that you use fuzzers, but don't know anything about them.
Presumably that's some random data generator. This was real-world data test.

**Comment by Cyan4973** [comment]
Thanks @aleksazr , it's always great to receive real-world experience feedback !
