### ISSUE TITLE
LZ4_FAST_DEC_LOOP on ARM64 need to improvement.

### ISSUE THREAD

**Issue by parheliamm** [lz4/lz4#710]
I was work on LZ4_FAST_DEC_LOOP #645 feature on my ARM64 devices.
I found some clues and share the info here:
1. LZ4_FAST_DEC_LOOP on Cortex-A53. didn't show obvious improvements like X86 did. 
Test case dickens has downgrade compare with v1.8.3 
2. Some clues:
a. different ARM64 has different memory implementation in libc. e.g Kryo use specific implementation compare with generic A53.
b. memcpy has different performance with different count. According to my current investigation, 16 bytes is better than 2 bytes.
c. ARM64 prefer 16 bytes copy instead of 8 bytes copy.

I am working on my local build, I will share my patch tomorrow once my commit available.

**Comment by Cyan4973** [comment]
Sounds great @parheliamm !

**Comment by parheliamm** [comment]
Hi @Cyan4973 :
I create a new pull request #713 to improve the ARM64 decompress performance.
Please review it.
I use the objdump the disassemble code to check memcpy behavior, current memcpy didn't invoke the libc code, it is optimized by compiler.
Frankly, I don't have chance to profile API one by one, but current change could improveme the performance.
Pleaes kindly check the commit.
Chenxi

**Comment by Cyan4973** [comment]
Thanks ! I will check on an ARM64 system !

**Comment by parheliamm** [comment]
Some information from profiling.
1.8.x vs 1.9.x

1. LZ4_wildCopy32 didn't show performance improvements.
v.1.9.x
  0.46      2.12     0.01   701666     0.00     0.00  LZ4_wildCopy8
  0.46      2.13     0.01   413760     0.00     0.00  LZ4_wildCopy32
v.1.8.x
  0.90      2.14     0.02  1077866     0.00     0.00  LZ4_wildCopy

2. LZ4_readLE16 invoked frequently on v.1.9.x
v1.9.x
  5.05      1.57     0.11 12670620     0.00     0.00  LZ4_readLE16
v1.8.x
  1.13      2.10     0.03 11614735     0.00     0.00  LZ4_readLE16
