### ISSUE TITLE
FAST_DEC_LOOP: GCC8 has downgrade compare with GCC6/7 on ARM64

### ISSUE THREAD

**Issue by parheliamm** [lz4/lz4#726]
@Cyan4973 
I build lzbench via GCC 8.3 which come from https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads
I found GCC 8.3 has big downgrade compare with Linaro GCC6/7 on lzbench.
GCC-8.3 w/o inline
lz4 1.9.x 59 MB/s 422 MB/s 6428742 63.07 /sdcard/silesia/dickens
GCC-8.3 w/ inline
lz4 1.9.x 77 MB/s 435 MB/s 6428742 63.07 /sdcard/silesia/dickens

GCC 6.3.1 Linaro
w/o inline
lz4 1.9.x 84 MB/s 439 MB/s 6428742 63.07 /sdcard/silesia/dickens
w/ inline
lz4 1.9.x 82 MB/s 453 MB/s 6428742 63.07 /sdcard/silesia/dickens

GCC6 has much better performance compare with GCC8.

**Comment by Cyan4973** [comment]
I've noticed `gcc-8` performance regressions (compared to `gcc-7`) on multiple software, therefore not limited to `lz4`. 
The 3% performance regression measured on your platform is unfortunately not even large compared to other known cases.

Unfortunately, I'm not sure what can be done. This seems more a `gcc` issue than an `lz4` one.

`gcc-8` likely changed its optimization heuristics in a way which happens to be detrimental for some use cases, but it might well be beneficial to some other ones, who knows. So many combinations are possible, it seems hard guarantee smooth progresses for all of them.

**Comment by parheliamm** [comment]
Can we add some warning message in Makefile to alert there are some downgrade if using GCC8?

**Comment by Cyan4973** [comment]
in `Makefile` ? 
or in documentation, like `README.md` ?

**Comment by parheliamm** [comment]
> in `Makefile` ?
> or in documentation, like `README.md` ?

README.md is OK for me.

**Comment by Cyan4973** [comment]
I verified again, and for my desktop system at least, moving from `gcc-6` to `gcc-7` to `gcc-8` improves performance.

|   | gcc-6 | gcc-7 | gcc-8 |
| --- | --- | --- | --- |
| calgary | 3515 | 3555 | 3660 |
| silesia | 3600 | 3690 | 3750 |

So I guess the conclusion that `gcc-8` generates worse performance is not straightforward. I'm sure it happens, having observed it in other softwares, but it's not a "guaranteed / necessary outcome". It depends on the specific situation. And for `lz4` at least, there are cases where it actually improves performance.
