### ISSUE TITLE
Decompression example should not use known src_size

### ISSUE THREAD

**Issue by pps83** [lz4/lz4#728]
> We'll create a *new_src location of size src_size since we know that value.

This doesn't make any sense. If it's ok to use known decoded size, why don't you go one step further and use known decoded data then?..
What about the case if decoded size isn't know, like in 99% of the use cases? What's the proper way to decode a buffer compressed with lz4? I'm staring at `LZ4_decompress_safe` in disbelief that nobody ever needed to know how much data to allocate before decompressing lz4-compressed data? Am I expected to store the size along with compressed buffer?! Or should I allocate N bytes, and if decompression fails try to double the output buffer and retry and so on in a loop?!

https://github.com/lz4/lz4/blob/3a3639e32dc70cc997f8cf31b5beeceb96c8b5c6/examples/simple_buffer.c#L70

**Comment by Cyan4973** [comment]
> Am I expected to store the size along with compressed buffer?!

Yes. 
Either the size, or an upper bound of the size. This second case can sometimes be implicit to the application.

If you want a format that free your application from thinking about it, storing metadata alongside compressed data, prefer using `lz4frame` API.

**Comment by pps83** [comment]
It would be helpful if the docs made it clear in api description that the format doesn't store or can say what the upper bound is.

**Comment by Cyan4973** [comment]
https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L60
https://github.com/lz4/lz4/blob/dev/doc/lz4_manual.html#L35
