### ISSUE TITLE
Having some trouble compressing/decompressing a buffer that is >4MB in size.

### ISSUE THREAD

**Issue by andrewsil1** [lz4/lz4#729]
I am building the LZ4 static library for use in a Xilinx FPGA Microblaze SDK C++ project.  I have no problem building or linking the library into my executable. I have some raw image data that I am compressing to reduce transmission time over a slow serial link.  As long as the total image data size is kept under 4MB (and the frameInfo blockSizeID is specified as LZ4F_max4MB), I am able to send and decompress the entire image successfully at the far end, which is a C# application using the K4os.Compression.LZ4.Streams NuGet package to decompress the incoming frame.

The problem comes when I expand the image resolution to something that exceeds the 4MB block size limit.  The compressed frame is seen as valid by the frame decompressor (about 300-500K bytes in total), but the decompressed data appears to stop being valid after reaching the 4MB boundary, and the remainder of the expected image is truncated when displayed (contains all zeroes.)  If I change the blockSizeID preference to one of the smaller values, the amount of valid data in the decompressed buffer shrinks correspondingly.

I was under the impression that I could use one of the following techniques:
1) Use the "simple" API to create a frame from the entire buffer, without limitation, as long as the dstBuffer is large enough (which it is, by orders of magnitude.) For some reason I can't figure out, the simple API sends the app into lala-land and hangs.
2) Using my existing technique of calling LZ4F_compressBegin, repetitively calling LZ4F_compressUpdate with chunks no larger than 4MB and updating the offset into the source and destination buffers each time, until the entire source has been processed, and finally calling LZ4F_compressEnd.  This results in a completed frame which can be transmitted and decompressed successfully, but the data in the destination buffer appears to stop after 4MB worth of decompressed data.

I don't know whether the stream is actually valid and contains multiple blocks, each of which is <= 4MB, and the C# stream library is not decoding the extra blocks, or whether the stream does not actually contain any additional data after the first 4MB block.

Any thoughts on where the problem might be would certainly be appreciated.

Thanks-

**Comment by Cyan4973** [comment]
Which API are you using for decoding ?

**Comment by andrewsil1** [comment]
In C#: 
```
using K4os.Compression.LZ4.Streams;

using (var source = LZ4Stream.Decode(incomingData, 0, false)) {
    source.Read(drawBuffer, 0, ImageBufferLength);              //Pass the stream through the decompressor 
}
```

**Comment by Cyan4973** [comment]
OK, so you are using `C#` for decoding,
but `C` for encoding ?

> Use the "simple" API to create a frame from the entire buffer

What do you call "simple API" ?

**Comment by andrewsil1** [comment]
Yes: compress with C, decompress with C#.

Simple API for compression:
LZ4F_compressFrame

Andy Silverman
Microsoft AIAA, Azure Hardware Systems Group

Written using Outlook<https://aka.ms/qtex0l> for iOS
Big thumbs, small keyboard — excuse typos.
________________________________

**Comment by Cyan4973** [comment]
Would you be in position to test the produced compressed frame with another tool ?
Such as, for example, the `lz4` CLI, if you can save the frame into a file ?
Or the `LZ4F_decompress()` API if you prefer to test all in RAM ?

This would help to pinpoint if the problem is on the encoder or decoder side.

**Comment by andrewsil1** [comment]
I can take a stab at that, good suggestions. I'll report back when I've had a chance to do that.

**Comment by andrewsil1** [comment]
I built the CLI and decompressed the incoming frame received by the C# app, and the decompressed frame is identical in content to what I can see in the original uncompressed memory buffer on the FPGA, which I've verified to contain correct data for the entire image (by sending it uncompressed and displaying it.)  My conclusion is therefore that something about the C# frame decompression library is skipping the blocks after the first one for some reason.  I assume my next step would be to contact the author of that package, which I'll do now.  Thanks Yann!

**Comment by andrewsil1** [comment]
Problem is solved: The C# stream reading API documentation is not _quite_ clear on the point that it may return less than the requested number of bytes even if all bytes are available, so you have to check its return values to determine if you are expecting more bytes than were supplied and call again to get the rest.
