### ISSUE TITLE
version info prints to stderr, not stdout

### ISSUE THREAD

**Issue by planet36** [lz4/lz4#734]
Version information is printed to stderr.  Please consider printing it to stdout instead.

https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html
GNU Coding Standards: --version
> The standard --version option should direct the program to print information about its name, version, origin and legal status, all on standard output, and then exit successfully.

**Comment by Cyan4973** [comment]
Thanks for pointing that out @planet36 ,
this is now fixed in `dev` branch, and will be part of next release.
