### ISSUE TITLE
How to use lz4hc to compress/decompress a file

### ISSUE THREAD

**Issue by CaptainDuke** [lz4/lz4#736]
When I type in lz4 -h in cli, there's no suggestion on 'lz4hc'

**Comment by Cyan4973** [comment]
Why should it ?

The help message mentions this line : 
` -9     : High compression`

**Comment by LeeYoung624** [comment]
@CaptainDuke The `hc` lz4hc means `High Compression`, which means you don't need to directly use `lz4hc`. You can just use a higher compression level of `lz4` and the `lz4hc` would work.
