### ISSUE TITLE
There is a heap-buffer-overflow vulnerability in 1.9.1

### ISSUE THREAD

**Issue by cxht** [lz4/lz4#737]
Hi!
When I run your decompression function, I use ASAN to run the program and it reports a heap-buffer-overflow bug in lz4.c:1729  `memcpy(op, match, 8);
`
and here is the information printed by ASAN:  

`==9410==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fed730f3e21 at pc 0x00000046e1b2 bp 0x7ffe230a0160 sp 0x7ffe230a0150
READ of size 8 at 0x7fed730f3e21 thread T0
    #0 0x46e1b1 in LZ4_decompress_generic /home/cx/workspace/target_group/lz4/lib/lz4.c:1729
    #1 0x46e1b1 in LZ4_decompress_safe /home/cx/workspace/target_group/lz4/lib/lz4.c:1990
    #2 0x5190e8 in LZ4IO_decodeLegacyStream /home/cx/workspace/target_group/lz4/programs/lz4io.c:925
    #3 0x5190e8 in selectDecoder /home/cx/workspace/target_group/lz4/programs/lz4io.c:1123
    #4 0x5190e8 in LZ4IO_decompressSrcFile /home/cx/workspace/target_group/lz4/programs/lz4io.c:1168
    #5 0x521ea7 in LZ4IO_decompressDstFile /home/cx/workspace/target_group/lz4/programs/lz4io.c:1202
    #6 0x521ea7 in LZ4IO_decompressFilename /home/cx/workspace/target_group/lz4/programs/lz4io.c:1223
    #7 0x405397 in main /home/cx/workspace/target_group/lz4/programs/lz4cli.c:741
    #8 0x7fed770f182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x409178 in _start (/home/cx/workspace/target_group/lz4/lz4+0x409178)

0x7fed730f3e21 is located 2527 bytes to the left of 8388608-byte region [0x7fed730f4800,0x7fed738f4800)
allocated by thread T0 here:
    #0 0x7fed77533602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x518df6 in LZ4IO_decodeLegacyStream /home/cx/workspace/target_group/lz4/programs/lz4io.c:902
    #2 0x518df6 in selectDecoder /home/cx/workspace/target_group/lz4/programs/lz4io.c:1123
    #3 0x518df6 in LZ4IO_decompressSrcFile /home/cx/workspace/target_group/lz4/programs/lz4io.c:1168

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/cx/workspace/target_group/lz4/lib/lz4.c:1729 LZ4_decompress_generic`

**Comment by terrelln** [comment]
Why did you close the issue? Is the report a mistake?

If this is a bug, can you provide the input that triggers the problem? That makes debugging 10x easier.
