### ISSUE TITLE
Add more oss-fuzz coverage

### ISSUE THREAD

**Issue by terrelln** [lz4/lz4#754]
@cmeister2 recently added oss-fuzz fuzzers to LZ4 in #739. I added some more fuzzer tests in #752. We still need more coverage. This is an (incomplete) list of fuzzers we still need:

* [x] Dictionary compression (extDict, prefix, attached, smaller than 64K prefix, etc)
* [x] LZ4HC
* [x] LZ4 frame (dictionary) compression
* [x] LZ4 frame (dictionary) decompression

**Comment by terrelln** [comment]
Added dictionary and streaming compression in https://github.com/lz4/lz4/pull/757.

**Comment by terrelln** [comment]
Also added LZ4HC fuzzers to #757.

**Comment by cmeister2** [comment]
These Iook great BTW. Are they finding bugs yet? (I'm not on the cc list)

**Comment by terrelln** [comment]
Yeah, 3 bugs fixed by https://github.com/lz4/lz4/pull/756, the bug fixed in https://github.com/lz4/lz4/pull/759, and an off-by-one in the bug fix in https://github.com/lz4/lz4/pull/760. Either found by oss-fuzz or when creating the fuzzers.

**Comment by terrelln** [comment]
I added LZ4 frame fuzzers in https://github.com/lz4/lz4/pull/762.

I still have to add streaming LZ4 frame fuzzers to `round_trip_stream_fuzzer`, then we should have fairly complete coverage.

**Comment by Cyan4973** [comment]
Are there still more `oss-fuzz` tests to add ? Or it this action completed ?
