### ISSUE TITLE
Problems with GNU-compiled LZ4 when any optimization level is enabled

### ISSUE THREAD

**Issue by andrewsil1** [lz4/lz4#764]
I’m back with another issue related to using a statically linked version of the library in an application on a Xilinx 32-bit Microblaze (little endian.) If any of the GNU compiler optimizations are enabled at all when compiling the library (anything other than -O0), the program will crash somewhere in the compression routines due to a memory access stall.  I have tried to troubleshoot multiple theories, including:
- Enable exceptions for both stack bounds violation and unaligned accesses, neither are triggered.
- Set #defines shown in the code to force use of memcpy rather than any less safe optimizations.

Because the debugger isn’t able to recover the state of the CPU when it crashes in this fashion, and because the optimization makes debugging very difficult even when -g3 is also set, I have been having a lot of difficulty identifying the exact location of the issue and determining what the problem actually is.  I have to suspect a memory access pointing to some location that isn’t being decoded by hardware and thus resulting in the stall, but that’s only a theory.

Any suggestions for further debugging techniques would certainly be appreciated.

**Comment by Cyan4973** [comment]
On the `liblz4` side,
you can enable `assert()` by compiling with `-DLZ4_DEBUG=1`.
If something is wrong within the library, it will help locating it.

**Comment by andrewsil1** [comment]
Good, I hadn’t seen that, so I’ll give it a try.

Andy Silverman
Microsoft AIAA, Azure Hardware Systems Group

Written using Outlook<https://aka.ms/qtex0l> for iOS
Big thumbs, small keyboard — excuse typos.
________________________________

**Comment by andrewsil1** [comment]
I played with turning up the value of LZ4_DEBUG.  At 5, the program still crashes after the following output:

`../lz4.c: LZ4_createStream 0x80a8c0b0
../lz4.c: LZ4_initStream
../lz4frame.c: LZ4F_compressUpdate (srcSize=1048576)
../lz4.c: LZ4_compress_fast_continue (inputSize=1048576)
../lz4.c: LZ4_compress_generic: srcSize=1048576, tableType = 2
../lz4.c: LZ4_compress_generic: compressed 1048576 bytes into 39194 bytes
../lz4frame.c: LZ4F_compressUpdate (srcSize=1048576)
../lz4.c: LZ4_compress_fast_continue (inputSize=1048576)
../lz4.c: LZ4_compress_generic: srcSize=1048576, tableType = 2
../lz4.c: LZ4_compress_generic: compressed 1048576 bytes into 92251 bytes
../lz4frame.c: LZ4F_compressUpdate (srcSize=1048576)
../lz4.c: LZ4_compress_fast_continue (inputSize=1048576)
../lz4.c: LZ4_compress_generic: srcSize=1048576, tableType = 2`
This  point of crashing in the third 1MB block seems consistent with my manual debugging attempts.
However, we have a bit of a heisenbug because if I crank the debug level up to 7, it slows down tremendously due to all of the additional debug output, but also completes the entire compression process (~5MB of source data.)

Any other suggestions?

**Comment by andrewsil1** [comment]
A few more findings.  I think it definitely has something to do with the assembly being generated whether optimized or not for the different cases of LZ4_FORCE_MEMORY_ACCESS.

- The lib defaults to memcpy, which is failing when the code is optimized, even though it's supposed to be "safe".  
- If I force the value to 1 to use __packed, this crashes in the fashion as memcpy.  
- Using Method 2 for direct access, the library does not crash,  but it is producing invalid output whether optimized or not. (For the same uncompressed ~5MB input, it claims to reduce to a size of 21788 bytes and the compressed data is clearly invalid.  The unoptimized code with memcpy produces a valid and verified correct compressed output of 431070 bytes, a sizable difference.

So at this point I think the problem clearly has to be the Microblaze-specific "mb-g++", which appears to have been compiled from gcc version 8.2.0.  Investigation continues...

**Comment by andrewsil1** [comment]
Unfortunately I think I'm going to have to abandon the investigation at this point - going any further with this is beyond my relatively minimal debugging skills.  Yes, the unoptimized code works, which I think I may have to just accept as the solution for the time being.  I don't expect Xilinx to care, as they are clearly abandoning Microblaze for all but budget platforms, as Zynq with hard ARM cores is where the money's really at for them.
