### ISSUE TITLE
No way to distinguish unknown size from zero size.

### ISSUE THREAD

**Issue by Timmmm** [lz4/lz4#775]
```
  unsigned long long     contentSize;         /* Size of uncompressed content ; 0 == unknown */
```

Erm yeah, what about if the `contentSize` *is* zero? That should be a distinct value.

**Comment by Cyan4973** [comment]
`contentSize == 0` cannot be represented with this API.
This is known limitation of the API, without any clear work-around, and it will remain so for the foreseeable future.

Indeed, allowing this distinction would have been useful when the API was created, years ago.
Unfortunately, now that it's widely in use, any change to this convention would break most if not all existing users of this API.
