### ISSUE TITLE
LZ4F_compressFrame doesn't fill contentSize

### ISSUE THREAD

**Issue by Timmmm** [lz4/lz4#776]
`LZ4F_compressFrame` knows the `contentSize` but it still leaves it as 0 (unknown), which is a bit of a shame.

**Comment by Cyan4973** [comment]
`contentSize` is a field that is controlled through the optional `const LZ4F_preferences_t* preferencesPtr` parameter.
So it's possible to instruct `LZ4F_compressFrame()` to insert this information into the frame header.
Note however that this field costs an additional 8 bytes.
