### ISSUE TITLE
clang-tidy warnings with v1.9.2

### ISSUE THREAD

**Issue by rvandermeulen** [lz4/lz4#782]
Hi, when looking at the recent 1.9.2 update, clang-tidy flagged some new issues:

**lz4.c:1417**
```diff
+    if ((dictEnd - p) > 64 KB) p = dictEnd - 64 KB;
+    base = dictEnd - dict->currentOffset;
```
Warning: Statement should be inside braces [clang-tidy: readability-braces-around-statements]
Checker reliability is high, meaning that the false positive ratio is low.

**lz4.c:1699**
```diff
-        if ((!endOnInput) && (unlikely(outputSize==0))) return (*ip==0 ? 1 : -1);
-        if ((endOnInput) && unlikely(srcSize==0)) return -1;
+            /* Empty output buffer */
+            if (partialDecoding) return 0;
+            return ((srcSize==1) && (*ip==0)) ? 0 : -1;
```
Warning: Statement should be inside braces [clang-tidy: readability-braces-around-statements]
Checker reliability is high, meaning that the false positive ratio is low.

**lz4.c:1977**
```diff
#endif
+            if ((checkOffset) && (unlikely(match + dictSize < lowPrefix))) goto _output_error;   /* Error : offset outside buffers */
            /* match starting within external dictionary */
```
Warning: Statement should be inside braces [clang-tidy: readability-braces-around-statements]
Checker reliability is high, meaning that the false positive ratio is low.

**lz4.c:2060**
```diff
           return (int) (((char*)op)-dst);     /* Nb of output bytes decoded */
-        else
+       } else {
           return (int) (((const char*)ip)-src);   /* Nb of input bytes read */
```
Warning: Do not use 'else' after 'return' [clang-tidy: readability-else-after-return]
Checker reliability is high, meaning that the false positive ratio is low.

**lz4.h:687**
```diff
-LZ4_DEPRECATED("use LZ4_compress_default() instead")       LZ4LIB_API int LZ4_compress               (const char* source, char* dest, int sourceSize);
-LZ4_DEPRECATED("use LZ4_compress_default() instead")       LZ4LIB_API int LZ4_compress_limitedOutput (const char* source, char* dest, int sourceSize, int maxOutputSize);
+LZ4_DEPRECATED("use LZ4_compress_default() instead")       LZ4LIB_API int LZ4_compress               (const char* src, char* dest, int srcSize);
+LZ4_DEPRECATED("use LZ4_compress_default() instead")       LZ4LIB_API int LZ4_compress_limitedOutput (const char* src, char* dest, int srcSize, int maxOutputSize);
LZ4_DEPRECATED("use LZ4_compress_fast_extState() instead") LZ4LIB_API int LZ4_compress_withState               (void* state, const char* source, char* dest, int inputSize);
```
Warning: Function 'LZ4_compress_limitedOutput' has a definition with different parameter names [clang-tidy: readability-inconsistent-declaration-parameter-name]
Checker reliability is high, meaning that the false positive ratio is low.

**Comment by terrelln** [comment]
Thanks for the analysis! The style in LZ4 is to not use braces for single line if statements. I'd be happy to accept a PR with the rest of the changes. But, these are all style suggestions, not errors, so this is not release blocking.
