### ISSUE TITLE
Cannot compress long zeroed buffer properly with LZ4_compress_HC_destSize()

### ISSUE THREAD

**Issue by hsiangkao** [lz4/lz4#784]
tested with the latest lz4 upstream library

tst.c
#include <lz4hc.h>
#include <string.h>
#include <stdio.h>

int main(void)
{

	int SrcSize = 1642496;
	char buf[1642496];
	char dst[4096];
	int compressed;

	void *ctx = LZ4_createStreamHC();

	memset(buf, 0, sizeof(buf));
	compressed = LZ4_compress_HC_destSize(ctx, buf, dst, &SrcSize, 4096, LZ4HC_CLEVEL_DEFAULT);

	LZ4_freeStreamHC(ctx);
	printf("compressed: %d SrcSize: %d", compressed, SrcSize);
	return 0;
}
gcc -I lz4-dev/lib -L lz4-dev/lib -o test tst.c lz4-dev/lib/liblz4.a

result:
compressed: 4095 SrcSize: 4078

and it seems goto _dest_overflow but I didn't dig into that. LZ4_compress_destSize seems fine.

**Comment by hsiangkao** [comment]
and LZ4HC_CLEVEL_MAX (LZ4HC_compress_optimal) has the same issue.

**Comment by hsiangkao** [comment]
it seems that LZ4HC_InsertAndFindBestMatch didn't consider the outputbufferlimit, and generate a much longer match with the matchlength is larger than the buffer size...

pos:      0 -- literals:  1, match:1642490, offset:    1, cost:6446 + 0
                                                                                                                ^ > 4096
hmmm...

**Comment by remittor** [comment]
It seems to me that it's my fault: https://github.com/lz4/lz4/commit/f007153e3f0c401d51d6ba5f6ecf27b223591ef2
I'll try to fix it ...

**Comment by remittor** [comment]
@hsiangkao, @Cyan4973 
> and it seems goto _dest_overflow but I didn't dig into that. LZ4_compress_destSize seems fine.

Seems to have fixed: https://github.com/remittor-pr/lz4/commits/hc_dstsize_3
Fuzzing test completed successfully!

Now should add new tests to the `fazzer`.

**Comment by esxgx** [comment]
Hi remittor,
I have not enough time to do the full regression test since I'm mainly focusing on EROFS development now.
But I'm very happy it could be fixed in LZ4 upstream :)

Thanks,
Gao Xiang

**Comment by Cyan4973** [comment]
Going back to this topic,
trying to get it fixed in time for next release,

My current understanding of the problem is the following :

when the last match is very long, and requires complementary length bytes,
and these bytes are so numerous that they overflow the `dst` buffer,
then, instead of truncating this last match to fit into the `dst` buffer,
the current `HC_destSize` algorithm does entirely drop this last match
and replace it with literals instead
resulting in no compression at all.

This seems fixable.
I've looked at the fixes proposed by @remittor in its own fork,
I presume they work fine,
but since there are several of them, and none look trivial,
it will require a bit of analysis.

**Comment by remittor** [comment]
> I've looked at the fixes proposed by `remittor` in its own fork,
> I presume they work fine,
> but since there are several of them, and none look trivial,
> it will require a bit of analysis.

But these complex fixes eliminate the use of this hacking: 
https://github.com/lz4/lz4/blob/7a75b045bde89e77e3573f91821d0314251aac1d/lib/lz4hc.c#L567
https://github.com/lz4/lz4/blob/7a75b045bde89e77e3573f91821d0314251aac1d/lib/lz4hc.c#L588-L589
https://github.com/lz4/lz4/blob/7a75b045bde89e77e3573f91821d0314251aac1d/lib/lz4hc.c#L636-L640
https://github.com/lz4/lz4/blob/7a75b045bde89e77e3573f91821d0314251aac1d/lib/lz4hc.c#L658-L659
https://github.com/lz4/lz4/blob/7a75b045bde89e77e3573f91821d0314251aac1d/lib/lz4hc.c#L714

See this commit: https://github.com/lz4/lz4/pull/834/commits/8019189326dcbbb3e43d136715fc06a30f858af0

**Comment by Cyan4973** [comment]
@hsiangkao,
latest updates in `dev` branch
should fix all previously reported `_destSize()` related problems.

While the test system has been upgraded to challenge and control this interface more aggressively,
there is still a chance that your own test suite, presumably centered around `erofs`,
may prove more thorough in some regards, and could unveil remaining weaknesses.

It would be great if you can find the time to challenge the `dev` version on your CI test environment,
as we are gearing towards v1.9.3 release.

**Comment by hsiangkao** [comment]
Hi Cyan, 

> @hsiangkao,
> latest updates in `dev` branch
> should fix all previously reported `_destSize()` related problems.
> 
> While the test system has been upgraded to challenge and control this interface more aggressively,
> there is still a chance that your own test suite, presumably centered around `erofs`,
> may prove more thorough in some regards, and could unveil remaining weaknesses.
> 
> It would be great if you can find the time to challenge the `dev` version on your CI test environment,
> as we are gearing towards v1.9.3 release.

Yeah, I will test the dev branch later (national holiday state now). If I could find something strange, I will raise another issue later. :)

I think it can be closed for now, or it can reopen later. Thanks for hard effort on this! 

Thanks, 
Gao Xiang

**Comment by hsiangkao** [comment]
some minor preliminary test update (can be ignored): I've done my own test with no regression so far.
I will ask for further integrated testing later.
