### ISSUE TITLE
Potential optimization: Use restrict keyword on LZ4_wildCopy8?

### ISSUE THREAD

**Issue by zerodefect** [lz4/lz4#788]
Would there be any performance improvement using the __restrict__ keyword on the LZ4_wildCopy8(..) function?  I'm guessing there is no overlapping between src/dst?

I've done a quick comparison in godbolt comparing the generated assembly with (and without) the use of the keyword. The compilers look to struggle to generate concise code without the use of the keyword. This looks equally applicable to both gcc 9 and clang 8. I don't have access to MSVS.

https://godbolt.org/z/nJOCHX

We would need to probably incorporate a #define because I believe that the availability of the keyword would not be uniform across environments (c99 only?).

**Comment by Cyan4973** [comment]
This is likely applicable when copying literals,
but more risky when applied to match copies.

The only condition for `wildCopy8` is that `src` and `dst` get separated by a distance of at least 8.
But match may still overlap, which would violate `restrict` contract.
Ensuring this contract would require another condition (that distance is >= match length), hence another test, hence a potential branch miss, on top of more code, right in the hot loop, so it's unclear if the final outcome would still be beneficial.

Testing this optimization could start with the first case, literals copy, which is less complex. Even there, there is a need to check if it really provides any measurable benefit.

Finally, it seems that the large instruction count visible in `godbolt` is related to an ill-attempt at auto-vectorizing the loop. This is likely a larger contributor, and may ultimately be a bad choice for speed. Hence, it is another possible route for optimization.

https://godbolt.org/z/hpY3g4 (without vectorization, both assembly look similar)

**Comment by Cyan4973** [comment]
cc @mgrice

**Comment by zerodefect** [comment]
Thanks for the quick response. I think there could be a chance to squeeze out some more performance.

**Comment by zerodefect** [comment]
The other thing I had considered is trying something like:

```
    auto diff = std::abs(static_cast<const BYTE *>(srcPtr) - static_cast<const BYTE *>(dstPtr));

    while (d + diff < dstEnd+8)
    {
        memcpy(d, s, diff); d+=diff; s+=diff;
    }
```

...but the mileage there would vary greatly if the diff is normally only 8 bytes. (Note: Untested). 

Just throwing around some ideas :)

**Comment by zerodefect** [comment]
It hopefully goes without saying, that the above code would still need existing code to handle remainder bytes.

**Comment by hsiangkao** [comment]
If it really works, maybe inplace decompression could be needed to resolve (such as in separated path)... (for long literal sequences, overlapped LZ4_wildCopy8 could happen)
since in the view of user scenarios, extra memory allocation and memcpy could be extra overhead than this improvement..
