### ISSUE TITLE
Detect if payload is compressed

### ISSUE THREAD

**Issue by archerian** [lz4/lz4#799]
Hello,

Is there a way to check a char array to confirm its lz4 compressed? Getting optionally lz4 compressed data, wanted to see if there was a way to confirm its compressed and if so decompress else process as-is.

Thanks

**Comment by Cyan4973** [comment]
If it's compressed using the [Frame format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md), which is the default format when using the `lz4` CLI, then yes : it's enough to read the first 4 bytes, and compare to the `lz4` magic number.

If it's a raw compressed lz4 block, then unfortunately no, there is no easy signal. Decompression must be attempted, and if if fails, it can be assumed that it's not an lz4 block.

**Comment by archerian** [comment]
Thanks, I will check the return vale for LZ4_decompress_safe for a negative value.
