### ISSUE TITLE
Link address makes misunderstanding

### ISSUE THREAD

**Issue by zhengjunling** [lz4/lz4#805]
Link: https://github.com/lz4/lz4/archive/v1.8.3.tar.gz
Archive name: lz4-1.8.3.tar.gz

From link address, users may treat v1.8.3.tar.gz as the archive name, however, actually, the archive name is lz4-1.8.3.tar.gz.

**Comment by Cyan4973** [comment]
That's the usual link and archive names produced by github,
there's very little one can do about it,
if the tag was modified into `lz4-1.8.3`, then the associated archive would be named `lz4-lz4-v1.8.3`, which is no better.

**Comment by zhengjunling** [comment]
> This is the way it works on github,
> there's very little one can do about it,
> if the tag was modified into `lz4-1.8.3`, then the associated archive would be named `lz4-lz4-v1.8.3`, which is no better.

I'm talking about the link address, not about tag name. Should the link address transfer to: https://github.com/lz4/lz4/archive/lz4-1.8.3.tar.gz ?

**Comment by Cyan4973** [comment]
Note that there are many possible links on the website, so it's important to be accurate about which one is the topic.

The link leading to https://github.com/lz4/lz4/archive/lz4-1.8.3.tar.gz is, as far as I know, the "Source code (tar.gz)" link in the ["Assets" section](https://github.com/lz4/lz4/releases/tag/v1.8.3).
As mentioned previously, this link and its name are automatically generated by Github, based on the tag.
