### ISSUE TITLE
Question: Can the "Framed Encoding Header Magic Number" alias with a "Block Encoding"?

### ISSUE THREAD

**Issue by martinradev** [lz4/lz4#806]
For one library we have been using lz4's block compression and storing the size in some separate structure.
However, we are considering switching to lz4's framed compression which adds a frame header the first 4 bytes of which is the following magic number: 0x184D2204U.
Unfortunately, there are already many files already created out-of-our reach using lz4's block compression. We would like to handle the transition gracefully.

My question is: can we determine 100% of the time whether we are parsing a file which was compressed using lz4's block compression or frame compression?

Reading the specification, it seems that the magic number 0x184D2204U, if interpreted as a block header, would mean 0 literal bytes and an offset of 0x4D22. Thus, if we read the first 4 bytes of a file, since there are no decoded literals, such an offset is invalid and we can be sure that:
1. if this is a block encoding header, the file is somehow corrupted/invalid.
2. if it's a valid lz4 compressed file, then it must be using frame compression.
Is this correct?

**Comment by Cyan4973** [comment]
Yes, correct.

The LZ4 frame magic number can only be a valid sequence at the beginning of a new block _if_ said block follows some other blocks, or a dictionary, _and_ is allowed to reference into them. If the implementation never does that, which is common, then it can't be correct.

FYI, the LZ4 frame header also contains a 1 byte checksum. Therefore, when the first few bytes of the stream can be interpreted as a valid LZ4 frame header, it pretty much seal the deal.

One generic way to handle such scenario is to interpret any bytestream starting with the LZ4 frame magic header as a LZ4 frame, which is almost always correct, and then backup to block mode if it fails and there exists a slight chance that it could be a valid block.
But in some cases, another problem shows up : an LZ4 block requires some additional metadata to be decodable, while an LZ4 frame doesn't. Therefore, the presence of such metadata is also indicative if this is supposed to be a block or a frame. Without metadata (compressed size, and maximum bound of decompressed size), it's more difficult if not impractical to "backup to block mode".

**Comment by martinradev** [comment]
This answers my concern. Thank you. Closing.
