### ISSUE TITLE
lz4 compression is only using a single core?

### ISSUE THREAD

**Issue by chrissound** [lz4/lz4#807]
I'm using cat largeFile.iso | lz4 -10 - and it's going quite slowly (30mb/s?).

Using htop I see it using only a single core to 100%? Are there any additional parameters I need to specify? I can't seem to find any relevant info about this in lz4 --help.

**Comment by Cyan4973** [comment]
There is no multi-threading provided by `lz4` command line utility.

**Comment by chrissound** [comment]
After reading the readme and seeing "providing compression speed > 500 MB/s per core, scalable with multi-cores CPU" this did give me the idea that it does support multiple cores. 

I very much appreciate having this project as open source, though I do think that quote is a bit misleading.

**Comment by Cyan4973** [comment]
`liblz4` is _multithreadable_, that's generally the way it's used in most server-side applications.
In this environment, a user application will often spawn a lot of threads, each one doing some compression at some point in the pipeline. The property mentioned guarantees there is no risk compressing simultaneously from multiple threads. We do have other tools that have checked that the compression speed increase from multi-threading is effectively linear.

`lz4`, the reference CLI, as a user program of `liblz4`, could use this capability to offer a multithreading mode. It doesn't, at least not yet.

There used to be a Windows-only variant of `lz4` which was offering multi-threading. It was non-portable, closed source and is now discontinued.

**Comment by juwens** [comment]
@chrissound i've came here for the very same reason.
the mentioned project is https://github.com/t-mat/lz4mt
there's also a go project which just implemented a kind of concurrency: https://github.com/pierrec/lz4

**Comment by smith558** [comment]
> After reading the readme and seeing "providing compression speed > 500 MB/s per core, scalable with multi-cores CPU" this did give me the idea that it does support multiple cores.
> 
> I very much appreciate having this project as open source, though I do think that quote is a bit misleading.

Came here due to the same reason. Also think the doc should be clarified.

**Comment by corneliusroemer** [comment]
I love your work on zstd/lz4! The man page that comes with the cli is misleading though, this would be good to be fixed.

**Comment by Cyan4973** [comment]
Reading the introduction paragraph of the `lz4` `man` page,
you are correct that the statement regarding multi-threadable properties is only applicable to `liblz4` the library,
and not to the `lz4` CLI.
This is confusing, given that the `man` page is supposed to describe the `lz4` CLI.

This will be fixed from now on (#1331).
