### ISSUE TITLE
verbose mode doesn't provide additional details

### ISSUE THREAD

**Issue by vidyasagargc** [lz4/lz4#813]
When the following command is executed
 `lz4 -v <file_name >` / `lz4 -d -v <file_name.lz4>`

Block size and time duration took to complete either compression/decompression are not getting displayed

**Actual output:**
`*** LZ4 command line interface 64-bits v1.8.3, by Yann Collet ***`
`Compressed filename will be : file1.lz4 `
`Compressed 1073741824 bytes into 4214543 bytes ==> 0.39%  `

**Expected output:**
`*** LZ4 command line interface 64-bits r128, by Yann Collet (Feb 17 2016) ***`
`Blocks size : 4096 KB`
`Compressed filename will be : file1.lz4 `
`Compressed 1073741824 bytes into 4214543 bytes ==> 0.39%   `                    
`Completed in 0.37 sec `

**Comment by Cyan4973** [comment]
These information are displayed when using the _very verbose_ command `-vv`.

**Comment by vidyasagargc** [comment]
It's working as expected, thanks.

**lz4 -vv file** 

*** LZ4 command line interface 64-bits v1.8.3, by Yann Collet ***
_POSIX_C_SOURCE defined: 200112L
_POSIX_VERSION defined: 200112L
PLATFORM_POSIX_VERSION defined: 200112L
Compressed filename will be : file.lz4 
Compressed 1024000000 bytes into 4019314 bytes ==> 0.39%                       
**Completed in 2.41 sec  (cpu load : 93%)**
