### ISSUE TITLE
There's a chance to introduce GitHub's issue templates

### ISSUE THREAD

**Issue by t-mat** [lz4/lz4#819]
Subject: Can we introduce [GitHub's issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) to this project?

Recently, actually recent 24 months ;) , I've observed that there're many vague issues here GitHub issues of LZ4 project.
And also I can say that there're many users and potential contributors who are struggling to express their issue/problem/concern/impressions.

I think GitHub's issue templates helps them a lot.  Because it has been designed to help normal/ordinal people who doesn't have technical/bare-metal computing background.
Especially for this project, there must be many people who doesn't have experience with bare-metal computer language (such as C/C++) but also has interest high performance computing and compression.

----
For example, `electron` project has [their own template](https://github.com/electron/electron/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) and their typical issue looks like this one `https://github.com/electron/electron/issues/21309` .

----
EDIT: I removed direct link to electron project's issue to avoid auto issue linking.  I'm sorry if someone from the team is looking this issue.

**Comment by Cyan4973** [comment]
Thanks for suggestion @t-mat !
Issue templates have been recently implemented by @bimbashrestha
