### ISSUE TITLE
LZ4_resetStream_fast in LZ4_attach_dictionary doesn't make sense any more

### ISSUE THREAD

**Issue by buweilv** [lz4/lz4#822]
function "LZ4_resetStream_fast" is added in LZ4_attach_dictionary at commit "f2ae385c2f" in order to make sure that changes will not be erased by subsequent calls to LZ4_resetStream_fast() in case stream was marked as having dirty context, e.g. requiring full reset.
Correspondingly， when LZ4_compress_generic goto failure cctx->dirtyContext is set to 1. However, now,  LZ4_compress_generic goto failure , no cctx->dirty would be set. So  `if (cctx->dirty)` in function LZ4_resetStream_fast makes no sense. No body will set this variable to 1.

**Comment by felixhandte** [comment]
Hi @buweilv,

Thanks for bringing this to our attention! Sorry it took so long to get to this. I believe you're correct. `dirty` is never set by our codebase. It remains only to detect uninitialized memory passed in by users, for which it isn't really sufficient. So I've put up #892 to remove this.
