### ISSUE TITLE
Apple Non-public API usage _LZ4_decompress_safe

### ISSUE THREAD

**Issue by reybits** [lz4/lz4#824]
Yesterday, when I uploaded app binary in Apple AppStore Connect, I received the following error message:

> ITMS-90338: Non-public API usage - The app references non-public symbols in MY_APP_NAME: _LZ4_decompress_safe. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions.

Can someone advise a way to solve the problem?

**Comment by Cyan4973** [comment]
I presume that's because Apple already offers a public symbol named `LZ4_decompress_safe()` for `iOS` applications ?

**Comment by 15393713650** [comment]
@andreyugolnik 
I also encountered the same problem. How did you solve it? I didn't find the code of "lz4" in my project
