### ISSUE TITLE
MS Visual Studio under Cygwin ?

### ISSUE THREAD

**Issue by nrgiii** [lz4/lz4#828]
We build lz4 under cygwin using MS Visual Studio command line invocations of cl and link. The makefiles that come with lz4 do not support this so, we roll our own.  Does anyone else do MS windows builds this way?  Any interest supporting this build configuration?  If so, I can try to update the makefiles that ship with lz4 and submit a PR.  If not, we will keep rolling our own.

Norm Green

**Comment by sunny-shu** [comment]
Hello, may I ask what version Visual Studio is? The purpose is to reproduce the problem. I am very interested in building.

**Comment by Cyan4973** [comment]
The `lz4` project features a `/contrib` directory where it's possible to host such contributions
