### ISSUE TITLE
lz4.h is trying to use undefined __GNUC__

### ISSUE THREAD

**Issue by mojca** [lz4/lz4#832]
Super low priority issue.

When compiling `lz4` as part of another library with clang in Visual Studio, I'm getting a warning about undefined `__GNUC__`:
```
lz4/lz4.h(673,10): warning : '__GNUC__' is not defined, evaluates to 0
```
which comes from admittedly "obsolete" corner of the code and which probably ends up in correct branch anyway:
```c
#ifdef LZ4_DISABLE_DEPRECATE_WARNINGS
#  define LZ4_DEPRECATED(message)   /* disable deprecation warnings */
#else
#  define LZ4_GCC_VERSION (__GNUC__ * 100 + __GNUC_MINOR__)
#  if defined (__cplusplus) && (__cplusplus >= 201402) /* C++14 or greater */
#    define LZ4_DEPRECATED(message) [[deprecated(message)]]
#  elif (LZ4_GCC_VERSION >= 405) || defined(__clang__)
#    define LZ4_DEPRECATED(message) __attribute__((deprecated(message)))
#  elif (LZ4_GCC_VERSION >= 301)
#    define LZ4_DEPRECATED(message) __attribute__((deprecated))
#  elif defined(_MSC_VER)
#    define LZ4_DEPRECATED(message) __declspec(deprecated(message))
#  else
#    pragma message("WARNING: You need to implement LZ4_DEPRECATED for this compiler")
#    define LZ4_DEPRECATED(message)
#  endif
#endif /* LZ4_DISABLE_DEPRECATE_WARNINGS */
```

**Comment by Cyan4973** [comment]
Thank for the notification @mojca !

Quick question :
we happen to have some Visual Studio compilation test, like this one : 
https://ci.appveyor.com/project/YannCollet/lz4-1lndh/builds/30391407/job/cl9ciecqgjtraiuj

but, for some reason, they don't trigger this warning.

Any idea what could be done to make the test produce the same "undefined" warning ?

**Comment by mojca** [comment]
First of all: You are using Visual Studio 10 which is pretty old. I suspect that clang came bundled with VS out of the box only in Visual Studio [16.1](https://devblogs.microsoft.com/cppblog/clang-llvm-support-in-visual-studio/). Out-of-the-box as in: you still need to explicitly install it, but it's just a click of a button as opposed to downloading from third-party website and tweaking build system in strange ways.

Second: You need to explicitly enable clang as the compiler. In CMake this can be done with `-T ClangCL` parameter, I never tried with other command-line builds.

Third: it might depend on compiler flags. I think we even added `/Wall`, but it could be that the warning is also visible without it, I would have to test.

**Comment by mojca** [comment]
I see that you also have a Visual Studio project for 2017. You would have to create one for 2019 and explicitly change the toolchain, so you would basically need to have two separate project files (one for the default compiler and one for clang; and then more if you want to test with different versions of VS) if you want to use them in CI. It might help to create CMake and generate VS project on the fly, but that's outside of the scope of this ticket :)

**Comment by Cyan4973** [comment]
> Second: You need to explicitly enable clang as the compiler.

You are using Visual Studio with `clang` as back-end compiler ?
Indeed, that's a combination that's not part of our current CI.

Note that we do have a `clang` test, but it's based on `msys2` environment.

`clang` normally defines `__GNUC__ ` by default.
That's the case for `clang` on `msys2`, hence there is no "undefined" warning.

But, apparently, `clang` for Visual Studio doesn't define `__GNUC__` ?

**Comment by mojca** [comment]
Sorry, I don't distinguish backend from frontend in compiler nomenclature :), but yes, I'm using clang as explained above.

Yes, clang definitely defines `__GNUC__` on macOS as well, but all I can tell you is that it's completely useless there as  it's always "gcc 4.2", and clang versions are not the most straightforward to extract after Apple mangles with numbering scheme.

Judging from this warning it apparently doesn't define it on MSVC. I don't really have much milleage with MSVC.

**Comment by ojeda** [comment]
@Cyan4973 `clang-cl` defines `_MSC_VER` instead because it is intended as a drop-in replacement for MSVC, so nothing special to be done for it.

The question becomes: why are we not seeing the warning for regular MSVC? It does not seem to appear in AppVeyor (is something defining `__GNUC__`?).

@mojca Can you please try building with the normal MSVC in your setup to see if the warning appears?
