### ISSUE TITLE
Archivo lz4 1.9,2 para win 32 

### ISSUE THREAD

**Issue by entrebites** [lz4/lz4#836]
Al descargar el ejecutable .exe de Lz4  resulta imposible su instalacion en winows 7 lo he provado en varias pc. hay algun requisito gracias...

**Comment by sunny-shu** [comment]
1. Download lz4_win32_v1_9_2.zip, directly extract, there is lz4.exe, do not need any special installation
2. Make sure you include both the library path DLL and header path into your system environment.

**Comment by Cyan4973** [comment]
I guess the answer of @361442342 looks correct.
Where you expecting some kind of Windows Installer ?

**Comment by ojeda** [comment]
Perhaps they are referring to #787?
