### ISSUE TITLE
LZ4HC_compress_optimal stack frame is too big

### ISSUE THREAD

**Issue by Yanpas** [lz4/lz4#837]
We are using coroutines, which are 32kb size by default. This function has the following variable:
```c
LZ4HC_optimal_t opt[LZ4_OPT_NUM + TRAILING_LITERALS];
```
which is 64kb.

There is already defined macro LZ4HC_HEAPMODE 1, but unfortunately it is used only for LZ4_streamHC_t

**Comment by Cyan4973** [comment]
Yes, I agree, this is indeed too big for some stack, and it would be better to have an option to pass that to heap.

**Comment by remittor** [comment]
@Yanpas,
`opt` pointer should be stored in HC context.
