### ISSUE TITLE
Comp speed regression on 1.9.2 on multiple corpus

### ISSUE THREAD

**Issue by JonKohler** [lz4/lz4#845]
I'm working on a project to upgrade our use of LZ4 from 1.7.1 to 1.9.2. 

Part of our regression suite is a compression performance test that we use benchmark speed/ratio for many compression algos, including both lz4 and lz4hc.

We're seeing regressions in comp speeds across all of the corpus for both LZ4 and LZ4HC. We use Canterbury, Silesia, and Enron. 

I've run our test a few dozen times for both 1.7.1 and 1.9.2 and results are always the same. This is on a server with 2x Intel 8168 and 768G DDR4 memory.

From our util side, our compress and decompress calls are pretty basic. Here's a small snippet. Note: We use acceleration == 3 and HC level == 6

I'm happy to help dig in if there is additional data points or questions, but I'm stuck on this upgrade until I can figure out what's going sideways :( 

```
///// Compress path
.....
    if (use_high_compress) {
      // We do not use LZ4_compress_HC() which allocates the state internally
      // from the stack. The state is about 256k. This casues LZ4_compress_HC()
      // hits sigsegv while memsetting the state in certain tests. Instead, we
      // allocate the state ourselves.
      CharArray state(LZ4_sizeofStateHC());
      compressed_size = LZ4_compress_HC_extStateHC(
        state.data(), inp_data, compressed_array->data() + block_header_size,
        size_to_compress, max_compress_size, lz4hc_compression_level);
    } else {
      compressed_size = LZ4_compress_fast(
        inp_data, compressed_array->data() + block_header_size,
        size_to_compress, max_compress_size, lz4_acceleration);
    }
.....

///// Decompress path
.....
    CharArray::Ptr uncompressed_array =
      make_shared<CharArray>(uncompressed_size);
    const int ret = LZ4_decompress_safe(
      compressed_data,
      uncompressed_array->data(),
      compressed_size,
      uncompressed_size);
.....
```

**Existing 1.7.1 benchmark**
```
Compression type:      lz4  comp_ratio(%): 46.81  comp_speed(MBps):  728.981  decomp_speed(MBps): 1838.373
Compression type:    lz4hc  comp_ratio(%): 36.52  comp_speed(MBps):  108.977  decomp_speed(MBps): 1928.401
Compression: lz4hc
  File:   l_20150507  comp_ratio(%): 35.64  comp_speed(MBps):  114.798  decomp_speed(MBps): 1940.005
  File:   estcalgary  comp_ratio(%): 45.70  comp_speed(MBps):   75.918  decomp_speed(MBps): 1851.211
  File:   stcantrbry  comp_ratio(%): 38.25  comp_speed(MBps):   65.776  decomp_speed(MBps): 1941.583
  File:   _testlarge  comp_ratio(%): 45.08  comp_speed(MBps):   31.369  decomp_speed(MBps): 1775.509
  File:   startificl  comp_ratio(%): 33.14  comp_speed(MBps):  302.362  decomp_speed(MBps): 2844.444
  File:   s_testmisc  comp_ratio(%): 73.52  comp_speed(MBps):   71.076  decomp_speed(MBps): 1359.783
  File:   estsilesia  comp_ratio(%): 43.35  comp_speed(MBps):   84.557  decomp_speed(MBps): 1845.631
Compression: lz4
  File:   l_20150507  comp_ratio(%): 45.94  comp_speed(MBps):  739.430  decomp_speed(MBps): 1839.649
  File:   estcalgary  comp_ratio(%): 58.86  comp_speed(MBps):  579.818  decomp_speed(MBps): 1750.019
  File:   stcantrbry  comp_ratio(%): 47.92  comp_speed(MBps):  613.420  decomp_speed(MBps): 1872.011
  File:   _testlarge  comp_ratio(%): 57.71  comp_speed(MBps):  462.930  decomp_speed(MBps): 1550.580
  File:   startificl  comp_ratio(%): 33.18  comp_speed(MBps): 3167.010  decomp_speed(MBps): 3041.584
  File:   s_testmisc  comp_ratio(%): 98.32  comp_speed(MBps): 1228.299  decomp_speed(MBps): 2573.128
  File:   estsilesia  comp_ratio(%): 53.31  comp_speed(MBps):  670.118  decomp_speed(MBps): 1842.839
```

**1.9.2 benchmark results**
```
Compression type:      lz4  comp_ratio(%): 44.88  comp_speed(MBps):  609.390  decomp_speed(MBps): 2191.344
Compression type:    lz4hc  comp_ratio(%): 36.49  comp_speed(MBps):  101.153  decomp_speed(MBps): 2357.520
Compression: lz4hc
  File:   l_20150507  comp_ratio(%): 35.61  comp_speed(MBps):  106.005  decomp_speed(MBps): 2378.564
  File:   estcalgary  comp_ratio(%): 45.64  comp_speed(MBps):   72.168  decomp_speed(MBps): 2206.443
  File:   stcantrbry  comp_ratio(%): 38.18  comp_speed(MBps):   59.341  decomp_speed(MBps): 2166.759
  File:   _testlarge  comp_ratio(%): 44.94  comp_speed(MBps):   32.990  decomp_speed(MBps): 2033.635
  File:   startificl  comp_ratio(%): 33.14  comp_speed(MBps):  242.846  decomp_speed(MBps): 3011.765
  File:   s_testmisc  comp_ratio(%): 73.52  comp_speed(MBps):   68.640  decomp_speed(MBps): 1511.325
  File:   estsilesia  comp_ratio(%): 43.29  comp_speed(MBps):   79.781  decomp_speed(MBps): 2217.503
Compression: lz4
  File:   l_20150507  comp_ratio(%): 43.86  comp_speed(MBps):  615.123  decomp_speed(MBps): 2214.321
  File:   estcalgary  comp_ratio(%): 56.51  comp_speed(MBps):  467.173  decomp_speed(MBps): 2012.037
  File:   stcantrbry  comp_ratio(%): 46.53  comp_speed(MBps):  536.947  decomp_speed(MBps): 2056.210
  File:   _testlarge  comp_ratio(%): 61.89  comp_speed(MBps):  434.310  decomp_speed(MBps): 1578.649
  File:   startificl  comp_ratio(%): 33.18  comp_speed(MBps): 3303.226  decomp_speed(MBps): 3072.000
  File:   s_testmisc  comp_ratio(%): 85.63  comp_speed(MBps):  370.987  decomp_speed(MBps): 1678.127
  File:   estsilesia  comp_ratio(%): 52.41  comp_speed(MBps):  580.050  decomp_speed(MBps): 2056.584
```

**Comment by remittor** [comment]
I confirm it
```
$ ./fullbench -c10 silesia.tar
*** LZ4 speed analyzer v1.7.6 64-bits, by Yann Collet ***
 silesia.tar :
10-LZ4_compress_HC :211947520 -> 78009943 (36.81%), 20.9 MB/s
```
```
$ ./fullbench -c10 silesia.tar
*** LZ4 speed analyzer v1.9.2 64-bits, by Yann Collet ***
 silesia.tar :
10-LZ4_compress_HC : 211947520 -> 78002071 (36.80%), 19.2 MB/s
```

**Comment by JonKohler** [comment]
I've updated the original post with more data and observations and updated the title to reflect what we're seeing. I've also added data from silesia and enron corpus. Same trend over each of them, we're seeing 1.9.2 be slower than our current 1.7.1 implementation

**Comment by Cyan4973** [comment]
There have been much changes between v1.7.1 and v1.9.2, so I'm not too surprised that there are measurable differences between these versions.

On the "fast" LZ4 side, one can note that the measured scenario uses `acceleration = 3`.
This is less common than `acceleration = 0 | 1`.
Under this specific condition, `v1.9.2` is now both slower and compress better than `v1.7.1`.

It could be that a later optimization, probably targeting the "normal" no-acceleration scenario, has a side effect on  how `acceleration` impacts the search process.

One quick work around is to try a different value on `v1.9.2`, such as `acceleration = 4`, which should make it faster, and compress less, and therefore make it maybe more comparable with previous results on `v1.7.1`.

On the "high compression" side, changes have been a lot more substantial.
There are different categories. To being with, very high levels, >= 10, now have a dedicated, different, search and parsing algorithm.
This is not applicable to your scenario, which uses `clevel=6`, but explains @remittor 's results (although he compares an unexpected `v1.7.6` to `v1.9.2` (`v1.7.6` was never released), rather than `v1.7.1`).

For level 6, updates are less drastic, but there are still changes, typically trying to mitigate some detrimental corner cases which disproportionally impact performance, but at the cost of a bit of performance essentially all the time. One can also note that compression ratio is _slightly_ improved, which is a side effect of this strategy, which skips faster through the list of (useless) candidates, and tends to find better matches when offered the same limited search budget, but do _more_ work in the same budget.

That being said, most of this "new stuff" is supposed to be disabled for level 6, so I'm surprised it leaves such a measurable impact.

**Comment by JonKohler** [comment]
Thanks for the detailed response @Cyan4973 

To compare some high levels for HC, I've measured 3-12 step by step. each of the results was almost exactly the same compression level, but the speed, of course, getting slower with each step. 

In between level 6 and level 12, at least on this data, it only makes a ~0.1-0.2-ish % better ratio but is ~3x lower speed. 

Is that expected for HC? I'm trying to figure out if this is a library issue or something else.

Also, I did test different LZ levels just now

- Level 4: 0.23% worse compression vs my baseline (not horrible) but down ~77 MBps.
- Level 5: 2.09% worse, ~42 MBps down
- Level 6: 3.92% worse, break-even speed, about ~.8 MBps up
- Level 7: 5.3% worse, ~~34 MBps up

I did notice that it looks like the worst offender for both ratio slip and speed slip is the Canterbury misc corpus, which is just the first 1M digits of PI - http://corpus.canterbury.ac.nz/descriptions/#misc

In 1.7.1, it hardly did any compression (98.32) and 1228 MBps. With 1.9.2 at the same accel 3, it is now doing some compression (85.63) and down to 370.987 MBps. I don't know how realistic that is for our customer base; however, it's a drastic swing. Thoughts?


**1.9.2 accel 4, lzhc 12**
```
Compression type:      lz4  comp_ratio(%): 47.04  comp_speed(MBps):  651.413  decomp_speed(MBps): 2204.885
Compression type:    lz4hc  comp_ratio(%): 36.33  comp_speed(MBps):   30.357  decomp_speed(MBps): 2368.845
Compression: lz4hc
  File:   l_20150507  comp_ratio(%): 35.48  comp_speed(MBps):   33.008  decomp_speed(MBps): 2387.254
  File:   estcalgary  comp_ratio(%): 45.40  comp_speed(MBps):   21.502  decomp_speed(MBps): 2201.980
  File:   stcantrbry  comp_ratio(%): 37.94  comp_speed(MBps):    6.861  decomp_speed(MBps): 2063.731
  File:   _testlarge  comp_ratio(%): 43.01  comp_speed(MBps):    9.234  decomp_speed(MBps): 2049.692
  File:   startificl  comp_ratio(%): 33.14  comp_speed(MBps):  180.070  decomp_speed(MBps): 3011.765
  File:   s_testmisc  comp_ratio(%): 73.27  comp_speed(MBps):   26.682  decomp_speed(MBps): 1445.994
  File:   estsilesia  comp_ratio(%): 43.00  comp_speed(MBps):   19.986  decomp_speed(MBps): 2251.158
Compression: lz4
  File:   l_20150507  comp_ratio(%): 46.17  comp_speed(MBps):  660.163  decomp_speed(MBps): 2227.497
  File:   estcalgary  comp_ratio(%): 58.57  comp_speed(MBps):  494.853  decomp_speed(MBps): 2023.257
  File:   stcantrbry  comp_ratio(%): 47.67  comp_speed(MBps):  556.434  decomp_speed(MBps): 2082.007
  File:   _testlarge  comp_ratio(%): 63.14  comp_speed(MBps):  443.983  decomp_speed(MBps): 1592.613
  File:   startificl  comp_ratio(%): 33.17  comp_speed(MBps): 3167.010  decomp_speed(MBps): 3167.010
  File:   s_testmisc  comp_ratio(%): 88.17  comp_speed(MBps):  426.848  decomp_speed(MBps): 1748.293
  File:   estsilesia  comp_ratio(%): 53.38  comp_speed(MBps):  602.653  decomp_speed(MBps): 2072.065
```

**Comment by Cyan4973** [comment]
I have no obvious idea to explain these performance swings. I will need more time for a thorough investigation.
What would be useful at this stage is a bisection, in order to detect which version(s) have introduced a performance change. This would point to some more precise code changes, and make it easier to arbitrate.

**Comment by Cyan4973** [comment]
I made a quick check, comparing `v1.7.3` to latest `dev` branch.

For "normal" `lz4`, I measure a < 1% compression speed reduction, and an identical compression ratio. Decompression speed, on the other hand, is dramatically improved.

For "accelerated" `lz4`, a strange thing is : I actually measure an _improved_ speed, of `dev` compared to `v1.7.3`, but with a corresponding _reduction_ of compression ratio. So that's the polar opposite of what was reported.

That's pretty strange.
I will try to benchmark other versions, to try to reproduce your result.
Also : my test corpus do not contain `pi.txt`, so I'll try to add it too.

**Comment by Cyan4973** [comment]
I've been updating my bench setup to get exactly the same version as the ones reported (`v1.7.1`, aka `r131`, vs `v1.9.2` (not `dev`)).

I measured again speed and compression ratio, using `calgary.tar`, and separately `pi.txt`.
Here are the results : 

| file | version | acceleration | Compression Speed | Compressed Size | Decompression Speed |
| --- | --- | --- | --- | --- | --- |
| pi.txt | v1.7.1 | 0 | 483 | 948970 | 1970 |
| pi.txt | v1.9.2 | 0 | 499 | 948970 | 3066 |
| calgary.tar | v1.7.1 | 0 | 444 | 1623291 | 1270 |
| calgary.tar | v1.9.2 | 0 | 438 | 1623291 | 3270 |
| pi.txt | v1.7.1 | 3 | 1056 | 980824 | 4200 |
| pi.txt | v1.9.2 | 3 | 1317 | 986338 | 7500 |
| calgary.tar | v1.7.1 | 3 | 519 | 1780917 | 1400 |
| calgary.tar | v1.9.2 | 3 | 541 | 1853702 | 3130 |

Once again, with no acceleration, both versions are comparable, but with the same acceleration level (==3), the new version `v1.9.2` is actually _faster_ but compress _less_ than `v1.7.1`.

I'm at a loss to explain the differences between our observations.

Speed _could_ be explained by looking into compiler versions and compiler flags. But compression ratio, on the other hand, should remain identical across observations, whatever the compiler.

**Comment by JonKohler** [comment]
Thanks @Cyan4973 - I've been spending my evening trying to figure this out as well. It's a real head scratcher. We're using the same compiler setup on both configurations, GCC 7.3.0 with a myriad of flags (but albeit the same for each toolchain). I'll try to monkey with that, as well as trying to reproduce this on fullbench or lzbench or (something else) rather than our own UT to see if we can get a correlation on a common toolset

**Comment by terrelln** [comment]
I'm comparing v1.7.1 (r131) against v1.9.2 and I'm a bit confused. On calgary.tar I've measured exactly the same output size and compression speed for every acceleration value from 1 to 3 when compiling with gcc-7 or gcc-10. Compiling with clang-10 v1.9.2 is faster.

I believe that the analysis that @Cyan4973 did has an off by one error. I believe that he was comparing acceleration=3 on v1.9.2 to acceleration=2 on v1.7.1.

So, overall, I also have not been able to reproduce this issue. And I find that the accelerations correspond 1:1 from v1.7.1 to v1.9.2, and speed has stayed the same or improved.

I see that you are seeing both a compression ratio improvement and a speed loss for `LZ4_compress_fast()`. Is it possible that you were somehow comparing acceleration=3 on v1.7.1 against acceleration=2 on v1.9.2?
