### ISSUE TITLE
Undefined behavior with clang 11 ("runtime error: applying zero offset to null pointer")

### ISSUE THREAD

**Issue by traversc** [lz4/lz4#847]
I believe the issue appears in two places (and possibly elsewhere)

https://github.com/lz4/lz4/blob/dev/lib/lz4.c#L822

https://github.com/lz4/lz4/blob/dev/lib/lz4.c#L830-L832

Here is a minimal example of the issue: [https://godbolt.org/z/g85jN_](https://godbolt.org/z/g85jN_)
(The error message doesn't appear on earlier versions of clang)

**Comment by mrks** [comment]
Ran into the same thing using clang 10 (from brew) on Mac. @traversc - your godbolt link is broken.

**Comment by traversc** [comment]
@mrks thanks for pointing that out, there was an underscore at the end of the link that github didn't properly captured.  Fixed.
