### ISSUE TITLE
Is LZ4_MEMORY_USAGE the granularity of compression in LZ4 "Block" API?

### ISSUE THREAD

**Issue by Yang-YiFan** [lz4/lz4#848]
The description of LZ4_MEMORY_USAGE is not clear to me. Is LZ4_MEMORY_USAGE in [lz4.c](https://github.com/lz4/lz4/blob/dev/lib/lz4.c) the compression block size described in [streaming_api_basics.md](https://github.com/lz4/lz4/blob/dev/examples/streaming_api_basics.md)?

**Comment by Cyan4973** [comment]
`LZ4_MEMORY_USAGE` refers to the size of the compressor state, aka the active memory required for the compression to work, _on top of_ the input and output buffers.

The LZ4 compression state is described here : 
https://github.com/lz4/lz4/blob/v1.9.2/lib/lz4.h#L563.

The vast majority of its size is controlled by `hashTable`, which is itself sized to occupy the space specified by `LZ4_MEMORY_USAGE`.

input and output buffers can have any size, this doesn't change the size of the LZ4 state.

A block is simply the size of an input buffer compressed in a single invocation.

**Comment by Yang-YiFan** [comment]
If I want to compress a huge input array in, for example, 4KB block granularity. Are you suggesting that I have to manually slice input array into 4KB blocks and invoke lz4 individually on each block to compress them?
A related question is that does each block (after compression) contain its own header (lz4 state/hash table) in "Block" API compression mode?

**Comment by Cyan4973** [comment]
> Are you suggesting that I have to manually slice input array into 4KB blocks and invoke lz4 individually on each block to compress them?

yep

> does each block (after compression) contain its own header (lz4 state/hash table) in "Block" API compression mode?

nope, the block mode doesn't store _any_ metadata, it has to be provide by any other way.
The reasoning is, there are so many ways metadata can be transported or inferred that it felt too restrictive to impose a "universal" one.

That being said, there is another format that does all this, it's the LZ4 frame format. This one is published in `lz4frame.h`, it does cut large input streams into smaller blocks, of controllable size.
On the API side, just add data using the wanted block size (4 KB), each invocation produces a block.

On the CLI side, it's even simpler : state the wanted block size on the command line.
For example : 
`lz4 -B4096 file` 
will cut `file` into small independent blocks of 4096 bytes, compress them, concatenate them in a single LZ4 frame, and add all required metadata to make it decodable by any other LZ4 frame decoder.

**Comment by Yang-YiFan** [comment]
Awesome! Does the LZ4 frame format have inter-block dependency?

**Comment by Cyan4973** [comment]
By default, blocks are independent,
but blocks can be made dependent by adding `-BD` on the command line.

**Comment by Yang-YiFan** [comment]
Thank you so much! It's very helpful.
