### ISSUE TITLE
LZ4_FORCE_INLINE has a performance hit

### ISSUE THREAD

**Issue by dimtass** [lz4/lz4#849]
**Describe the bug**
First of all it's not really a bug, but it's not a feature, too; therefore I create this as a bug.

I've did some tests on the compression algorithm using an STM32F303CC microcontroller and the GCC 9 compiler. This MCU has a Cortex-M4 core. I've tried to place the `LZ4_compress_generic()` function in FLASH, SRAM and CCM and run some benchmarks and I've found out that the `LZ4_FORCE_INLINE` actually has a hit in the performance as the GCC compiler is able to do a better optimization.

I've written a more detail post [here](https://www.stupid-projects.com/using-ccm-on-stm32f303cc/)

**To Reproduce**
1. Download the sample code:
```sh
cd ~/Downloads
git clone https://dimtass@bitbucket.org/dimtass/stm32f303-ccmram-test.git
cd stm32f303-ccmram-test
```
2. Build the default code using the `LZ4_FORCE_INLINE`
```sh
docker run --rm -it -v $(pwd):/tmp -w=/tmp dimtass/stm32-cde-image:0.1 -c "USE_CCM=OFF USE_SRAM=OFF USE_FLASH=ON ./build.sh"
```
3. Flash the code on the STM32F303 and wait for the UART output
4. Bulid the code that removes the `LZ4_FORCE_INLINE`
```sh
docker run --rm -it -v $(pwd):/tmp -w=/tmp dimtass/stm32-cde-image:0.1 -c "USE_CCM=OFF USE_SRAM=OFF USE_FLASH=OFF ./build.sh"
```
5. Flash the code on the STM32F303 and wait for the UART output

**Expected behavior**
I expected that the enforced inline improves performance, but it doesn't. The performance is better if the compiler is let to do the optimizations.

**Screenshots**
This is a table with the results:

Block size | w/o LZ4_FORCE_INLINE | w/ LZ4_FORCE_INLINE
-|-|-
16K @72MHz | 466 ms | 631 ms
16K @128MHz | 262 ms | 355 ms

**Desktop (please complete the following information):**
 - OS: baremetal
 - Version: N/A
 - Compiler: gcc-arm-none-eabi-9-2019-q4-major 
 - Build System: Ubuntu (docker)
 - Other hardware specs: STM32F303CC
 - Compiler flags:
```
-mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -mthumb-interwork  -ffast-math -Wall -Werror -Wl,-Map=output.map -Wl,--gc-sections -lm -lc
```

**Additional context**
Suggestion is to let the compiler do the optimizations.

**Comment by felixhandte** [comment]
Ah, I'm not surprised that force-inlining everything could be a pessimization for microcontrollers. LZ4 in general is tuned towards big CPUs, with multiple execution units, deep pipelines, fat instruction caches, etc.

You can always turn off our inlining with `-DLZ4_FORCE_INLINE=static`. Potentially we could even merge a check to see if we're on this sort of platform, and turn it off automatically, but we'd have to have a good way of detecting that situation.

In your benchmark it seems like you're also changing where the code lives between the two scenarios. Is that the case? Can you measure just the difference between inlining and not?

**Comment by dimtass** [comment]
@felixhandte the benchmark is with and without inlining while the code _is running from the FLASH_.

What you see in the code, is another benchmark case where I'm copying the whole function in to two different RAM areas (SRAM and CCRAM) and as expected the performance is much better there. But I've didn't post those results here.

I'm only referring to the difference between w/ and w/o inline when the code runs from the FLASH.

**Comment by Cyan4973** [comment]
Inlining as an optimization policy only works fine on certain architectures and not other ones.
As mentioned, it's no surprise that an optimization intended for servers does not bring benefits for micro-controllers.
The best course of action is to benchmark (as you did) and change manually the inlining decision based on collected metrics.
