### ISSUE TITLE
Visual fails the aligment test on 32-bit x86

### ISSUE THREAD

**Issue by kotnis** [lz4/lz4#851]
Part of code:

#ifndef _MSC_VER  /* for some reason, Visual fails the aligment test on 32-bit x86 :
					 it reports an aligment of 8-bytes,
					 while actually aligning LZ4_stream_t on 4 bytes. */
static size_t LZ4_stream_t_alignment(void)
{
#pragma pack(push, 1) // add this line to fix it!
	struct { char c; LZ4_stream_t t; } t_a;
#pragma pack(pop) // add this line to fix it :)
	return sizeof(t_a) - sizeof(t_a.t);
}
#endif

**Comment by Cyan4973** [comment]
What is the issue ?

The alignment check is already disabled on Visual, to avoid potentially wrong outcome.
