### ISSUE TITLE
LZ4F_compressBound and automatic flushing

### ISSUE THREAD

**Issue by sandyharvie** [lz4/lz4#865]
When automatic flushing is enabled, there will never be any data buffered upon a call to `LZ4F_compressUpdate` or `LZ4F_compressEnd`. There will obviously also not be any data buffered when `LZ4F_compressBegin` is invoked. This behavior, however, is not reflected in `LZ4F_compressBound`. In particular, `LZ4F_compressBound` always invokes `LZ4F_compressBound_internal` with the `alreadyBuffered` parameter set to the maximum possible value. To resolve this, `LZ4F_compressBound` should invoke `LZ4F_compressBound_internal` with the `alreadyBuffered` parameter set to 0 if automatic flushing is enabled.

**Comment by sandyharvie** [comment]
FYI, this causes `LZ4F_compressBound` to return a value that is approximately one block size larger than it should be (when automatic flushing is enabled). This is significant for larger block sizes (and also how I came to discover this).

**Comment by Cyan4973** [comment]
Fixed in #866
