### ISSUE TITLE
LZ4 decompressor for the 6502 CPU

### ISSUE THREAD

**Issue by pararaum** [lz4/lz4#868]
The https://lz4.github.io/lz4/ page links for the 6502 code of the LZ4 decompressor to this site: http://pferrie.host22.com/misc/appleii.htm. Unfortunately the web page is not available anymore.

Could you please add a link to either the copy I did https://github.com/pararaum/lz4-6502 or to the archive.org page? You could just add the code to the project if you like.

Thanks!

**Comment by Cyan4973** [comment]
Thanks for pointing that out @pararaum !
Indeed, internet weblinks tend to age pretty badly...

Link updated
