### ISSUE TITLE
Different language gives different compressed data

### ISSUE THREAD

**Issue by sahilpaudel-pe** [lz4/lz4#870]
I am using lz4 to compress a data, that data is consumed by different application written in Java, Go & Python.
Thankfully, libraries are available for the said languages.

However, the issue is all of them gives different compressed data base64 string for same string.
So the receiving applications are unable to get the expected data.

Is this a expected behaviour or it is a bug?

Eg: Java.decompress(IOS.compress(data)) != data

Thanks.

**Comment by Cyan4973** [comment]
If you are employing ports of `LZ4` in different languages,
be aware that only those listed in the "interoperable" category are presumed to work fine together : 
https://lz4.github.io/lz4/#interoperable-lz4

Other versions may employ different metadata format, and as a consequence be incompatible with each other.

`LZ4` being a lossless algorithm, any iteration of `decompress_variantA(compress_variantB(data)) == data` should always give you back exactly the same original `data`. 
If not, `decompress_variantA` and `compress_variantB` are likely incompatible.

**Comment by felixhandte** [comment]
But it sounds like you're describing something else. Not:

```
impl_B.decompress(impl_A.compress(data)) != data
```

but rather that

```
impl_A.compress(data) != impl_B.compress(data)
```

The first should be the case, but the second is not guaranteed or even expected.

**Comment by sahilpaudel-pe** [comment]
Hi there,
Thank you for your response.
The issue was that lz4 compression was padding additional A's which was causing the issue.
I had to remove those A's incase of Java.
