### ISSUE TITLE
lib/lz4: smatch warning in LZ4_decompress_generic()

### ISSUE THREAD

**Issue by vaverin** [lz4/lz4#872]
Found by smatch in linux kernel:
lib/lz4/lz4_decompress.c:150 LZ4_decompress_generic() warn: maybe use && instead of &

The code was coped from last lz4 mainstream
https://github.com/lz4/lz4/blob/dev/lib/lz4.c#L1865

I believe it is wrong and it was caused by typo in following patch
https://github.com/lz4/lz4/commit/1a191b3f8d26b50a7c1d41590b529ec308d768cd

**Comment by Cyan4973** [comment]
Answer : https://github.com/lz4/lz4/pull/873#issuecomment-640310752
