### ISSUE TITLE
LZ4_compress_generic  - out-of-bounds

### ISSUE THREAD

**Issue by iceman1001** [lz4/lz4#874]
**Describe the bug**
We recently added LZ4 to the Proxmark3 RRG/Iceman repo and we run CI using Travis CI/Appveyor as well as Coverity Scan on the code base.  Coverity report `out-of-bounds`  with a call to LZ4_compress_generic in lz4.c     See picture below.

Now whether or not its a false positive,  I thought of mention it to you. 

**To Reproduce**
Run coverity scan.

**Expected behavior**
Expect the software to compile without any findings in Coverity.

**Screenshots**
![image](https://user-images.githubusercontent.com/8577004/84000799-aac43d80-a965-11ea-8f20-8f7ef85533fb.png)

**Desktop (please complete the following information):**
 - OS: WIN 10  / WSL 1
 - Version 10
 - Compiler GCC

**Comment by iceman1001** [comment]
Coverity also report two `null pointer dereference` findings in lz4.c

**Comment by iceman1001** [comment]
And there is also two missing prototypes,  we deal with it at the moment with patching locally.

ref:
https://github.com/RfidResearchGroup/proxmark3/blob/master/common/get_lz4.sh

**Comment by doegox** [comment]
note that the patch mentioned above is also removing inlining from LZ4_decompress_generic because this has a large impact on size (2 kbytes on ARM). Maybe sth you want to consider too.

**Comment by iceman1001** [comment]
@Cyan4973  I understand you are busy and might not have time to setup Covery Scan for this project but I can add you the Coverty Scan for proxmark so you can look at the findings there.  Might be easier for you and speed up things?

**Comment by Cyan4973** [comment]
I plan on coming back to work on `lz4` during the Summer.
I presume I already have a branch setup to use coverity, though it must be updated manually, or something like that.
Will look into it more once I've got allocated time for it.

**Comment by Cyan4973** [comment]
`lz4` source code has been updated, with several fixes related to static analyzer.
It _may_ have solved some of those reported here, but I can't check directly : 
I was not successful using my coverity-scan account to update analysis report using newest source code version.
