### ISSUE TITLE
LZ4F_compressFrame: Using too small compressionLevel causes a crash

### ISSUE THREAD

**Issue by picoHz** [lz4/lz4#876]
**Describe the bug**
Using `compressionLevel` smaller than -33554430 for `LZ4F_compressFrame` causes the integer overflow and may result in a dangling pointer dereferencing.

Strangely, the following test program crashes when linked with obj files directly (lz4.o, lz4f.o, lz4hc.o and xxhash.o) but seems to work fine with liblz4.a. 
It probably depends on the address space layout 🤔 ?

**To Reproduce**
```c
#include <string.h>
#include <memory.h>
#include "lz4frame.h"

int main(void) {
    int i;
    char src[1023];
    char dst[65544];
    LZ4F_preferences_t pref;

    memset(&pref, 0, sizeof(pref));
    pref.compressionLevel = -33554431;
    
    for (i = 0; i < sizeof(src); ++i) {
        src[i] = (char)i;
    }

    LZ4F_compressFrame(dst, sizeof(dst), src, sizeof(src), &pref);
    return 0;
}
```

**Expected behavior**
Run without a crash.

**Desktop (please complete the following information):**
 - **OS**
macOS 10.15.4 / Linux Mint 19.3 Tricia
 - **Version** 
liblz4@v1.9.2 and latest dev branch (https://github.com/lz4/lz4/commit/1db9be5c47b70c9e35564d282b18a1a973d22305)
 - **Compiler** 
Apple clang version 11.0.3 (clang-1103.0.32.62) / gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
 - **Build System**
`$ cc main.c -I./lz4/lib ./lz4/lib/*.c -o main`
 - **Other hardware specs**
Core i5-5257U (macOS) / Core i5-7200U (Linux)

**How does this happen?**
1. If `compressionLevel` < -33554430 then `acceleration` > 33554431 and `searchMatchNb`  can be negative due to the integer overflow (undefined behavior).
https://github.com/lz4/lz4/blob/1db9be5c47b70c9e35564d282b18a1a973d22305/lib/lz4.c#L900

2. If `searchMatchNb` is negative, `step` also becomes negative.
https://github.com/lz4/lz4/blob/1db9be5c47b70c9e35564d282b18a1a973d22305/lib/lz4.c#L909

3. And `forwardIp` moves backward in the next iteration.
https://github.com/lz4/lz4/blob/1db9be5c47b70c9e35564d282b18a1a973d22305/lib/lz4.c#L908

4. A wrong `forwardIp` does not break the loop because this line only checks the upper bounds.
https://github.com/lz4/lz4/blob/1db9be5c47b70c9e35564d282b18a1a973d22305/lib/lz4.c#L911

5. Dereferencing `forwardIp` occurs at this line.
https://github.com/lz4/lz4/blob/1db9be5c47b70c9e35564d282b18a1a973d22305/lib/lz4.c#L939

**Comment by Cyan4973** [comment]
Good point @picoHz !
Enforcing a limit should probably protect from this issue.
