### ISSUE TITLE
Compressible string not compressed

### ISSUE THREAD

**Issue by saipreetham08** [lz4/lz4#881]
Hi!

I just wanted to know if the string **"qabcdefxwvuabcdefghi"** is compressible or not?
According to my understanding of the algorithm, it is compressible and should yield the result :
0xb0 0x71 0x61 0x62 0x63 0x64 0x65 0x66 0x78 0x77 0x76 0x75 0x0a 0x00 0x50 0x65 0x66 0x67 0x68 0x69

In the above compressed output, the last 5 bytes are sent as literals and the 'abcd' beginning at index 11 is matched with a previous existing 'abcd' beginning at index 1 and hence compressed. Is there any rule that is being violated in the above compression?

When I try to compress it using the lz4 module using the below snippet,

```
char str[20] = "qabcdefxwvuabcdefghi";
char comp_buf[30];
int comp_size = LZ4_compress_fast(str,comp_buf,20,30,1);
```

 It does not compress it and processes all the bytes as literals and yields the following output :
0xf0 0x05 0x71 0x61 0x62 0x63 0x64 0x65 0x66 0x78 0x77 0x76 0x75 0x61 0x62 0x63 0x64 0x65 0x66 0x67 0x68 0x69

Thanks!

**Comment by mwgamera** [comment]
“The last match must start at least 12 bytes before the end of block.”

**Comment by Cyan4973** [comment]
@mwgamera provided the right answer
https://github.com/lz4/lz4/blob/v1.9.2/doc/lz4_Block_format.md#end-of-block-restrictions
