### ISSUE TITLE
Can not build shared library (dll) on MSVC with cmake

### ISSUE THREAD

**Issue by emmenlau** [lz4/lz4#883]
I very much like the cmake based build instructions, they work quite well on many platforms. But recently I tried to switch from a static to a shared library build. Since then I receive the following error on MSVC with Visual Studio 2017 and 2019:
```
[...]
 [10/10] cmd.exe /C "cd . && C:\data\Tools\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\lz4cli.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe  CMakeFiles\lz4cli.dir\C_\lz4\programs\bench.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\lz4cli.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\lz4io.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\datagen.c.obj  /out:lz4.exe /implib:lz4.lib /pdb:lz4.pdb /version:0.0  /machine:x64 /MACHINE:X64 /DEBUG /debug /INCREMENTAL /subsystem:console  lz4.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
 FAILED: lz4.exe 
 cmd.exe /C "cd . && C:\data\Tools\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\lz4cli.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe  CMakeFiles\lz4cli.dir\C_\lz4\programs\bench.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\lz4cli.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\lz4io.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\datagen.c.obj  /out:lz4.exe /implib:lz4.lib /pdb:lz4.pdb /version:0.0  /machine:x64 /MACHINE:X64 /DEBUG /debug /INCREMENTAL /subsystem:console  lz4.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
 Visual Studio Incremental Link with embedded manifests
 Create CMakeFiles\lz4cli.dir/manifest.rc
 Create empty: CMakeFiles\lz4cli.dir/embed.manifest
 RC Pass 1:
 C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe /fo CMakeFiles\lz4cli.dir/manifest.res CMakeFiles\lz4cli.dir/manifest.rc
 LINK Pass 1:
 C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe CMakeFiles\lz4cli.dir\C_\lz4\programs\bench.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\lz4cli.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\lz4io.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\datagen.c.obj /out:lz4.exe /implib:lz4.lib /pdb:lz4.pdb /version:0.0 /machine:x64 /MACHINE:X64 /DEBUG /debug /INCREMENTAL /subsystem:console lz4.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\lz4cli.dir/intermediate.manifest CMakeFiles\lz4cli.dir/manifest.res
 LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe CMakeFiles\lz4cli.dir\C_\lz4\programs\bench.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\lz4cli.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\lz4io.c.obj CMakeFiles\lz4cli.dir\C_\lz4\programs\datagen.c.obj /out:lz4.exe /implib:lz4.lib /pdb:lz4.pdb /version:0.0 /machine:x64 /MACHINE:X64 /DEBUG /debug /INCREMENTAL /subsystem:console lz4.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\lz4cli.dir/intermediate.manifest CMakeFiles\lz4cli.dir/manifest.res" failed (exit code 1104) with the following output:
 Microsoft (R) Incremental Linker Version 14.26.28805.0
 Copyright (C) Microsoft Corporation.  All rights reserved.
 LINK : lz4.exe not found or not built by the last incremental link; performing full link
 LINK : fatal error LNK1104: cannot open file 'lz4.lib'
 ninja: build stopped: subcommand failed.
```

This must be in some way dependent on building the command line tool `lz4.exe`, because when disabling all command line tools the build works.

**Comment by sunny-shu** [comment]
@Cyan4973 @emmenlau

It's OK to generate dynamic libraries. The problem is to link dynamic libraries.

Visual studio link dynamic library mechanism: under the window platform, when the DLL project is compiled through visual studio, the target DLL file and a LIB file with the same name will be generated. When other projects need to reference the DLL, the LIB file should be introduced into the new project as a resource, so that the compilation can be successful when the project is generated. In this process, the DLL file is not used. Only when the compilation is complete, the DLL file is needed at run time. If there is no DLL file, an exception will be thrown.

Through the experiment, it is also proved that when the window platform and visual studio are built, target_ link_ libraries(lz4cli ${LZ4_ LINK_ Library}) always links to LIB file. And add_ The library function will not generate a lib file when it is executed to generate a dynamic library. Therefore, when lz4 is dynamically constructed through visual studio on the windows platform, it will report that lz4.lib library cannot be found, so an error is reported.

So, my solution is: when Windows platform is compiled through visual studio, it will be limited to static link only.

**Comment by emmenlau** [comment]
Dear @sunny-shu , thanks for your help!

But I am quite certain that there is some misunderstanding. There is no problem to build and link a shared library (DLL) on Windows with cmake. It is not difficult. The problem in lz4 is somewhere else. I think the problem is related to the names of targets: `lz4.exe`, `lz4.dll` and `lz4.lib` have all very similar target names, and so this may create confusion (i.e. and ambiguity) in cmake?

For example, when I rename `lz4.exe` to `lz4tool.exe` then the build works better, and can proceed further. It still does not fully work, so there must be more, probably similar problems, or I did not do the rename correctly.

But in principle, it is possible to build a shared library with visual studio and link it to a command line tool, and use the tool in automatic testing. We have many projects that do that, there should not be a problem.

**Comment by sunny-shu** [comment]
@emmenlau

**Comment by sunny-shu** [comment]
@emmenlau

The following is a simple code file. The purpose is to explain that it is not the library name problem, but the Lib files is linked when visual studio compiles, and the DLL file is linked when executing.

environment: Visual Studio 2019 Community(Window 10)
[recurrence_problem_applet.zip](https://github.com/lz4/lz4/files/5028123/recurrence_problem_applet.zip)

**Comment by emmenlau** [comment]
Dear @sunny-shu , maybe then the confusion is on my side: I'm not sure what you are saying. Can you please help me understand?

My point is, that cmake can build and link correctly with shared libraries on Windows with Visual Studio. Many many projects do that, including at least 20 shared libraries that I'm maintaining. There is usually only one potential problem, and that is about exporting shared library symbols for all entries that should be linkable from outside the shared library. Everything else usually "just works" with cmake. The problem with lz4 must be something very specific, and I assume it is an error in lz4 cmake instructions.

I understood that you said there is a fundamental problem using shared libraries Windows with Visual Studio? Did I misunderstand?

**Comment by emmenlau** [comment]
To help this discussion, I have implemented a workaround for the problem. See https://github.com/lz4/lz4/pull/891. When you add this change and set "BUILD_PROGRAMS=OFF" in cmake (for example using `cmake -DBUILD_PROGRAMS=OFF` then you can make a successful shared library build on Windows.

I have used this shared lz4 in other projects like folly, Qt, and others successfully (or at least the other projects have claimed to link lz4 successfully, I have not tested if it works). Also my executables can find `lz4.dll` and start successfully.

**Comment by emmenlau** [comment]
I've made further progress with the problem. It is related to something I said above:
> My point is, that cmake can build and link correctly with shared libraries on Windows with Visual Studio. Many many projects do that, including at least 20 shared libraries that I'm maintaining. There is usually only one potential problem, and that is *about exporting shared library symbols for all entries that should be linkable from outside the shared library*.

See the italic part: *exporting shared library symbols*. This is currently not enabled on MSVC. I've added the corresponding defines to CMakeLists.txt and the build starts to work.

**Comment by emmenlau** [comment]
I've updated https://github.com/lz4/lz4/pull/891 to reflect this change. Please review?

**Comment by Cyan4973** [comment]
Building a shared library (dll) on Visual Studio from a `cmake` recipe is a fine objective,
but don't try to build an `lz4.exe` CLI by linking it to the shared library.

The CLI is designed to be linked to the _static_ variant of library, in order to guarantee the version being linked.
Trying to link `lz4.exe` CLI to the shared library will introduce all sorts of advanced troubles, that can't be easily solved, at least not within the reasonable scope of a single PR.
