### ISSUE TITLE
Not able to install lz4 (0.5.2) as a dependency for my node (6.2.1) build 

### ISSUE THREAD

**Issue by mughal61** [lz4/lz4#894]
**Describe the bug**
I am trying to build/install node packages that I have listed in package.json file and that includes lz4 v0.5.2 as well.
When I run npm install, its failing with the below error:

 lz4@0.5.2 install /Users/username/Desktop/code/master/mobile/node_modules/lz4
> node-gyp rebuild

  CXX(target) Release/obj.target/lz4/lib/binding/lz4_binding.o
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../lib/binding/lz4_binding.cc:6:
../../nan/nan.h:59:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/lz4/lib/binding/lz4_binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm[/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/user/.nvm[/versions/node/v6.2.1/bin/node" "/Users/user/.nvm[/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/username/Desktop/code/master/mobile/node_modules/lz4
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

**Expected behavior**
It shall build as it was doing before (like months ago)

**System (please complete the following information):**
Running on MacOS Catalina 10.15.6 
> xcode-select --version
> xcode-select version 2373.

**Comment by Cyan4973** [comment]
It's probably better to direct this question towards the nodejs repository concerned.

This repository is about the native version only, it is not relevant for node packages.

**Comment by mughal61** [comment]
I am trying to install lz4 v0.5.2 and getting above errors, not sure what got changed and now I can't build it.

**Comment by Cyan4973** [comment]
I'm not sure what you are trying to do, but this thing does not come from this repository.

**Comment by mughal61** [comment]
I am trying to download and install all dependencies defined in packages.json file, that has a package listed i.e.   
"lz4": "0.5.2",

during download and installation of other dependencies, when it tries "lz4", I am getting error that I mentioned in my main post.

Here is the rest of the error, hopefully it'll make more sense why it can be some issue with lz4.

  CXX(target) Release/obj.target/lz4/lib/binding/lz4_binding.o
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../lib/binding/lz4_binding.cc:6:
../../nan/nan.h:59:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/lz4/lib/binding/lz4_binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm[/versions/node/v6.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/user/.nvm[/versions/node/v6.3.0/bin/node" "/Users/user/.nvm[/versions/node/v6.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/username/Desktop/code/master/mobile/node_modules/lz4
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
...
npm WARN sass-loader@6.0.6 requires a peer of webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0 but none was installed.
npm ERR! Darwin 19.6.0
npm ERR! argv "/Users/user/.nvm[/versions/node/v6.3.0/bin/node" "/Users/user/.nvm[/versions/node/v6.3.0/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! lz4@0.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lz4@0.5.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lz4 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lz4
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lz4
npm ERR! There is likely additional logging output above.

**Comment by felixhandte** [comment]
@mughal61, the compiler error you're seeing is clearly in C++ code, none of which is present in the LZ4 codebase maintained here.  This is all C. The issue you're seeing is with the binding that takes the core LZ4 library maintained here and makes it available to nodejs. It looks like this is the component you're having trouble with: https://github.com/pierrec/node-lz4.

**Comment by mughal61** [comment]
> @mughal61, the compiler error you're seeing is clearly in C++ code, none of which is present in the LZ4 codebase maintained here. This is all C. The issue you're seeing is with the binding that takes the core LZ4 library maintained here and makes it available to nodejs. It looks like this is the component you're having trouble with: https://github.com/pierrec/node-lz4.

Thanks for catching this out, I appreciate it.
