### ISSUE TITLE
Interoperable Haskell binding

### ISSUE THREAD

**Issue by nh2** [lz4/lz4#906]
I have written a Haskell binding to `lz4frame.h`:

https://hackage.haskell.org/package/lz4-frame-conduit

Would you mind adding it to https://lz4.github.io/lz4/ in the `Interoperable LZ4 ports and bindings` section?

I also have a [test suite](https://github.com/nh2/lz4-frame-conduit/blob/8402a8161098e7be9eb237c0edeeaf3d99c9699a/test/Main.hs) that checks roundtripping against the `lz4` binary and does generative testing against `compress | decompress`.

**Comment by Cyan4973** [comment]
Great work @nh2 !

Sure ! Haskell binding added : https://lz4.github.io/lz4/#interoperable-lz4

**Comment by nh2** [comment]
Thanks! CC @stefanjaax @ulan who helped me with it at [MuniHac 2018](https://munihac.de/2018.html).
