### ISSUE TITLE
Question: LZ4F_decompress() return when it needs more data in order to decompress, how a caller can identify

### ISSUE THREAD

**Issue by bit-nitin** [lz4/lz4#912]
My application call LZ4F_decompress() to decompress 2 MB of data at a time and I see that this function returns control if he finds that more data is needed in order to complete the decompression which is not an error.

Now at called I see no error but dstSizePtr == 0 and srcSizePtr > 0 how I will take this condition?
I believe some handling is required in order to distinguish that decompress logic need more input data to complete the frame decompression?

My understanding says that a frame can be split in different source buffer and end of one of the buffer leave the decompression without decompressing any thing.

Any advise?

**Comment by Cyan4973** [comment]
I'm not sure to understand the question.

One typical issue that comes to mind is that 
sometimes the output buffer is not large enough to contain all the data that needs to be flushed.
In which case, even if the entire (compressed) frame was read,
it stills needs more space to finish flushing the content.

(N.B: in which case, the compressed frame cannot be entirely consumed : the "end of frame" mark is generally not read until the last block is completely flushed).

You may be describing something different, but then I have a hard time understanding it.

> My application call LZ4F_decompress() to decompress 2 MB of data at a time 

What are "2 MB of data" ?
Is that input data ? or decompressed data ?
What are the respective sizes of input and output buffers ?
