### ISSUE TITLE
how to install in a different directory?

### ISSUE THREAD

**Issue by edwardhartnett** [lz4/lz4#917]
I am trying to install LZ4 in a directory /usr/local/lz4-1.9.2. I would like lib, bin, etc. to be under that directory instead of /usr/local.

Based on the docs I tried this:
`
DESTDIR=/usr/local/lz4-1.9.2/ make install`

But that resulted in files being installed in:

`/usr/local/lz4-1.9.2//usr/local/lib
`
How do I specify the root install directory for LZ4? Is is possible without modifying the Makefile?

**Comment by Cyan4973** [comment]
Indeed,
`DESTDIR` is about changing the root of installation (often used to run a "jailed" installation and analyze the outcome).

What you seem to be looking for is `PREFIX`,
or possibly a combination of `LIBDIR`, `BINDIR` and `INCLUDEDIR` if they don't follow the classical sub-tree convention.
See https://github.com/lz4/lz4/blob/v1.9.2/lib/Makefile#L143 .
