### ISSUE TITLE
Error	LNK2019	unresolved external symbol ___chkstk_ms referenced in function LZ4_compress_fast  liblz4_static.lib(lz4.o)

### ISSUE THREAD

**Issue by TimelifeCzy** [lz4/lz4#920]
liblz4_staic.lib(lz4.o)   referenced in function LZ4_compress_fast()?
1. #include "lz4.h"
2. Linker liblz4_static.lib
3. Add Library Directory

code:
int nRet = LZ4_decompress_safe((char*)(SectionAddress + m_lpbase), (char*)(pSections->VirtualAddress + m_lpbase), g_stud.s_blen[i], pSections->SizeOfRawData);

need help ！Thank

**Comment by TimelifeCzy** [comment]
![图片](https://user-images.githubusercontent.com/43507143/94096035-af016180-fe55-11ea-9097-70e2ff359ac1.png)

**Comment by TimelifeCzy** [comment]
static no-import? dll\liblz4.dll.a Success, run error： msys-lz4-1.dll

**Comment by Ruiyang19** [comment]
Have you solved the problem? I ran into the same problem just like yours.

**Comment by Cyan4973** [comment]
I have no experience with this setup unfortunately.

For Windows + MSVC compilation and link, `lz4.h` can receive special declaration instructions, [using `LZ4_DLL_EXPORT` or `LZ4_DLL_IMPORT`](https://github.com/lz4/lz4/blob/v1.9.2/lib/lz4.h#L92), that will influence the way MS exposes and link symbols. Try any of these and see if they help. 
I would expect `EXPORT` to be useful with `.dll`, and `IMPORT` maybe for `.lib`.

Hopefully, other users of `LZ4` on MSVC may be able to help more.

**Comment by TimelifeCzy** [comment]
Recompile, the release version is invalid

**Comment by JohnAlcatraz** [comment]
Have the same issue here, how was this solved?

Edit: Well, solved it by manually compiling the .lib from the .sln in the build folder. Seems, as TimelifeCzy mentioned, the .lib in the lz4_win64_v1_9_3.zip from the releases is just broken.

**Comment by syn-tel** [comment]
@JohnAlcatraz Hey, I am complete noob, and I have no idea how to compile a .lib from .sln. can you help me out?

**Comment by Cyan4973** [comment]
I suspect the issue is that the binary files in the package `lz4_win64_v1_9_3.zip` were built using `mingw64`, not `msvc`.
When it comes to linking, this is likely an incompatibility issue, compilers probably expect different conventions.
