### ISSUE TITLE
Multi-thread compression

### ISSUE THREAD

**Issue by yumeyao** [lz4/lz4#933]
https://github.com/yumeyao/lz4/pull/1

- I forked lz4 and modified lz4-cli to support multi-thread compression. (based on 1.9.2 then merged to dev)
- For comparison with other 'existing' multi-thread implmentations from https://lz4.github.io/lz4/ , see the link above.

Right now, it's implemented in kind of a 'hackish' way. Because there is no native per-block API support in lz4frame. So I created this issue, hoping there would be some discussion about one or more things from below:
- put this into contrib/ directory or add a link to it in https://lz4.github.io/lz4/
- refactor lz4frame with (static) api supporting block-level operations, so that lz4-cli and other user implemtations could write their own multi-thread logic to compress in parallel.

**Comment by yumeyao** [comment]
BTW, the code is completely `C90` compatible if ENABLE_MT=yes is **not** specified when calling `make`, otherwise it requires `C++11` thread support. (which is, maybe more portable than pthread.) It doesn't use any other stuff from C++11 like rvalue-reference/lambda, so theoretically, one could change `C++11` thread to `boost` thread if compiling on a pre-C++11 platform is needed.

But I'm not any makefile fan so the makefile modifications maybe improved

**Comment by Cyan4973** [comment]
That's great work @yumeyao !
It could make a great C++11 fork !

**Comment by Cyan4973** [comment]
By the way, both ideas (host the project into `contrib/`, evolve `lz4frame` API to help support multi-threaded compression with an external multi-thread logic) are welcome.
