### ISSUE TITLE
Different prototype and function declaration on LZ4HC_compress_optimal

### ISSUE THREAD

**Issue by alfonso-soto** [lz4/lz4#935]
**Describe the bug**
The prototype and the actual function declaration of `LZ4HC_compress_optimal` differ on a `const` qualifier for the last parameter.

**PROTORYPE**
```
static int LZ4HC_compress_optimal( LZ4HC_CCtx_internal* ctx,
    const char* const source, char* dst,
    int* srcSizePtr, int dstCapacity,
    int const nbSearches, size_t sufficient_len,
    const limitedOutput_directive limit, int const fullUpdate,
    const dictCtx_directive dict,
    HCfavor_e favorDecSpeed);
```

**DECLARATION**
```
static int LZ4HC_compress_optimal ( LZ4HC_CCtx_internal* ctx,
                                    const char* const source,
                                    char* dst,
                                    int* srcSizePtr,
                                    int dstCapacity,
                                    int const nbSearches,
                                    size_t sufficient_len,
                                    const limitedOutput_directive limit,
                                    int const fullUpdate,
                                    const dictCtx_directive dict,
                                    **const** HCfavor_e favorDecSpeed)
{....}
```

The parameter **favorDecSpeed** is missing a const qualifier on the prototype. This will cause compilation errors on some older compilers like diab compiler.

**Expected behavior**
Same qualifier for both definitions.

**Comment by aqrit** [comment]
~~MISRA rule 77 explicitly allows const in the prototype to be different.~~

Some people say things like [this](https://softwareengineering.stackexchange.com/questions/204500/when-and-for-what-purposes-should-the-const-keyword-be-used-in-c-for-variables):
> Never use **const** in a function prototype for a parameter passed by **value**. It has no meaning and is hence just 'noise'.

ofc. if it helps some compiler then there is no reason not to change it.

**Comment by Cyan4973** [comment]
Is there some kind of compiler flag that would help detecting such declaration difference ?
This would be useful to track and continuously maintain such issues.

For prototypes, I tend to not use `const` on parameters passed by value, as suggested by @aqrit.
But there are many contributors on this code base, so without an automated test to enforce it, this policy will have a few exceptions here and there.
