### ISSUE TITLE
Could you please add this new Dart binding to the website?

### ISSUE THREAD

**Issue by marianopeck** [lz4/lz4#948]
Hi guys,

We have created a new LZ4 binding for Dart language. Our binding not only covers all the LZ4 features and options but also we added streaming functionality that play well with Dart streams. We would like if you can add a new entry in the table of "Customs LZ4 ports and bindings" in https://lz4.github.io/lz4/

The info should be:

Language: Dart
Author: Instantiations
URL: https://pub.dev/documentation/es_compression/latest/lz4/lz4-library.html

Thanks in advance and thanks a lot for such a great product!

**Comment by Cyan4973** [comment]
Sure @marianopeck !

By the way, the documentation states that it's using "the Lz4 frame format".
Is the binding directly compatible with `lz4` CLI ?
If yes, it could become part of "Interoperable LZ4 ports and bindings" instead of "Customs LZ4 ports and bindings" (which are presumed _not_ interoperable with `lz4` CLI).

**Comment by marianopeck** [comment]
Hi @Cyan4973 
Thanks for the quick reply! Yes, good question. Sorry I didn't realize before the difference between both lists. You are right,  "Interoperable LZ4 ports and bindings" should be more accurate. In that regard:

Pharo Smalltalk | Mariano Martinez Peck | http://smalltalkhub.com/#!/~marianopeck/LZ4/   is outdated, dead and the source repository is down. So you may want to remove that one. 


VA Smalltalk | Instantiations | http://www.instantiations.com/docs/91/wwhelp/wwhimpl/js/html/wwhelp.htm#href=pr/compression2.html#pID0E0LB0FA

Could also be moved to "Interoperable LZ4 ports and bindings". Basically, the new binding to Dart was a port/inspired from the VA Smalltalk one. 

Sounds good?

**Comment by Cyan4973** [comment]
Sure !
The LZ4 homepage has been updated with regards to these ports
