### ISSUE TITLE
Parallel test does not work

### ISSUE THREAD

**Issue by xkszltl** [lz4/lz4#957]
**Describe the bug**

`make check -j` fails:
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/5203025/100534400-5c736580-3249-11eb-8920-4b7711e64a14.png">

Likely to be a race condition for filename.

**Expected behavior**

Support parallelism as other target.

**System (please complete the following information):**
 - OS: [e.g. Mac] CentOS 7
 - Version [e.g. 22] v1.9.3
 - Compiler [e.g. gcc] gcc-9 (devtoolset-9)
 - Build System [e.g. Makefile] makefile
 - Other hardware specs [e.g Core 2 duo...] Xeon Gold 6140

**Comment by Cyan4973** [comment]
I suspect tests were never designed to be run in parallel.
That's probably fixable, though it will require available time.

**Comment by xkszltl** [comment]
May worth documenting it here:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/5203025/100969035-68269b00-356d-11eb-8fd3-7ba8ae825023.png">

**Comment by Cyan4973** [comment]
parallel build != parallel test

**Comment by llebout** [comment]
Parallel testing also failed for me. Disabling parallel testing fixed the failures. On GNU Guix parallel testing is enabled by default.

Logs of failures: 
[srb2c0mzra8vdxfblxqhxm5mxk2l8d-lz4-1.9.3.drv.log](https://github.com/lz4/lz4/files/5939819/srb2c0mzra8vdxfblxqhxm5mxk2l8d-lz4-1.9.3.drv.log)
