### ISSUE TITLE
CFLAGS env var ignored by makefile

### ISSUE THREAD

**Issue by xkszltl** [lz4/lz4#958]
**Describe the bug**

We set some debug flags (`-O3 -fdebug-prefix-map=... -g`) during our build as env var.
Only `$CXXFLAGS` works.
`$CXXFLAGS` seems to be ignored.

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/5203025/100534829-30a6ae80-324e-11eb-872e-590b5436243d.png">

Work-around is to use `make all CFLAGS="$CFLAGS"` but I don't know why.

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/5203025/100534898-f853a000-324e-11eb-97bc-0314da690d47.png">

And with the work-around, those `-W` from `$(DEBUGFLAGS)` disappeared.

**System (please complete the following information):**
 - OS: [e.g. Mac] CentOS 7
 - Version [e.g. 22] 1.9.3
 - Compiler [e.g. gcc] gcc-9 (devtoolset-9)
 - Build System [e.g. Makefile] gnu make 3.82

**Comment by Cyan4973** [comment]
This issue is mysterious to me.
When doing : 
`CFLAGS=something make all`
I expect CFLAGS to be passed as an environment variable to the local `make`
__and__ to sub-`Makefile`.

This is, btw, what happens when using other variables : 
`CPPFLAGS=something make all` works as intended,
and `MOREFLAGS=something make all` also works as intended.

Hence, why does it _not_ work correspondingly for `CFLAGS` ?
It's as if the content of `CFLAGS` environment variable would not survive the first `Makefile`...

**Comment by xkszltl** [comment]
Had the same feeling, so I thought maybe you did something special.
I also tried to write a makefile with `CFLAGS ?=` and `CFLAGS +=`, but all works perfectly.

**Comment by Cyan4973** [comment]
It seems the issue is related to `Makefile.inc`,
which is not too surprising as it has been a source of side effects since its introduction.

I still don't see how it could influence `CFLAGS`, but will keep looking.

**Comment by Cyan4973** [comment]
It seems I can track the issue to the in-recipe lazy assignment of `CFLAGS` : https://github.com/lz4/lz4/blob/dev/Makefile#L130
`clangtest: CFLAGS ?= -O3`

Incredibly enough, it seems this line has the same side effect as `unexport CFLAGS`.

Possibly a `make` bug ?...

**Comment by Cyan4973** [comment]
I believe I fixed the `CFLAGS` forwarding issue in #960.
It seems to be a [`make` bug](http://savannah.gnu.org/bugs/?func=detailitem&item_id=59230), as this behavior is weird and undocumented.
Fortunately, the `export` statement fixes it and remains compatible with other versions of `make` that would be unaffected by the bug (if they exist).

**Comment by xkszltl** [comment]
Can we have 1.9.4 for this (and probably a few other bugfixes)?
Hard to cherry-pick the fix since the merge tree is complicated.

**Comment by Cyan4973** [comment]
No `lz4` release is planned on short term.

**Comment by xkszltl** [comment]
Do you mean 1) there won't be any release recently or 2) not just for this patch because there'll soon be a release?

**Comment by Cyan4973** [comment]
1)
