### ISSUE TITLE
NullPointerException while reading the a compressed file

### ISSUE THREAD

**Issue by MarcoBerlot** [lz4/lz4#961]
**Describe the bug**
Null pointer exception being thrown while attempting to read lz4 file.
```
java.lang.NullPointerException
at net.jpountz.lz4.LZ4FrameInputStream.read(LZ4FrameInputStream.java:295)
at java.base/java.io.FilterInputStream.read(Unknown Source)

```

**Expected behavior**
The file should be properly uncompressed and read.

**To Reproduce**
Unfortunately I can't provide steps to reproduce since this has happened in our production environment. Here's the function that is reading the lz4 files

```
private byte[] readCompressedFile(File file) throws IOException {
        LZ4FrameInputStream gis = new LZ4FrameInputStream(new FileInputStream(file));
        ByteArrayOutputStream fos = new ByteArrayOutputStream();
        byte[] buffer = new byte[1024];
        int len;
        while ((len = gis.read(buffer)) != -1) {
            fos.write(buffer, 0, len);
        }
        fos.close();
        gis.close();
        return fos.toByteArray();
    }
```

**System (please complete the following information):**
 - OS: CentOS Linux release 7.8.2003 (Core)
 - Compiler: OpenJ9
 - Build System [e.g. Makefile]
 - Other hardware specs [e.g Core 2 duo...]

**Comment by Cyan4973** [comment]
It looks like a Java related issue.
Could it be redirected to the appropriate repository ? (likely https://github.com/lz4/lz4-java by @odaira )
This repository only deals with the reference `C` implementation.

**Comment by MarcoBerlot** [comment]
Thanks @Cyan4973, opened a new issue at https://github.com/lz4/lz4-java/issues/174
