### ISSUE TITLE
Problems with installation of your package from spack manager

### ISSUE THREAD

**Issue by zimaaaaa** [lz4/lz4#968]
Hello!

**Describe the bug**
Trying to install PIConGPU from `spack` manager, I have some issues with the installation of LZ4 package. It's trying to reach the directory /usr/local for some reason.

**Expected behavior**
I've tried to reproduce this thing on my PC with almost the same condition except the CPU architecture and it installs without any problems. However, on the server it tries to do something in `/usr/local` directory and server denies to do it.  

**To Reproduce**
1. Install `spack` manager like [there](https://spack.readthedocs.io/en/latest/getting_started.html)
2. `spack install lz4`

**The Output of `spack install lz4`**
```
==> Installing lz4-1.9.2-lyxnahjrwx4g5bwcp3yuaeql5rzj6dl2
==> No binary for lz4-1.9.2-lyxnahjrwx4g5bwcp3yuaeql5rzj6dl2 found: installing from source
==> Using cached archive: /home/labuser/src/spack/var/spack/cache/_source-cache/archive/65/658ba6191fa44c92280d4aa2c271b0f4fbc0e34d249578dd05e50e76d0e5efcc.tar.gz
==> lz4: Executing phase: 'edit'
==> lz4: Executing phase: 'build'
==> lz4: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'install' 'PREFIX=/home/labuser/src/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-9.3.0/lz4-1.9.2-lyxnahjrwx4g5bwcp3yuaeql5rzj6dl2'

1 error found in build log:
     15    /home/labuser/src/spack/lib/spack/env/gcc/gcc -O3  -lrt -I../lib -DX
           XH_NAMESPACE=LZ4_  ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../
           lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o -o lz4
     16    make[1]: Leaving directory '/home/labuser/tsp_output/spack-stage/spa
           ck-stage-lz4-1.9.2-lyxnahjrwx4g5bwcp3yuaeql5rzj6dl2/spack-src/progra
           ms'
     17    ==> lz4: Executing phase: 'install'
     18    ==> [2021-01-27-12:34:00.850895] 'make' '-j16' 'install' 'PREFIX=/ho
           me/labuser/src/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-9.3
           .0/lz4-1.9.2-lyxnahjrwx4g5bwcp3yuaeql5rzj6dl2'
     19    make[1]: Entering directory '/home/labuser/tsp_output/spack-stage/sp
           ack-stage-lz4-1.9.2-lyxnahjrwx4g5bwcp3yuaeql5rzj6dl2/spack-src/lib'
     20    creating pkgconfig
  >> 21    make[1]: execvp: /usr/local: Permission denied
     22    make[1]: *** [Makefile:174: install] Error 127
     23    make[1]: Leaving directory '/home/labuser/tsp_output/spack-stage/spa
           ck-stage-lz4-1.9.2-lyxnahjrwx4g5bwcp3yuaeql5rzj6dl2/spack-src/lib'
     24    make: *** [Makefile:94: install] Error 2
```

**System (please complete the following information):**
 - OS: [Ubuntu 20.04.1 LTS, server version]
 - Version [1.9.2]
 - Compiler [gcc]
 - Build System [make]
 - Other hardware specs [Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz]

**Comment by Cyan4973** [comment]
`sudo spack install` ?

**Comment by zimaaaaa** [comment]
In this way I get the next output:
```
sudo spack install lz4
sudo: spack: command not found
```
I guess that spack environment doesn't work in sudo.

**Comment by spadova-a** [comment]
Hi, sorry to comment on closed problem, but I am having the same problem - may I ask how did you solve it?

**Comment by t-mat** [comment]
## Our official answer

Please note that here is a dedicated issue board of the LZ4 library.

Therefore, we can't answer anything about `spack` package manager.

So, please ask at https://github.com/spack/spack/issues

----

But, I like `spack` a lot, I'd like to help you a bit.   The following installation procedure may help you.

```sh
cd
git clone -c feature.manyFiles=true https://github.com/spack/spack.git
. spack/share/spack/setup-env.sh
spack install lz4@1.9.4
spack load lz4@1.9.4
lz4 --version
# *** LZ4 command line interface 64-bits v1.9.4, by Yann Collet ***
```

See also : 
- https://github.com/spack/spack#-spack
- https://spack.readthedocs.io/en/latest/package_list.html#lz4

**Comment by spadova-a** [comment]
Hi,
thanks very much for your help, together with setting the right way to my PATH, it fixed my problem.
