### ISSUE TITLE
[Question] Independent blocks with dictionary

### ISSUE THREAD

**Issue by MiloszKrajewski** [lz4/lz4#969]
Hi,

I would like to apologize for asking this question without going deep into source code, but I think that overall just asking a question might be a little bit quicker and answering it won't be too taxing for you.

I'm implementing dictionaries now for my .NET port of LZ4 (https://github.com/MiloszKrajewski/K4os.Compression.LZ4).
I would like to ask what would be the expected behaviour and file format produced by lz4 command line tool (I would like my files to be fully compatible) with it.

So, **Independent blocks and dictionaries**

1. Would it use same dictionary for each block?
2. Would it reinitialize dictionary with `LZ4_loadDict` for each block? 
3. ...or maybe if would initialize  `context.hashTable` once (with `LZ4_loadDict`) and `memcpy` it for reuse in following blocks?

Thanks,
Milosz

**Comment by Cyan4973** [comment]
Just a note about terminology : the `lz4` command line tool creates _frames_. Frames then consist of a number of blocks, each one preceded by a block header.

The `lz4` command line tool is able to compress data into frames using a dictionary.
The command is : `lz4 file -D dict`, and corresponding decompression is `lz4 -d file.lz4 -D dict`.
Omitting the dictionary will make decompression fail.
Providing an incorrect dictionary will likely trigger a checksum error.

To compress multiple files : `lz4 -m file1 file2 -D dict`, 
in which case the same dictionary is used for each file.

The other questions are more about optimization strategies.
The `lz4` command line utility uses `LZ4F_compressFrame_usingCDict()`, which takes as argument a pre-computed `cdict`, which avoids having to re-populate the hash table every time. Of course, this function creates a frame, not a block.

Now, under the hood, `lz4frame` still uses block functions. The recipe is present in function [`LZ4F_initStream()`](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.c#L570). It uses a combination of `LZ4_resetStream_fast()` and `LZ4_attach_dictionary()`.

Such level of optimization is only useful when re-loading the same dictionary very often.
If loading a dictionary is occasional, then `LZ4_loadDict()` will do just fine.

**Comment by MiloszKrajewski** [comment]
My original question intention (1) was overshadowed my my other question (3), so let me ask it differently:

what would be a difference between `-BD -D dict` and `-BI -D dict`?
I do assume that with `-BD` load dict is used once, but I'm curious about behaviour of `-BI`.

Thanks,

**Comment by Cyan4973** [comment]
Ah ok, you are wondering if independent blocks re-use the dictionary at the beginning of each block (within the same frame),
or if only the first block of the frame effectively benefits from the dictionary.

The frame specification states that : 
> When the frame descriptor defines independent blocks, each block will be initialized with the same dictionary

I've verified (with a contrived example) that it does indeed work this way within `lz4` CLI:

```
cat calgary.tar | head 4096 > cal4096
cat cal4096 >> concal4096
cat cal4096 >> concal4096
cat cal4096 >> concal4096
lz4 concal4096 -c | wc -c
  2677
lz4 concal4096 -c -D cal4096 | wc -c
  86
lz4 concal4096 -c -B4096 | wc -c
  7877
lz4 concal4096 -c -B4096 -BD | wc -c
  2806
lz4 concal4096 -c -B4096 -D cal4096 | wc -c
  132
```
(note : blocks are independent (`-BI`) by default)
