### ISSUE TITLE
makefile echo problem

### ISSUE THREAD

**Issue by tkiraly** [lz4/lz4#975]
https://github.com/lz4/lz4/blob/bdc9d3b0c10cbf7e1ff40fc6e27dad5f693a00e7/lib/Makefile#L201

 doest not take into account the DESTDIR variable so this:

`	@echo Installing headers in $(includedir)`
should be
`	@echo Installing headers in $(DESTDIR)$(includedir)`

**Comment by Cyan4973** [comment]
fixed by @eloj in #1012
