### ISSUE TITLE
Skippable frames breaks LZ4 decoding of streams

### ISSUE THREAD

**Issue by davidmankin** [lz4/lz4#977]
**Describe the bug**

I have an LZ4 stream containing skippable frames.  When I try to use `lz4 -d -c` to decode it, I get `Error 43 : Stream error : cannot skip skippable area`. 

**Expected behavior**
LZ4 should behave the same whether or not the input is a pipe.  

**To Reproduce**

This is the simple way to reproduce it

```shell
echo "hello" | lz4 -c > file.lz4
# Create a skippable frame: magic number, length (32 bytes), 32 null bytes
cat > skippable_frame.xxd <<SKIP
00000000: 5a2a 4d18 2000 0000 0000 0000 0000 0000  Z*M. ...........
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000                           ......
SKIP
xxd -r skippable_frame.xxd > sippable_frame.bin
cat file.lz4 sippable_frame.bin | lz4 -dc
# Note that it fails
cat file.lz4 sippable_frame.bin > combined.lz4
lz4 -d combined.lz4
# Note that it succeeds
cat combined
# See "hello"
```

Here's my real input that's causing errors:

``` shell
cat > bad_input.xxd <<EOXXD
00000000: 0422 4d18 6050 fb1b 0000 0022 0c00 0100
00000010: f005 f4c8 fe0a 6865 6c6c 6f20 7468 6572
00000020: 650a 3b18 2bca 0000 0000 5a2a 4d18 2000
00000030: 0000 e289 88e2 8988 5359 4e43 e289 88e2
00000040: 8988 18b2 ddf4 b561 4220 ab4f 3e3a f4cd
00000050: 5c49
EOXXD
xxd -r bad_input.xxd > bad_input.lz4
cat bad_input.lz4 | lz4 -dc 
# See it fails "Error 43 : Stream error : cannot skip skippable area"
```

**System (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Version: lz4-1.9.3
 - Compiler: Error 43 : Stream error : cannot skip skippable area 
 - Build System: Makefile

**Additional context**
(Note that this does not fail in zstd-1.4.9.)

I added some additional debugging code to `fseek_u32` in `lz4io.c`:

```c
/** Safely handle cases when (unsigned)offset > LONG_MAX */
static int fseek_u32(FILE *fp, unsigned offset, int where)
{
    const unsigned stepMax = 1U << 30;
    int errorNb = 0;

    if (where != SEEK_CUR) return -1;  /* Only allows SEEK_CUR */
    while (offset > 0) {
        unsigned s = offset;
        if (s > stepMax) s = stepMax;
        errorNb = UTIL_fseek(fp, (long) s, SEEK_CUR);
        if (errorNb != 0) {
            int local_errno = errno;
            fprintf(stderr,
                "Failed trying to seek %ld forward in stream: errno=%d %s: %s\n",
                (long) s,
                local_errno,
                local_errno == ESPIPE ? "ESPIPE" : "(try man errno)",
                strerror(local_errno));
            break;
        }
        offset -= s;
    }
    return errorNb;
}
```

When it runs on my input, I get: 
```text
Failed trying to seek 32 forward in stream: errno=29 ESPIPE: Illegal seek
Error 43 : Stream error : cannot skip skippable area 
```

I don't know much about it but my guess at a fix is that fseek_u32 should be able to handle `ESPIPE` and fall back to `read` instead of `fseek`.

**Comment by lixiaofei38** [comment]
> **To Reproduce**
> 
> This is the simple way to reproduce it
> 
> ```shell
> echo "hello" | lz4 -c > file.lz4
> # Create a skippable frame: magic number, length (32 bytes), 32 null bytes
> cat > skippable_frame.xxd <<SKIP
> 00000000: 5a2a 4d18 2000 0000 0000 0000 0000 0000  Z*M. ...........
> 00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
> 00000020: 0000 0000 0000                           ......
> SKIP
> ```

This example you provide has a little flaw, since the skippable frame size takes 4 bytes, your data is lacking two bytes of zero(30 bytes instead of 32). But this shall not matter unless you concatenate another frame. The problem still exits.
It seems that `fseek` does not work on a pipe.
So what I tried is to call `fgetc()` size times to replace `fseek_u32()`, and it does work on your example.
```c
unsigned const size = LZ4IO_readLE32(MNstore);
//int const errorNb = fseek_u32(finput, size, SEEK_CUR);
//if (errorNb != 0)
//    EXM_THROW(43, "Stream error : cannot skip skippable area");
for (unsigned count = 0; count < size; ++count) fgetc(finput);
```
``` shell
# cat file.lz4 skippable_frame.bin file.lz4| lz4 -dc
hello
hello
```
But I feel there might be better way to do this.

**Comment by Cyan4973** [comment]
> It seems that fseek does not work on a pipe.

Yes, that's an issue for pipes.

> fseek_u32 should be able to handle ESPIPE and fall back to read instead of fseek.

Yes, that's likely a correct way to handle this problem.

**Comment by Cyan4973** [comment]
Strangely, I've been trying to reproduce the issue recently,
but couldn't.

When concatenating one or multiple skippable frames into a file, combined with normal `lz4` frames, decoding the concatenated input always works, even when input is passed via `stdin`.

What could help reproducing the issue ?

_edit_ :
OK, that's interesting.

In my previous tests, I would concatenate skippable frames and `lz4` frames into a file, then stream the file via `stdin` to `lz4 -dc`.
And it would work without trouble.

Now, if I _don't_ create an intermediate file, and send the output of `cat` directly into `lz4` via `stdin`, like `cat file1 file2 file2 | lz4 -dc`, _then_ it fails and produces the expected error message.

So maybe `fseek()` works fine as long as `stdin` is streaming a single file ...
